// Sol: Converted directly from Btech/BTECH_1431.c, 1431:000A.
// Segment fields are actual typed globals; arithmetic, branches and original
// bugs retained. UI calls remain contracts pending their graphical conversion.
// BTECH_1431.c
// Generated by decompiling BTECH.EXE
// using Reko decompiler version 0.11.2.0.

#include "game.h"

// Sol: Exact EXE-owned strings are readable source; retain native addresses as provenance.
#define HealingMedicSkillPrefixText ((unsigned char  *)" uses his ") // 3EDB:2538
#define HealingEquipmentPrefixText ((unsigned char  *)" skill and his ") // 3EDB:2543
#define HealingUnskilledMedicText ((unsigned char  *)" fumbles with some bandages") // 3EDB:2553
#define HealingCharacterResultText ((unsigned char  *)" healing.") // 3EDB:2587
#define HealingNoInjuriesText ((unsigned char  *)"Nobody is wounded.") // 3EDB:2591
#define HealingRecoveryPendingText ((unsigned char  *)"Your characters need more time to recover.") // 3EDB:25A4
#define HealingNoFurtherRecoveryText ((unsigned char  *)"Nobody is wounded.") // 3EDB:25CF
#define HealingDoctorText ((unsigned char  *)"The doctor") // 3EDB:252D
#define HealingAssistWoundedText ((unsigned char  *)" to assist the wounded.") // 3EDB:256F

enum {
    HealingMenuLayout = 1, // native menu layout index, not a medical skill
    MedicalDescription_Hospital = 3 // fourth entry in the medical-description pointer table
};

// 1431:000A: void Heal_Characters(Stack int16 medicalServiceTier)
// Called from:
//      Game_Pause_Menu
//      Combat_Run_Encounter
//      Citadel_Building_Dialogs
// Sol: Summary: Apply medical recovery to the party.
// Sol: Outline: Check recovery gating, select a medic, calculate health gains from equipment and skills, and update characters.
void Heal_Characters(uint16_t medicalServiceTier)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: local flow matches under
	// Sol: native BYTE/WORD/FAR memory views and documented shared-call contracts.
	// Sol: Selectors5522/5526=3092 and5524=3EDB; character stride17 bytes.
	// Sol: health is reloaded after the dice, matching native 01D9; no new health validation.
	// Sol: Gameplay arithmetic is native WORD width; skill/body/health use signed BYTE loads.
	// Sol: The packed healing-roll BYTE is decoded unsigned to avoid host signed-right-shift rules.
	if (PartyHealthRecoveryTimer != 0)
	{
		Draw_Message_Box(); // Sol:02FB recovery gate precedes all medic selection/dice; hospital script clears D335 BEFORE calling
		uint16_t hasInjuredPartyMember = FALSE;
		for (uint16_t partyMemberId = 0; partyMemberId < PartySize; ++partyMemberId)
		{
			if (Characters[partyMemberId].name != Character_Dead
			 && CharacterHealthPerBodyPoint * (int16_t)(int8_t)Characters[partyMemberId].body != (int16_t)(int8_t)Characters[partyMemberId].health)
				hasInjuredPartyMember = TRUE; // Sol:031E signed inequality, not health<maximum
		}
		unsigned char  *recoveryStatusText = hasInjuredPartyMember ? HealingRecoveryPendingText : HealingNoFurtherRecoveryText;
		Display_Text_From_Memory_ScreenRetrace_KeyboardInput(recoveryStatusText); // Sol:034D helper displays/waits;0357 below reads key
		Keyboard_Get_ASCII_Hex_Input();
		return; // Sol:does not reset recovery timer, debit money or roll healing
	}

	int16_t effectiveMedicalSkill = SkillLevel_Unskilled; // Sol: greatest party Medical skill; doctor service tier later overrides it
	uint16_t partyMedicId = Character_Jason;
	for (uint16_t partyMemberId = 0; partyMemberId < PartySize; ++partyMemberId)
	{
		if (Characters[partyMemberId].name != Character_Dead)
		{
			int16_t medicalSkill = (int8_t)Characters[partyMemberId].skillMedical;
			if (medicalSkill > effectiveMedicalSkill)
			{
				partyMedicId = partyMemberId;
				effectiveMedicalSkill = medicalSkill; // Sol:0048..005E strict signed improvement; first tie wins, fixes missing C braces
			}
		}
	}
	Citadel_Building_Dialogs(CitadelDialog_QueryPartyInjuries); // Sol:raw17 computes D325 injury query
	if (PartyHasInjuredMember == FALSE)
	{
		if (medicalServiceTier != MedicalService_UsePartyMedicAndEquipment)
			return; // Sol:02DC paid/nonzero service silently exits with no recovery reset
		Draw_Message_Box();
		Display_Text_From_Memory(HealingNoInjuriesText);
		Drain_Pending_Keyboard_Input();
		Keyboard_Get_ASCII_Hex_Input();
		return;
	}

	Menu_Memory_Variables(HealingMenuLayout);
	Draw_Menu_Border(HealingMenuLayout);
	Draw_Top_Graphic_Sidebar();
	uint16_t medicalEquipment = MedEquip_TornCloth;
	if (PurchasedMedkit != FALSE)
		medicalEquipment = MedEquip_Medkit;
	if (effectiveMedicalSkill >= SkillLevel_Good && PurchasedFieldSurgeryKit != FALSE)
		medicalEquipment = MedEquip_FieldSurgeryKit;
	if (medicalServiceTier != MedicalService_UsePartyMedicAndEquipment)
	{
		medicalEquipment = MedEquip_Medkit;
		if ((int16_t)medicalServiceTier > MedicalService_LastMedkitTier) // Sol:00CC signed JLE; service tiers>2 use hospital facilities
			medicalEquipment = MedEquip_HospitalFacilities;
		Display_Text_From_Memory(HealingDoctorText);
		effectiveMedicalSkill = (int16_t)medicalServiceTier; // Sol:doctor service tier overrides chosen party skill
	}
	else
	{
		int16_t medicNameId = (int8_t)Characters[partyMedicId].name;
		Display_Text_From_Memory(CharacterNames[medicNameId]);
	}

	if (effectiveMedicalSkill != SkillLevel_Unskilled)
	{
		Display_Text_From_Memory(HealingMedicSkillPrefixText);
		unsigned char  *medicalSkillText;
		if (effectiveMedicalSkill >= MedicalSkill_HospitalSurgeryTier)
			medicalSkillText = MedicalSkillText[MedicalDescription_Hospital]; // Sol:0160 constant FAR pointer25EE
		else if (effectiveMedicalSkill >= SkillLevel_Good)
			medicalSkillText = MedicalSkillText[effectiveMedicalSkill - SkillLevel_Average]; // Sol:014F biased25DA+skill*4
		else
			medicalSkillText = MedicalSkillText[effectiveMedicalSkill - SkillLevel_Amateur]; // Sol:013E biased25DE+skill*4
		Display_Text_From_Memory(medicalSkillText);
		Display_Text_From_Memory(HealingEquipmentPrefixText);
		Display_Text_From_Memory(MedicalEquipmentText[medicalEquipment - MedEquip_TornCloth]);
	}
	else
		Display_Text_From_Memory(HealingUnskilledMedicText);
	Display_Text_From_Memory(HealingAssistWoundedText);
	Set_Text_Colour_Bright_Green();

	for (uint16_t partyMemberId = 0; partyMemberId < PartySize; ++partyMemberId)
	{
		if (Characters[partyMemberId].name == Character_Dead)
			continue;
		int16_t maximumHealth = (int16_t)(CharacterHealthPerBodyPoint * (int8_t)Characters[partyMemberId].body); // Sol:0227 signed BYTE IMUL10, WORD maximum
		int16_t currentHealth = (int8_t)Characters[partyMemberId].health;
		if (currentHealth == maximumHealth)
			continue;
		Display_Text_4FA0_Value();
		int16_t characterNameId = (int8_t)Characters[partyMemberId].name;
		Display_Text_From_Memory(CharacterNames[characterNameId]);
		Display_Text_From_Memory(HealingCharacterResultText);
		uint8_t healingRollEntry = (uint8_t)HealingDice[effectiveMedicalSkill][medicalEquipment - MedEquip_TornCloth]; // Sol:023C..02A7 BYTE2601+skill*4+equipment, NOT4B88
		// Sol: Packed hexadecimal healing rule: A2 = 2D6 x 10; 82 = 2D6 x 8.
		// Sol: The low hexadecimal digit is the dice count; the high digit is the multiplier.
		int16_t healingDiceRemaining = (int16_t)(healingRollEntry & HealingRoll_DiceCountLowNibbleMask);
		int16_t healingMultiplier = (int16_t)(healingRollEntry >> HealingRoll_MultiplierHighNibbleShift);
		if (healingMultiplier == 0)
			healingMultiplier = 1; // Sol: no encoded multiplier means ordinary D6 healing, not zero healing
		int16_t healingDiceTotal = 0;
		while (healingDiceRemaining-- != 0) // Sol:01BC tests OLD count; zero exits, positive count rolls that many D6
			healingDiceTotal = (int16_t)(healingDiceTotal + RollD6());
		int16_t healthRecovered = (int16_t)(healingDiceTotal * healingMultiplier); // Sol:01C6 IMUL low WORD
		currentHealth = (int8_t)Characters[partyMemberId].health; // Sol:01D9 reload after display and dice calls
		int16_t healthAfterTreatment = (int16_t)(currentHealth + healthRecovered); // Sol:native WORD sum, not pointer arithmetic
		if (healthAfterTreatment > maximumHealth)
			healthAfterTreatment = maximumHealth; // Sol:01F2 signed upper clamp only
		Characters[partyMemberId].health = (unsigned char)healthAfterTreatment; // Sol:01F5 writes low BYTE
	}
	TextColour = EGA_BrightWhite;
	Wait_For_50Hz_Then_Check_Input();
	Prompt_And_Wait_For_Key();
	Draw_Health_and_C_Bills_Sidebar(FALSE);
	PartyHealthRecoveryTimer = HealingRecoveryWorldTicks; // Sol:02AF reset63 even if table rolls zero or nobody becomes fully healed
}
