// BTECH_1543.c
// Generated by decompiling BTECH.EXE using Reko decompiler version 0.11.2.0.
// Sol: Fresh systematic ASM/.dis audit 2026-09-17: all five methods checked,
// Sol: five mismatched. See docs/phase4/BTECH_1543_SYSTEMATIC_ASM_AUDIT.md.
// Sol: This checking pass adds comments only; substantive corrections are queued.
// Sol: Annotated research pseudo-C; not a standalone compilable replacement.

#include "BTECH.h"

// 1543:0004-07CA: void Combat_Weapon_UI_0004(Stack uint16 AttackerCombatantId)
// Called from: Combat_UI_Menu_Logic
// Sol: Summary: Choose an attacker's weapons and attack options.
// Sol: Outline: Collect critical-slot weapons, show ammo and range, handle shutdown/damaged equipment and override prompts, then record targets; range does not block selection.
void Combat_Weapon_UI_0004(unsigned short AttackerCombatantId)
{
	// Sol TODO ASM-1543-0004: Explicit near mech/raw-byte/target/text locals lose
	// Sol: native FAR3092 bindings with DS=3EDB; list strlen uses FAR SS:BP-20.
	// Sol: Native signed WORD ID/menu gates and CBW infantry Weapon differ from
	// Sol: unsigned C for high-bit values. Preserve 29BE's 09/0B column controls
	// Sol: and 29F9's 06/0F colour controls, not their current spacing/plain text.
	// Sol: BYTE list at BP-20h..BP-15h. The original later uses strlen on it;
	// Sol: do not silently replace that with the collector count (see BUG-012).
	unsigned char WeaponComponents[12] = { 0 };
	if (AttackerCombatantId < 12)
		seg3092->CombatantActionState[AttackerCombatantId] = 0;

	if (AttackerCombatantId >= 4)
	{
		// Sol: Friendly on-foot combat IDs 4..11 map to party records 0..7.
		// Sol: C5DB + combatId*11h = C61F + partySlot*11h (weapon byte +0Bh).
		Combat_MovementTarget_unknown_1774(AttackerCombatantId, 1);
		Menu_Memory_Variables(4);
		Draw_Top_Graphic_Sidebar();
		unsigned short OverrideTarget = TRUE;
		unsigned short WeaponIndex = (unsigned short)(signed short)(signed char)seg3092->Infantry[AttackerCombatantId - 4].Weapon; // Sol: native CBW before weapon-table lookup.
		// Sol: CBW sign-extends this target byte. Opcode 83's immediate FF is
		// Sol: also sign-extended: the comparison at 064C is with FFFF, NOT 00FF.
		signed short ExistingTarget = (signed char)
			seg3092->CombatWeaponTarget[AttackerCombatantId * 12];
		if (ExistingTarget != -1)
		{
			Display_Text_From_Memory("You are using your "); //3EDB:2AC6
			Display_Text_From_Memory(seg3EDB->WeaponStats[WeaponIndex].Name);
			Display_Text_From_Memory(" against a "); //3EDB:2ADA
			if (ExistingTarget >= 16)
				Display_Text_From_Memory("Human"); //3EDB:2AE6
			else
				Display_Text_From_Memory(seg3092->Mechs[ExistingTarget - 8].Name);
			// Sol: C33C + enemyCombatId*7Dh aliases Mechs[enemyCombatId-8].
			// Sol: Unlike the mech panel, this branch itself does not mask the fired
			// Sol: bit or recheck active state. Normal next-round entry follows
			// Sol:1631:0C63..0CC9 cleanup for ALL24 units; AI/picker writes raw IDs.
			// Sol: Preserve CBW here, not an extra mask. Malformed bytes remain
			// Sol: outside that normal caller contract.
			Display_Text_From_Memory(" at "); //3EDB:2AEC
			unsigned short RangeBracket = Combat_Calculate_RangeBracket(ExistingTarget, WeaponIndex);
			Display_Text_From_Memory(seg3EDB->WeaponRangeText[RangeBracket]);
			Display_Text_From_Memory(" range already.\r\rOverride?"); //3EDB:2AF1
			OverrideTarget = Prompt_Yes_No(1);
		}
		if (OverrideTarget != FALSE)
		{
			Draw_Top_Graphic_Sidebar();
			Display_Text_From_Memory("Use your\r"); //3EDB:2B0C
			Display_Text_From_Memory(seg3EDB->WeaponStats[WeaponIndex].Name);
			Display_Text_From_Memory("\ragainst:"); //3EDB:2B16
			Combat_Select_Weapon_Target_UI(AttackerCombatantId, WeaponIndex, 0);
		}
		goto RestoreCombatPanels;
	}

	Mech *AttackingMech = &seg3092->Mechs[AttackerCombatantId];
	unsigned char *MechBytes = (unsigned char *)AttackingMech;
	unsigned short CollectedWeaponCount = 0;
	for (unsigned short CriticalOffset = 0x33; CriticalOffset < 0x56; CriticalOffset++)
	{
		if (CollectedWeaponCount >= 12)
			continue;
		unsigned char Component = MechBytes[CriticalOffset];
		unsigned char ComponentId = Component & MechComponentIdMask;
		if (ComponentId >= Mech_Small_Laser && ComponentId <= Mech_SRMissile6)
			WeaponComponents[CollectedWeaponCount++] = Component;
	}
	Menu_Memory_Variables(4);
	Draw_Top_Graphic_Sidebar();
	// Sol: Exact heat equality with 30, not >=30. Shutdown sets the high bit
	// Sol: in all twelve planned targets, preserving each low-seven-bit target.
	if (seg3092->Mech_HeatLevel[AttackerCombatantId] == MECH_Heat_Max)
	{
		Display_Text_From_Memory("This 'Mech has overheated and shut down."); //3EDB:2904
		Prompt_And_Wait_For_Key_2A4F();
		for (unsigned short WeaponSlot = 0; WeaponSlot < 12; WeaponSlot++)
			seg3092->CombatWeaponTarget[AttackerCombatantId * 12 + WeaponSlot] |= 0x80;
		goto RestoreCombatPanels;
	}
	if (AttackingMech->SensorHits == 1)
	{
		Display_Text_From_Memory("This Mech's sensors are damaged. Accuracy is impaired."); //3EDB:292D
		Keyboard_Get_ASCII_Hex_Input();
		Draw_Top_Graphic_Sidebar();
	}
	if (AttackingMech->SensorHits == 2)
	{
		Display_Text_From_Memory("This Mech's sensors are destroyed. It cannot fire its weapons."); //3EDB:2964
		Keyboard_Get_ASCII_Hex_Input();
		Draw_Top_Graphic_Sidebar();
		return; //Sol: Native jumps directly to the epilogue, skipping panel restore.
	}
	Display_Text_From_Memory("Select the weapon to fire."); //3EDB:29A3
	unsigned short WeaponChoice;
	unsigned short WeaponMenuCount;
	do
	{
		Combat_MovementTarget_unknown_1774(AttackerCombatantId, 1);
		// Sol: Geometry is based on a string LENGTH, not a frame pointer. If
		// Sol: twelve entries were collected there is no NUL left in the array.
		WeaponMenuCount = Loop_Until_TextPtr_Null(WeaponComponents);
		seg305B->t0056 = WeaponMenuCount + 2;
		seg305B->w0052 = 0x16 - WeaponMenuCount;
		Menu_Memory_Variables(5);
		Draw_Menu_Border(0);
		Draw_Top_Graphic_Sidebar();
		Set_Text_Colour_Bright_Green_28A2();
		Display_Text_From_Memory("Weapon\t\vAmmo Target  Range"); // Sol:3EDB:29BE includes column controls09/0B.
		for (unsigned short WeaponSlot = 0; WeaponSlot < 12; WeaponSlot++)
		{
			seg3092->HorizontalLine_Offset = 0;
			seg3092->VerticalLine_Offset = WeaponSlot + 1;
			unsigned char Component = WeaponComponents[WeaponSlot];
			if (Component == 0)
				continue;
			unsigned char *PlannedTarget = &seg3092->CombatWeaponTarget[
				AttackerCombatantId * 12 + WeaponSlot];
			seg3092->EGATextColour = EGA_BrightWhite;
			if (*PlannedTarget != 0xFF)
				seg3092->EGATextColour = seg3EDB->GraphicsAdapter == 0 ? EGA_Blue : EGA_BrightYellow;
			if ((Component & Component_Destroyed) != 0)
				seg3092->EGATextColour = seg3EDB->GraphicsAdapter == 0 ? EGA_Green : EGA_DarkGrey;
			unsigned short WeaponIndex = (Component & MechComponentIdMask) - 1;
			Display_Text_From_Memory(seg3EDB->WeaponStats[WeaponIndex].Name);
			seg3092->HorizontalLine_Offset = 0x0B;
			if ((Component & Component_Destroyed) != 0)
			{
				Display_Text_From_Memory("Destroyed"); //3EDB:29D9
				*PlannedTarget = 0xFF;
				continue;
			}
			// Sol: Native reads raw +27h+slot for ALL twelve UI entries. Slots
			// Sol: ten and eleven alias WalkMove and JumpMove, not ammo (BUG-012).
			unsigned char Ammo = MechBytes[0x27 + WeaponSlot];
			if (Ammo == 0xFF)
				Display_Text_From_Memory("Full"); //3EDB:29E3
			else if (Ammo == 0)
				Display_Text_From_Memory("Out"); //3EDB:29E8
			else
			{
				unsigned char *DynamicText = (unsigned char *)&seg3092->DynamicString;
				ASM_Text_Formatting_3BB6(Ammo, DynamicText, 10);
				unsigned short DigitCount = Loop_Until_TextPtr_Null(DynamicText);
				for (unsigned short Column = DigitCount; Column < 3; Column++)
					Display_Text_From_Memory(" "); //Sol: Left-pad numeric ammo to width three.
				Display_Text_From_Memory(DynamicText);
			}
			seg3092->HorizontalLine_Offset = 0x10;
			if (*PlannedTarget != 0xFF &&
				seg3092->CombatantActive[*PlannedTarget & 0x7F] == FALSE)
				*PlannedTarget = 0xFF;
			if (*PlannedTarget == 0xFF)
				Display_Text_From_Memory("None"); //3EDB:29F4
			else
			{
				// Sol: Merely rendering an active planned target clears its high bit.
				*PlannedTarget &= 0x7F;
				unsigned short TargetCombatantId = *PlannedTarget;
				unsigned short SavedTextRow = seg3092->VerticalLine_Offset;
				Display_Text_From_Memory(TargetCombatantId >= 16 ? "Human" :
					seg3092->Mechs[TargetCombatantId - 8].Name); //3EDB:29EE / C33C+id*7Dh
				// Sol:0387 uses a segment-byte address, not a bounded Mech array.
				// Targets6/7 alias character bytes atC62A/C6A7; portable C binds
				// that read through OriginalSavedState, never Mechs[-2/-1].
				seg3092->HorizontalLine_Offset = 0x18;
				seg3092->VerticalLine_Offset = SavedTextRow;
				unsigned short RangeBracket = Combat_Calculate_RangeBracket(TargetCombatantId, WeaponIndex);
				Display_Text_From_Memory(seg3EDB->WeaponRangeText[RangeBracket]);
			}
		}
		seg3092->HorizontalLine_Offset = 0;
		WeaponMenuCount = Loop_Until_TextPtr_Null(WeaponComponents);
		seg3092->VerticalLine_Offset = WeaponMenuCount + 1;
		Display_Text_From_Memory("\006\017Done"); // Sol:3EDB:29F9 restores white before the label.
		seg305B->ptr00E6 = WeaponMenuCount + 1; //Sol: WORD row count, not a pointer.
		Menu_Memory_Variables(5);
		WeaponChoice = Display_Menu_Choices_And_Check(5);
		if (WeaponChoice < WeaponMenuCount)
		{
			unsigned char *PlannedTarget = &seg3092->CombatWeaponTarget[
				AttackerCombatantId * 12 + WeaponChoice];
			unsigned char *UnavailableText = 0;
			if ((WeaponComponents[WeaponChoice] & Component_Destroyed) != 0)
				UnavailableText = "That weapon has been destroyed.\r\rChoose a different one."; //3EDB:2A00
			else if (MechBytes[0x27 + WeaponChoice] == 0)
				UnavailableText = "That weapon is out of ammunition.\r\rChoose a different one."; //3EDB:2A39
			if (UnavailableText != 0)
			{
				// Sol: Distinct messages share this popup/redraw tail; the old goto
				// Sol: accidentally replaced the destroyed message with the ammo one.
				Combat_Weapon_Display_Text_And_Menu_Options(UnavailableText);
				DrawCall_Combat_Menu(seg3092->BTBORDER_XStart,
					seg305B->w00E2 + seg3092->BTBORDER_YStart + WeaponChoice,
					seg305B->t00E4, seg305B->t00EC);
			}
			else
			{
				unsigned short OverrideTarget = TRUE;
				if (*PlannedTarget != 0xFF)
				{
					Menu_Memory_Variables(4);
					Draw_Top_Graphic_Sidebar();
					Display_Text_From_Memory("That weapon is already going to be fired. Override?"); //3EDB:2A74
					OverrideTarget = Prompt_Yes_No(1);
					Draw_Top_Graphic_Sidebar();
				}
				if (OverrideTarget != FALSE)
				{
					*PlannedTarget = 0xFF; //Sol: Clear old target BEFORE the picker.
					Menu_Memory_Variables(4);
					Draw_Menu_Border(4);
					Draw_Top_Graphic_Sidebar();
					Display_Text_From_Memory("Choose the enemy to shoot at:"); //3EDB:2AA8
					Combat_Select_Weapon_Target_UI(AttackerCombatantId,
						(WeaponComponents[WeaponChoice] & 0x7F) - 1, WeaponChoice);
					Menu_Memory_Variables(3);
					Draw_Top_Graphic_Sidebar();
					Menu_Memory_Variables(4);
					Draw_Top_Graphic_Sidebar();
				}
			}
		}
	} while (WeaponChoice != WeaponMenuCount);

RestoreCombatPanels:
	seg3092->EGATextColour = EGA_BrightWhite;
	Menu_Memory_Variables(4);
	Draw_Top_Graphic_Sidebar();
	Draw_Menu_Border(4);
	seg3092->EGATextColour = EGA_BrightWhite;
	Menu_Memory_Variables(3);
	Draw_Top_Graphic_Sidebar();
	Draw_Menu_Border(3);
	seg3092->EGATextColour = EGA_BrightWhite;
}

// 1543:07CB-0A34: void Combat_Select_Weapon_Target_UI(Stack WORD attacker, weapon, slot)
// Called from: Combat_Weapon_UI_0004; Combat_Kick_Target
// Sol: Summary: Choose a target for a selected weapon.
// Sol: Outline: Cycle active enemy slots, display their identity and range, and store a target or FF on Cancel; an out-of-range target can still be selected.
void Combat_Select_Weapon_Target_UI(unsigned short AttackerCombatantId,
	unsigned short WeaponIndex, unsigned short WeaponSlot)
{
	// Sol TODO ASM-1543-07CB: 2B22 ends 06/0F; 2B54 is Weapon: +06/0F,
	// Sol: not Weapon: +space. Enemy weapon lookup uses signed BYTE IMUL;
	// Sol: enemy-kind/cursor-wrap comparisons use signed WORDs, not unsigned.
	Set_Text_Colour_Bright_Green_28A2();
	Display_Text_From_Memory("\r\rTarget:\r\rRange:"); //3EDB:2B22 (colour controls omitted)
	unsigned short TargetMenuChoice = 1;
	do
	{
		// Sol: Persistent cursor at DS:2B20. Enemy IDs 12..23 cycle; inactive
		// Sol: entries skip without a prompt. No all-enemies-inactive exit exists.
		if (seg3092->CombatantActive[seg3EDB->EnemyTargetId] == FALSE)
			goto NextEnemy;
		Menu_Memory_Variables(3);
		Draw_Menu_Border(3);
		Draw_Top_Graphic_Sidebar();
		seg305B->Menu_HorizontalSections = 3;
		Display_Text_From_Memory("Target here Next enemy Cancel"); //3EDB:2B36
		Combat_MovementTarget_unknown_1774(seg3EDB->EnemyTargetId, 1);
		Menu_Memory_Variables(4);
		if (seg3EDB->EnemyTargetId >= 16)
		{
			Set_Text_Colour_Bright_Green_28A2();
			seg3092->HorizontalLine_Offset = 0;
			seg3092->VerticalLine_Offset = 8;
			Display_Text_From_Memory("Weapon: "); //3EDB:2B54
		}
		else
			Draw_Horizontal_EGA_Line(8, 0x48, 0x57, 0x57, 0);
		seg3092->HorizontalLine_Offset = 0;
		seg3092->VerticalLine_Offset = 5;
		if (seg3EDB->EnemyTargetId >= 16)
		{
			Display_Text_From_Memory("Human      "); //3EDB:2B5E
			Draw_Horizontal_EGA_Line(8, 0x50, 0x57, 0x57, 0);
			// Sol: C597 + combatId*11h aliases the enemy character's Weapon byte;
			// Sol: enemy infantry combat IDs 16..23 map to character records 8..15.
			unsigned short EnemyWeaponIndex = seg3092->Infantry[seg3EDB->EnemyTargetId - 8].Weapon;
			Draw_EGA_Text_To_Screen(seg3EDB->WeaponStats[EnemyWeaponIndex].Name,
				1, 10, EGA_BrightWhite, EGA_Black);
		}
		else
		{
			Display_Text_From_Memory(seg3092->Mechs[seg3EDB->EnemyTargetId - 8].Name);
			Draw_Horizontal_EGA_Line(8, 0x48, 0x57, 0x4F, 0);
		}
		seg3092->HorizontalLine_Offset = 0;
		seg3092->VerticalLine_Offset = 7;
		Move_Map_View_To_Packed_Position_17BB(seg3092->CombatantPackedX[AttackerCombatantId],
			seg3092->CombatantPackedY[AttackerCombatantId]);
		unsigned short RangeBracket = Combat_Calculate_RangeBracket(seg3EDB->EnemyTargetId, WeaponIndex);
		Display_Text_From_Memory(seg3EDB->WeaponRangeText[RangeBracket]);
		Display_Text_From_Memory("  "); //Sol: 3EDB:2B6A is two spaces, NOT the destruction message at 2B6D.
		Menu_Memory_Variables(3);
		TargetMenuChoice = Display_Menu_Choices_And_Check(3);
		if (TargetMenuChoice == 1)
			goto NextEnemy;
		if (TargetMenuChoice == 0)
			seg3092->CombatWeaponTarget[AttackerCombatantId * 12 + WeaponSlot] = seg3EDB->EnemyTargetId;
		else if (TargetMenuChoice == 2)
			seg3092->CombatWeaponTarget[AttackerCombatantId * 12 + WeaponSlot] = 0xFF;
		// Sol: Out-of-range is displayed but does not block Target here. The kick
		// Sol: caller uses the SAME picker with weapon-table index 20h and slot 11.
		continue;
NextEnemy:
		if (++seg3EDB->EnemyTargetId > 23)
			seg3EDB->EnemyTargetId = 12;
	} while (TargetMenuChoice == 1);
}

// 1543:0A35-0C71: void Combat_Mech_Eject_0A35(Stack uint16 MechCombatantId)
// Called from: Combat_Mechanics
// Sol: Summary: Retire a destroyed mech and eject friendly occupants.
// Sol: Outline: Mark inactive/wreck, clear exact target references, preserve its name initial, handle arena companions/map patch and messages, then place pilot/rider on foot; seat IDs remain stored.
void Combat_Mech_Eject_0A35(unsigned short MechCombatantId)
{
	// Sol TODO ASM-1543-0A35: Target and DestroyedMech locals need FAR3092
	// Sol: bindings. Native record normalization/ejection/speed gates are signed
	// Sol: WORD tests. Pilot/rider source coordinates use normalized MechRecordId,
	// Sol: not the original combatant ID (equal for ordinary friendly IDs0..3).
	// Sol: Header3986 is already WORD-sized: its clear DOES match native0B1A.
	seg3092->CombatantActive[MechCombatantId] = FALSE;
	seg3092->CombatantCasualtyFlags[MechCombatantId] = TRUE;
	for (unsigned short CombatantId = 0; CombatantId < 24; CombatantId++)
		for (unsigned short WeaponSlot = 0; WeaponSlot < 12; WeaponSlot++)
		{
			unsigned char *PlannedTarget = &seg3092->CombatWeaponTarget[CombatantId * 12 + WeaponSlot];
			// Sol: Exact signed-byte comparison, WITHOUT masking the high bit.
			if ((signed short)(signed char)*PlannedTarget == MechCombatantId)
				*PlannedTarget = 0xFF;
		}
	unsigned short MechRecordId = MechCombatantId >= 12 ? MechCombatantId - 8 : MechCombatantId;
	Mech *DestroyedMech = &seg3092->Mechs[MechRecordId];
	seg3092->DestroyedMechNameInitial[MechRecordId] = DestroyedMech->Name[0];
	DestroyedMech->Name[0] = MECH_Destroyed;
	if (seg3092->ArenaRentalMechMode != FALSE)
	{
		if (MechRecordId == 4)
		{
			// Sol: C995 is mech RECORD FIVE; active WORD 4084 is COMBATANT 13.
			seg3092->Mechs[5].Name[0] = MECH_Destroyed;
			seg3092->CombatantActive[13] = FALSE;
		}
		else if (MechRecordId == 5)
			Starport_MapPatch_SaveApply_Or_Restore_0C72(FALSE);
	}
	seg3092->CombatNotificationLatch = FALSE;
	seg3092->Bool_ShowArmShotOffAnimation = FALSE;
	Menu_Memory_Variables(4);
	Set_Text_Colour_Bright_Green_28A2();
	// Sol: Rental suppression tests the ORIGINAL combatant ID 13, not the
	// Sol: translated mech-record ID 5. They must remain separate variables.
	if (!(seg3092->ArenaRentalMechMode != FALSE && MechCombatantId == 13) &&
		seg3EDB->CombatMessageVerbosity != CombatMessage_None)
		Combat_CombatMessageVerbosityFilter("\rMech is destroyed!"); //3EDB:2B6D
	if (MechRecordId < 4)
	{
		Display_Text_From_Memory("\rMen eject!"); //3EDB:2B81
		unsigned char PilotId = DestroyedMech->PilotId;
		if (PilotId != MECH_NoPilot)
		{
			seg3092->Infantry[PilotId].Piloting = Character_OnFoot;
			seg3092->CombatantActive[PilotId + 4] = TRUE;
			seg3092->CombatantPackedX[PilotId + 4] = seg3092->CombatantPackedX[MechCombatantId];
			seg3092->CombatantPackedY[PilotId + 4] = seg3092->CombatantPackedY[MechCombatantId];
		}
		unsigned char RiderId = DestroyedMech->RiderId;
		if (RiderId != MECH_NoRider)
		{
			seg3092->Infantry[RiderId].Piloting = Character_OnFoot;
			seg3092->CombatantActive[RiderId + 4] = TRUE;
			unsigned short RiderX = seg3092->CombatantPackedX[MechCombatantId] + 1;
			// Sol: Test bit 80h in the LOW byte, then add 0080h to the full WORD.
			// Sol: This crosses the packed-coordinate boundary; do not use XOR.
			if ((RiderX & 0x80) != 0)
				RiderX += 0x80;
			seg3092->CombatantPackedX[RiderId + 4] = RiderX;
			seg3092->CombatantPackedY[RiderId + 4] = seg3092->CombatantPackedY[MechCombatantId];
		}
		if (seg3EDB->CombatSpeedSetting < 5)
			GameSpeed_RateControl();
	}
	// Sol: Pilot/RiderId bytes in the destroyed mech are retained, not cleared.
	seg3092->EGATextColour = EGA_BrightWhite;
}

// 1543:0C72-0CDD: void Starport_MapPatch_SaveApply_Or_Restore_0C72(Stack word RestoreSavedBytes)
// Called from: Main_Game_Loop; DOS_Load_Map_Files; Combat_Mech_Eject_0A35;
// Citadel_Building_Dialogs. Sol: Previously reviewed; behavior retained here.
// Sol: Summary: Apply or remove the Starport map patch.
// Sol: Outline: Save affected bytes before installation or restore the previously saved bytes on exit.
void Starport_MapPatch_SaveApply_Or_Restore_0C72(unsigned short RestoreSavedBytes)
{
	// Sol TODO ASM-1543-0C72: StarportMapRegion is explicitly near in C;
	// Sol: native uses ES=246C with DS=3EDB. Preserve the FAR246C:1C1D binding.
	// Sol: The 38-byte save/nonzero-override/restore loops otherwise agree.
	// Sol: 246C:1C1D is byte offset 0x0C00 inside the MTP tile payload
	// Sol: loaded at 246C:101D. The argument is a 16-bit stack word.
	unsigned char* StarportMapRegion = &seg246C->MapTile[0x0C00];
	if (RestoreSavedBytes != FALSE)
	{
		for (unsigned short ByteIndex = 0; ByteIndex < 0x26; ByteIndex++)
			StarportMapRegion[ByteIndex] = seg3EDB->StarportSavedMapBytes[ByteIndex];
	}
	else
	{
		for (unsigned short ByteIndex = 0; ByteIndex < 0x26; ByteIndex++)
		{
			seg3EDB->StarportSavedMapBytes[ByteIndex] = StarportMapRegion[ByteIndex];
			if (seg3EDB->StarportMapPatchOverrides[ByteIndex] != 0)
				StarportMapRegion[ByteIndex] = seg3EDB->StarportMapPatchOverrides[ByteIndex];
		}
	}
}

// 1543:0CDE-0EE5: uint32 Prompt_For_Unsigned_Decimal_0CDE()
// Called from: Mechlube_Buy_Ammo; Citadel_Building_Dialogs (investment/stock)
// Sol: Summary: Read an unsigned decimal value from the player.
// Sol: Outline: Redraw up to seven digits, Backspace deletes and Escape resets without exiting; Enter parses a 32-bit value, including zero for empty input, and restores white text.
unsigned long Prompt_For_Unsigned_Decimal_0CDE()
{
	// Sol TODO ASM-1543-0CDE: InputText must retain FAR3092:0012, not a
	// Sol: near pointer in DS3EDB. Native length gate is signed WORD and final
	// Sol: digit read is CBW/CWD; generated0..7 ASCII digits make these agree
	// Sol: with current unsigned expressions under the valid-input contract.
	unsigned char *InputText = (unsigned char *)&seg3092->DynamicString;
	InputText[0] = KEY_ZERO;
	InputText[1] = 0;
	unsigned short SavedTextColumn = seg3092->HorizontalLine_Offset;
	unsigned short SavedTextRow = seg3092->VerticalLine_Offset;
	seg3092->EGATextColour = seg3EDB->GraphicsAdapter == 0 ? EGA_Blue : EGA_Green;
	unsigned short EnterPressed = FALSE;
	do
	{
		seg3092->HorizontalLine_Offset = SavedTextColumn;
		seg3092->VerticalLine_Offset = SavedTextRow;
		Display_Text_From_Memory(InputText);
		// Sol: Use the text cursor AFTER display to clear the rest of its eight-
		// Sol: pixel-high row. Both coordinate sums are shifted, not just one term.
		unsigned short ClearX = (seg3092->BTBORDER_XStart + seg3092->HorizontalLine_Offset) << 3;
		unsigned short ClearY = (seg3092->BTBORDER_YStart + seg3092->VerticalLine_Offset) << 3;
		unsigned short ClearRight = ((seg3092->BTBORDER_XStart + seg3092->BTBORDER_XEnd) << 3) - 1;
		Draw_Horizontal_EGA_Line(ClearX, ClearY, ClearRight, ClearY + 7, EGA_Black);
		signed short Key = Keyboard_Get_ASCII_Hex_Input();
		if (Key == KEY_CARRIAGERETURN)
			EnterPressed = TRUE;
		else
		{
			unsigned short TextLength = Loop_Until_TextPtr_Null(InputText);
			if (Key >= KEY_ZERO && Key <= KEY_NINE)
			{
				// Sol: Limit is seven stored decimal digits, checked before stripping
				// Sol: leading zeroes. Empty input is allowed after Backspace.
				if (TextLength < 7)
				{
					while (InputText[0] == KEY_ZERO)
						Append_Large_Text_To_Memory(InputText, &InputText[1]);
					TextLength = Loop_Until_TextPtr_Null(InputText);
					InputText[TextLength] = (unsigned char)Key;
					InputText[TextLength + 1] = 0;
				}
			}
			else
			{
				// Sol: Escape resets to "0"; it does NOT accept/cancel/exit.
				if (Key == KEY_ESC)
				{
					InputText[0] = KEY_ZERO;
					InputText[1] = 0;
				}
				if (Key == KEY_BACKSPACE && TextLength != 0)
					InputText[TextLength - 1] = 0;
			}
		}
	} while (EnterPressed == FALSE);

	// Sol: Native uses 207F:3E2E to multiply a DX:AX accumulator by ten, then
	// Sol: ADD/ADC and SUB/SBB add the next digit. Seven digits fit in 32 bits.
	unsigned long Value = 0;
	for (unsigned short DigitIndex = 0; InputText[DigitIndex] != 0; DigitIndex++)
		Value = Value * 10UL + InputText[DigitIndex] - KEY_ZERO;
	seg3092->EGATextColour = EGA_BrightWhite;
	return Value; //Sol: Empty text returns zero. DX:AX is the 32-bit result, not money state.
}
