// BTECH_204B.c
// Generated by decompiling BTECH.EXE
// using Reko decompiler version 0.11.2.0.

#include "BTECH.h"

// Sol:Fresh systematic comparison complete: docs/phase4/BTECH_204B_SYSTEMATIC_ASM_AUDIT.md.
// Sol:All19 retained implementations checked:17 local contract matches,2 dispatcher argument-binding mismatches.
// Sol:No executable corrections here; sound/IRQ bindings are reference effects, not playback validation.

// Sol: Exploration dump's14 code-region differences are all writable CS state
// Sol: below; no instruction mismatch. IRQ/setup/idle visited, PC/Tandy note
// Sol: stream handlers NOT observed. Do not infer audible playback validation.

// Sol:Complete music-path audit and platform boundaries: docs/phase4/BTECH_STARTUP_MUSIC_PLATFORM_AUDIT.md.
// Sol:Named overlapping CS204B state view, not a portable serialized structure.
typedef struct MusicState_204B_t {
	unsigned short systemTickDivider; //CS000E, only AL decremented
	unsigned short systemTickDividerReload; //CS0010
	unsigned short savedIrq0Offset, savedIrq0Segment; //CS0012/0014
	unsigned short interruptCallbackOffset, interruptCallbackSegment; //CS0016/0018
	unsigned short streamOffset, streamSegment; //CS0205/0207
	unsigned char ticksUntilNextNote, noteTickReload; //CS0209/020A
} MusicState_204B_t;
MusicState_204B_t SoundState;

// Sol:0139/00CF: unsigned BYTE note /12 -> octave/semitone, native DWORD DIV then8086 WORD SHL.
// Sol: Summary: Convert a music note to its speaker pitch divisor.
// Sol: Outline: Index the original embedded note-divisor table using the native note interpretation.
unsigned short Music_Note_To_Pit_Divisor_0139(unsigned char Note)
{
	// Sol:Fresh ASM check0139..015F plus00CF..00DD: BYTE DIV12, table WORD/DWORD DIV and unmasked CL shift agree.
	// Sol:C return models native DX, not AX; named CS tables/state are logical relocated views.
	static const unsigned short SemitoneFrequency[12] = {0x105A,0x1153,0x125B,0x1372,0x149A,0x15D4,0x1720,0x1880,0x19F5,0x1B80,0x1D23,0x1EDE};
	unsigned short Divisor = 0x1234DEUL / SemitoneFrequency[Note % 12];
	unsigned char ShiftCount = (unsigned char)(8 - Note / 12);
	while (ShiftCount-- != 0) Divisor <<= 1; // Sol:8086 does NOT mask CL to five bits; Word wrap each shift.
	return Divisor;
}

// Sol: Summary: Set the PC-speaker pitch.
// Sol: Outline: Write the divisor's low and high bytes to the PIT channel.
void Music_Write_Pit_Divisor_00B2(unsigned short Divisor)
{
	// Sol:Fresh ASM check00B2..00BC: native CL then CH to port42, preserving AX; C argument models CX.
	__out<byte>(0x42, (unsigned char)Divisor);
	__out<byte>(0x42, (unsigned char)(Divisor >> 8)); // Sol:does not set PIT mode or speaker gate.
}

// Sol: Summary: Write the PC-speaker divisor for one music note.
// Sol: Outline: Use divisor14 for a high-bit note, otherwise calculate pitch, then write both PIT bytes without changing the gate.
void Music_Emit_Pc_Note_0187(unsigned char Note)
{
	// Sol:Fresh ASM check0187..019C: high-bit gate chooses divisor14; otherwise0139/00B2, not a speaker-off call.
	Music_Write_Pit_Divisor_00B2((Note & 0x80) != 0 ? 14 : Music_Note_To_Pit_Divisor_0139(Note)); // Sol:ANY high-bit BYTE writes divisor14, not a native speaker-off command.
}

// Sol: Summary: Send one music note to a Tandy channel.
// Sol: Outline: Decode channel and note fields and write the native sound-chip command bytes.
void Music_Emit_Tandy_Note_01B8(unsigned char Note, unsigned char Channel)
{
	// Sol:Fresh ASM check01B8..01FD: AL note/AH channel, BYTE octave shift, SAR and two PSG writes agree.
	static const unsigned short TonePeriods[12] = {0x06AC,0x064C,0x05F0,0x0598,0x054C,0x04FE,0x04B6,0x0474,0x0432,0x03F6,0x03BA,0x0384};
	unsigned short Period = TonePeriods[Note % 12];
	unsigned char ShiftCount = (unsigned char)(Note / 12 - 2);
	while (ShiftCount-- != 0) Period = (Period >> 1) | (Period & 0x8000); // Sol:8086 SAR, BYTE count unmasked; high bit has no separate rest test here.
	unsigned char ChannelLatch = Channel == 0 ? 0x80 : Channel == 1 ? 0xA0 : 0xC0;
	__out<byte>(0xC0, ChannelLatch | (Period & 0x0F));
	__out<byte>(0xC0, (Period >> 4) & 0x3F); // Sol:PSG tone-register protocol, not DMA despite Reko label.
}

// Sol: Summary: Read the next music-stream byte.
// Sol: Outline: Read through the shared FAR cursor and advance its WORD offset without segment carry.
static unsigned char Music_Read_Stream_Byte()
{
	// Sol:Fresh inline-ASM check024F/0298: LODSB with inherited DF clear, WORD SI wrap, no selector carry.
	// Sol:Shared cursor abstracts local SI; tick contracts require stable, non-reentrant stream/state/IO bindings.
	unsigned char far *StreamSegment = (unsigned char far *)((unsigned long)SoundState.streamSegment << 16);
	return StreamSegment[SoundState.streamOffset++]; // Sol:LODSB offset WORD wraps without segment carry.
}

// Sol:0233 consumes extra words through parent dispatcher's BP; explicit arguments below are research notation.
// Sol: Summary: Start PC-speaker stream playback.
// Sol: Outline: Store the FAR stream cursor and low-byte cadence, and make the first music tick immediately due.
void Music_Start_Stream_0233(unsigned char far *Stream, unsigned short Cadence)
{
	// Sol:Fresh ASM check0233..024E: parent's BP+8/+A/+C supplies cursor/cadence; setup does NOT bind callback itself.
	// Sol:Explicit parameters are a research adapter;0306 must supply them, currently queued as a mismatch.
	SoundState.streamOffset = (unsigned short)(unsigned long)Stream;
	SoundState.streamSegment = (unsigned short)((unsigned long)Stream >> 16);
	SoundState.noteTickReload = (unsigned char)Cadence;
	SoundState.ticksUntilNextNote = 1; // Sol:first IRQ consumes first note; reload zero means256 ticks thereafter.
}

// Sol: Summary: Start Tandy stream playback.
// Sol: Outline: Initialise the stream cursor and cadence, then set volume3 on the three PSG tone channels.
void Music_Start_Tandy_Stream_020B(unsigned char far *Stream, unsigned short Cadence)
{
	// Sol:Fresh ASM check020B..0232: same four stores as0233, then PSG93/B3/D3; no callback-binding store here.
	Music_Start_Stream_0233(Stream, Cadence);
	__out<byte>(0xC0, 0x93); __out<byte>(0xC0, 0xB3); __out<byte>(0xC0, 0xD3); // Sol:PSG tone-channel volume3 setup; noise channel not programmed.
}

// Sol: Summary: Silence the Tandy music channels.
// Sol: Outline: Write the native mute commands and stop or reset the associated playback state.
void Music_Stop_Tandy_0160()
{
	// Sol:Fresh ASM check0160..0178: idle callback offset, speaker gate clear, PSG9F/BF/DF in that order agree.
	PC_Speaker_Set_Value_0179();
	__out<byte>(0xC0, 0x9F); __out<byte>(0xC0, 0xBF); __out<byte>(0xC0, 0xDF); // Sol:mute three PSG tone channels.
}

// Sol: Summary: Process one Tandy music callback.
// Sol: Outline: Read stream commands, apply cadence and termination controls, and emit channel notes.
void Music_Tandy_Stream_Tick_024F()
{
	// Sol:Fresh ASM check024F..0297: BYTE cadence, first-zero stop, PSG0/PC/PSG1/PSG2 order and four-byte cursor commit agree.
	// Sol:Native commits SI after all note writes; helper commits eagerly. Stable non-reentrant state/IO contract only.
	// Sol:Inherited DF clear; interrupt/register mechanics abstracted, not an arbitrary-DF native ISR certificate.
	if (--SoundState.ticksUntilNextNote != 0) return;
	SoundState.ticksUntilNextNote = SoundState.noteTickReload;
	unsigned short ReadOffset = SoundState.streamOffset;
	unsigned char FirstNote = Music_Read_Stream_Byte();
	if (FirstNote == 0)
	{
		SoundState.streamOffset = ReadOffset; // Sol:terminator branch does NOT commit local SI into0205.
		Music_Stop_Tandy_0160(); return;
	}
	Music_Emit_Tandy_Note_01B8(FirstNote, 0);
	Music_Emit_Pc_Note_0187(Music_Read_Stream_Byte());
	Music_Emit_Tandy_Note_01B8(Music_Read_Stream_Byte(), 1);
	Music_Emit_Tandy_Note_01B8(Music_Read_Stream_Byte(), 2);
}

// Sol: Summary: Process one PC-speaker music callback.
// Sol: Outline: Read stream commands, apply cadence and termination controls, and emit speaker notes.
void Music_Pc_Stream_Tick_0298()
{
	// Sol:Fresh ASM check0298..02E3: BYTE cadence, single-zero skip/double-zero stop, cursor commit before PIT and high-bit14 agree.
	// Sol:Inherited DF clear and stable non-reentrant stream bindings; register saves abstracted.
	if (--SoundState.ticksUntilNextNote != 0) return;
	SoundState.ticksUntilNextNote = SoundState.noteTickReload;
	unsigned short ReadOffset = SoundState.streamOffset;
	unsigned char Note = Music_Read_Stream_Byte();
	if (Note == 0)
	{
		Note = Music_Read_Stream_Byte(); // Sol:single zero skips straight to next BYTE in SAME tick.
		if (Note == 0) { SoundState.streamOffset = ReadOffset; PC_Speaker_Set_Value_0179(); return; }
	}
	Music_Emit_Pc_Note_0187(Note);
}

// Sol:0020/003C interrupt effect model, NOT a C ISR signature; returns1 for chaining saved system IRQ0.
// Sol: Summary: Advance the game's music clock.
// Sol: Outline: Run the music callback every IRQ, then test the old system-divider BYTE to chain IRQ0 or decrement and acknowledge it.
unsigned short Music_Clock_Tick_0020()
{
	// Sol:Fresh ASM check0020..0047: callback FIRST, old low divider zero reload/chains, else BYTE decrement preserving high.
	// Sol:Valid callback segment=relocated CS, offsets idle0186/024F/0298 only; C return abstracts FAR chain versus PIC EOI/IRET.
	if (SoundState.interruptCallbackOffset == 0x024F) Music_Tandy_Stream_Tick_024F();
	else if (SoundState.interruptCallbackOffset == 0x0298) Music_Pc_Stream_Tick_0298();
	// Sol:Native CALL FAR also supports arbitrary callback offsets; model covers the two valid stream tables/idle only.
	if ((unsigned char)SoundState.systemTickDivider == 0)
	{
		SoundState.systemTickDivider = SoundState.systemTickDividerReload;
		return TRUE; // Sol:native FAR jump chains saved IRQ0; callback has already run.
	}
	SoundState.systemTickDivider = (SoundState.systemTickDivider & 0xFF00) | (unsigned char)(SoundState.systemTickDivider - 1);
	return FALSE; // Sol:native sends PIC EOI20h and IRET; platform scheduler needs neither operation.
}

// 204B:0048: void Install_Music_Timer_0048()
// Called from:
//      Load_And_Play_Intro_Music_476D
// Sol: Summary: Install the original music timer hook.
// Sol: Outline: Save the previous interrupt vector, initialise callback state, and bind the music clock handler.
void Install_Music_Timer_0048()
{
	// Sol:Fresh ASM check0048..0090: IVT WORD reads, six state WORDs, DOS vector8 install then PIT36/FF/0F agree.
	// Sol:Hardcoded204B denotes the logical relocated CS; a portable binding must not install a host address as DOS16:16.
	// Sol: Save IRQ0 from the real-mode vector table at 0000:0020, install
	// Sol: 204B:0020, and attempt to preserve legacy system ticks by chaining
	// Sol: immediately on first interrupt, then every SEVENTEEN: test old AL zero before decrement, reload16.
	unsigned short far* InterruptVectorTable = SEQ(0x0000, 0x0000);
	SoundState.savedIrq0Offset = InterruptVectorTable[0x10];
	SoundState.savedIrq0Segment = InterruptVectorTable[0x11];
	SoundState.systemTickDividerReload = 0x0010;
	SoundState.systemTickDivider = 0x0000;
	SoundState.interruptCallbackOffset = 0x0186;
	SoundState.interruptCallbackSegment = 0x204B;
	msdos_set_interrupt_vector(0x08, SEQ(0x204B, 0x0020));

	// Sol: PIT channel 0 mode 3, divisor 0FFFh: approximately 291.375 Hz.
	__out<byte>(0x43, 0x36);
	__out<byte>(0x40, 0xFF);
	__out<byte>(0x40, 0x0F);
}

// 204B:0091: void Restore_System_Timer_0091()
// Called from:
//      Load_And_Play_Intro_Music_476D
// Sol: Summary: Remove the game's music timer hook.
// Sol: Outline: Restore the saved native interrupt vector and timer state.
void Restore_System_Timer_0091()
{
	// Sol:Fresh ASM check0091..00B1: restore saved vector before PIT36/FF/FF; not restoration of an arbitrary prior divisor.
	// Sol: Restore the saved IRQ0 handler and PIT channel 0's conventional
	// Sol: divisor FFFFh. The former "0.7 Hz" annotation was false: the PIT
	// Sol: input clock divided by 65535 is approximately 18.2 Hz.
	msdos_set_interrupt_vector(0x08,
		SEQ(SoundState.savedIrq0Segment, SoundState.savedIrq0Offset));
	__out<byte>(0x43, 0x36);
	__out<byte>(0x40, 0xFF);
	__out<byte>(0x40, 0xFF);
}

// 204B:00BD: void PC_Speaker_ON()
// Called from:
//      Tandy_1000_PC_Speakers
//      Tandy_Music_Control_02E4
//      PC_Speaker_Music_Control_0306
// Sol: Summary: Enable the PC speaker.
// Sol: Outline: Set the required gate bits in the original speaker control port.
void PC_Speaker_ON() //EnablePCSpeaker
{
	// Sol:Fresh ASM check00BD..00C5: port61 read/OR3/write; bits0/1, native AX preserved.
	// What you need to do is to enable the speaker to PIT counter 2 by switching on bit 1 and 2 in the system control port (0x61). We do this by reading what is there already and ORing with 3 (11b 
	__out<byte>(0x61, __in<byte>(0x61) | 0x03);
}

// 204B:00C6: void PC_Speaker_00C6()
// Called from:
//      Tandy_SoundCard_Output
//      PC_Speaker_Set_Value_0179
// Sol: Summary: Disable the PC speaker.
// Sol: Outline: Clear the speaker gate bits in the original control port.
void PC_Speaker_00C6() //DisablePCSpeaker
{
	// Sol:Fresh ASM check00C6..00CE: port61 read/AND FC/write, no pitch write; native AX preserved.
	// To turn off the PC speaker, clear bits 0 and 1 in port 0x61.
    // The value 252 in decimal is 0xFC (binary 11111100), which clears those bits.	
	__out<byte>(0x61, __in<byte>(0x61) & 0xFC);
}

// 204B:0179: void PC_Speaker_Set_Value_0179()
// Sol: Summary: Stop PC-speaker music and select the idle callback.
// Sol: Outline: Store idle callback offset0186 and clear the speaker gate without changing its divisor.
void PC_Speaker_Set_Value_0179() //ResetSpeakerFrequencyAndDisable()
{
	// Sol:Fresh ASM check0179..0185: callback-offset WORD store and00C6 gate-off only; legacy frequency-reset name misleading.
	SoundState.interruptCallbackOffset = 0x0186;
	PC_Speaker_00C6(); // Sol:native near00C6 gate-off; does NOT write/reset frequency despite legacy name.
}

// 204B:02E4: void Tandy_Music_Control_02E4(Stack word Selector, ...)
// Called from:
//      Load_And_Play_Intro_Music_476D
// Sol: Summary: Dispatch Tandy music control requests.
// Sol: Outline: Use the selector to start or stop the stream and preserve the native argument contract.
void Tandy_Music_Control_02E4(unsigned short Selector, ...)
{
	// Sol:Fresh ASM check02E4..0305: signed selector/stride4, speaker enable, setup call then callback store.
	// Sol:TODO ASM mismatch: native selector1 setup020B reads stream/cadence through this dispatcher's BP frame.
	// Sol:No-argument indirect C call neither forwards variadic values nor models that frame; bind cursor/cadence explicitly.
	// Sol:Near target and CS table offsets are research addresses, not an independently callable host function-pointer API.
	// Sol: This is the Tandy counterpart to 0306. The two used four-byte
	// Sol: setup/interrupt-callback records begin at 204B:0328. Selector 1's
	// Sol: setup callback consumes the following SIF pointer and cadence words.
	if ((short)Selector < 0x0D) // Sol:signed JGE; only selectors0/1 have verified records, not thirteen safe entries.
	{
		PC_Speaker_ON();
		unsigned short far* ControlRecord = SEQ(0x204B, (unsigned short)(0x0328 + (unsigned short)(Selector << 2)));
		((void (near*)())ControlRecord[0])();
		SoundState.interruptCallbackOffset = ControlRecord[1];
	}
}

// 204B:0306: void PC_Speaker_Music_Control_0306(Stack word Selector, ...)
// Called from:
//      Load_And_Play_Intro_Music_476D
// Sol: Summary: Dispatch PC-speaker music control requests.
// Sol: Outline: Enable the speaker, call the selected stop/start setup entry, then store its paired interrupt-callback offset.
void PC_Speaker_Music_Control_0306(unsigned short Selector, ...)
{
	// Sol:Fresh ASM check0306..0327: signed selector/stride4, speaker enable, setup call then callback store.
	// Sol:TODO ASM mismatch: native selector1 setup0233 reads stream/cadence through this dispatcher's BP frame.
	// Sol:No-argument indirect C call omits the required variadic/frame binding; correction must forward FAR cursor and cadence.
	// Sol: The two used four-byte setup/interrupt-callback records begin at
	// Sol: 204B:0332. Selector 0 resets/stops; selector 1 starts the sequential
	// Sol: PC-speaker SIF consumer using extra arguments on the caller's stack.
	if ((short)Selector < 0x0D) // Sol:signed JGE; preserve native permissive/unsafe table dispatch, not a validated public API.
	{
		PC_Speaker_ON();
		unsigned short far* ControlRecord = SEQ(0x204B, (unsigned short)(0x0332 + (unsigned short)(Selector << 2)));
		((void (near*)())ControlRecord[0])();
		SoundState.interruptCallbackOffset = ControlRecord[1];
	}
}

// 204B:033C: Register word Music_Playback_Finished_033C()
// Called from:
//      Load_And_Play_Intro_Music_476D
// Sol: Summary: Report whether the music stream has ended.
// Sol: Outline: Inspect the native playback callback or completion state and return a WORD boolean.
unsigned short Music_Playback_Finished_033C()
{
	// Sol:Fresh check033C..034B: listing truncates after first load; dis and profile-checked EXE tail confirm XOR0186/test, AX0/1.
	// Sol:Only callback OFFSET equality matters, even when its segment differs; no stream read or speaker IO occurs here.
	// Sol: Both consumers restore the idle RETF callback at 204B:0186 after
	// Sol: encountering the appended zero terminator. The original uses an
	// Sol: XOR/test and returns one only on equality.
	return SoundState.interruptCallbackOffset == 0x0186;
}
