// BTECH_135D.c
// Generated by decompiling BTECH.EXE
// using Reko decompiler version 0.11.2.0.

#include "BTECH.h"

// 135D:0004: void Draw_STARLEAG_ICN_AND_Game_Logic()
// Called from:
//      Load_Game
//      Interact_with_BLD
// Sol: Summary: Prepare the Star League cache's special map and state.
// Sol: Outline: Load the special artwork and initialise cache-related tiles, positions and story conditions.
void Draw_STARLEAG_ICN_AND_Game_Logic()
{
	// TODO Sol: Fresh whole-body ASM audit: Mech.Name is a 16-byte array;
	// TODO Sol: the save/hide operations below need Name[0], not array assignment.
	// Sol: EGA-only cache setup/replay flow compared; see systematic audit report.
	// Sol:0014 saves only Name[0], then hides the four live records; all other mech bytes survive.
	for (unsigned short MechLanceId = 0; MechLanceId < Friendly_Mech_Record_Count; ++MechLanceId)
	{
		seg3092->CacheEntryMechNameInitial[MechLanceId] = seg3092->Mechs[MechLanceId].Name; // Sol:3092:3248+slot BYTE
		seg3092->Mechs[MechLanceId].Name = MECH_Destroyed;
	}

	//Remove all character from piloting	
	for (unsigned short PartyMemberId = 0; PartyMemberId < 8; ++PartyMemberId)
	{
		seg3092->Infantry[PartyMemberId].Piloting = 0; // Sol:0051 temporarily assigns every character to mech slot0, NOT on foot yet
	}

	//Star League cache start POS?
	seg246C->CrescentHawk_MapPositionX = Cache_Entrance_ExternalX; //A44B - Character Position X 
	seg246C->CrescentHawk_MapPositionY = Cache_Entrance_ExternalY; //A44D - Character position Y

	// Sol:0086 adapter0-only colour conversion2FE8:01B0 is omitted from maintained EGA.
	Select_Game_Disk_And_Drive_28CC(2);
	for (unsigned short DescriptorByteIndex = 0; DescriptorByteIndex < 0x0240; ++DescriptorByteIndex)
	{
		seg246C->MapDescriptorCache[DescriptorByteIndex] = 0xD0; // Sol:00A3 fills all nine64-byte grids; not just top-left allocation
	}
	DOS_Load_Map_Files(0x04, MAP_StarLeague_Cache);

	 
	for (unsigned short PendingGridIndex = 0; PendingGridIndex < 3; ++PendingGridIndex)
	{
		seg246C->PendingMapGridSlot[PendingGridIndex] = 0xFF; // Sol:00CF invalidates three pending slot BYTEs
	}

	seg3EDB->GraphicsCompatibilityFlag = TRUE; // Sol:00E5 WORD flag before tile load
	Load_File_To_Memory("STARLEAG.ICN", &seg246C->Ptr_DecompressedFile_Memory_Block); // Memory ref: [3EDB:2068]
	Decompress_File_Into_Memory(&seg246C->Ptr_DecompressedFile_Memory_Block, &seg3092->Ptr_File_To_Memory_Block);
		
	if (seg3EDB->GraphicsAdapter == EGA_VGA)
		DrawCall_Image_To_VGA_Memory(&seg3092->Ptr_File_To_Memory_Block, VGA_Buffer); // Sol:0129 adapter2-only A400 tile buffer, not screenA800

	seg3092->TilesetId = TileSet_StarLeagueCache; //w3988 - Tileset Id - BattleTech, Destruct, StarLeague, MapRoom
	Map_NineGrid_Parent_1DA8();

	PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY); // Sol:014F world-position WORD pair

	Copy_Data_To_GraphicsMemory();
	EGA_DrawBox_Wrapper();
	Wait_For_N_Vertical_Retraces(Refresh_60hz);
	StarLeague_Key_Codes(Cache_Entrance_InsideX, Cache_Entrance_InsideY, CacheDoor_LookupByPosition); // Sol:017A passes signed WORD-1; coordinate lookup, NOT door index255

	//Set all Party Members to be on foot	
	for (unsigned short PartyMemberId = 0; PartyMemberId < 8; ++PartyMemberId)
	{
		seg3092->Infantry[PartyMemberId].Piloting = Character_OnFoot; // Sol:0195 BYTE8 after entrance redraw
	}

	Interact_with_BLD(BLD_INSTRUCT);
		
	for (unsigned short OpenedDoorIndex = 0; OpenedDoorIndex < 11; ++OpenedDoorIndex)
	{
		if (seg3092->CacheDoorOpened[OpenedDoorIndex] != 0)
			StarLeague_Key_Codes(0, 0, OpenedDoorIndex); // Sol:01C1 replay stored doors0..10; not a fresh security-code lookup
	}
}

// 135D:01E9: void StarLeague_Secret_Passageway_Discovered()
// Called from:
//      Map_Interactables_Building_Or_Items
// Sol: Summary: Reveal the cache's secret passage.
// Sol: Outline: Replace a six-by-three tile pattern, redraw the world, show the discovery message and mark the message box open.
void StarLeague_Secret_Passageway_Discovered()
{
	// Sol: Fresh whole-body ASM match under native BYTE/WORD/FAR memory contracts.
	//This replaces the wall tiles with floor tiles
	//Once the secret passageway is discovered

	unsigned short PassageRowTileOffset = 0x0A10; // Sol:map BYTE offset; native246C:101D+0A10=1A2D

	for (unsigned short PassageRow = 0; PassageRow < 6; ++PassageRow)
	{
		for (unsigned short PassageColumn = 0; PassageColumn < 3; ++PassageColumn)
		{
			seg246C->MapTile[PassageRowTileOffset + PassageColumn] = seg3EDB->SecretPassageTilePattern[PassageRow * 3 + PassageColumn]; // Sol:0204 reads source BYTE; never stores the20BC pointer value
		}
		PassageRowTileOffset += 8; // Sol:022B destination row pitch8 BYTEs, source pitch3; preserves five intervening bytes
	}

	PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY); //A44B - Character Position X //A44D - Character position Y
	Copy_Data_To_GraphicsMemory();
	Draw_Infantry_And_Mechs();
	EGA_DrawBox_Wrapper();

	Draw_Message_Box();	
	Display_Text_From_Memory_ScreenRetrace_KeyboardInput("Part of the hallway here crumbles away, revealing a secret passageway!"); // Memory ref: [3EDB:2075] 
	Keyboard_Get_ASCII_Hex_Input();

	seg3092->MessageBox_Open = TRUE; //wD55C - MessageBox Open
}

// 135D:0288: void StarLeague_Cache_PhoenixHawk()
// Called from:
//      Map_Interactables_Building_Or_Items
// Sol: Summary: Handle the cache's Phoenix Hawk discovery.
// Sol: Outline: Invoke ENDMECH only while the found flag is zero; the script owns any discovery-state change.
void StarLeague_Cache_PhoenixHawk()
{
	// Sol: Fresh whole-body ASM match; no discovery flag write occurs here.
	// Sol:0288 tests BYTE D34B==0; any nonzero suppresses ENDMECH.BLD (ID16h).
	// Sol:This routine does not itself mark PhoenixHawk_Found; the script owns that transition.
	if (seg3092->PhoenixHawk_Found == FALSE)
		Interact_with_BLD(BLD_ENDMECH);
}

// 135D:02A8: void Display_StarLeague_Cache_Dialog_Window()
// Called from:
//      Map_Interactables_Building_Or_Items
// Sol: Summary: Open the cache dialogue panel.
// Sol: Outline: Select the appropriate menu layout and display the cache text.
void Display_StarLeague_Cache_Dialog_Window()
{
	// TODO Sol: Fresh ASM audit: native DS:20CE has TWO spaces after 'gyros!'.
	// Sol: Calls, blocking key and message-box WORD write otherwise match.
	// Sol:02A8 unconditional dialogue: layout/message -> FAR text20CE/retrace -> ASCII key -> WORD D55C=1.
	Draw_Message_Box();	
	Display_Text_From_Memory_ScreenRetrace_KeyboardInput("These boxes are full of 'Mech gyros! The cache must be around here!"); // Memory ref: [3EDB:20CE] 
	Keyboard_Get_ASCII_Hex_Input();

	seg3092->MessageBox_Open = TRUE; //wD55C - MessageBox Open
}

// 135D:02D2: void StarLeague_HyperPulse_Power_Dialog_Window(WORD world X, WORD world Y)
// Called from:
//      Map_Interactables_Building_Or_Items
// Sol: Summary: Handle interaction with the cache power controls.
// Sol: Outline: Check the player's location and current power state, then show or apply the scripted response.
void StarLeague_HyperPulse_Power_Dialog_Window(unsigned short CharacterPosX, unsigned short CharacterPosY)
{
	// Sol: Fresh whole-body ASM match, including repeated calls and masked bounds.
	unsigned short PowerSwitchLocalX = (unsigned short)(CharacterPosX + 1) & 0x7E; // Sol:02D2 WORD INC wraps, then mask discards region/high bits and low parity bit
	unsigned short PowerSwitchLocalY = CharacterPosY & 0x7E;
	if (PowerSwitchLocalX == Cache_HyperPulse_PowerX
	 && PowerSwitchLocalY >= Cache_HyperPulse_PowerMinY
	 && PowerSwitchLocalY <= Cache_HyperPulse_PowerMaxY) // Sol:02EF/02F5 inclusive0C..11; masked Y is even, so only0C/0E/10 qualify
	{
		Draw_Message_Box();		
		Display_Text_From_Memory_ScreenRetrace_KeyboardInput("You have turned on the power to the Hyperpulse Generator."); // Memory ref: [3EDB:2113] 
		Keyboard_Get_ASCII_Hex_Input();
		seg3092->HPGTerminal_PowerOn = TRUE; //bD34C is HPG Terminal PowerOn Bool
		seg3092->MessageBox_Open = TRUE; //wD55C - MessageBox Open
		// Sol:No prior PowerOn guard: repeated qualifying calls can display this message again. Other positions change no flags.
	}
}

// 135D:0327: void OverHead_Map_Function()
// Called from:
//      Show_Overhead_Map
// Sol: Summary: Swap buffers for the special overhead view.
// Sol: Outline: Swap 250 colour bytes with the cache or map-room overview selected by the room-loaded flag; the caller presents it.
void OverHead_Map_Function()
{
	// Sol: Fresh whole-body ASM match; this swaps bytes but does not render a map.
	// Sol:0327 swaps the active overview colour map with a cache/map-room map.
	// Sol:Show_Overhead_Map calls this on entry and exit; with unchanged D34E, two swaps restore both buffers.
	for (unsigned short OverheadMapLoop = 0; OverheadMapLoop < CacheOverviewColourSwapCount; ++OverheadMapLoop)
	{
		unsigned char OriginalOverviewColour = seg246C->OverviewTileColours[OverheadMapLoop]; // Sol:0367 saves old BYTE via CBW/BP-2; only low BYTE is restored
		if (seg3092->CacheMapRoomLoaded != FALSE) //Star League HPG Map Room Loaded
		{
			seg246C->OverviewTileColours[OverheadMapLoop] = seg246C->MapRoomOverviewTileColours[OverheadMapLoop]; // Sol:0383 BYTE2351 ->215D
			seg246C->MapRoomOverviewTileColours[OverheadMapLoop] = OriginalOverviewColour;
		}
		else
		{
			seg246C->OverviewTileColours[OverheadMapLoop] = seg246C->CacheOverviewTileColours[OverheadMapLoop]; // Sol:0339 BYTE2257 ->215D
			seg246C->CacheOverviewTileColours[OverheadMapLoop] = OriginalOverviewColour;
		}
	}
}

// 135D:03AA: void StarLeague_Security_Terminal(Stack Eq_3701 CharacterPos_X, Stack int16 CharacterPos_Y)
// Called from:
//      Map_Interactables_Building_Or_Items
// Sol: Summary: Use a cache security terminal.
// Sol: Outline: Find the terminal by coordinates, check its state, and apply the one-use colour-code operation.
void StarLeague_Security_Terminal(unsigned short CharacterPosX, unsigned short CharacterPosY)
{
	// TODO Sol: Fresh ASM audit: native DS:2187 includes '.\rDo you want to
	// TODO Sol: imprint '; DS:21B9 ends with colour controls06h/0Fh. Restore later.
	// Sol: All33 terminals, signed coordinate/colour indices and writes compared.
	unsigned short TeamPosX = (unsigned short)(CharacterPosX + 1) & Byte_MostSignificantBitMask; // Sol:03AA WORD INC then7F mask; unlike power switch7E, preserves odd local coordinates
	unsigned short TeamPosY = CharacterPosY & Byte_MostSignificantBitMask;

	// Sol:0454 signed WORD counter exits at33; no early break after a match.
	for (unsigned short CodeNumber = 0; CodeNumber < CacheSecurityTerminalCount; ++CodeNumber)
	{
		short SecurityTerminalPosX = (signed char)seg3EDB->SecurityTerminalPosX[CodeNumber]; // Sol:0467 CBW BYTE21CE
		short SecurityTerminalPosY = (signed char)seg3EDB->SecurityTerminalPosY[CodeNumber]; // Sol:045A CBW BYTE21F0


		if (SecurityTerminalPosY == TeamPosY)		{
			
			if ((short)TeamPosX >= SecurityTerminalPosX && (short)TeamPosX < (short)(SecurityTerminalPosX + 3)) // Sol:0467/0473 signed lower-inclusive, upper-exclusive three-column span
			{
				Draw_Message_Box();
				if (seg3092->HasCodeBeenUsed[CodeNumber] == FALSE) //45DE - Has the security terminals code been used to open a door. One use only
				{					
					Display_Text_From_Memory("Security Terminal"); // Memory ref: [3EDB:2187] 
					short ColourCode = (signed char)seg3EDB->SecurityTerminalColour[CodeNumber]; // Sol:03CC CBW BYTE2212 then FAR pointer stride4
					Display_Text_From_Memory(seg3EDB->SecurityCodeColourText[ColourCode]); // Sol:load pointer VALUE at2234/2236, not address of table entry
					Display_Text_From_Memory(" code "); // Memory ref: [3EDB:21B2] 
					Display_Text_Dynamic_Value(CodeNumber + 1);					
					Display_Text_From_Memory(" on your code key?"); // Memory ref: [3EDB:21B9] 

					if (Prompt_Yes_No(1) != FALSE) // Sol:default yes; displayed code is index+1, stored code remains index
					{
						short AcceptedCodeColour = (signed char)seg3EDB->SecurityTerminalColour[CodeNumber]; // Sol:042E reloads colour after prompt
						seg3092->SelectedCacheCodeByColour[AcceptedCodeColour] = (unsigned char)CodeNumber; // Sol:D347+colour, replaces prior same-colour code; does NOT set HasCodeBeenUsed
					}
				}
				else
				{
					Display_Text_From_Memory_ScreenRetrace_KeyboardInput("You've already used this terminal's code."); // Memory ref: [3EDB:215D]
					Keyboard_Get_ASCII_Hex_Input();
				}
				seg3092->MessageBox_Open = TRUE; //wD55C - MessageBox Open
			}
		}		
	}
}

// 135D:04AB: void HPGTransmitter(unsigned int CharacterPos_X, int CharacterPos_Y)
// Called from:
//      Map_Interactables_Building_Or_Items
// Sol: Summary: Handle the hyperpulse transmitter.
// Sol: Outline: Check location and prerequisite flags, then display the result or update the transmitter state.
void HPGTransmitter(unsigned short CharacterPosX, unsigned short CharacterPosY)
{
	// Sol: Fresh whole-body ASM match, including WHITE exactly1 and both positions.
	CharacterPosX = (unsigned short)(CharacterPosX + 1) & 0x7E; // Sol:04AB native WORD INC then local even-coordinate mask

	if (((CharacterPosY & 0x7E) != 0x04 || CharacterPosX != 0x04)
	  && (CharacterPosX != 0x02 || (CharacterPosY & 0x7E) != 0x0E))
		return;

	unsigned char far *TransmitterText; // Sol:053E passes DS:AX as16:16 FAR string
	if (seg3092->HPGTerminal_PowerOn == FALSE) //bD34C is HPG Terminal PowerOn Bool
	{
		Draw_Message_Box();
		TransmitterText = "It seems the power to these terminals is turned off."; // Memory ref: [3EDB:2240]
	}
	else if (seg3092->isWHITECodeCorrect != TRUE) //bD34A = isWHITECodeCorrect?
	{
		Draw_Message_Box(); 
		TransmitterText = "Incorrect WHITE code."; // Memory ref: [3EDB:2275]
	}
	else
	{
		// Sol:Requires power!=0, WHITE exactly1, and parts-found!=0, in that order.
		if (seg3092->MechPartsCacheFound != FALSE) // Sol:D34D parts discovery, NOT the WHITE-code puzzle result
		{
			Interact_with_BLD(BLD_WINSCENE);
			seg3092->MessageBox_Open = TRUE; //wD55C - MessageBox Open
			seg3EDB->TransmittedCacheFound = TRUE;
			return;
		}
		Draw_Message_Box();
		TransmitterText = "You want to radio Katrina, but you haven't found the cache."; // Memory ref: [3EDB:228B]
	}
	Display_Text_From_Memory_ScreenRetrace_KeyboardInput(TransmitterText);
	Keyboard_Get_ASCII_Hex_Input();
	seg3092->MessageBox_Open = TRUE; //wD55C - MessageBox Open
}

// 135D:055A: void StarLeague_Map_Room(Stack uint16 CharacterPos_X, Stack uint16 CharacterPos_Y)
// Called from:
//      Map_Interactables_Building_Or_Items
// Sol: Summary: Enter and operate the cache's map room.
// Sol: Outline: Dispatch parts discovery or WHITE-hole dialogue, then stage the room artwork, saved tiles, descriptors and collision threshold.
void StarLeague_Map_Room(unsigned short CharacterPos_X, unsigned short CharacterPos_Y)
{	
	// TODO Sol: Fresh ASM audit: native DS:22E8 says 'painted', not 'pointed'.
	// Sol: EGA flow and backup ordering match; there is no interaction loop here.
	unsigned short CharPosX2 = (unsigned short)(CharacterPos_X + 1) & 0x7E; // Sol:055A WORD wrap then local mask
	unsigned short CharPosY = (CharacterPos_Y & 0x7E);

	//The location of the parts cache
	// Sol:057E FINDIT runs on every qualifying call; no prior D34D guard. The later WHITE-hole check is independent.
	if (CharPosX2 == Cache_PartsX 
	 && CharPosY == Cache_PartsY)
	{
		Interact_with_BLD(BLD_FINDIT);
		seg3092->MechPartsCacheFound = TRUE;
		seg3092->MessageBox_Open = TRUE; //wD55C - MessageBox Open
	}

	if (CharPosX2 == Cache_WhiteSecurityX
	 && CharPosY == Cache_WhiteSecurityY)
	{
		Draw_Message_Box();
		seg3092->MessageBox_Open = TRUE; //wD55C - MessageBox Open

		if (seg3092->isWHITECodeCorrect == TRUE)  //bD34A = IsWHITEcodeCorrect?
		{
			Display_Text_From_Memory_ScreenRetrace_KeyboardInput("You already have the WHITE code."); // Memory ref: [3EDB:22C7]
			Keyboard_Get_ASCII_Hex_Input();
		}
		else
		{
			Display_Text_From_Memory_ScreenRetrace_KeyboardInput("You peer down the hole and see a huge map pointed on the floor."); // Memory ref: [3EDB:22E8]
			Keyboard_Get_ASCII_Hex_Input();
			Draw_Top_Graphic_Sidebar();

			Display_Text_From_Memory_ScreenRetrace_KeyboardInput("You climb down the ladder to investigate it."); // Memory ref: [3EDB:2328]
			Keyboard_Get_ASCII_Hex_Input();

			seg3EDB->ExplorationStepsPerInput = 1; // Sol:060F WORD015A forces single exploration step in the map-room view
			seg246C->CrescentHawk_MapPositionX = Cache_Map_Ladder_TopX; //A44B - Character Position X 
			seg246C->CrescentHawk_MapPositionY = Cache_Map_Ladder_TopY; //A44D - Character position Y

			// Sol:Original adapter0 conversion2FE8:01D0 is omitted from maintained EGA.
			Select_Game_Disk_And_Drive_28CC(2);
			for (unsigned short DescriptorIndex = 0; DescriptorIndex < 0x0240; ++DescriptorIndex)
			{
				seg246C->MapDescriptorCache[DescriptorIndex] = 0xD1; // Sol:064B fills all576 descriptor BYTEs
			}  
						
			seg3EDB->GraphicsCompatibilityFlag = TRUE; // Sol:0662 WORD flag before asset load
			Load_File_To_Memory("MAP.ICN", &seg246C->Ptr_DecompressedFile_Memory_Block); // Memory ref:  [3EDB:2355]
			Decompress_File_Into_Memory(&seg246C->Ptr_DecompressedFile_Memory_Block, &seg3092->Ptr_File_To_Memory_Block);
						
			if (seg3EDB->GraphicsAdapter == EGA_VGA)
				DrawCall_Image_To_VGA_Memory(&seg3092->Ptr_File_To_Memory_Block, VGA_Buffer); // Sol:06A6 A400 tile staging must precede buffer reuse below

			unsigned char far *CacheTileBackupBytes = (unsigned char far *)&seg3092->Ptr_File_To_Memory_Block; // Sol:06BF native destination3092:4614 is a BYTE buffer, not DWORD pointer indexing
			for (unsigned short TileId = 0; TileId < 0x0300; ++TileId)
			{
				CacheTileBackupBytes[TileId] = seg246C->MapTile[TileId]; // Sol:preserves first768 cache tile BYTEs after graphics upload
			} 

			seg3092->TilesetId = TileSet_MapRoom; //w3988 - Tileset Id - BattleTech, Destruct, StarLeague, MapRoom
			
			DOS_Load_File_to_memory("MAP15.MTP", &seg246C->MapTile, 0x0300); // Memory ref: [3EDB:235D] 
			seg3092->CacheMapRoomLoaded = TRUE; //Star League HPG Map Room Loaded

			unsigned short MapRoomDescriptorId = 0x90; // Sol:WORD BP-2; twelve descriptor IDs90..9B
			for (unsigned short MapRoomDescriptorRow = 0; MapRoomDescriptorRow < 3; ++MapRoomDescriptorRow)
			{
				for (unsigned short MapRoomDescriptorColumn = 0; MapRoomDescriptorColumn < 4; ++MapRoomDescriptorColumn)
				{
					seg246C->Map_NineGrid_MiddleCentre[MapRoomDescriptorRow * 8 + MapRoomDescriptorColumn] = (unsigned char)MapRoomDescriptorId++;
				}
			}

			Map_NineGrid_Parent_1DA8();
			PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY); //A44B - Character Position X //A44D - Character position Y
			Copy_Data_To_GraphicsMemory();
			
			EGA_DrawBox_Wrapper();
			seg3EDB->BlockingTileCodeThreshold = 0x8B; // Sol:map-room collision threshold; this is not a WHITE-code success write
		}
	}
}

// 135D:079C: void Draw_STARLEAG_ICN_Scene()
// Called from:
//      Map_Interactables_Building_Or_Items
// Sol: Summary: Return from the map room to the cache scene.
// Sol: Outline: Restore staged positions and display buffers, reload the scene, and resume the outside view.
void Draw_STARLEAG_ICN_Scene()
{
	// Sol: Fresh whole-body EGA ASM match; restore tiles BEFORE decoding artwork.
	Draw_Message_Box();
	Display_Text_From_Memory_ScreenRetrace_KeyboardInput("You easily scale the ladder back up to the Star League cache."); // Memory ref: [3EDB:2367]
	Keyboard_Get_ASCII_Hex_Input();

	seg246C->CrescentHawk_MapPositionX = Cache_Ladder_TopX; //A44B - Character Position X 
	seg246C->CrescentHawk_MapPositionY = Cache_Ladder_TopY; //A44D - Character position Y

	
	// Sol:Original adapter0 conversion2FE8:01B0 is omitted; restore disk2 selection.
	Select_Game_Disk_And_Drive_28CC(2);
	for (unsigned short DescriptorIndex = 0; DescriptorIndex < 0x240; ++DescriptorIndex)
	{
		seg246C->MapDescriptorCache[DescriptorIndex] = 0xD0; // Sol:07F5 full576-byte descriptor cache
	} 

	unsigned char far *CacheTileBackupBytes = (unsigned char far *)&seg3092->Ptr_File_To_Memory_Block;
	for (unsigned short TileId = 0; TileId < 0x0300; ++TileId)
	{
		seg246C->MapTile[TileId] = CacheTileBackupBytes[TileId]; // Sol:0811 restore768 BYTEs BEFORE decode overwrites backup4614
	} 

	seg3EDB->GraphicsCompatibilityFlag = TRUE; // Sol:0830 WORD4FBC then D55C
	seg3092->MessageBox_Open = TRUE;
	
	Load_File_To_Memory("STARLEAG.ICN", &seg246C->Ptr_DecompressedFile_Memory_Block); // Memory ref: [3EDB:23A5]
	Decompress_File_Into_Memory(&seg246C->Ptr_DecompressedFile_Memory_Block, &seg3092->Ptr_File_To_Memory_Block);
		
	if (seg3EDB->GraphicsAdapter == EGA_VGA)
		DrawCall_Image_To_VGA_Memory(&seg3092->Ptr_File_To_Memory_Block, VGA_Buffer); // Sol:087C A400 tile upload

	seg3092->TilesetId = TileSet_StarLeagueCache; //w3988 - Tileset Id - BattleTech, Destruct, StarLeague, MapRoom

	
	for (unsigned short MapTileOffset = 0; MapTileOffset < 0x40; ++MapTileOffset)
	{
		seg246C->Map_NineGrid_MiddleCentre[MapTileOffset] = (unsigned char)(MapTileOffset - 0x70); // Sol:08A0 low-BYTE index minus70 ->90..CF, exactly64 descriptors; CHECK ASM resolved
	}

	Map_NineGrid_Parent_1DA8();
	PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY); //A44B - Character Position X //A44D - Character position Y
	Copy_Data_To_GraphicsMemory();

	EGA_DrawBox_Wrapper();
	seg3092->CacheMapRoomLoaded = FALSE; //Star League HPG Map Room Loaded
	seg3EDB->BlockingTileCodeThreshold = 0x21; // Sol:restore ordinary cache collision threshold; exploration step015A is NOT restored here
}

// 135D:0913: void Map_Interactable_Play_Sound(Stack uint16 CharacterPos_X, Stack uint16 CharacterPos_Y)
// Called from:
//      Map_Interactables_Building_Or_Items
// Sol: Summary: Play the special-map interaction sound.
// Sol: Outline: Check the supplied map position and dispatch the corresponding effect.
void Map_Interactable_Play_Sound(unsigned short CharacterPos_X, unsigned short CharacterPos_Y)
{
	// Sol: Fresh whole-body ASM match: computed tile toggle plus sound, no gate.
	unsigned short Offset_PosX = (unsigned short)(CharacterPos_X + 1) & Byte_MostSignificantBitMask;
	unsigned short Offset_PosY = ((CharacterPos_Y & 0x70) << 0x04) + ((CharacterPos_Y & 0x0E) << 0x02) + (((Offset_PosX & 0x70) << 0x02) + (Offset_PosX >> 0x01 & 0x07));

	seg246C->MapTile[Offset_PosY] = (unsigned char)(((unsigned char)(seg246C->MapTile[Offset_PosY] + 1) ^ 1) - 1); // Sol:0913 BYTE INC/XOR1/DEC: odd->next even(selected), even->previous odd; FF->00 wrap

	Play_Sound_If_Enabled(Sound_MapInteraction);
}

// 135D:0980: void Cache_StarMap_CorrectPassword()
// Called from:
//      Map_Interactables_Building_Or_Items
// Sol: Summary: Process the star-map puzzle response.
// Sol: Outline: Check seven required tiles and reject extra selected stars; latch WHITE on success or deselect stars on failure.
void Cache_StarMap_CorrectPassword()
{
	// TODO Sol: Fresh ASM audit: native DS:23B2 also prints WHITE-code installed
	// TODO Sol: and HyperPulse-ready lines after 'Password accepted.'. Restore later.
	// Sol: Membership-set logic and persistent success latch match; not a sequence.
	//This code is checking the users selected star systems against the copyright protection
	//If succeeds then sets the isWhiteCodeCorrect bool which enables the HPG Transmitter
	unsigned short IsStarSelectionCorrect = TRUE; // Sol:0980 WORD BP-2; success is latched below, failure does not clear existing WHITE
	
	for (unsigned short SystemsSelected = 0; SystemsSelected < CacheStarPuzzleTargetCount; ++SystemsSelected)
	{
		if ((seg246C->MapTile[seg3EDB->CacheStarPuzzleTargetOffsets[SystemsSelected]] & 1) != 0)
			IsStarSelectionCorrect = FALSE;
	} 

	if (IsStarSelectionCorrect != FALSE)
	{		
		for (unsigned short StarTileIndex = 0; StarTileIndex < 0x0300; ++StarTileIndex)
		{
			unsigned char SelectedStarTile = seg246C->MapTile[StarTileIndex];
			if (SelectedStarTile >= CacheStarTileRangeFirst && SelectedStarTile <= CacheStarTileRangeLast && (SelectedStarTile & 1) == 0) // Sol:zero-extended BYTE selected star in puzzle ID range
			{
				unsigned short IsRequiredStarTile = FALSE; // Sol:WORD BP-8 membership result
				
				for (unsigned short RequiredStarIndex = 0; RequiredStarIndex < CacheStarPuzzleTargetCount; ++RequiredStarIndex)
				{
					if (seg3EDB->CacheStarPuzzleTargetOffsets[RequiredStarIndex] == StarTileIndex)
					{
						IsRequiredStarTile = TRUE;
						break; // Sol:09FC sets counter8 then increments/exits; no further membership side effects
					}								
				} 

				if (IsRequiredStarTile == FALSE)
					IsStarSelectionCorrect = FALSE;
			}			
		} 
	}
	Draw_Message_Box();

	if (IsStarSelectionCorrect != FALSE)
	{
		Play_Sound_If_Enabled(Sound_PasswordAccepted);
		Display_Text_From_Memory_ScreenRetrace_KeyboardInput("Password accepted."); // Memory ref: [3EDB:23B2]
		seg3092->isWHITECodeCorrect = TRUE;
	}
	else
	{
		Play_Sound_If_Enabled(Sound_PasswordIncorrect);
		Display_Text_From_Memory_ScreenRetrace_KeyboardInput("Incorrect password."); // Memory ref: [3EDB:2409]
 
		for (unsigned short TileId = 0; TileId < 0x0300; ++TileId)
		{
			unsigned char ResetStarTile = seg246C->MapTile[TileId];
		
			if (ResetStarTile >= CacheStarTileRangeFirst && ResetStarTile <= CacheStarTileRangeLast && (ResetStarTile & 1) == 0)
				--seg246C->MapTile[TileId];	
		} 
	}
	Keyboard_Get_ASCII_Hex_Input();
	seg3092->MessageBox_Open = TRUE; //wD55C - MessageBox Open
}

// 135D:0AB6: void StarLeague_Key_Codes(Stack uint16 CharacterPos_X, Stack uint16 CharacterPos_Y, Stack int16 CacheOpenedId)
// Called from:
//      Map_Interactables_Building_Or_Items
//      Draw_STARLEAG_ICN_AND_Game_Logic
// Sol: Summary: Use a door's colour code.
// Sol: Outline: Locate the door, test and consume its stored code, and replay or update the door state.
void StarLeague_Key_Codes(unsigned short PosX, unsigned short PosY, signed short CacheOpenedId)
{
	// TODO Sol: Fresh whole-body ASM audit: .dis proves the playback tests at
	// TODO Sol: 0C5F/0CB6/0D21 compare FFFF (-1), NOT00FF. Current playback
	// TODO Sol: constant suppresses lookup animation/sound and wait; correct later.
	unsigned short DoorLocalX = (unsigned short)(PosX + 1) & 0x7F;
	unsigned short DoorLocalY = PosY & 0x7E;
	unsigned short CanOpenDoor = FALSE; // Sol:WORD BP-6; negative argument searches coordinates, nonnegative replays a door ID
	short DoorIndex;
	short RequiredCode[3]; // Sol:each native CBW table BYTE then WORD DEC, so zero becomes-1
	if (CacheOpenedId >= 0)
	{
		DoorIndex = CacheOpenedId;
		DoorLocalX = (unsigned short)(signed char)seg3EDB->CacheDoorPositionX[DoorIndex];
		DoorLocalY = (unsigned short)(signed char)seg3EDB->CacheDoorPositionY[DoorIndex];
		CanOpenDoor = TRUE;
	}
	else
	{
		for (unsigned short DoorCandidateIndex = 0; DoorCandidateIndex < 12; ++DoorCandidateIndex)
		{
			if ((short)DoorLocalY != (signed char)seg3EDB->CacheDoorPositionY[DoorCandidateIndex]
			 || (DoorLocalX & 0x7E) != seg3EDB->CacheDoorPositionX[DoorCandidateIndex])
				continue; // Sol:0AF1 signed Y,0AFE BYTE X equality with parity cleared
			DoorIndex = DoorCandidateIndex;
			CanOpenDoor = TRUE;
			RequiredCode[0] = (short)(signed char)seg3EDB->CacheDoorRequiredRed[DoorIndex] - 1;
			RequiredCode[1] = (short)(signed char)seg3EDB->CacheDoorRequiredBlue[DoorIndex] - 1;
			RequiredCode[2] = (short)(signed char)seg3EDB->CacheDoorRequiredYellow[DoorIndex] - 1;
			if (DoorIndex != 11) // Sol:0B32 special entrance bypasses colour checks
			{
				if ((signed char)seg3092->currentCode_RED != RequiredCode[0]
				 || (signed char)seg3092->currentCode_BLUE != RequiredCode[1]
				 || (signed char)seg3092->currentCode_YELLOW != RequiredCode[2])
				{
					Draw_Message_Box();
					if ((signed char)seg3092->currentCode_RED != RequiredCode[0]) Display_Text_From_Memory("Incorrect RED code.\r"); // Sol:242C
					if ((signed char)seg3092->currentCode_BLUE != RequiredCode[1]) Display_Text_From_Memory("Incorrect BLUE code.\r"); // Sol:2441
					if ((signed char)seg3092->currentCode_YELLOW != RequiredCode[2]) Display_Text_From_Memory("Incorrect YELLOW code."); // Sol:2457
					CanOpenDoor = FALSE;
					Wait_For_50Hz_Then_Check_Input();
					Keyboard_Get_ASCII_Hex_Input();
					seg3092->MessageBox_Open = TRUE;
				}
			}
			break; // Sol:0B29 forces candidate12 then increments/exits; first match only, even if validation fails
		}
	}
	if (CanOpenDoor == FALSE) return;
	if (CacheOpenedId >= 0)
	{
		RequiredCode[0] = (short)(signed char)seg3EDB->CacheDoorRequiredRed[DoorIndex] - 1;
		RequiredCode[1] = (short)(signed char)seg3EDB->CacheDoorRequiredBlue[DoorIndex] - 1;
		RequiredCode[2] = (short)(signed char)seg3EDB->CacheDoorRequiredYellow[DoorIndex] - 1;
	}
	if (DoorIndex != 11)
	{
		seg3092->HasCodeBeenUsed[RequiredCode[0]] = TRUE;
		seg3092->HasCodeBeenUsed[RequiredCode[1]] = TRUE;
		seg3092->HasCodeBeenUsed[RequiredCode[2]] = TRUE; // Sol:0C1D consumes required codes even on replay; selected slots remain unchanged
	}
	else
	{
		seg3092->currentCode_RED = 0xFF;
		seg3092->currentCode_BLUE = 0xFF;
		seg3092->currentCode_YELLOW = 0xFF; // Sol:entrance clears selections, no used-code writes
	}
	seg3092->CacheDoorOpened[DoorIndex] = TRUE; // Sol:door11 writes adjacentD35A, not replayed by eleven-entry01C1 loop
	// TODO Sol: Old 'native00FF versus lookupFFFF' claim was false: abbreviated
	// TODO Sol: sign-extended imm8 in .asm is WORDFFFF in .dis. No original bug.
	if (CacheOpenedId == CacheDoor_AnimatedArgument_00FF) Play_Sound_If_Enabled(Sound_CacheUnknown);
	unsigned short DoorStartTileColumn = (DoorLocalX >> 1) & 7;
	unsigned short PosXY = ((DoorLocalY & 0x70) << 5) + ((DoorLocalY & 0x0E) << 2)
		+ ((DoorLocalX & 0x70) << 2) + DoorStartTileColumn; // Sol:0C73 native Y stride32, not0913 stride16
	for (unsigned short DoorSpriteLocation = 0; DoorSpriteLocation < 3; ++DoorSpriteLocation)
	{
		unsigned short DoorTileColumn = DoorStartTileColumn;
		unsigned short DoorTileWriteOffset = 0;
		if (CacheOpenedId != CacheDoor_AnimatedArgument_00FF) DoorSpriteLocation = 2; // TODO Sol:only replay should force final frame; native-1 lookup animates
		for (unsigned short LoopCounter = 0; LoopCounter < 4; ++LoopCounter)
		{
			seg246C->MapTile[PosXY + DoorTileWriteOffset] = seg3EDB->CacheDoorAnimationTiles[DoorSpriteLocation * 4 + LoopCounter];
			++DoorTileColumn;
			++DoorTileWriteOffset;
			if (DoorTileColumn == 8) DoorTileWriteOffset += 0x38; // Sol:0CF0 add56 to normal+1 on crossing8-tile block; next block pitch64
		}
		PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY);
		Copy_Data_To_GraphicsMemory();
		Draw_Infantry_And_Mechs();
		EGA_DrawBox_Wrapper();
		if (CacheOpenedId == CacheDoor_AnimatedArgument_00FF) Wait_For_N_Vertical_Retraces(0x14); // TODO Sol:native20 retraces per frame onFFFF(-1) lookup
	}
}
