// BTECH_1F3D.c
// Generated by decompiling BTECH.EXE
// using Reko decompiler version 0.11.2.0.

#include "BTECH.h"

// Sol:Whole-segment ASM review: docs/phase4/BTECH_1F3D_SEGMENT_REVIEW.md.
// Sol:Research pseudo-C, not host C; deleted non-EGA adapter bodies remain absent.
// Sol:Fresh systematic ASM audit: docs/phase4/BTECH_1F3D_SYSTEMATIC_ASM_AUDIT.md.
// Sol:All18 implementations checked (17 native/one research helper):16 locally matched,
// Sol:one stack-address mismatch at063B, one unresolved native allocator result at05BC.
// Sol:Native FAR arithmetic changes the offset WORD without carrying into the segment.
// Sol: Summary: Advance a research FAR pointer without segment normalisation.
// Sol: Outline: Add bytes to its WORD offset and preserve its segment.
static unsigned char far *Advance_Far_Offset_1F3D(unsigned char far *Address, unsigned short Bytes)
{
	unsigned long PackedAddress = (unsigned long)Address;
	return (unsigned char far *)((PackedAddress & 0xFFFF0000UL) | (unsigned short)(PackedAddress + Bytes));
}

// Sol:ASM-backed declarations: EGA/text/copy bodies now reconstructed in207F C;3835 remains a memory-service contract.
void Set_Text_Colours_2127(unsigned short Foreground, unsigned short Background); //207F:2127
void EGA_Draw_Glyph_2251(unsigned short GlyphByteOffset, unsigned short RowByteOffset, unsigned short Column); //207F:2251
void EGA_Draw_Vertical_Pixel_Run_05D0(unsigned short X, unsigned short Y0, unsigned short Y1, unsigned short Colour); //207F:05D0
void EGA_Draw_Aligned_Span_0780(unsigned short X, unsigned short Y, unsigned short GroupCount, unsigned short Colour); //207F:0780
unsigned char far *Runtime_Allocate_Word_Buffer_3835(unsigned short ByteCount); //207F:3835 returns DX:AX
void Copy_Strided_Word_Rows_0931(unsigned char far *Source, unsigned char far *Destination,
	unsigned short WordsPerRow, unsigned short Rows, unsigned short SourceRowGap); //207F:0931, DL/DH truncate counts to BYTE

// 1F3D:0006: void Wait_For_N_Vertical_Retraces(Stack Eq_21 NumberOfRetraces)
// Called from:
//      Main_Game_Loop
//      Decode_Draw_Next_ANM_Frame
//      Overhead_Map_Draw_3FAE
//      Display_Animation_Scene
//      Setup_Game
//      Salvage_Mechs_Dialog
//      Examine_Screen_BTSTATS_CMP
//      Mech_Mission_0629
//      Play_Failed_Mech_Startup_Scene_16B2
//      Draw_STARLEAG_ICN_AND_Game_Logic
//      StarLeague_Key_Codes
//      GameSpeed_RateControl
//      Combat_AudioVisual_Effects
//      Citadel_Building_Dialogs
//      Keyboard_Get_ASCII_Hex_Input
//      Wait_For_50Hz_Then_Check_Input
// Sol: Summary: Wait for a number of display retraces.
// Sol: Outline: Call the retrace-polling helper repeatedly using the native WORD count.
void Wait_For_N_Vertical_Retraces(unsigned short NumberOfRetraces)
{
	// Sol:0023 MOV AX,[BP+6]; DEC WORD argument; JNZ tests OLD AX, not decremented count.
	// Sol:Zero performs no waits; count256 is256 waits, not a truncated BYTE zero.
	while (NumberOfRetraces-- != 0)
	{
		Wait_For_Retrace(seg3092->VideoStatusInactiveLevel);
	}
}

// 1F3D:002F: Register uint16 Pending_Input()
// Called from:
//      Main_Game_Loop
//      Drain_Pending_Keyboard_Input_2A2B
//      Overhead_Map_Draw_3FAE
//      Load_And_Play_Intro_Music_476D
//      Start_Game
//      Setup_Game
//      Examine_Screen_BTSTATS_CMP
//      Mech_Mission_0629
//      Recruit_Crescent_Hawk_Agent
//      Combat_Parent_000A
// Sol: Summary: Check whether keyboard input is available.
// Sol: Outline: Use the original live or attract-mode input state and return the native availability result.
unsigned short Pending_Input()
{
	// Sol:003F JZ0050: report pending when a real key exists OR attractor replay is active.
	// Sol:3938 is replay mode, not "disable all input"; probe keyboard first as the native call does.
	if (Check_Input_For_Character() != 0 || seg3092->DisableInput != 0)
		return TRUE;
	return FALSE; // Sol:0050 AX=0; return contract is WORD0/1, no key is consumed here.
}

// 1F3D:0053: void Display_Text_Dynamic_Value(Stack Eq_21 Value)
// Called from:
//      Inspect_Characters
//      Salvage_Armour_Dialog
//      Loot_Enemy_Soldiers_Dialog
//      Distribute_Purchased_Armour
//      Mechlube_Repair_Mech
//      Mechlube_Upgrade_Mech
//      Mechlube_Buy_Ammo
//      StarLeague_Security_Terminal
//      Combat_Parent_000A
//      Combat_Select_Movement_Plan_For_Turn
//      Citadel_Building_Dialogs
// Sol: Summary: Print an unsigned WORD value.
// Sol: Outline: Format the value into the shared numeric string and send it to the text renderer.
void Display_Text_Dynamic_Value(unsigned short Value)
{
	// Sol:0053 native FAR3092:0012 scratch string; unsigned WORD decimal (radix10), then1E56:03F5.
	ASM_Text_Formatting_3BB6(Value, &seg3092->DynamicStringVariable, 0x0A);
	Display_Text_From_Memory(&seg3092->DynamicStringVariable);
}

// 1F3D:0086: void Draw_GraphicsFile_In_Memory(unsigned long * DecompressedMemoryPtr, unsigned short x0, unsigned short y0, unsigned short x1, unsigned short y1)
// Called from:
//      Decode_Draw_Next_ANM_Frame
//      Load_And_Draw_BTTITLE_CMP
//      Setup_Game
//      Examine_Screen_BTSTATS_CMP
//      Copyright_Check_Mech_Quiz
//      Citadel_Building_Dialogs
// Sol: Summary: Copy a staged image rectangle onto the screen.
// Sol: Outline: Keep the original buffer argument but use the retained EGA framebuffer-copy branch.
void Draw_GraphicsFile_In_Memory(unsigned char far *DecompressedMemoryPtr, unsigned short x0, unsigned short y0, unsigned short x1, unsigned short y1)
{	
	// Sol:0086 receives FAR file buffer + four WORDs; EGA branch00B3 ignores buffer, copies preconvertedA800.
	EGA_DrawBox_Operation(VGA_FRAMEBUFFER_FAR, EGA_SCREEN_FAR, x0, y0, x1, y1);
}

// Sol:1F3D:00D5 restored EGA-only text helper, already referenced by maintained callers.
// Sol: Summary: Draw a string using the EGA bitmap font.
// Sol: Outline: Walk characters, find embedded glyph rows, and draw foreground and background pixels.
void Draw_EGA_Text_To_Screen(unsigned char far *Text, unsigned short Column, unsigned short Row,
	unsigned short Foreground, unsigned short Background)
{
	Set_Text_Colours_2127(Foreground, Background);
	unsigned char far *TextCursor = Text;
	unsigned short InitialColumn = Column;
	unsigned short RowByteOffset = (unsigned short)(320UL * Row); // Sol:eight scanlines * forty EGA bytes, not one pixel row.
	while (*TextCursor != 0)
	{
		if (*TextCursor == 0x0D)
		{
			Column = InitialColumn;
			RowByteOffset += 320;
			TextCursor = Advance_Far_Offset_1F3D(TextCursor, 1);
			// Sol:0122 CR does NOT increment global4FBE; only automatic column wrap does.
		}
		else
		{
			unsigned short GlyphByteOffset = (*TextCursor & 0x7F) << 3; // Sol:each glyph eight BYTEs; high bit stripped, not a control marker here.
			TextCursor = Advance_Far_Offset_1F3D(TextCursor, 1);
			if ((short)Column > (short)(unsigned short)(seg3EDB->HorizontalResolution - 1))
			{
				Column = InitialColumn;
				++seg3EDB->CurrentVerticalLine;
				RowByteOffset += 320;
			}
			unsigned short DrawColumn = Column++;
			EGA_Draw_Glyph_2251(GlyphByteOffset, RowByteOffset, DrawColumn);
		}
	}
}

// Sol:1F3D:01FB legacy name retained: this fills an INCLUSIVE rectangle, not one line.
// Sol: Summary: Fill an inclusive EGA rectangle.
// Sol: Outline: Stage coordinates and colour and write its pixel spans without sorting or clipping; the legacy line name is misleading.
void Draw_Horizontal_EGA_Line(unsigned short X0, unsigned short Y0, unsigned short X1, unsigned short Y1, unsigned short Colour)
{
	// Sol:EGA skips the adapter1 special rectangle path. No coordinate sorting/clamping occurs here.
	while ((short)Y1 >= (short)Y0)
	{
		unsigned short DrawRow = Y0++;
		Draw_EGA_Horizontal_Span_03EB(DrawRow, X0, X1, Colour);
	}
}





// 1F3D:0259: Register int16 Keyboard_Get_ASCII_Hex_Input()
// Called from:
//      Main_Game_Loop
//      Prompt_Yes_No
//      Request_Game_Disk_2913
//      Drain_Pending_Keyboard_Input_2A2B
//      Prompt_And_Wait_For_Key_2A4F
//      Load_Game
//      Save_Game
//      Inspect_Characters
//      Overhead_Map_Draw_3FAE
//      Menu_Assign_Pilots
//      Setup_Game
//      Loot_Enemy_Soldiers_Dialog
//      Display_Friendly_Combatant_Description_18E8
//      Examine_Screen_BTSTATS_CMP
//      Interact_with_BLD
//      Execute_Bld_Bytecode_01C0
//      Mech_Mission_0629
//      Distribute_Purchased_Armour
//      Distribute_Weapon_To_Party
//      Talk_To_Building_Occupants
//      Mechlube_Repair_Mech
//      Mechlube_Upgrade_Mech
//      Recruit_Crescent_Hawk_Agent
//      Mechlube_Buy_Ammo
//      StarLeague_Secret_Passageway_Discovered
//      Display_StarLeague_Cache_Dialog_Window
//      StarLeague_HyperPulse_Power_Dialog_Window
//      StarLeague_Security_Terminal
//      HPGTransmitter
//      StarLeague_Map_Room
//      Draw_STARLEAG_ICN_Scene
//      Cache_StarMap_CorrectPassword
//      StarLeague_Key_Codes
//      Heal_Characters
//      Assign_Pilot_and_rider_to_Mechs
//      Copyright_Check_Mech_Quiz
//      Combat_Weapon_UI_0004
//      Prompt_For_Unsigned_Decimal_0CDE
//      Combat_Weapon_Display_Text_And_Menu_Options
//      GameSpeed_RateControl
//      Combat_Parent_000A
//      Combat_Select_Movement_Plan_For_Turn
//      Combat_Kick_Target
//      Scan_Enemies
//      Combat_AudioVisual_Effects
//      Citadel_Building_Dialogs
//      Display_Menu_Choices_And_Check
// Sol: Summary: Read live input or the attract-demo stream.
// Sol: Outline: Read the BIOS-style keyboard value or replay bytes, handling delay tokens and interruption.
signed short Keyboard_Get_ASCII_Hex_Input()
{
	// Sol:0259..031B:3938 zero=live keyboard, nonzero=attractor replay. Legacy DisableInput name retained.
	short InputWord;
	unsigned char far *ReplayMemory = (unsigned char far *)0x30920000UL;
	if (seg3092->DisableInput == 0)
	{
		do
		{
			InputWord = Keyboard_GetKey(); // Sol: BIOS byte -> signed WORD, including FFxx extended keys
			if (seg3092->Bool_Input == 0) return InputWord;
			if (InputWord == 0x0068) InputWord = 0x0048; // Sol: recording h normalises to H delay token
			unsigned short ReplayWriteIndex = seg3092->AttractModeReplayIndex++;
			ReplayMemory[(unsigned short)(0x00A0 + ReplayWriteIndex)] = (unsigned char)InputWord;
		} while (InputWord == 0x0048); // Sol: record H but continue fetching actual input
	}
	else
	{
		do
		{
			unsigned short ReplayReadIndex = seg3092->AttractModeReplayIndex++;
			InputWord = (short)(signed char)ReplayMemory[(unsigned short)(0x00A0 + ReplayReadIndex)];
			if (InputWord == 0x0048) Wait_For_N_Vertical_Retraces(30); // Sol: H waits, then consume next replay byte
		} while (InputWord == 0x0048);
		if (Check_Input_For_Character() != 0)
		{
			seg3EDB->ExitMainLoop = TRUE; // Sol: native3EDB:0152
			Keyboard_GetKey(); // Sol: consume real interruption, not replay input
		}
		Wait_For_N_Vertical_Retraces(1);
		if (InputWord == 0x0050) seg3EDB->ExitMainLoop = TRUE; // Sol: P replay exit token
	}
	return InputWord; // Sol:0318 original local WORD returned in AX; no low-BYTE masking
}

// Sol:1F3D:031C signed sorting/clipping; only axis-aligned lines, not a general diagonal renderer.
// Sol: Summary: Draw a clipped horizontal or vertical line.
// Sol: Outline: Sort and clip endpoints, reject diagonal lines, and dispatch the matching EGA pixel run.
void Draw_Clipped_Axis_Aligned_EGA_Line(unsigned short X0, unsigned short Y0, unsigned short X1, unsigned short Y1, unsigned short Colour)
{
	if ((short)X1 < (short)X0) { unsigned short Swap = X0; X0 = X1; X1 = Swap; }
	if ((short)Y1 < (short)Y0) { unsigned short Swap = Y0; Y0 = Y1; Y1 = Swap; }
	// Sol:Clamp EACH endpoint independently to native inclusive320x200 pixel bounds.
	if ((short)X0 < 0) X0 = 0;
	if ((short)Y0 < 0) Y0 = 0;
	if ((short)X1 < 0) X1 = 0;
	if ((short)Y1 < 0) Y1 = 0;
	if (X0 > 319) X0 = 319;
	if (X1 > 319) X1 = 319;
	if (Y0 > 199) Y0 = 199;
	if (Y1 > 199) Y1 = 199;
	if (X0 == X1)
		EGA_Draw_Vertical_Pixel_Run_05D0(X0, Y0, Y1, Colour); // Sol:03B1 vertical wins for a single point.
	else if (Y0 == Y1)
		Draw_EGA_Horizontal_Span_03EB(Y0, X0, X1, Colour);
	// Sol:03E7 diagonal after clipping emits nothing; wholly offscreen line can clamp to a border point.
}

// Sol:1F3D:03EB: individual edge pixels, aligned groups, then inclusive tail pixels.
// Sol: Summary: Draw a horizontal pixel span.
// Sol: Outline: Split the span into edge masks and aligned groups and write the selected colour through EGA latches.
void Draw_EGA_Horizontal_Span_03EB(unsigned short Y, unsigned short XStart, unsigned short XEnd, unsigned short Colour)
{
	unsigned short AlignmentMask = seg3EDB->HorizontalSpanAlignmentMask[EGA_VGA];
	while ((XStart & AlignmentMask) != 0)
	{
		if ((short)XStart > (short)XEnd) break;
		EGA_Draw_Vertical_Pixel_Run_05D0(XStart++, Y, Y, Colour);
	}
	if ((short)XStart < (short)XEnd)
	{
		unsigned short GroupCount = (unsigned short)(XEnd - XStart);
		GroupCount = (unsigned short)((short)GroupCount >> (unsigned char)seg3EDB->HorizontalSpanGroupShift[EGA_VGA]); // Sol:0441 SAR, not unsigned SHR.
		if (GroupCount != 0)
			EGA_Draw_Aligned_Span_0780(XStart, Y, GroupCount, Colour);
		XStart = XEnd & seg3EDB->HorizontalSpanEndAlignmentMask[EGA_VGA]; // Sol:0468 even if group countzero.
	}
	while ((short)XStart <= (short)XEnd)
		EGA_Draw_Vertical_Pixel_Run_05D0(XStart++, Y, Y, Colour);
}





// 1F3D:049D: void Decompress_File_Into_Memory(Stack (ptr32 Eq_5478) CompressedByteArray, Stack (ptr32 Eq_3311) GraphicByteArray)
// Called from:
//      DOS_Load_Map_Files
//      Load_And_Draw_ANIMATE_ICN
//      Load_And_Draw_BTTLTECH_ICN
//      Load_And_Draw_BTTITLE_CMP
//      Setup_Game
//      Examine_Screen_BTSTATS_CMP
//      Draw_STARLEAG_ICN_AND_Game_Logic
//      StarLeague_Map_Room
//      Draw_STARLEAG_ICN_Scene
//      Copyright_Check_Mech_Quiz
//      Citadel_Building_Dialogs
// Sol: Summary: Decode the game's packed graphics data.
// Sol: Outline: Read compressed commands and copy literal or repeated output bytes into the destination buffer.
void Decompress_File_Into_Memory(unsigned char far *CompressedByteArray, unsigned char far *GraphicByteArray)
{
	// Sol:049D CMP BYTE[ES:BX],1; INC source OFFSET WORD only. Marker is ONE BYTE, not DWORD.
	unsigned char FormatMarker = *CompressedByteArray;
	unsigned char far *EncodedPayload = Advance_Far_Offset_1F3D(CompressedByteArray, 1);
	if (FormatMarker == 0x01)
		Format01_Decode(EncodedPayload, GraphicByteArray); // Sol:207F:22F8
	else
		Format02_Decode(EncodedPayload, GraphicByteArray); // Sol:207F:2368; ALL non1 markers, not only2
	// Sol:04D6..0521 adapter0 post-conversion is intentionally omitted from the maintained EGA path.
}

// 1F3D:0525: void Set_Palette_registers(FAR palette)
// Called from:
//      Load_And_Draw_BTTITLE_CMP
//      Setup_Game
//      Examine_Screen_BTSTATS_CMP
//      Citadel_Building_Dialogs
// Sol: Summary: Apply an EGA palette.
// Sol: Outline: Pass the original palette values to the BIOS-style palette operation.
void Set_Palette_registers(const unsigned char far *Palette)
{
	// Sol:055D..059E maintained EGA body. LES SI,[BP+6] loads a16:16 pointer,
	// Sol: not a BYTE offset. Other adapter bodies remain intentionally removed.
	Wait_For_Retrace(seg3092->VideoStatusInactiveLevel);

	for (unsigned short PaletteRegister = 0; PaletteRegister < 16; ++PaletteRegister)
	{
		short EgaColourValue = (signed char)Palette[PaletteRegister]; // Sol:057E CBW, then signed JLE7
		if (EgaColourValue > 7)
			EgaColourValue += 8; // Sol: map normal logical8..15 to EGA hardware16..23; do not alter high-bit signed inputs
		EGA_Set_Palette_Registers_in_out(PaletteRegister, (unsigned short)EgaColourValue); // Sol:two native WORD arguments
	}
}

// Sol:1F3D:05BC DWORD request wrapper around WORD runtime allocation; restored native research behavior.
// Sol: Summary: Allocate a native working buffer.
// Sol: Outline: Allocate the low WORD byte count, report oversized or null results, and retain the unresolved oversize return path.
unsigned char far *Allocate_Far_Buffer_05BC(unsigned long RequestedBytes)
{
	// Sol:TODO ASM-1F3D-05BC:oversize branch reads native SS:BP-6/BP-4 without assignment.
	// Sol:C uninitialised-pointer use is undefined, not a defined reproduction of those stack WORDs.
	// Sol:Normal/null allocation paths match; do not certify the whole return contract until A-009 is resolved.
	unsigned short RequestedWord = (unsigned short)RequestedBytes;
	unsigned char far *AllocationResult; // Sol:UNINITIALISED natively on positive high-WORD error path; see notes/Astra candidate, NOT safe host code.
	if ((short)(RequestedBytes >> 16) > 0)
	{
		Draw_EGA_Text_To_Screen(seg3EDB->AllocationTooLargeText, 0, 10, EGA_BrightWhite, EGA_Black); // Sol:native FAR3EDB:4FDA, "Alloc too big!".
		Keyboard_Get_ASCII_Hex_Input();
	}
	else
		AllocationResult = Runtime_Allocate_Word_Buffer_3835(RequestedWord);
	// Sol:High WORD zero accepts every low WORD; negative high WORD also falls through to WORD allocation.
	if (AllocationResult == 0)
	{
		Draw_EGA_Text_To_Screen(seg3EDB->AllocationNullReturnText, 0, 10, EGA_BrightWhite, EGA_Black); // Sol:native FAR3EDB:4FE9, "Alloc: Null pointer return!".
		Keyboard_Get_ASCII_Hex_Input();
	}
	return AllocationResult; // Sol:0631 DX:AX; no retry/termination/substitute result added.
}

// 1F3D:063B: void Load_File_To_Memory(Stack Eq_21 FileName, Stack Eq_21 Memory)
// Called from:
//      DOS_Load_Map_Files
//      Load_And_Draw_ANIMATE_ICN
//      Load_And_Draw_BTTLTECH_ICN
//      Load_And_Draw_BTTITLE_CMP
//      Setup_Game
//      Examine_Screen_BTSTATS_CMP
//      Load_And_Decode_Indexed_BLD_1D30
//      Draw_STARLEAG_ICN_AND_Game_Logic
//      StarLeague_Map_Room
//      Draw_STARLEAG_ICN_Scene
//      Copyright_Check_Mech_Quiz
//      Citadel_Building_Dialogs
// Sol: Summary: Load a complete original asset into a buffer.
// Sol: Outline: Retry failed opens, read a two-byte payload length, read that many bytes into the buffer, and close without checking read status.
unsigned short Load_File_To_Memory(const unsigned char far *FileName, unsigned char far *Memory)
{
	// Sol:TODO ASM-1F3D-0665:native LEA AX,[BP-2]; PUSH SS supplies a FAR stack address.
	// Sol:Ordinary &PayloadByteCount does not explicitly retain SS when converted to a FAR buffer argument.
	// Sol:Use an explicit stack binding/temporary byte buffer in the correction pass; retry/read/close order otherwise matches.
	unsigned short RetryOpen;
	do
	{
		RetryOpen = FALSE; // Sol:0646 reset each attempt, native WORD BP-4.
		signed short FileHandle = (signed short)Get_FileHandle(FileName, 0x8000); // Sol:207F:33D0 library binary/read-only flag, NOT raw DOS open mode.
		if (FileHandle != FileOperation_Failed)
		{
			unsigned short PayloadByteCount; // Sol:0665 FAR SS:BP-2 receives little-endian length prefix.
			DOS_read_file_handler(FileHandle, &PayloadByteCount, 2);
			DOS_read_file_handler(FileHandle, Memory, PayloadByteCount);
			DOS_close_file(FileHandle);
			// Sol:Read/close return values are ignored natively; no invented short-read retries.
		}
		else
			RetryOpen = TRUE;
		if (RetryOpen != FALSE)
			Request_Game_Disk_2913(seg3EDB->RequestedGameDiskNumber); // Sol:06A5 prompt before retry.
	} while (RetryOpen != FALSE);
	return TRUE; // Sol:06BC MOV AX,1; means open path completed, NOT verified payload integrity.
}

// 1F3D:06C3: void EGA_DrawBox_Wrapper()
// Called from:
//      Main_Game_Loop
//      Game_Pause_Menu
//      Show_Overhead_Map
//      Mech_Mission_0629
//      Restore_Mission_Map_View_After_Combat
//      Draw_STARLEAG_ICN_AND_Game_Logic
//      StarLeague_Secret_Passageway_Discovered
//      StarLeague_Map_Room
//      Draw_STARLEAG_ICN_Scene
//      StarLeague_Key_Codes
//      Menu_Draw_MultiSelect
//      Combat_Parent_000A
//      Combat_MovementTarget_unknown_1774
//      Combat_Mechanics
//      Combat_AudioVisual_Effects
//      Citadel_Building_Dialogs
// Sol: Summary: Present the working world viewport.
// Sol: Outline: Copy the native AC00 working rectangle to the A000 screen using the fixed viewport bounds.
void EGA_DrawBox_Wrapper()
{
	EGA_DrawBox_Operation(EGA_MAP_FRAMEBUFFER_FAR, EGA_SCREEN_FAR, 0x0D, 0x00, 0x1B, 200); // Sol:06D1 ASM FAR buffers,216x200px viewport.
}



// Sol:1F3D:070A startup sprite snapshot allocation; fills the39FA FAR-pointer table.
// Sol:0800's eight readers now use CombatSpritePointers; see BTECH_0800_SPRITE_POINTER_READERS.md.
// Sol: Summary: Allocate and capture one sprite snapshot.
// Sol: Outline: Store its geometry header, copy its planar pixel rectangle, and publish the FAR pointer under the sprite ID.
void Capture_Combat_Sprite_070A(unsigned short SpriteId, unsigned short X, unsigned short Y, unsigned short Width, unsigned short Height)
{
	unsigned short PayloadBytes = (unsigned short)((unsigned long)(unsigned short)((unsigned long)Width * Height) * 4); // Sol:IMUL retains AX before MUL4; native wrap BEFORE adding header.
	unsigned char far *SpriteBuffer = Allocate_Far_Buffer_05BC((unsigned short)(PayloadBytes + 4));
	seg3092->CombatSpritePointers[SpriteId].Offset = (unsigned short)(unsigned long)SpriteBuffer;
	seg3092->CombatSpritePointers[SpriteId].Segment = (unsigned short)((unsigned long)SpriteBuffer >> 16);
	if (SpriteBuffer == 0) return;
	SpriteBuffer[1] = (unsigned char)(Height - 1);
	SpriteBuffer[2] = (unsigned char)Width; // Sol:0757 writes only header BYTEs1/2;0/3 are not initialised here.
	unsigned short SourceX = (unsigned short)(X << 2); // Sol:X/width units are eight-pixel cells: four INTERLEAVED PLANE BYTEs each, after startup0572 conversion.
	unsigned short SourceRowOffset = (unsigned short)(160UL * Y); // Sol:forty cells *four planes =160BYTEs per scanline; Y/height are scanlines.
	unsigned short WordsPerRow = (unsigned short)(Width << 1); // Sol:EGA branch0787 doubles width before0931 REP MOVSW.
	unsigned short SourceRowGap = (unsigned short)(160 - (unsigned short)(WordsPerRow << 1));
	unsigned char far *Source = Advance_Far_Offset_1F3D((unsigned char far *)&seg246C->Ptr_DecompressedFile_Memory_Block, (unsigned short)(SourceX + SourceRowOffset)); // Sol:native FAR246C:244B buffer ADDRESS, not dereferenced pointer-shaped scratch field.
	Copy_Strided_Word_Rows_0931(Source, Advance_Far_Offset_1F3D(SpriteBuffer, 4), WordsPerRow, Height, SourceRowGap);
	// Sol:07D7 second-buffer copy belongs ONLY to removed adapter0; EGA captures interleaved planar buffer once.
	// Sol:0931 truncates row/width counts to BYTE; heightzero executes256 rows, not zero. No guard invented.
}

// 1F3D:0814: void DOS_Load_File_to_memory(Stack Eq_21 Filename, Stack Eq_21 BufferForData, Stack Eq_21 BytesToRead)
// Called from:
//      Display_Animation_Scene
//      Start_Game
//      Play_Failed_Mech_Startup_Scene_16B2
//      StarLeague_Map_Room
// Sol: Summary: Read a requested number of file bytes.
// Sol: Outline: Open the original filename, read into the supplied buffer, and close while preserving the native error contract.
void DOS_Load_File_to_memory(const unsigned char far *Filename, unsigned char far *BufferForData, unsigned short BytesToRead)
{
	// Sol:0814 raw fixed-count loader: no two-byte length prefix; failed open prompts/retries.
	signed short FileHandle = (signed short)Get_FileHandle(Filename, 0x8000);
	while (FileHandle == FileOperation_Failed) // Sol:0832 INC AX/JZ recognises FFFF exactly.
	{
		Request_Game_Disk_2913(seg3EDB->RequestedGameDiskNumber);
		FileHandle = (signed short)Get_FileHandle(Filename, 0x8000);
	}
	DOS_read_file_handler(FileHandle, BufferForData, BytesToRead);
	DOS_close_file(FileHandle); // Sol:read/close status ignored; unlike063B, no deliberate AX=1 result.
}

// 1F3D:086A: void Wait_For_50Hz_Then_Check_Input()
// Called from:
//      Inspect_Characters
//      Loot_Enemy_Soldiers_Dialog
//      Display_Friendly_Combatant_Description_18E8
//      Execute_Bld_Bytecode_01C0
//      Mech_Mission_0629
//      Distribute_Purchased_Armour
//      Distribute_Weapon_To_Party
//      StarLeague_Key_Codes
//      Heal_Characters
//      Assign_Pilot_and_rider_to_Mechs
//      Combat_Parent_000A
//      Citadel_Building_Dialogs
//      Display_Text_From_Memory_ScreenRetrace_KeyboardInput
// Sol: Summary: Apply the standard short presentation pause.
// Sol: Outline: Wait the native retrace count and inspect input through the shared keyboard helpers.
void Wait_For_50Hz_Then_Check_Input()
{
	// Sol:086A waits FIFTY retrace edges, then drains pending keys. This does not configure a50Hz rate.
	Wait_For_N_Vertical_Retraces(InputPause_RetraceCount);
	Drain_Pending_Keyboard_Input_2A2B();
}
