// BTECH_11B8.c
// Generated by decompiling BTECH.EXE
// using Reko decompiler version 0.11.2.0.

#include "BTECH.h"

// 11B8:0002: void Mechlube_Repair_Mech(void)
// Called from:
//      Citadel_Building_Dialogs
// Sol: Summary: Buy repairs for a party mech.
// Sol: Outline: Inspect damage by component category, calculate charges, obtain confirmation, and apply affordable repairs.
void Mechlube_Repair_Mech(void)
{
	// Sol: Preservation cleanup: retain FAR3092 record/byte views and explicit
	// Sol: WORD narrowing for deficits, combined damage, quotes and menu subtraction.
	// Sol: Original BUG-008/009 and over-maximum repair behaviour remain unchanged.
	Draw_Top_Graphic_Sidebar();
	Display_Text_From_Memory((uint8_t far *)"Fix which 'Mech?\r"); //3EDB:17E5
	Display_Text_Mech_Names();

	Mech far *selectedMech = &seg3092->Mechs[seg3092->Mech_Selected];
	uint8_t far *selectedMechBytes = (uint8_t far *)selectedMech;
	uint16_t armourRepairsRemaining = 0;
	uint16_t structureRepairsRemaining = 0;
	uint16_t destroyedHeatSinkCount = 0;
	uint16_t hasDestroyedWeapons = FALSE;
	uint16_t damagedActuatorFlags = 0;
	uint16_t weaponMenuComponentIndexes[MechRepairWeaponScratchCount] = { 0 };
	uint16_t destroyedWeaponCountByType[MechRepairWeaponScratchCount] = { 0 };
	uint8_t far *finalRepairStatusText;
	uint8_t far *repairResultText;

	// Sol: Sum all eleven missing armour points. The former pseudo-C used the
	// Sol: structure array and overwrote rather than accumulated the total.
	for (uint16_t armourIndex = 0; armourIndex < MechArmourLocationCount; armourIndex++)
	{
		armourRepairsRemaining = (uint16_t)(armourRepairsRemaining +
			selectedMech->MaxArmour[armourIndex] - selectedMech->CurrentArmour[armourIndex]);
	}

	// Sol: Sum all eight missing internal-structure points independently.
	for (uint16_t structureIndex = 0;
		 structureIndex < MechInternalStructureLocationCount;
		 structureIndex++)
	{
		structureRepairsRemaining = (uint16_t)(structureRepairsRemaining +
			selectedMech->MaxStructure[structureIndex] - selectedMech->CurrentStructure[structureIndex]);
	}

	// Sol: Critical offsets 33h-55h are one contiguous 35-byte component block.
	// Sol: Count destroyed heat sinks separately and destroyed weapons by the
	// Sol: verified component-ID range 10h-20h. Kick (21h) is not repair-listed.
	for (uint16_t criticalOffset = MECH_ComponentBlock_Start;
		 criticalOffset <= MECH_ComponentBlock_End;
		 criticalOffset++)
	{
		uint8_t rawComponent = selectedMechBytes[criticalOffset];
		if ((rawComponent & Component_Destroyed) != 0)
		{
			uint8_t componentId = rawComponent & MechComponentIdMask;
			if (componentId == Heat_Sink)
				destroyedHeatSinkCount++;

			if (componentId >= Mech_Small_Laser && componentId <= Mech_SRMissile6)
			{
				destroyedWeaponCountByType[componentId - Mech_Small_Laser]++;
				hasDestroyedWeapons = TRUE;
			}
		}
	}

	// Sol: Bit 0 means the left packed actuator byte differs from maximum;
	// Sol: bit 1 means the right byte differs. These are side flags, not limbs.
	if (selectedMech->CurrentActuators[MechActuatorSide_Left] != selectedMech->MaxActuators[MechActuatorSide_Left])
		damagedActuatorFlags = MechRepairDamagedActuators_Left;
	if (selectedMech->CurrentActuators[MechActuatorSide_Right] != selectedMech->MaxActuators[MechActuatorSide_Right])
		damagedActuatorFlags |= MechRepairDamagedActuators_Right;

	if ((uint16_t)(destroyedHeatSinkCount + armourRepairsRemaining + hasDestroyedWeapons
		+ structureRepairsRemaining + damagedActuatorFlags) == 0)
	{
		uint16_t facilityCannotRepair = FALSE;
		for (uint16_t internalDamageOffset = MECH_Offset_Engine;
			 internalDamageOffset <= MECH_Offset_Sensors;
			 internalDamageOffset++)
		{
			if (selectedMechBytes[internalDamageOffset] != 0)
			{
				Display_Text_From_Memory((uint8_t far *)"Our facility doesn't have the equipment to fix your damaged "); // Memory ref: [3EDB:17F7]
				Display_Text_From_Memory(
					seg3EDB->UnrepairableMechComponentText[
						internalDamageOffset - MECH_Offset_Engine]);
				facilityCannotRepair = TRUE;
				break;
			}
		}

		if (facilityCannotRepair != FALSE)
		{
WaitForRepairAcknowledgement:
			Keyboard_Get_ASCII_Hex_Input();
			return;
		}
		finalRepairStatusText = (uint8_t far *)"\r\rThat 'Mech looks shiny new to me.  It doesn't need anything fixed."; //3EDB:1834
	}
	else
	{		
		
		// Sol: The native test ORs the low and high WORDs of the 32-bit balance.
		// Sol: A zero balance ends the whole shop visit before any repair prompt.
		if (seg3092->CBills == 0) // D370:D372
		{
			Display_Text_From_Memory((uint8_t far *)"\r\rYou don't have any C-bills.  "); //3EDB:1879
			Display_Text_Shop_Cannot_Afford_Text();
			goto WaitForRepairAcknowledgement;
		}

		if (armourRepairsRemaining != 0)
		{
			Draw_Top_Graphic_Sidebar();
			Display_Text_From_Memory((uint8_t far *)"Looks like this 'Mech has lost about "); //3EDB:1899
			Display_Text_Dynamic_Value(armourRepairsRemaining);
			Display_Text_From_Memory((uint8_t far *)" pieces of armor.  If you want those replaced, it's going to cost "); //3EDB:18BF
			Display_Text_Dynamic_Value((uint16_t)(armourRepairsRemaining * MechRepairArmourPointCostCBills));
			Display_Text_From_Memory((uint8_t far *)" C-bills.  You've got "); //3EDB:1902
			Citadel_Building_Dialogs(CitadelDialog_DisplayCBillBalance);
			Display_Text_From_Memory((uint8_t far *)"  Want it fixed?"); //3EDB:1919
			if (Prompt_Yes_No(TRUE))
			{
				// Sol: Repair in record order, one point and four C-bills at a time.
				// Sol: This preserves affordable partial work if funds run out midway.
				for (uint16_t armourIndex = 0;
					 armourIndex < MechArmourLocationCount;
					 armourIndex++)
				{
					uint16_t missingArmourAtLocation =
						(uint16_t)(selectedMech->MaxArmour[armourIndex] - selectedMech->CurrentArmour[armourIndex]);

					while (missingArmourAtLocation != 0)
					{
						// Sol: The assembly performs an unsigned 32-bit comparison with four.
						// Sol: On failure it abandons this location; the outer loop continues.
						if (seg3092->CBills < MechRepairArmourPointCostCBills)
							missingArmourAtLocation = 0;
						else
						{
							seg3092->CBills -= MechRepairArmourPointCostCBills;
							missingArmourAtLocation--;
							armourRepairsRemaining--;
							selectedMech->CurrentArmour[armourIndex]++;
							Display_Text_CBill_Balance();
						}
					}
				}

				if (armourRepairsRemaining != 0)
				{
					Draw_Top_Graphic_Sidebar();
					Display_Text_From_Memory((uint8_t far *)"We fixed as much as you could afford, but you ran out of cash before the job was done."); //3EDB:192A
					Keyboard_Get_ASCII_Hex_Input(); //1F3D:0259
				}
			}
		}
		if (structureRepairsRemaining != 0)
		{
			Draw_Top_Graphic_Sidebar();
			Display_Text_From_Memory((uint8_t far *)"This 'Mech has had some of its internal structure damaged."); //3EDB:1981
			Display_Text_From_Memory((uint8_t far *)"  If you want to fix any weapons or heat sinks, you have to have structure to mount them on."); //3EDB:19BC
			Display_Text_From_Memory((uint8_t far *)" If you want the structure fixed, it's going to cost "); //3EDB:1A19
			Display_Text_Dynamic_Value((uint16_t)(structureRepairsRemaining * MechRepairStructurePointCostCBills));
			Display_Text_From_Memory((uint8_t far *)" C-bills.  You've got "); //3EDB:1A4F
			Citadel_Building_Dialogs(CitadelDialog_DisplayCBillBalance);
			Display_Text_From_Memory((uint8_t far *)"  Want it fixed?"); //3EDB:1A66

			if (Prompt_Yes_No(TRUE))
			{
				// Sol: Raw offsets 1Ch-23h are the eight CurrentStructure bytes.
				// Sol: Repair them in record order for nine C-bills per point.
				for (uint16_t structureIndex = 0;
					 structureIndex < MechInternalStructureLocationCount;
					 structureIndex++)
				{
					uint16_t missingStructureAtLocation =
						(uint16_t)(selectedMech->MaxStructure[structureIndex] - selectedMech->CurrentStructure[structureIndex]);

					while (missingStructureAtLocation != 0)
					{
						// Sol: The native comparison and subtraction cover both balance WORDs.
						// Sol: Insufficient funds stop this location but do not roll work back.
						if (seg3092->CBills < MechRepairStructurePointCostCBills)
							missingStructureAtLocation = 0;
						else
						{
							seg3092->CBills -= MechRepairStructurePointCostCBills;
							missingStructureAtLocation--;
							structureRepairsRemaining--;
							selectedMech->CurrentStructure[structureIndex]++;
							Display_Text_CBill_Balance();
						}
					}
				}

				if (structureRepairsRemaining != 0)
				{
					Draw_Top_Graphic_Sidebar();
					Display_Text_From_Memory((uint8_t far *)"We fixed as much as you could afford, but you ran out of cash before the job was done."); //3EDB:1A77
					Keyboard_Get_ASCII_Hex_Input(); //1F3D:0259
				}
			}
		}
		if (destroyedHeatSinkCount != 0)
		{
			Draw_Top_Graphic_Sidebar();
			Display_Text_From_Memory((uint8_t far *)"You've had "); //3EDB:1ACE
			Display_Text_Dynamic_Value(destroyedHeatSinkCount);
			Display_Text_From_Memory((uint8_t far *)" heat sink"); //3EDB:1ADA
			if (destroyedHeatSinkCount > 0x0001)
				Display_Text_From_Memory((uint8_t far *)"s"); //3EDB:1AE5

			Display_Text_From_Memory((uint8_t far *)"   damaged.  We have a special on heat sinks this month: only 800 C-bills each!  You've got "); //3EDB:1AE7
			Citadel_Building_Dialogs(CitadelDialog_DisplayCBillBalance);
			Display_Text_From_Memory((uint8_t far *)"  Want to fix some heat sinks?"); //3EDB:1B44

			if (Prompt_Yes_No(TRUE))
			{
				// Sol: Scan all 35 critical slots in physical record order. Only the
				// Sol: exact destroyed-heat-sink byte A2h is replaced with intact 22h.
				for (uint16_t criticalOffset = MECH_ComponentBlock_Start;
					 criticalOffset <= MECH_ComponentBlock_End;
					 criticalOffset++)
				{
					if (destroyedHeatSinkCount != 0
						&& selectedMechBytes[criticalOffset] == Destroyed_Heat_Sink)
					{
						// Sol: The native comparison and SUB/SBB charge the full
						// Sol: 32-bit balance. Unaffordable slots remain destroyed.
						if (seg3092->CBills >= MechRepairHeatSinkCostCBills)
						{
							seg3092->CBills -= MechRepairHeatSinkCostCBills;
							destroyedHeatSinkCount--;
							selectedMechBytes[criticalOffset] = Heat_Sink;
							Display_Text_CBill_Balance();
						}
					}
				}

				if (destroyedHeatSinkCount != 0)
				{
					Draw_Top_Graphic_Sidebar();
					repairResultText = (uint8_t far *)"The job's not complete.  You need to come up with some cash before we can finish."; //3EDB:1B63
DisplayRepairResultAndWait:
					Display_Text_From_Memory(repairResultText);
					Keyboard_Get_ASCII_Hex_Input(); //1F3D:0259
				}
			}
		}
		while (hasDestroyedWeapons != FALSE)
		{
			Draw_Top_Graphic_Sidebar();
			Display_Text_From_Memory((uint8_t far *)"Here's your weapons estimate:"); //3EDB:1BB5

			// Sol: This twenty-WORD array maps visible menu rows back to the
			// Sol: zero-based mech weapon-type indexes used by the damage counts.
			for (uint16_t menuMapIndex = 0;
				 menuMapIndex < MechRepairWeaponScratchCount;
				 menuMapIndex++)
			{
				weaponMenuComponentIndexes[menuMapIndex] = 0;
			}

			uint16_t visibleWeaponRowCount = 0;

			// Sol: Indexes 0..10h correspond to component IDs 10h..20h.
			for (uint16_t weaponTypeIndex = 0;
				 weaponTypeIndex < MechRepairWeaponTypeCount;
				 weaponTypeIndex++)
			{
				if (destroyedWeaponCountByType[weaponTypeIndex] != 0)
				{
					Display_Text_4FA0_Value();
					Display_Text_Dynamic_Value(
						destroyedWeaponCountByType[weaponTypeIndex]);
					seg3092->HorizontalLine_Offset++;

					// Sol: 2FD7h is weapon-table index 0Fh (SmallLaser). Each
					// Sol: following mech weapon record has the verified 11h stride.
					Display_Text_From_Memory(
						seg3EDB->WeaponStats[
							weaponTypeIndex + (Mech_Small_Laser - MechComponentToWeaponRecordBias)].Name);
					weaponMenuComponentIndexes[visibleWeaponRowCount] =
						weaponTypeIndex;
					visibleWeaponRowCount++;
				}
			}

			// Sol: These 305B words are generic menu bounds/state here; their
			// Sol: legacy party-member field names do not describe this use.
			seg305B->VerticalOffset = MechRepairWeaponMenuFirstRow;
			seg305B->NumberOfPartyMembers = seg3092->VerticalLine_Offset;
			seg305B->CrescentHawks = 0;

			Display_Text_From_Memory((uint8_t far *)"\rNothing\r\rAt 300 C-bills per item, what do you want to fix?"); //3EDB:1BD3
			seg3092->HorizontalLine_Offset = 0;
			seg3092->VerticalLine_Offset = MechRepairCBillDisplayRow;

			Display_Text_From_Memory((uint8_t far *)"C-bills: "); //3EDB:1C0F
			Citadel_Building_Dialogs(CitadelDialog_DisplayCBillBalance);

			// Sol: The native caller stores AX as a WORD; the1E56 audit now confirms
			// Sol: Display_Menu_Choices_And_Check has a matching unsigned-short signature.
			uint16_t weaponMenuChoice =
				(uint16_t)Display_Menu_Choices_And_Check(MechRepairWeaponMenuBottomRow);
			if ((uint16_t)(seg305B->NumberOfPartyMembers - 1)
				!= weaponMenuChoice)
			{
				if (seg3092->CBills >= MechRepairWeaponSelectionCostCBills)
				{
					seg3092->CBills -= MechRepairWeaponSelectionCostCBills;
					Display_Text_CBill_Balance();

					uint16_t selectedWeaponTypeIndex =
						weaponMenuComponentIndexes[weaponMenuChoice];
					destroyedWeaponCountByType[selectedWeaponTypeIndex]--;

					uint16_t destroyedComponentByte =
						selectedWeaponTypeIndex + Component_Destroyed
						+ Mech_Small_Laser;
					// Sol: Original BUG-008: one purchase clears EVERY matching slot,
					// Sol: although the menu count above is decremented only once.
					for (uint16_t criticalOffset = MECH_ComponentBlock_Start;
						 criticalOffset <= MECH_ComponentBlock_End;
						 criticalOffset++)
					{
						if (selectedMechBytes[criticalOffset]
							== destroyedComponentByte)
						{
							selectedMechBytes[criticalOffset] &= MechComponentIdMask;
						}
					}
					hasDestroyedWeapons = FALSE;

					// Sol: Original BUG-009: the native '< 10h' bound checks only
					// Sol: indexes 0..0Fh and omits SRM-6 index 10h.
					for (uint16_t remainingWeaponTypeIndex = 0;
						 remainingWeaponTypeIndex < MechRepairWeaponContinuationTypeCount;
						 remainingWeaponTypeIndex++)
					{
						if (destroyedWeaponCountByType[remainingWeaponTypeIndex]
							!= 0)
						{
							hasDestroyedWeapons = TRUE;
						}
					}

					if (hasDestroyedWeapons != FALSE)
						continue;

					seg3092->HorizontalLine_Offset = 0;
					seg3092->VerticalLine_Offset = MechRepairWeaponResultDisplayRow;
					repairResultText = (uint8_t far *)"All your weapons are fixed."; //3EDB:1C19
					goto DisplayRepairResultAndWait;
				}
				else
				{
					hasDestroyedWeapons = FALSE;
					repairResultText = (uint8_t far *)"\r\rYou're out of cash."; //3EDB:1C35
					goto DisplayRepairResultAndWait;
				}
			}
			hasDestroyedWeapons = FALSE;
		}
		if (damagedActuatorFlags == 0)
			return;

		Draw_Top_Graphic_Sidebar();
		Display_Text_From_Memory((uint8_t far *)"You've got some damaged actuators.  "); //3EDB:1C4B

		// Sol: This is one flat repair price whether one or both packed side
		// Sol: bytes differ from maximum. The native check covers both C-bill WORDs.
		if (seg3092->CBills >= MechRepairActuatorsCostCBills)
		{
			Display_Text_From_Memory((uint8_t far *)"For 200 C-bills, we'll patch them all."); //3EDB:1C70
			Display_Text_From_Memory((uint8_t far *)"\r\rIs it a deal?"); //3EDB:1C97

			if (Prompt_Yes_No(TRUE))
			{
				Display_Text_From_Memory((uint8_t far *)"\r\rThey're all patched up, good as new."); //3EDB:1CA7
				Keyboard_Get_ASCII_Hex_Input(); //1F3D:0259

				// Sol: Restore the complete right then left packed actuator bytes
				// Sol: from the chassis maxima. The correct value is not always FFh.
				selectedMech->CurrentActuators[MechActuatorSide_Right] = selectedMech->MaxActuators[MechActuatorSide_Right];
				selectedMech->CurrentActuators[MechActuatorSide_Left] = selectedMech->MaxActuators[MechActuatorSide_Left];

				seg3092->CBills -= MechRepairActuatorsCostCBills;
				Display_Text_CBill_Balance();
			}
			return;
		}
		finalRepairStatusText = (uint8_t far *)"However, you don't have the 200 C-bills it takes to get them fixed."; //3EDB:1CCE
	}
	// Sol: The native paths carry this 16-bit data-segment string offset in AX
	// Sol: to the shared display-and-wait epilogue at 07F6h.
	Display_Text_From_Memory(finalRepairStatusText);
	goto WaitForRepairAcknowledgement;
}

// 11B8:080A: void Mechlube_Modify_Mech()
// Called from:
//      Citadel_Building_Dialogs
// Sol: Summary: Select a mech modification package and quote its price.
// Sol: Outline: Check upgrade state, choose the chassis/stage package, and store the package ID and price for the purchase routine.
void Mechlube_Modify_Mech()
{
	// TODO Sol: Fresh ASM audit: SelectedMech must retain FAR3092, not near DS.
	// Sol: This routine selects/quotes only; 0925 performs the charge and upgrade.
	Draw_Top_Graphic_Sidebar();
	Display_Text_From_Memory("Modify which 'Mech?\r"); //3EDB:1D1E
	Display_Text_Mech_Names();

	Mech* SelectedMech = &seg3092->Mechs[seg3092->Mech_Selected];

	// Sol: +7Ch is the upgrade-level flag byte. Value 3 means both upgrade
	// Sol: stages are installed; this is not a Chameleon chassis-ID check.
	if (SelectedMech->UpgradeLevelFlags == 0x03)
	{
		Draw_Top_Graphic_Sidebar();
		Display_Text_From_Memory("Hey, that thing is already pretty powerful.  We can't modify that any further."); //3EDB:1D33
		seg3092->MechModificationWorkflowEnabled = FALSE;
		return;
	}

	seg3092->MechModificationWorkflowEnabled = TRUE;
	Draw_Top_Graphic_Sidebar();
	seg3092->HorizontalLine_Offset = 0x0000;
	seg3092->VerticalLine_Offset = 0x0016;

	Display_Text_From_Memory("C-bills: "); //3EDB:1D82
	Citadel_Building_Dialogs(0x0A);
	seg3092->VerticalLine_Offset = 0x0000;
	seg3092->HorizontalLine_Offset = 0x0000;

	unsigned short SelectedUpgradePackage = SelectedMech->UpgradePackageBase;

	// Sol: Base values 0..3 select the four supported chassis packages.
	// Sol: Exact level value 1 selects their second-stage entries 4..7.
	if (SelectedUpgradePackage > MECH_COMMANDO_LEVEL1)
		SelectedUpgradePackage = MECH_UPGRADE_UNSUPPORTED;
	else if (SelectedMech->UpgradeLevelFlags == 0x01)
		SelectedUpgradePackage += 0x0004;

	if (SelectedUpgradePackage > MECH_COMMANDO_LEVEL2)
		SelectedUpgradePackage = MECH_UPGRADE_UNSUPPORTED;

	seg3092->SelectedMechUpgradePackage =
		(unsigned char)SelectedUpgradePackage;

	if (SelectedUpgradePackage == MECH_UPGRADE_UNSUPPORTED)
	{
		// Sol: Original BUG-010: [1D8Ch + 8*2] reads the CR CR bytes at
		// Sol: 1D9Ch. Express the observed 0D0Dh value without C array overrun.
		seg3092->MechUpgradeCost = MECH_UPGRADE_UNSUPPORTED_PSEUDO_COST;
	}
	else
	{
		seg3092->MechUpgradeCost =
			seg3EDB->MechUpgradeCostByPackage[SelectedUpgradePackage];
	}
}

// 11B8:0925: void Mechlube_Upgrade_Mech()
// Called from:
//      Citadel_Building_Dialogs
// Sol: Summary: Buy a mech upgrade package.
// Sol: Outline: Select the supported package, check funds and prerequisites, and modify the mech's statistics and equipment.
void Mechlube_Upgrade_Mech()
{
	// TODO Sol: Fresh whole-body ASM audit: SelectedMech must retain FAR3092.
	// Sol: All eight package mutations and unsigned DWORD affordability checked.
	Display_Text_From_Memory("\r\rAll for the incredibly low price of only "); //3EDB:1D9C
	Display_Text_Dynamic_Value((unsigned short)seg3092->MechUpgradeCost);
	Display_Text_From_Memory(" C-bills.  Want to modify your 'Mech?"); //3EDB:1DC8

	if (Prompt_Yes_No(0x01))
	{
		// Sol: CWD proves the stored WORD is treated as signed before the
		// Sol: unsigned two-WORD comparison with the 32-bit C-bill balance.
		signed long UpgradeCost = (signed long)seg3092->MechUpgradeCost;
		if ((unsigned long)UpgradeCost > seg3092->CBills)
		{
			Display_Text_4FA0_Value();
			Display_Text_4FA0_Value();
			Display_Text_Shop_Cannot_Afford_Text();
		}
		else
		{
			// Sol: The charge happens before selector validation. Original
			// Sol: BUG-010 therefore charges pseudo-package 8 before doing no work.
			seg3092->CBills -= (unsigned long)UpgradeCost;

			// Sol: Historical package descriptions retained from the earlier notes.
			// Sol: The case bodies below document the executable's exact mutations.
			//LOCUST
			//1: The two machine guns are swapped by two medium lasers. 
			//2: The fusion generator is swapped by a smaller model, in return two additional small lasers are installed. 

			//WASP
			//1: The SRM-2 is removed in favour of a medium laser and an improved armour. 
			//2: The jump jets are removed to make room for three other medium lasers. 

			//STINGER
			//1: Two machine guns are removed and are more than compensated by four small lasers. 
			//2: The jump jets are removed. For this two medium lasers are installed and the armour is pimped.

			//COMMANDO
			//1: The missile launcher SRM-4 is swapped by two medium lasers and an improved armour.
			//2: The SRM-6 is also removed, a medium laser and two small lasers are added as enhancement. Among experts, the upgrade is called "Blazing Inferno". 

			// Sol: Every package recomputes Mech_Selected * 0x7D in the native
			// Sol: code. This pointer is the cleaned representation for reviewed cases.
			Mech* SelectedMech = &seg3092->Mechs[seg3092->Mech_Selected];

			Display_Text_CBill_Balance();
			if (seg3092->SelectedMechUpgradePackage <= 0x07)
			{
				switch (seg3092->SelectedMechUpgradePackage)
					{
					case MECH_LOCUST_LEVEL1:
						// Sol: 11B8:09D3-0A0F. The stock Locust's first arm
						// Sol: weapon entries are replaced with medium lasers. Their
						// Sol: paired ammo-state bytes become the laser sentinel 0xFF.
						SelectedMech->Critical_R_Arm[0] = Mech_Med_Laser; // record+41h
						SelectedMech->Critical_L_Arm[0] = Mech_Med_Laser; // record+33h
						SelectedMech->MaxAmmo[1] = Ammo_Laser_Infinite;   // record+6Ch
						SelectedMech->MaxAmmo[0] = Ammo_Laser_Infinite;   // record+6Bh
						SelectedMech->CurrentAmmo[1] = Ammo_Laser_Infinite; // record+28h
						SelectedMech->CurrentAmmo[0] = Ammo_Laser_Infinite; // record+27h
						// Sol: Assignment, not OR: this establishes exact stage-one state.
						SelectedMech->UpgradeLevelFlags = 0x01; // record+7Ch
						break;

					case MECH_WASP_LEVEL1:
						// Sol: 11B8:0A10-0A97. Replace the first left-leg weapon,
						// Sol: then copy both armour profiles from the reference Locust.
						SelectedMech->Critical_L_Leg[0] = Mech_Med_Laser;
						SelectedMech->MaxAmmo[1] = Ammo_Laser_Infinite;
						SelectedMech->CurrentAmmo[1] = Ammo_Laser_Infinite;
						for (unsigned short ArmourLocation = 0x0000;
							 ArmourLocation < 0x000B; ArmourLocation++)
						{							
							SelectedMech->CurrentArmour[ArmourLocation] =
								seg2FE8->MechRefs[MECH_REF_Locust].CurrentArmour[ArmourLocation];
							SelectedMech->MaxArmour[ArmourLocation] =
								seg2FE8->MechRefs[MECH_REF_Locust].MaxArmour[ArmourLocation];
						}
						SelectedMech->UpgradeLevelFlags = 0x01;
						break;

					case MECH_STINGER_LEVEL1:
						// Sol: 11B8:0A98-0AF2. Four arm critical entries become
						// Sol: small lasers and weapon-state slots 0..4 become infinite.
						SelectedMech->Critical_R_Arm[2] = Mech_Small_Laser;
						SelectedMech->Critical_R_Arm[1] = Mech_Small_Laser;
						SelectedMech->Critical_L_Arm[1] = Mech_Small_Laser;
						SelectedMech->Critical_L_Arm[0] = Mech_Small_Laser;
						for (unsigned short WeaponSlot = 0x0000;
							 WeaponSlot <= 0x0004; WeaponSlot++)
						{						
							SelectedMech->MaxAmmo[WeaponSlot] = Ammo_Laser_Infinite;
							SelectedMech->CurrentAmmo[WeaponSlot] = Ammo_Laser_Infinite;
						}
						SelectedMech->UpgradeLevelFlags = 0x01;
						break;

					case MECH_COMMANDO_LEVEL1:
						// Sol: 11B8:0AF3-0B75. Preserve the old slot-2 ammo in
						// Sol: slot 3 before converting slots 1 and 2 to energy weapons.
						SelectedMech->Critical_R_Torso[2] = Mech_Med_Laser;
						SelectedMech->Critical_R_Arm[0] = Mech_Med_Laser;
						SelectedMech->CurrentAmmo[3] = SelectedMech->CurrentAmmo[2];
						SelectedMech->MaxAmmo[3] = SelectedMech->MaxAmmo[2];
						SelectedMech->MaxAmmo[2] = Ammo_Laser_Infinite;
						SelectedMech->MaxAmmo[1] = Ammo_Laser_Infinite;
						SelectedMech->CurrentAmmo[2] = Ammo_Laser_Infinite;
						SelectedMech->CurrentAmmo[1] = Ammo_Laser_Infinite;
						for (unsigned short ArmourLocation = 0x0000;
							 ArmourLocation < 0x000B; ArmourLocation++)
						{				
							unsigned char ImprovedArmour =
								seg3EDB->CommandoStageOneArmour[ArmourLocation];
							SelectedMech->MaxArmour[ArmourLocation] = ImprovedArmour;
							SelectedMech->CurrentArmour[ArmourLocation] = ImprovedArmour;
						}
						SelectedMech->UpgradeLevelFlags = 0x01;
						break;

					case MECH_LOCUST_LEVEL2:
						// Sol: 11B8:0B76-0BBE. +75h is the verified engine-hit
						// Sol: counter, not a model-of-engine field as the old C claimed.
						SelectedMech->WalkMove = 0x07;
						SelectedMech->EngineHits = 0x00;
						SelectedMech->Critical_R_Torso[1] = Mech_Small_Laser;
						SelectedMech->Critical_L_Torso[1] = Mech_Small_Laser;
						SelectedMech->MaxAmmo[4] = Ammo_Laser_Infinite;
						SelectedMech->MaxAmmo[3] = Ammo_Laser_Infinite;
						SelectedMech->CurrentAmmo[4] = Ammo_Laser_Infinite;
						SelectedMech->CurrentAmmo[3] = Ammo_Laser_Infinite;
						SelectedMech->UpgradeLevelFlags |= 0x02;
						break;

					case MECH_WASP_LEVEL2:
						// Sol: 11B8:0BBF-0C31. Remove jump movement and install
						// Sol: three medium-laser entries with ammo-state slots 2..4.
						SelectedMech->JumpMove = JumpJets_Removed;
						SelectedMech->Critical_C_Torso[0] = Mech_Med_Laser;
						SelectedMech->Critical_L_Arm[0] = Mech_Med_Laser;
						SelectedMech->Critical_Head = Mech_Med_Laser;
						for (unsigned short LaserSlot = 0x0002;
							 LaserSlot <= 0x0004; LaserSlot++)
						{						
							SelectedMech->MaxAmmo[LaserSlot] = Ammo_Laser_Infinite;
							SelectedMech->CurrentAmmo[LaserSlot] = Ammo_Laser_Infinite;
						}
						SelectedMech->UpgradeLevelFlags |= 0x02;
						break;

					case MECH_STINGER_LEVEL2:
						// Sol: 11B8:0C32-0CB9. Both destination armour arrays
						// Sol: receive the Locust template's CURRENT armour bytes.
						SelectedMech->JumpMove = JumpJets_Removed;
						for (unsigned short ArmourLocation = 0x0000;
							 ArmourLocation < 0x000B; ArmourLocation++)
						{						
							unsigned char LocustArmour =
								seg2FE8->MechRefs[MECH_REF_Locust].CurrentArmour[ArmourLocation];
							SelectedMech->MaxArmour[ArmourLocation] = LocustArmour;
							SelectedMech->CurrentArmour[ArmourLocation] = LocustArmour;
						}
						SelectedMech->Critical_C_Torso[1] = Mech_Med_Laser;
						SelectedMech->Critical_C_Torso[0] = Mech_Med_Laser;
						SelectedMech->MaxAmmo[6] = Ammo_Laser_Infinite;
						SelectedMech->MaxAmmo[5] = Ammo_Laser_Infinite;
						SelectedMech->CurrentAmmo[6] = Ammo_Laser_Infinite;
						SelectedMech->CurrentAmmo[5] = Ammo_Laser_Infinite;
						SelectedMech->UpgradeLevelFlags |= 0x02;
						break;

					case MECH_COMMANDO_LEVEL2:
						// Sol: 11B8:0CBA-0D30 writes 10h to every critical byte
						// Sol: at offsets 4Fh..54h, then writes a MEDIUM laser to +55h.
						// Sol:1AE8/1631 collect each weapon-valued critical byte separately:
						// Sol: these six10h bytes expose six small-laser firing entries, not two.
						// TODO Sol: A-005 still needs the anatomical critical-group labels confirmed.
						SelectedMech->Critical_L_Leg[0] = Mech_Small_Laser;
						SelectedMech->Critical_L_Leg[1] = Mech_Small_Laser;
						SelectedMech->Critical_R_Leg[0] = Mech_Small_Laser;
						SelectedMech->Critical_R_Leg[1] = Mech_Small_Laser;
						SelectedMech->Critical_C_Torso[0] = Mech_Small_Laser;
						SelectedMech->Critical_C_Torso[1] = Mech_Small_Laser;
						SelectedMech->Critical_Head = Mech_Med_Laser;
						for (unsigned short WeaponSlot = 0x0000;
							 WeaponSlot < 0x000A; WeaponSlot++)
						{
							SelectedMech->MaxAmmo[WeaponSlot] = Ammo_Laser_Infinite;
							SelectedMech->CurrentAmmo[WeaponSlot] = Ammo_Laser_Infinite;
						}
						SelectedMech->UpgradeLevelFlags |= 0x02;
						break;
					}
			}
			Display_Text_From_Memory("\r\rYour 'Mech is done.  It's waiting for you outside."); //3EDB:1DEE
		}
		Keyboard_Get_ASCII_Hex_Input();
	}
}

// 11B8:0D58: void Recruit_Crescent_Hawk_Agent(unsigned short SpecialtySkillIndex)
// Called from:
//      Execute_Bld_Bytecode_01C0
// Sol: Summary: Recruit an agent with the requested specialty.
// Sol: Outline: Check recruitment and party conditions, initialise the character, and update story flags and dialogue.
void Recruit_Crescent_Hawk_Agent(unsigned short SpecialtySkillIndex)
{
	// TODO Sol: Fresh ASM audit: retain FAR3092 record/skill views and native
	// TODO Sol: signed assignment/name indices. PRNG seed uses signed LOW WORD
	// TODO Sol: of Name*0187h, not the full product. See systematic audit report.
	// Sol: E9 operands in the shipped scripts are 4=Piloting (JAIL),
	// Sol: 5=Tech (REPAIR), and 6=Medical (HOSPITAL).
	for (unsigned short PartyMemberId = 0x0000;
		 PartyMemberId < 0x0008; PartyMemberId++)
	{
		if (seg3092->Infantry[PartyMemberId].Name == Character_Dead)
		{
			Infantry* NewRecruit = &seg3092->Infantry[PartyMemberId];
			unsigned char RecruitNameId = seg3092->NextRecruitNameId;
			// TODO Sol: Native IMUL yields DX:AX, but CWD then REPLACES DX with the
			// TODO Sol: sign of wrapped AX. This full-product expression differs if
			// TODO Sol: the product does not fit signed16; ordinary Name IDs agree.
			signed long RecruitRandomState =
				(signed long)(signed char)RecruitNameId * 0x0187L;
			seg3EDB->RandomSeed = (unsigned short)RecruitRandomState;
			seg3EDB->RandomState =
				(unsigned short)((unsigned long)RecruitRandomState >> 16);

			NewRecruit->Name = RecruitNameId;
			seg3092->NextRecruitNameId++;
			if ((signed char)seg3092->NextRecruitNameId >= 0x0A)
				seg3092->NextRecruitNameId = 0x02;

			NewRecruit->TrainingFlags = 0x00;
			NewRecruit->ArmourValue = 0x00;
			NewRecruit->ArmourType = 0x00;
			NewRecruit->Weapon = 0x00;
			NewRecruit->Body = Roll2D6();
			NewRecruit->Dexterity = Roll2D6();
			NewRecruit->Charisma = Roll2D6();
			NewRecruit->Health = NewRecruit->Body * 0x0A;
			seg3092->CombatantSpriteFamilyOffset[
				Friendly_Infantry_Combatant_Range_First + PartyMemberId] = 0x00;
			NewRecruit->Piloting = Character_OnFoot;

			unsigned char* RecruitSkills = &NewRecruit->Skill_BowsAndBlade;
			for (unsigned short SkillIndex = 0x0000;
				 SkillIndex <= 0x0006; SkillIndex++)
				RecruitSkills[SkillIndex] = Rand_0x00_to_0xFF() & 0x01;

			// Sol: Piloting is forced to zero before the selected specialty becomes Good.
			NewRecruit->Skill_Piloting = SkillLevel_Unskilled;
			RecruitSkills[SpecialtySkillIndex] = SkillLeveL_Good;
			if (SpecialtySkillIndex == 0x0004)
				NewRecruit->Health -= NewRecruit->Body << 0x01;

			// Sol: A new agent becomes the rider/passenger in the first occupied
			// Sol: party mech whose rider slot is free; PilotId is not changed.
			for (unsigned short MechLanceId = 0x0000;
				 MechLanceId < 0x0004; MechLanceId++)
			{
				Mech* AvailableMech = &seg3092->Mechs[MechLanceId];
				if (AvailableMech->Name[0] != MECH_Destroyed
				 && AvailableMech->RiderId == MECH_NoRider)
				{
					AvailableMech->RiderId = (unsigned char)PartyMemberId;
					NewRecruit->Piloting = (unsigned char)MechLanceId;
					break;
				}
			}

			Display_Text_From_Memory("His name is "); //3EDB:1E2F
			Display_Text_From_Memory(seg3EDB->CharacterNameList[NewRecruit->Name]);
			Display_Text_From_Memory(" and he will be "); //3EDB:1E3C

			if (NewRecruit->Piloting == Character_OnFoot)
			{
				Display_Text_From_Memory("on foot."); //3EDB:1E4D
			}
			else
			{
				Display_Text_From_Memory("riding as a passenger in "); //3EDB:1E56
				unsigned char PilotPartyMemberId =
					seg3092->Mechs[NewRecruit->Piloting].PilotId;
				unsigned char PilotNameId =
					seg3092->Infantry[PilotPartyMemberId].Name;
				Display_Text_From_Memory(seg3EDB->CharacterNameList[PilotNameId]);
				Display_Text_From_Memory("'s 'Mech."); //3EDB:1E70
			}

			Draw_Health_and_C_Bills_Sidebar(TRUE);

			if (seg3092->DisableInput == FALSE)
			{
				while (Pending_Input() == FALSE)
					Rand_0x00_to_0xFF();
			}

			Drain_Pending_Keyboard_Input_2A2B();
			Keyboard_Get_ASCII_Hex_Input();

			// Sol: The first eligible recruited agent has a 50% chance of becoming
			// Sol: the future traitor. D331 stores this party slot, not the Name ID.
			if (seg3092->Traitor_EventOccurred == FALSE
			 && (Rand_0x00_to_0xFF() & 0x01) != FALSE)
			{
				seg3092->Traitor_CharacterId = (unsigned char)PartyMemberId;
				seg3092->Traitor_EventOccurred = TRUE;
				seg3092->Traitor_InParty = TRUE;
				seg3092->Traitor_BattleProbability = 0x1F;
			}
			break;
		}
	}

	// Sol: Restore the original building's saved return position after the
	// Sol: recruitment presentation, or immediately when all eight slots are full.
	unsigned short BuildingId = seg3092->EnteredBuildingId;
	seg246C->CrescentHawk_MapPositionX =
		seg3092->DOSFile_CrescentHawk_MapPositionX[BuildingId];
	seg246C->CrescentHawk_MapPositionY =
		seg3092->DOSFile_CrescentHawk_MapPositionY[BuildingId];
}

// 11B8:104E: void Recruit_Rex_And_Start_KuritaParty_Ambush()
// Called from:
//      Citadel_Building_Dialogs
// Sol: Summary: Recruit Rex and trigger the associated ambush.
// Sol: Outline: Stage the recruit and enemy party, update story state, and enter the scripted combat workflow.
void Recruit_Rex_And_Start_KuritaParty_Ambush()
{
	// TODO Sol: Fresh whole-body ASM audit: record, skill, NPC and combat-table
	// TODO Sol: temporary views must retain FAR3092. Value flow/RNG order checked.
	Alloca(0x0E);

	// Sol: This action is the complete scripted transition: recruit Rex, stage
	// Sol: the party in the Kurita alley, generate 2..5 enemy soldiers, and enter
	// Sol: pre-arranged combat mode (FFFFh).
	seg246C->CrescentHawk_MapPositionX = KuritaPartyAlleyX;
	seg246C->CrescentHawk_MapPositionY = KuritaPartyAlleyY;

	Infantry* RexRecord = &seg3092->Infantry[Character_Rex];
	// Sol: D456 contains the Name ID to assign, not a party count. The native
	// Sol: order is load, increment, then store the old value into Rex's record.
	unsigned char RexNameId = seg3092->NextRecruitNameId;
	seg3092->NextRecruitNameId++;
	RexRecord->Name = RexNameId;
	RexRecord->Body = 0x0C;
	RexRecord->Dexterity = 0x09;
	RexRecord->Charisma = 0x08;
	RexRecord->Weapon = Infantry_Pistol; //3092:C630 = 07h
	RexRecord->Health = 0x78;            //12 Body * 10
	RexRecord->TrainingFlags = 0x00;
	RexRecord->ArmourValue = 0x00;
	RexRecord->ArmourType = ArmourType_None;
	RexRecord->Piloting = Character_OnFoot;
	seg3092->CombatantSpriteFamilyOffset[
		Friendly_Infantry_Combatant_Range_First + Character_Rex] = 0x00;

	// Sol: DS:1E7A supplies the seven exact skills in record order:
	// Sol: Bows/Blade 1, Pistol 3, Rifle 2, Gunnery 4, Piloting 4, Tech 1,
	// Sol: Medical 0. The earlier pseudo-C mistook Weapon, assignment, armour,
	// Sol: Health, and TrainingFlags for skill bytes.
	unsigned char* RexSkills = &RexRecord->Skill_BowsAndBlade;
	for (unsigned short SkillIndex = 0x0000; SkillIndex < 0x0007; SkillIndex++)
		RexSkills[SkillIndex] = seg3EDB->RexStartingSkills[SkillIndex];

	// Sol: D452-D455 retain the first character of each temporarily hidden party
	// Sol: mech name. The first FFh slot receives a complete Commando template.
	// Sol: There is no full-table guard: if all four bytes are occupied, the
	// Sol: original proceeds with slot 4 and writes beyond the friendly tables.
	unsigned short NewCommandoSlot = 0x0000;
	while (NewCommandoSlot < Friendly_Mech_Record_Count
		&& seg3092->StoredPartyMechNameInitial[NewCommandoSlot] != MECH_Destroyed)
	{
		NewCommandoSlot++;
	}

	unsigned char* NewCommandoBytes = (unsigned char*)&seg3092->Mechs[NewCommandoSlot];
	unsigned char far* CommandoTemplateBytes = (unsigned char far*)&seg2FE8->COMMANDO;
	for (unsigned short RecordByte = 0x0000; RecordByte < MECH_RecordSize; RecordByte++)
		NewCommandoBytes[RecordByte] = CommandoTemplateBytes[RecordByte];

	seg3092->StoredPartyMechNameInitial[NewCommandoSlot] = KEY_C;
	seg3092->Mechs[NewCommandoSlot].Name[0] = MECH_Destroyed;
	seg3092->Mechs[NewCommandoSlot].PilotId = Character_Rex;
	seg3092->CombatantSpriteFamilyOffset[NewCommandoSlot] = MECH_Sprite_COMMANDO;

	unsigned short* CombatantWorldX =
		(unsigned short*)&seg3092->CharacterPosX_Mech; //3092:4004
	unsigned short* CombatantWorldY =
		(unsigned short*)&seg3092->CharacterPosY_Mech; //3092:4036
	unsigned short* CombatantOnMap =
		(unsigned short*)&seg3092->Character_OnMap; //3092:406A
	unsigned short* CombatantWreckState =
		(unsigned short*)&seg3092->CombatantCasualtyFlags; //3092:393C

	// Sol: Preserve roaming NPC positions from combatant IDs 16..23 before
	// Sol: those shared enemy-infantry slots are reused for the ambush.
	for (unsigned short NpcSlot = 0x0000; NpcSlot < Enemy_Infantry_Record_Count; NpcSlot++)
	{
		RoamingMapNpcRecordView* Npc = (RoamingMapNpcRecordView*)(
			(unsigned char*)&seg3092->EnemyInfantryPosX + NpcSlot * 0x1A);
		unsigned short CombatantId = Enemy_Infantry_CombatantId_Range_First + NpcSlot;
		Npc->CurrentPositionX = CombatantWorldX[CombatantId];
		Npc->CurrentPositionY = CombatantWorldY[CombatantId];
	}

	for (unsigned short EnemyMechSlot = 0x0000;
		 EnemyMechSlot < Enemy_Mech_Record_Count;
		 EnemyMechSlot++)
	{
		seg3092->Mechs[Enemy_Mech_Record_First + EnemyMechSlot].Name[0] = MECH_Destroyed;
	}

	for (unsigned short EnemyRecord = Enemy_Infantry_Record_First;
		 EnemyRecord < Enemy_Infantry_Record_First + Enemy_Infantry_Record_Count;
		 EnemyRecord++)
	{
		seg3092->Infantry[EnemyRecord].Name = Character_Dead;
	}

	for (unsigned short CombatantId = 0x0000;
		 CombatantId < All_CombatantId_Range_Last;
		 CombatantId++)
	{
		CombatantWreckState[CombatantId] = FALSE;
		CombatantOnMap[CombatantId] = FALSE;
		CombatantWorldY[CombatantId] = CombatantPosition_Unused;
		CombatantWorldX[CombatantId] = CombatantPosition_Unused;
	}

	// Sol: Jason and Rex enter this encounter on foot. These are common
	// Sol: combatant IDs 4 and 5, not indexes 0 and 1 of a separate WORD table.
	CombatantOnMap[Friendly_Infantry_Combatant_Range_First + Character_Rex] = TRUE;
	CombatantOnMap[Friendly_Infantry_Combatant_Range_First + Character_Jason] = TRUE;
	seg3092->CombatantActionState[
		Friendly_Infantry_Combatant_Range_First + Character_Rex] = 0x00;
	seg3092->CombatantActionState[
		Friendly_Infantry_Combatant_Range_First + Character_Jason] = 0x00;

	unsigned short AmbushOriginX = (Rand_0x00_to_0xFF() & 0x01) + 0x0A72;
	unsigned short AmbushOriginY = (Rand_0x00_to_0xFF() & 0x01) + 0x805D;
	// Sol: This is an exclusive compact-record end in the range 10..13.
	// Sol: Starting at record 8 therefore creates 2..5 soldiers, not 10..17.
	unsigned short EnemyRecordEndExclusive = (Rand_0x00_to_0xFF() & 0x03) + 0x0A;

	for (unsigned short EnemyRecord = Enemy_Infantry_Record_First;
		 EnemyRecord < EnemyRecordEndExclusive;
		 EnemyRecord++)
	{
		Infantry* Enemy = &seg3092->Infantry[EnemyRecord];
		unsigned short EnemyCombatantId =
			EnemyRecord + Enemy_Infantry_RecordToCombatantId_Offset;

		Enemy->Name = 0x00;
		Enemy->Piloting = Character_OnFoot;
		seg3092->CombatantSpriteFamilyOffset[EnemyCombatantId] =
			CharacterSpriteFamily_EnemyInfantry;
		seg3092->CombatantSpriteFrame[EnemyCombatantId] = 0x1C;
		seg3EDB->CombatantAnimationCursor[EnemyCombatantId] =
			&seg2FE8->InfantryWalkAnimationStreams[0x30]; //2FE8:02E0
		seg3092->SpawnedCombatant[EnemyRecord] = 0x06;
		seg3092->CombatantAnimationSelector[EnemyCombatantId] = 0x06;
		CombatantOnMap[EnemyCombatantId] = TRUE;
		CombatantWorldX[EnemyCombatantId] = AmbushOriginX
			+ seg3EDB->KuritaPartyEnemyDeltaX[EnemyRecord];
		CombatantWorldY[EnemyCombatantId] = AmbushOriginY
			+ seg3EDB->KuritaPartyEnemyDeltaY[EnemyRecord];

		// Sol: Only the first six skills are randomized; Medical and the other
		// Sol: untouched record bytes retain their prior contents.
		unsigned char* EnemySkills = &Enemy->Skill_BowsAndBlade;
		for (unsigned short SkillIndex = 0x0000; SkillIndex < 0x0006; SkillIndex++)
			EnemySkills[SkillIndex] = Rand_0x00_to_0xFF() & 0x01;

		Enemy->Body = Roll2D6();
		Enemy->Health = Enemy->Body * 0x0A;
		Enemy->Weapon = Rand_0x00_to_0xFF() % 0x08; //Cudgel through Pistol
	}

	Combat_Parent_000A(0xFFFF);
}

// 11B8:137F: void Arena_Select_And_Apply_Combat_Map_Patch_137F()
// Called from:
//      Citadel_Building_Dialogs (ARENA.BLD action 23h)
// Sol: Summary: Prepare the arena's combat terrain patch.
// Sol: Outline: Roll one of four variants, remember the selector, and write the selected terrain pattern without a backup.
void Arena_Select_And_Apply_Combat_Map_Patch_137F()
{
	// TODO Sol: Fresh ASM audit: selector is FAR246C:0010, NOT3092:0010.
	// TODO Sol: DS:54EA contains 246Ch. Tile loops match; correct binding later.
	// Sol: AX is masked after the 16-bit RNG call, and the complete WORD is
	// Sol: stored at 246C:0010. Selector zero deliberately applies no patch.
	unsigned short ArenaPatchVariant = Rand_0x00_to_0xFF() & 0x0003;
	seg3092->ArenaCombatMapPatchVariant = ArenaPatchVariant;

	// Sol: These are indexes into MapTile, whose base is 246C:101D. The old
	// Sol: Reko translation compared absolute addresses with bogus E3xx/E5xx
	// Sol: bounds, turning each small counted loop into a huge overwrite.
	if (ArenaPatchVariant == 0x0001)
	{
		seg246C->MapTile[0x0C72] = 0x6F; // 246C:1C8F
		for (unsigned short TileOffset = 0; TileOffset < 5; TileOffset++)
			seg246C->MapTile[0x0C73 + TileOffset] = 0x6A; // 1C90-1C94
		seg246C->MapTile[0x0CB0] = 0x70; // 246C:1CCD
	}
	else if (ArenaPatchVariant == 0x0002)
	{
		seg246C->MapTile[0x0A5B] = 0x6F; // 246C:1A78
		for (unsigned short TileOffset = 0; TileOffset < 4; TileOffset++)
			seg246C->MapTile[0x0A5C + TileOffset] = 0x6A; // 1A79-1A7C
		for (unsigned short TileOffset = 0; TileOffset < 6; TileOffset++)
			seg246C->MapTile[0x0A98 + TileOffset] = 0x6A; // 1AB5-1ABA
		seg246C->MapTile[0x0A9E] = 0x70; // 246C:1ABB
	}
	else if (ArenaPatchVariant == 0x0003)
	{
		seg246C->MapTile[0x0ABC] = 0x71; // 246C:1AD9
		// Sol: Assembly starts its local counter at 4 and adds 8 through 34h:
		// Sol: seven sparse cells at 1CA1, 1CA9, ... 1CD1.
		for (unsigned short TileIndex = 0x0C84; TileIndex < 0x0CBC; TileIndex += 8)
			seg246C->MapTile[TileIndex] = 0x6B;
		seg246C->MapTile[0x0CBC] = 0x70; // 246C:1CD9
	}
}

// 11B8:1441: void Arena_Remove_And_Randomize_Combat_Map_Patch_1441()
// Called from:
//      Citadel_Building_Dialogs (post-combat path of ARENA.BLD action 23h)
// Sol: Summary: Remove the arena terrain patch.
// Sol: Outline: Read the remembered variant, replace its endpoints, and randomise its interior tiles; no cache refresh occurs here.
void Arena_Remove_And_Randomize_Combat_Map_Patch_1441()
{
	// TODO Sol: Fresh ASM audit: read selector from FAR246C:0010, NOT3092:0010.
	// TODO Sol: DS:54EA contains 246Ch. Tile loops/RNG count match; fix later.
	// Sol: 246C:0010 is a WORD. Selector zero means setup changed no tiles,
	// Sol: so teardown also returns without touching the map or consuming RNG.
	unsigned short ArenaPatchVariant = seg3092->ArenaCombatMapPatchVariant;
	if (ArenaPatchVariant == 0x0001)
	{
		seg246C->MapTile[0x0C72] = 0x43; // 246C:1C8F
		for (unsigned short TileOffset = 0; TileOffset < 5; TileOffset++)
			seg246C->MapTile[0x0C73 + TileOffset] =
				(Rand_0x00_to_0xFF() & 0x03) + 0x40; // 1C90-1C94
		seg246C->MapTile[0x0CB0] = 0x42; // 246C:1CCD
	}
	else if (ArenaPatchVariant == 0x0002)
	{
		seg246C->MapTile[0x0A5B] = 0x41; // 246C:1A78
		for (unsigned short TileOffset = 0; TileOffset < 4; TileOffset++)
			seg246C->MapTile[0x0A5C + TileOffset] =
				(Rand_0x00_to_0xFF() & 0x03) + 0x40; // 1A79-1A7C
		for (unsigned short TileOffset = 0; TileOffset < 6; TileOffset++)
			seg246C->MapTile[0x0A98 + TileOffset] =
				(Rand_0x00_to_0xFF() & 0x03) + 0x40; // 1AB5-1ABA
		seg246C->MapTile[0x0A9E] = 0x42; // 246C:1ABB
	}
	else if (ArenaPatchVariant == 0x0003)
	{
		seg246C->MapTile[0x0ABC] = 0x40; // 246C:1AD9
		for (unsigned short TileIndex = 0x0C84; TileIndex < 0x0CBC; TileIndex += 8)
			seg246C->MapTile[TileIndex] =
				(Rand_0x00_to_0xFF() & 0x03) + 0x40; // 1CA1-1CD1
		seg246C->MapTile[0x0CBC] = 0x41; // 246C:1CD9
	}
}

// 11B8:152F: void Run_Jailbreak_Mission_And_Award_Stinger_152F()
// Called from:
//      Citadel_Building_Dialogs (JAIL.BLD action 28h)
// Sol: Summary: Run the prison escape and award its resulting mech.
// Sol: Outline: Stage the escape, run the jailbreak mission, and install the successful Stinger and party state.
void Run_Jailbreak_Mission_And_Award_Stinger_152F()
{
	// TODO Sol: Fresh whole-body ASM audit: NewPartyMech is FAR3092 and the
	// TODO Sol: reference Stinger is FAR2FE8; both current casts lose segments.
	// Sol: Preserve only the byte-sized Name ID for party slots 1..7, then mark
	// Sol: those records absent. Jason in slot zero remains active for Mission 9.
	for (unsigned short PartyMemberSlot = 0x0001; PartyMemberSlot < 0x0008;
		PartyMemberSlot++)
	{
		seg3092->SavedPartyNameId[PartyMemberSlot] =
			seg3092->Infantry[PartyMemberSlot].Name;
		seg3092->Infantry[PartyMemberSlot].Name = Character_Dead;
	}

	// Sol: Friendly mech records are likewise hidden using only Name[0]. The
	// Sol: complete 7Dh-byte records remain in place throughout the mission.
	for (unsigned short MechSlot = 0x0000; MechSlot < 0x0004; MechSlot++)
	{
		seg3092->StoredPartyMechNameInitial[MechSlot] =
			seg3092->Mechs[MechSlot].Name[0];
		seg3092->Mechs[MechSlot].Name[0] = MECH_Destroyed;
	}

	seg246C->CrescentHawk_MapPositionX = Jail_EntranceX;
	seg246C->CrescentHawk_MapPositionY = Jail_EntranceY;
	seg3092->Infantry[Jason].Piloting = Character_OnFoot;
	Mech_Mission_0629(Mission09_JailBreak);

	seg246C->CrescentHawk_MapPositionX = Jail_EscapeX;
	seg246C->CrescentHawk_MapPositionY = Jail_EscapeY;

	for (unsigned short PartyMemberSlot = 0x0001; PartyMemberSlot < 0x0008;
		PartyMemberSlot++)
	{
		seg3092->Infantry[PartyMemberSlot].Name =
			seg3092->SavedPartyNameId[PartyMemberSlot];
	}

	for (unsigned short MechSlot = 0x0000; MechSlot < 0x0004; MechSlot++)
	{
		seg3092->Mechs[MechSlot].Name[0] =
			seg3092->StoredPartyMechNameInitial[MechSlot];
		seg3092->StoredPartyMechNameInitial[MechSlot] = MECH_Destroyed;
	}

	// Sol: A surviving Jason leaves in the stolen Stinger described immediately
	// Sol: after JAIL.BLD action 28h. Install one exact reference record in the
	// Sol: first empty friendly slot; a full four-mech roster receives nothing.
	if (seg3EDB->Bool_MainCharactersAlive != FALSE)
	{
		for (unsigned short MechSlot = 0x0000; MechSlot < 0x0004; MechSlot++)
		{
			if (seg3092->Mechs[MechSlot].Name[0] == MECH_Destroyed)
			{
				unsigned char* NewPartyMech = (unsigned char*)&seg3092->Mechs[MechSlot];
				unsigned char* ReferenceStinger = (unsigned char*)&seg2FE8->STINGER;
				for (unsigned short RecordOffset = 0x0000;
					RecordOffset < MECH_RecordSize; RecordOffset++)
					NewPartyMech[RecordOffset] = ReferenceStinger[RecordOffset];
				break;
			}
		}
	}
}

// 11B8:16B2: void Play_Failed_Mech_Startup_Scene_16B2()
// Called from:
//      Mech_Mission_0629
// Sol: Summary: Show a failed attempt to start a jailbreak mech.
// Sol: Outline: Load O0, clear frame workspace, draw the startup prefix, play its failure sound, then restore layout and sidebar.
void Play_Failed_Mech_Startup_Scene_16B2()
{
	// TODO Sol: Fresh ASM audit: 172D uses signed BYTE JL49h; this unsigned
	// TODO Sol: control-byte comparison differs for80h..FFh. Normal O0 agrees.
	// Sol: O0 is on logical game disk 1. This specialized path bypasses the
	// Sol: general animation-scene controller and therefore selects it itself.
	Select_Game_Disk_And_Drive_28CC(1);
	DOS_Load_File_to_memory("O0.ANM", &seg246C->AnimationFile_MemoryBlock, 0x3E80);

	// Sol: Clear the complete shared scratch range 246C:244B-42C2. The old
	// Sol: 1E7Dh bound was a transcription error; assembly compares with 1E78h.
	unsigned char far* FrameWorkspace = SEQ(0x246C, 0x244B);
	for (unsigned short ByteIndex = 0x0000; ByteIndex < 0x1E78; ByteIndex++)
		FrameWorkspace[ByteIndex] = 0x00;

	seg3092->FrameNumber = 0x0000;

	// Sol: The loaded ANM begins at 246C:42C3 and its compressed frame stream
	// Sol: starts after the 33h-byte control/timing header at 246C:42F6.
	seg3092->AnimationStreamOffset = 0x42F6;
	seg3092->AnimationStreamSegment = 0x246C;

	// Sol: Decode_Draw_Next_ANM_Frame increments FrameNumber. The test examines
	// Sol: the NEXT playback-control byte, not a frame count. Shipped O0 has
	// Sol: controls 41h..52h, so this failure prefix draws frames 0..7 and stops
	// Sol: before control 49h/frame 8.
	do
		Decode_Draw_Next_ANM_Frame();
	while (seg246C->AnimationFile_MemoryBlock[seg3092->FrameNumber] < 0x49);

	Play_Sound_If_Enabled(Sound_MechStartUpFailed);
	Wait_For_N_Vertical_Retraces(Refresh_60hz);
	Menu_Memory_Variables(0x04);
	Draw_Top_Graphic_Sidebar();
}

// 11B8:1762: void Mechlube_Buy_Ammo(void)
// Called from:
//      Citadel_Building_Dialogs
// Sol: Summary: Purchase ammunition for a mech.
// Sol: Outline: Find eligible ammo components, calculate quantities and cost, then update the paid-for ammo state.
void Mechlube_Buy_Ammo(void)
{
	// Sol: Preservation correction: FAR3092 records, signed deficit/request cap,
	// Sol: signed missile-price BYTE and native prompt/control bytes retained.
	// Sol: No autocannon shop support or corrupted-state validation is added.
	Draw_Top_Graphic_Sidebar();
	Display_Text_From_Memory((uint8_t far *)"Buy ammo for:\r"); // Memory ref: [3EDB:1E99]; Sol: exact ammo EXE text
	Display_Text_Mech_Names();

	Mech far *selectedMech = &seg3092->Mechs[seg3092->Mech_Selected];
	uint8_t far *selectedMechBytes = (uint8_t far *)selectedMech;
	uint8_t weaponComponents[Mech_WeaponOrdinal_Count] = { 0 };
	uint16_t criticalSlotOffset = MECH_ComponentBlock_Start;
	uint16_t weaponSlotCount = 0;

	// Sol: Build the same ten-entry list used by CurrentAmmo and MaxAmmo. The
	// Sol: executable scans raw mech bytes 33h..55h in order and appends every
	// Sol: critical byte whose masked component ID is 10h..20h. The destroyed
	// Sol: high bit is deliberately retained for the later damaged-weapon test.
	while (criticalSlotOffset <= MECH_ComponentBlock_End &&
		weaponSlotCount < Mech_WeaponOrdinal_Count)
	{
		uint8_t criticalComponent = selectedMechBytes[criticalSlotOffset++];
		uint8_t componentId = criticalComponent & MechComponentIdMask;
		if (componentId >= Mech_Small_Laser && componentId <= Mech_SRMissile6)
			weaponComponents[weaponSlotCount++] = criticalComponent;
	}

	uint16_t hasDamagedWeapon = FALSE;
	uint16_t hasFunctionalAmmoWeapon = FALSE;

	for (uint16_t weaponSlot = 0; weaponSlot < Mech_WeaponOrdinal_Count; weaponSlot++)
	{
		uint8_t criticalComponent = weaponComponents[weaponSlot];
		uint8_t componentId = criticalComponent & MechComponentIdMask;

		if ((criticalComponent & Component_Destroyed) != 0)
			hasDamagedWeapon = TRUE;

		// Sol: The signed comparisons in the original exclude high-bit/destroyed
		// Sol: entries. Only the machine gun and the seven missile components are
		// Sol: offered here; autocannons 14h..17h are not handled by this shop path.
		if ((criticalComponent & Component_Destroyed) == 0 &&
			(componentId == Mech_MachineGun ||
			(componentId >= Mech_LRMissile5 && componentId <= Mech_SRMissile6)))
		{
			hasFunctionalAmmoWeapon = TRUE;
		}
	}

	// Sol: No functional shop-supported ammunition weapon; this is not a full-ammo test.
	if (hasFunctionalAmmoWeapon == FALSE)
	{
		Display_Text_From_Memory_ScreenRetrace_KeyboardInput((uint8_t far *)"You don't have any functional weapons that require ammunition."); // Memory ref: [3EDB:1FC9]; Sol: exact ammo EXE text
		if (hasDamagedWeapon == FALSE)
			Keyboard_Get_ASCII_Hex_Input();
	}
	else
	{
		for (uint16_t weaponSlot = 0; weaponSlot < Mech_WeaponOrdinal_Count; weaponSlot++)
		{
			uint8_t criticalComponent = weaponComponents[weaponSlot];
			uint8_t componentId = criticalComponent & MechComponentIdMask;
			if ((criticalComponent & Component_Destroyed) == 0 &&
				(componentId == Mech_MachineGun ||
				(componentId >= Mech_LRMissile5 && componentId <= Mech_SRMissile6)))
			{
				Draw_Top_Graphic_Sidebar();
				Display_Text_From_Memory((uint8_t far *)"Your "); // Memory ref: [3EDB:1EA8]; Sol: exact ammo EXE text
				// Sol: Critical component IDs are one greater than their zero-based
				// Sol: 11h-byte WeaponStats record indexes.
				Display_Text_From_Memory(seg3EDB->WeaponStats[componentId - MechComponentToWeaponRecordBias].Name);

				if (selectedMech->CurrentAmmo[weaponSlot] != selectedMech->MaxAmmo[weaponSlot])
				{
					Display_Text_From_Memory((uint8_t far *)" could use some ammunition.  You've expended "); // Memory ref: [3EDB:1ED1]; Sol: exact ammo EXE text

					int16_t missingRounds = (int16_t)(
						selectedMech->MaxAmmo[weaponSlot] - selectedMech->CurrentAmmo[weaponSlot]);

					Set_Text_Colour_Bright_Green_28A2();
					Display_Text_Dynamic_Value((uint16_t)missingRounds);
					Display_Text_From_Memory((uint8_t far *)"\006\017 rounds.\r\rReloads cost "); // Memory ref: [3EDB:1EFF]; Sol: exact ammo EXE text
					Set_Text_Colour_Bright_Green_28A2();

					int16_t ammoPrice = MechAmmoMachineGunRoundCostCBills; // Machine-gun round price.
					if (componentId != Mech_MachineGun)
						ammoPrice = (int8_t)seg3EDB->MissileAmmoPriceByComponent[
							componentId - Mech_LRMissile5];

					Display_Text_Dynamic_Value((uint16_t)ammoPrice);
					Display_Text_From_Memory((uint8_t far *)"\006\017 C-bills each.  How many do you want to buy? "); // Memory ref: [3EDB:1F19]; Sol: exact ammo EXE text
					uint32_t requestedRounds = Prompt_For_Unsigned_Decimal_0CDE();
					if (requestedRounds != 0)
					{
						uint16_t roundsRemainingToLoad;
						// Sol: Native cap interprets the decimal parser's DWORD bit pattern as signed.
						int32_t signedRequestedRounds = requestedRounds <= INT32_MAX
							? (int32_t)requestedRounds
							: -1 - (int32_t)(UINT32_MAX - requestedRounds);

						if (signedRequestedRounds > missingRounds)
						{
							Display_Text_From_Memory_ScreenRetrace_KeyboardInput((uint8_t far *)"\rThat's more than you can carry for that weapon.  We'll max out your ammo."); // Memory ref: [3EDB:1F49]; Sol: exact ammo EXE text
							Keyboard_Get_ASCII_Hex_Input();
							roundsRemainingToLoad = (uint16_t)missingRounds;
						}
						else
							roundsRemainingToLoad = (uint16_t)requestedRounds;

						// Sol: The executable buys one round at a time and redraws the
						// Sol: balance after every successful debit.
						while (roundsRemainingToLoad != 0)
						{
							// Sol: CBW/CWD sign-extends price, then affordability compares unsigned DWORDs.
							uint32_t roundCostCBills = (uint32_t)(int32_t)ammoPrice;
							if (roundCostCBills > seg3092->CBills)
								break;

							selectedMech->CurrentAmmo[weaponSlot]++;
							seg3092->CBills -= roundCostCBills;

							roundsRemainingToLoad--; // Sol: native194A purchase block decrements BEFORE the display call

							Display_Text_CBill_Balance();
						}

						if (roundsRemainingToLoad != 0)
						{
							Display_Text_From_Memory_ScreenRetrace_KeyboardInput((uint8_t far *)"\r\rYou ran out of money before the ammo bay was full."); // Memory ref: [3EDB:1F94]; Sol: exact ammo EXE text
							Keyboard_Get_ASCII_Hex_Input();
						}

						Display_Text_CBill_Balance();
					}
				}
				else
				{
					Display_Text_From_Memory_ScreenRetrace_KeyboardInput((uint8_t far *)" has maximum ammunition right now."); // Memory ref: [3EDB:1EAE]; Sol: exact ammo EXE text
					Keyboard_Get_ASCII_Hex_Input();
				}
			}
		}
	}
	if (hasDamagedWeapon != FALSE)
	{
		Display_Text_From_Memory_ScreenRetrace_KeyboardInput((uint8_t far *)"\r\r\rSome of your weaponry is damaged, so selling you ammunition for it would be a waste."); // Memory ref: [3EDB:2008]; Sol: exact ammo EXE text
		Keyboard_Get_ASCII_Hex_Input();
	}
}
