// BTECH_1631.c
// Generated by decompiling BTECH.EXE
// using Reko decompiler version 0.11.2.0.

#include "BTECH.h"

// Sol: Segment-wide assembly audit: docs/phase4/BTECH_1631_SEGMENT_REVIEW.md.
// Sol: Research pseudo-C, not a compilable replacement: DOS memory views
// Sol: overlap and shared renderer/formatter helpers still require reconstruction.
// Sol: Earlier first-pass review is not a whole-method certificate. Fresh
// Sol: results: docs/phase4/BTECH_1631_SYSTEMATIC_ASM_AUDIT.md. Keep native contracts.

// 1631:0006: void Position_0006(Stack int16 CombatantId, Stack int16 TargetX,
//                              Stack int16 TargetY, Stack int16 ScreenX,
//                              Stack int16 ScreenY, Stack int16 AlternateDirectionSearch)
// Called from:
//      Update_Roaming_Map_Npcs_24C2
//      Combat_Calculate_Movement
//      Combat_Assess_FirstEnemy_Reachability_28DB
// Sol: Summary: Try a combat actor's movement step.
// Sol: Outline: Test candidate directions, terrain and footprint restrictions, then occupancy before accepting a position.
void Position_0006(unsigned short CombatantOrProbeId, unsigned short TargetX,
	unsigned short TargetY, unsigned short ScreenX, unsigned short ScreenY,
	unsigned short AlternateDirectionSearch)
{
	// TODO Sol: Fresh audit: native0237 SUB CX,13 wraps WORD BEFORE SAR1.
	// TODO Sol: Current (CandidateScreenX - 13) shifts a promoted value instead;
	// TODO Sol: narrow that subtraction to signed WORD before shift in fixing pass.
	// Sol:0006..02E3 reconstructed against ASM; six WORD arguments.
	// Sol: outputs working packed position/facing and signed WORD step, NOT actor position tables.
	if (AlternateDirectionSearch != 0)
	{
		--seg3EDB->MovementSearchBankTimer;
		if (seg3EDB->MovementSearchBankTimer == 0)
		{
			seg3EDB->MovementSearchBankTimer = 30; // Sol:001F shared bank-toggle period, not actor budget.
			seg3EDB->MovementSearchBankBytes[0] ^= 8; // Sol: BYTE toggle selects other8-entry direction bank.
		}
	}
	else
		seg3EDB->MovementSearchBank = 0; // Sol:002C clears WORD, not only low BYTE.
	unsigned short FacingSlot = CombatantOrProbeId & 0x7F; // Sol:0032 mask probe bit for facing table.
	short CandidateFacing = (signed char)seg3092->CombatantFacing[FacingSlot]; // SS:BP-10 WORD from CBW BYTE.
	seg3092->CombatChosenStepX = 0;
	seg3092->CombatChosenStepY = 0; // Sol: no legal candidate leaves zero step and unchanged working position/facing.
	unsigned short NeedsMechFootprint = ((unsigned char)CombatantOrProbeId & 0x7F) < Friendly_Infantry_Combatant_Range_First
		|| ((short)CombatantOrProbeId >= Enemy_All_CombatantId_Range_First && (short)CombatantOrProbeId < Enemy_Infantry_CombatantId_Range_First); // Sol:0058 masked BYTE first clause, unmasked signed WORD enemy clause; probe80 has mech footprint.

	unsigned short DesiredFacing = Get_Target_Compass_Direction(seg3092->CrescentHawk_CompassPositionX,
		seg3092->CrescentHawk_CompassPositionY, TargetX, TargetY);
	if (DesiredFacing == 0xFFFF) return; // Sol:0093 heading sentinel = already at destination; step outputs already zero.
	short HeadingDifference = (short)(DesiredFacing - CandidateFacing);
	if (HeadingDifference != 0)
	{
		HeadingDifference &= 7; // Sol: eight octants; modulo difference1..4 turns +1,5..7 turns -1.
		CandidateFacing += HeadingDifference < 5 ? 1 : -1;
		CandidateFacing &= 7;
	}
	for (short Attempt = 7; Attempt >= 0; --Attempt) // Sol:01D6 .dis confirms CMP counter,FFFF = -1, not255.
	{
		short Adjustment = (signed char)seg3EDB->MovementDirectionSearchOffsets[seg3EDB->MovementSearchBank + Attempt];
		CandidateFacing = (CandidateFacing + Adjustment) & 7; // Sol:01DF LOAD signed BYTE; cumulative adjustment before each candidate.
		short StepX = seg3EDB->MovementDirectionStepX[CandidateFacing];
		short StepY = seg3EDB->MovementDirectionStepY[CandidateFacing];
		unsigned short CandidateX = seg3092->CrescentHawk_CompassPositionX + StepX; // BP-2 WORD wrapping add.
		unsigned short CandidateY = seg3092->CrescentHawk_CompassPositionY + StepY; // BP-6.
		if ((CandidateX & 0x80) != 0) CandidateX += seg3EDB->MovementPackedBoundaryX[CandidateFacing];
		if ((CandidateY & 0x80) != 0) CandidateY += seg3EDB->MovementPackedBoundaryY[CandidateFacing]; // Sol: low BYTE bit80 triggers coarse packed-region crossing.
		short CandidateScreenX = (short)(ScreenX + StepX); // BP-8 WORD character-cell coordinate.
		short CandidateScreenY = (short)(ScreenY + StepY); // BP-0A.
		short Cell = (short)((CandidateScreenY >> 1) * 24 + ((CandidateScreenX - 13) >> 1)); // Sol:0237 signed SARs;24-column cache, screen panel starts13.
		if ((CandidateScreenX & 1) == 0 && (seg246C->CrescentHawk_MapPositionX & 1) != 0) ++Cell;
		if ((CandidateScreenY & 1) != 0 && (seg246C->CrescentHawk_MapPositionY & 1) != 0) Cell += 24;
		unsigned short CacheIndex = seg246C->CachedMapOriginIndex + Cell;
		unsigned short Tile = seg246C->CombatMap[CacheIndex]; // Sol:028F BYTE load zero-extended; numeric cache index, not pointer arithmetic.
		if ((short)seg3EDB->BlockingTileCodeThreshold <= (short)Tile) continue; // Sol:02A7 signed threshold comparison.
		unsigned short CandidateAllowed = TRUE; // BP-0C.
		if (NeedsMechFootprint != FALSE)
		{
			Cell += ((CandidateScreenX ^ seg246C->CrescentHawk_MapPositionX) & 1) == 0 ? 1 : -1; // Sol:02C5 horizontally adjacent footprint tile chosen by parity.
			CacheIndex = seg246C->CachedMapOriginIndex + Cell;
			Tile = seg246C->CombatMap[CacheIndex];
			if (Tile >= seg3EDB->BlockingTileCodeThreshold) CandidateAllowed = FALSE; // Sol:00CB adjacent comparison uses unsigned JC, unlike first tile.
		}
		if (CandidateAllowed != FALSE && (short)CombatantOrProbeId < 0x80) // Sol:00FB probe80 skips occupancy ONLY, not tile/footprint checks.
		{
			unsigned short SavedMapX = seg246C->CrescentHawk_MapPositionX; // BP-1A.
			unsigned short SavedMapY = seg246C->CrescentHawk_MapPositionY; // BP-1C.
			seg246C->CrescentHawk_MapPositionX = CandidateX;
			seg246C->CrescentHawk_MapPositionY = CandidateY;
			if (Return_bool_fn1631_16AB(CombatantOrProbeId, StepX, StepY, FALSE) != 0) // Sol:013D four WORD occupancy args; planning disables opposing-infantry crushing.
			{
				CandidateAllowed = FALSE;
				if (CandidateX == TargetX && CandidateY == TargetY)
					seg3092->CombatDestinationBlocked = 1; // Sol:0164 occupied requested destination latch; not cleared by this helper.
			}
			seg246C->CrescentHawk_MapPositionX = SavedMapX;
			seg246C->CrescentHawk_MapPositionY = SavedMapY; // Sol:016F restore temporary occupancy anchor even when blocked.
		}
		if (CandidateAllowed != FALSE)
		{
			seg3092->CrescentHawk_CompassPositionX = CandidateX;
			seg3092->CrescentHawk_CompassPositionY = CandidateY;
			seg3092->CombatantFacing[FacingSlot] = (unsigned char)CandidateFacing;
			seg3092->CombatChosenStepX = StepX;
			seg3092->CombatChosenStepY = StepY;
			return; // Sol:018B first allowed direction wins; actual actor moves elsewhere.
		}
	}
	// Sol: no cache bounds guard in ASM; caller/view-cache preconditions remain for managed port.
}

// 1631:02E4: void Display_Text_Human_Health(Stack int16 MechLanceId)
// Called from:
//      Inspect_Characters
//      Combat_Browse_Scan_Targets_1467
//      Display_Friendly_Combatant_Description_18E8
// Sol: Summary: Describe a person's health.
// Sol: Outline: Divide signed health by Body and select the matching condition text.
void Display_Text_Human_Health(unsigned short Scan_TargetId)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: Signed-byte operands are CBW-expanded before IDIV; this is a
	// Sol: health-description band, not a percentage. No zero-Body guard in ASM.
	short HealthBand = (signed char)seg3092->Infantry[Scan_TargetId].Health
		/ (short)(signed char)seg3092->Infantry[Scan_TargetId].Body;
	Display_Text_From_Memory(seg3EDB->a2E0C[HealthBand]); //DS:2E0C far-pointer table
}

// 1631:032F: void Menu_Draw_MultiSelect(Register Eq_21 ds, Stack Eq_21 MechLanceId)
// Called from:
//      Load_Game
//      Save_Game
//      Combat_Browse_Scan_Targets_1467
// Sol: Summary: Refresh the combat planning display.
// Sol: Outline: Redraw the world and status panels and optionally display the combat menu.
void Menu_Draw_MultiSelect(unsigned short Bool_DrawMenu)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY); //A44B - Character Position X //A44D - Character position Y
	Copy_Data_To_GraphicsMemory();

	if (Bool_DrawMenu != FALSE)
		Draw_Menu_MultiSelect_0E4B();
	else
		Draw_Infantry_And_Mechs();

	EGA_DrawBox_Wrapper();
	Menu_Memory_Variables(0x04);

	Draw_Top_Graphic_Sidebar();
	Draw_Menu_Border(0x04);

	Menu_Memory_Variables(0x03);

	Draw_Top_Graphic_Sidebar();
	Draw_Menu_Border(0x03);
}

// 1631:03AB: void Combat_Computer_Control(Stack Eq_21 MechLanceId, Stack int16 Mech_CurrentActuators)
// Called from:
//      Combat_Parent_000A
//      Combat_Computer_Control_1482
//      Combat_UI_Menu_Logic
// Sol: Summary: Plan one computer-controlled actor's combat orders.
// Sol: Outline: Choose a target, evaluate approach paths and weapon ranges, assign movement and attacks, then restore the view anchor.
void Combat_Computer_Control(unsigned short ActorCombatantId, unsigned short ShowPlanningPreview)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: ShowPlanningPreview (formerly Bool_wArg06): request
	// Sol: friendly actor's movement preview after planning; enemy actors ignore it.
	// Sol: Reconstructed03AB..0BB4 in bounded checkpoints; range-policy
	// Sol: intent remains A-004, but instruction/call ordering is recovered.
	// Sol: First argument is the ACTOR combatant ID (formerly TargetId_wArg04).
	unsigned short ActorCombatantId = ActorCombatantId;
	unsigned short Character_PosX = seg246C->CrescentHawk_MapPositionX; // DS:A44B saved anchor
	unsigned short Character_PosY = seg246C->CrescentHawk_MapPositionY; // DS:A44D saved anchor

	// Sol: ASM scales BOTH WORD arrays by two bytes, not Y's C index twice.
	Move_Map_View_To_Packed_Position_17BB(
		seg3092->CombatantPackedX[ActorCombatantId], // DS:4004
		seg3092->CombatantPackedY[ActorCombatantId]); // DS:4036

	// Sol: Clear all 48 BYTE orders before normalizing the enemy actor ID.
	for (unsigned short OrderByte = 0; OrderByte < Combat_MovementOrder_RowSize; ++OrderByte) // 48-byte actor row
		seg3092->CombatMovementOrders[ActorCombatantId * Combat_MovementOrder_RowSize + OrderByte] = 0xFF; // DS:32C6

	// Sol: BP-36 is a WORD record-bank offset, not a BYTE or target ID.
	unsigned short ActorRecordBankOffset = 0;
	if ((short)ActorCombatantId >= Enemy_All_CombatantId_Range_First)
	{
		ActorCombatantId -= Enemy_All_CombatantId_Range_First; // enemy IDs12..23 -> side-local0..11
		ActorRecordBankOffset = Enemy_Mech_Record_First; // add4: enemy mechs4..7 / infantry8..15
	}
	else
		seg3092->CombatantActionState[ActorCombatantId] = 1; // DS:3994 friendly action state

	// Sol: BP-1A: run-mode eligibility starts true, but only a mech at
	// Sol: exactly zero heat retains it. Short-circuit avoids infantry heat lookup.
	// Sol: BP-1A stores the selected movement mode, not a boolean.
	unsigned short SelectedMovementMode = MovementMode_Run;
	if ((short)ActorCombatantId >= Friendly_Infantry_Combatant_Range_First
		|| seg3092->Mech_HeatLevel[ActorCombatantId + ActorRecordBankOffset] != 0) // DS:006E BYTE[mech record]
		SelectedMovementMode = MovementMode_Walk;

	if ((short)ActorCombatantId < Friendly_Infantry_Combatant_Range_First)
		Combat_Mech_Movement(ActorCombatantId + ActorRecordBankOffset, SelectedMovementMode); // 183B:22BC
	else
		Combat_Infantry_Movement(ActorCombatantId + ActorRecordBankOffset); // 183B:2474; infantry record = side-local ID+bank

	// Sol: Reconstructed target scan 1631:047E..05AA. These shared named
	// Sol: locals are WORDs: BP-4 targetY, BP-2 targetX, BP-A nearest distance,
	// Sol: BP-12 target combatant ID. Later movement may adjust target X/Y.
	unsigned short CandidatesRemaining = Enemy_Mech_Record_Count; // BP-22 candidates remaining
	unsigned short CandidateCombatantId = Enemy_All_CombatantId_Range_First; // BP-34 candidate ID, NOT necessarily traitor
	unsigned short PlannedTargetPackedY = CombatantPosition_Unused;
	unsigned short PlannedTargetPackedX = CombatantPosition_Unused;
	short NearestTargetDistance = 0x7FFF; // largest signed WORD distance
	unsigned short SelectedTargetCombatantId = All_CombatantId_Range_Last - 1; // original default23 even if none selected

	if (ActorRecordBankOffset != 0)
		CandidateCombatantId = 0; // enemy actor scans friendly mechs0..3

	if ((short)ActorCombatantId >= Friendly_Infantry_Combatant_Range_First)
	{
		CandidatesRemaining = Enemy_Infantry_Record_Count; // eight opposing infantry
		CandidateCombatantId = Enemy_Infantry_CombatantId_Range_First;
		if (ActorRecordBankOffset != 0)
			CandidateCombatantId = Friendly_Infantry_Combatant_Range_First;
	}

	// Sol:0594 tests OLD count, then decrements even on the terminating test.
	while (CandidatesRemaining-- != 0)
	{
		if (seg3092->CombatantActive[CandidateCombatantId] != 0) // DS:406A WORD, not BYTE
		{
			unsigned short CandidateX = seg3092->CombatantPackedX[CandidateCombatantId]; // DS:4004
			unsigned short CandidateY = seg3092->CombatantPackedY[CandidateCombatantId]; // DS:4036
			unsigned short CandidateAllowed = TRUE; // BP-38 WORD
			if (seg3092->ArenaRentalMechMode != 0 && CandidateCombatantId == 0x0D) // rental opponent combatant13
				CandidateAllowed = FALSE;
			if (ActorRecordBankOffset != 0 && seg3092->Traitor_InParty != 0 // DS:D333 BYTE
				&& (short)(signed char)seg3092->Traitor_CharacterId
					+ Friendly_Infantry_Combatant_Range_First == CandidateCombatantId) // DS:D331; ASM CBW
				CandidateAllowed = FALSE; // enemy AI avoids story-protected party infantry

			// Sol: Signed JGE rejects ties: first equally near candidate remains.
			// Sol: ASM calls0BB5 again for an accepted candidate; retain both calls.
			if (CandidateAllowed != FALSE
				&& (short)Combat_Operation_0BB5(CandidateX, CandidateY) < NearestTargetDistance)
			{
				NearestTargetDistance = (short)Combat_Operation_0BB5(CandidateX, CandidateY);
				PlannedTargetPackedX = CandidateX;
				PlannedTargetPackedY = CandidateY;
				SelectedTargetCombatantId = CandidateCombatantId;
			}
		}
		++CandidateCombatantId;

		// Sol:0579 compares WORD FFFF (.dis), despite ASM export printing FF.
		// Sol: After a failed mech scan, candidate4/16 naturally starts infantry.
		// Sol: This also retries after a failed infantry scan; no original guard
		// Sol: prevents further scans or out-of-range IDs when every target fails.
		if (CandidatesRemaining == 0 && PlannedTargetPackedX == CombatantPosition_Unused)
		{
			if (CandidateCombatantId == Enemy_All_CombatantId_Range_First
				|| CandidateCombatantId == All_CombatantId_Range_Last)
				CandidateCombatantId -= Enemy_All_CombatantId_Range_First;
			CandidatesRemaining = Enemy_Infantry_Record_Count;
		}
	}

	if (ActorRecordBankOffset != 0)
		ActorCombatantId += Enemy_All_CombatantId_Range_First; //05A7 restore full actor ID

	// Sol: BYTE alias for downstream target writes, not an extra ASM local.
	unsigned char SelectedTargetByte = (unsigned char)SelectedTargetCombatantId;
	// Sol: Reconstructed range selection1631:05AB..0687. BP-2C is a WORD
	// Sol: movement-distance threshold, NOT a Short/Medium/Long bracket enum.
	unsigned short WeaponApproachDistance;
	if ((short)ActorCombatantId < Enemy_Infantry_CombatantId_Range_First
		&& ((short)ActorCombatantId < Friendly_Infantry_Combatant_Range_First
			|| (short)ActorCombatantId >= Enemy_All_CombatantId_Range_First))
	{
		unsigned short MinimumPackedShortRange = 0xFF; // BP-2C no qualifying weapon yet
		unsigned short ApproachMechRecordId = ActorCombatantId; // BP-2E
		if (ActorRecordBankOffset != 0)
			ApproachMechRecordId -= Enemy_All_CombatantId_Range_First - Enemy_Mech_Record_First; // enemy combatant12..15 -> mech record4..7

		for (unsigned short CriticalOffset = MECH_ComponentBlock_Start;
			CriticalOffset <= MECH_ComponentBlock_End; ++CriticalOffset) // BP-E; offsets33..55 inclusive
		{
			unsigned short ComponentCode = ((unsigned char far *)&seg3092->Mechs[ApproachMechRecordId])[CriticalOffset]; // BP-3A; zero-extended BYTE
			if (ComponentCode != 0 && (ComponentCode & Component_Destroyed) == 0
				&& ComponentCode >= Mech_Small_Laser && ComponentCode <= Mech_SRMissile6)
			{
				// Sol:064A RAW code indexes DS:2EE6+code*11h. Do not subtract1:
				// Sol: unlike firing's10A2 mapping; intended policy unresolved(A-004).
				unsigned short PackedShortRange = seg3EDB->WeaponStats[ComponentCode].RangeBracket & 0xE0; // top3 bits
				if ((short)PackedShortRange < (short)MinimumPackedShortRange)
					MinimumPackedShortRange = PackedShortRange;
			}
		}
		// Sol:0675 no eligible weapon =>0. Otherwise SAR3 of nonnegative
		// Sol: packed bits =4*encoded short range, not the usual >>5 decoding.
		WeaponApproachDistance = MinimumPackedShortRange == 0xFF
			? 0 : MinimumPackedShortRange >> 3;
	}
	else
	{
		// Sol: C5DB+actor*11h / C597+actor*11h rebase to C614+record*11h+0B.
		unsigned short ActorInfantryRecordId = ActorCombatantId - Friendly_Infantry_Combatant_Range_First;
		if ((short)ActorCombatantId >= Enemy_Infantry_CombatantId_Range_First)
			ActorInfantryRecordId = ActorCombatantId - Enemy_Infantry_RecordToCombatantId_Offset;
		short WeaponTableIndex = (signed char)seg3092->Infantry[ActorInfantryRecordId].Weapon; // BP-1C; ASM CBW
		WeaponApproachDistance = (seg3EDB->WeaponStats[WeaponTableIndex].RangeBracket >> 5) & 7; // top3 bits, no fourfold scaling
	}
	// Sol: Reconstructed1631:0688..0796. AX from1BFE is WORD1 clear/0 blocked.
	unsigned short TargetPathClear = Combat_Return_bool_fn1631_1BFE(
		ActorCombatantId, SelectedTargetCombatantId,
		seg3092->CombatantPackedX[SelectedTargetCombatantId],
		seg3092->CombatantPackedY[SelectedTargetCombatantId]); // four WORD arguments; BP-32

	// Sol: Infantry actors4..11/16..23 facing mech targets0..3/12..15
	// Sol: withdraw rather than approach. ASM classifies IDs with signed WORD tests.
	if (((short)ActorCombatantId >= Enemy_Infantry_CombatantId_Range_First
		|| ((short)ActorCombatantId >= Friendly_Infantry_Combatant_Range_First
			&& (short)ActorCombatantId < Enemy_All_CombatantId_Range_First))
		&& ((short)SelectedTargetCombatantId < Friendly_Infantry_Combatant_Range_First
			|| ((short)SelectedTargetCombatantId >= Enemy_All_CombatantId_Range_First
				&& (short)SelectedTargetCombatantId < Enemy_Infantry_CombatantId_Range_First)))
	{
		// Sol:3992 is actor-side state here, not a measured enemies-in-range test.
		seg3092->Bool_EnemiesWithinRange =
			(short)ActorCombatantId < Enemy_All_CombatantId_Range_First ? TRUE : FALSE; // DS:3992 WORD; broader meaning unresolved
		if ((short)ActorCombatantId >= Enemy_Infantry_CombatantId_Range_First)
			seg3092->EnemyPersonnelFlightPossible = TRUE; // DS:374C WORD; enemy withdrawal feeds later flight handling

		unsigned short WithdrawalActorPackedX = seg246C->CrescentHawk_MapPositionX; // DS:A44B; BP-1E
		unsigned short WithdrawalActorPackedY = seg246C->CrescentHawk_MapPositionY; // DS:A44D; BP-26
		// Sol: Six steps AWAY on each unequal axis; equal axes stay unchanged.
		// Sol: JBE/JNC comparisons are unsigned; assignments wrap as WORDs before bit7 tests.
		if (WithdrawalActorPackedX > PlannedTargetPackedX)
		{
			PlannedTargetPackedX = WithdrawalActorPackedX + 6; // original withdrawal displacement
			if ((PlannedTargetPackedX & 0x80) != 0)
				PlannedTargetPackedX += 0x80; // skip unused local-X bit7 into next region
		}
		else if (WithdrawalActorPackedX < PlannedTargetPackedX)
		{
			PlannedTargetPackedX = WithdrawalActorPackedX - 6;
			if ((PlannedTargetPackedX & 0x80) != 0)
				PlannedTargetPackedX &= 0x0F7F; // packed-X backward boundary correction
		}
		if (WithdrawalActorPackedY > PlannedTargetPackedY)
		{
			PlannedTargetPackedY = WithdrawalActorPackedY + 6;
			if ((PlannedTargetPackedY & 0x80) != 0)
				PlannedTargetPackedY += 0x0F80; // local-Y wrap advances region nibble
		}
		else if (WithdrawalActorPackedY < PlannedTargetPackedY)
		{
			PlannedTargetPackedY = WithdrawalActorPackedY - 6;
			if ((PlannedTargetPackedY & 0x80) != 0)
				PlannedTargetPackedY &= 0xF07F; // preserve Y-region high nibble, clear borrow/local bit7
		}
		// Sol:078F bypasses weapon-range stopping/path-clear branch:0797 then
		// Sol: encodes this withdrawal destination directly; not a new obstruction test.
		TargetPathClear = FALSE;
		WeaponApproachDistance = 0;
	}

	// Sol: Reconstructed1631:0797..08F8. BP-A is shared with target
	// Sol: selection: Reko's remaining-approach-distance alias is merged
	// Sol: into NearestTargetDistance, not a second/uninitialized variable.
	unsigned short OrderRowOffset = ActorCombatantId * Combat_MovementOrder_RowSize; // actor's48-byte row
	if (WeaponApproachDistance == 0 || TargetPathClear == FALSE)
	{
		// Sol:07A3 direct destination (includes infantry withdrawal).
		seg3092->CombatMovementOrders[OrderRowOffset] = (unsigned char)SelectedMovementMode;
		seg3092->CombatMovementOrders[OrderRowOffset + 1] =
			(unsigned char)(((PlannedTargetPackedX & 0x0F00) | (PlannedTargetPackedY & 0xF000)) >> 8); // combined region byte
		// Sol: ASM also masks these shared locals in-place, not just output bytes.
		PlannedTargetPackedX &= 0x7F;
		PlannedTargetPackedY &= 0x7F;
		seg3092->CombatMovementOrders[OrderRowOffset + 2] = (unsigned char)PlannedTargetPackedX;
		seg3092->CombatMovementOrders[OrderRowOffset + 3] = (unsigned char)PlannedTargetPackedY;
	}
	else
	{
		// Sol:07EB signed comparison of DISTANCE, never target combatant ID.
		// Sol: Already within weapon-derived approach range => leave cleared row.
		if (NearestTargetDistance <= (short)WeaponApproachDistance)
			goto AssignWeaponTargetsAndMeleeOverrides;

		unsigned short ApproachPackedX = seg246C->CrescentHawk_MapPositionX; // BP-1E WORD
		unsigned short ApproachPackedY = seg246C->CrescentHawk_MapPositionY; // BP-26 WORD
		short ApproachStepY = 0; // BP-16 signed WORD, not BYTE FF
		short ApproachStepX = 0; // BP-10 signed WORD
		if (ApproachPackedX > PlannedTargetPackedX) ApproachStepX = -1;
		else if (ApproachPackedX < PlannedTargetPackedX) ApproachStepX = 1;
		if (ApproachPackedY > PlannedTargetPackedY) ApproachStepY = -1;
		else if (ApproachPackedY < PlannedTargetPackedY) ApproachStepY = 1;

		// Sol:08A4 compares OLD distance, but decrements on EVERY test,
		// Sol: including final false test. Fixed deltas step both axes together.
		while (NearestTargetDistance-- > (short)WeaponApproachDistance)
		{
			ApproachPackedX += ApproachStepX; // WORD wrapping before bit7
			if ((ApproachPackedX & 0x80) != 0)
			{
				if (ApproachStepX == -1) ApproachPackedX &= 0x0F7F;
				else if (ApproachStepX == 1) ApproachPackedX += 0x80;
			}
			ApproachPackedY += ApproachStepY;
			if ((ApproachPackedY & 0x80) != 0)
			{
				if (ApproachStepY == -1) ApproachPackedY &= 0xF07F;
				else if (ApproachStepY == 1) ApproachPackedY += 0x0F80;
			}
		}
		// Sol:08AF encode intermediate destination, not actual movement.
		seg3092->CombatMovementOrders[OrderRowOffset] = (unsigned char)SelectedMovementMode;
		seg3092->CombatMovementOrders[OrderRowOffset + 1] =
			(unsigned char)(((ApproachPackedX & 0x0F00) | (ApproachPackedY & 0xF000)) >> 8);
		ApproachPackedX &= 0x7F; // preserve ASM local writes
		ApproachPackedY &= 0x7F;
		seg3092->CombatMovementOrders[OrderRowOffset + 2] = (unsigned char)ApproachPackedX;
		seg3092->CombatMovementOrders[OrderRowOffset + 3] = (unsigned char)ApproachPackedY;
	}

	// Sol: No movement-budget/occupancy check in this destination-order block;
	// Sol: target assignment and close-contact overrides follow at08F9.

AssignWeaponTargetsAndMeleeOverrides:
	// Sol: Reconstructed08F9..0A9F. Infantry have one target slot at row+0.
	if (((short)ActorCombatantId >= Friendly_Infantry_Combatant_Range_First
		&& (short)ActorCombatantId < Enemy_All_CombatantId_Range_First)
		|| (short)ActorCombatantId >= Enemy_Infantry_CombatantId_Range_First)
	{
		seg3092->CombatWeaponTarget[ActorCombatantId * Combat_WeaponTarget_RowSize] = (unsigned char)SelectedTargetCombatantId; // DS:3800 BYTE;12-byte row
		// Sol:0930 CBW: protected party infantry cannot fire while D333 is set.
		if (seg3092->Traitor_InParty != 0
			&& (short)(signed char)seg3092->Traitor_CharacterId
				+ Friendly_Infantry_Combatant_Range_First == ActorCombatantId)
			seg3092->CombatWeaponTarget[ActorCombatantId * Combat_WeaponTarget_RowSize] = 0xFF;
	}
	else
	{
		// Sol: Keep exact signed ASM gate: friendly mech with target<16,
		// Sol: or enemy mech12..15 with target<4. With opposing-side selection,
		// Sol: these are opposing mech pairs, not personnel kick targets.
		if (((short)ActorCombatantId < Friendly_Infantry_Combatant_Range_First
			&& (short)SelectedTargetCombatantId < Enemy_Infantry_CombatantId_Range_First)
			|| ((short)ActorCombatantId >= Enemy_All_CombatantId_Range_First
				&& (short)ActorCombatantId < Enemy_Infantry_CombatantId_Range_First
				&& (short)SelectedTargetCombatantId < Friendly_Infantry_Combatant_Range_First))
		{
			unsigned short FacingActorPackedX = seg3092->CombatantPackedX[ActorCombatantId];
			unsigned short FacingActorPackedY = seg3092->CombatantPackedY[ActorCombatantId];
			unsigned short FacingTargetPackedX = seg3092->CombatantPackedX[SelectedTargetCombatantId];
			unsigned short FacingTargetPackedY = seg3092->CombatantPackedY[SelectedTargetCombatantId];
			unsigned short ActorWorldX = ((FacingActorPackedX & 0x0F00) >> 1) | (FacingActorPackedX & 0x7F);
			unsigned short ActorWorldY = ((FacingActorPackedY & 0xF000) >> 5) | (FacingActorPackedY & 0x7F);
			unsigned short TargetWorldX = ((FacingTargetPackedX & 0x0F00) >> 1) | (FacingTargetPackedX & 0x7F);
			unsigned short TargetWorldY = ((FacingTargetPackedY & 0xF000) >> 5) | (FacingTargetPackedY & 0x7F);
			++ActorWorldX; // ASM centres both mech X anchors with+1
			++TargetWorldX;
			if (TargetPathClear != FALSE)
			{
				short SeparationX = (short)(TargetWorldX - ActorWorldX);
				short SeparationY = (short)(TargetWorldY - ActorWorldY);
				// Sol:207F:3C6C signed WORD abs; NEG preserves8000 on overflow.
				if (SeparationX < 0) SeparationX = (short)-SeparationX;
				if (SeparationY < 0) SeparationY = (short)-SeparationY;
				if (SeparationX <= 3 && SeparationY < 2) // mech close-contact box: |dx|<=3, |dy|<=1
				{
					seg3092->CombatantAnimationSelector[ActorCombatantId] = 0xFF; // DS:396C
					seg3092->CombatMovementOrders[ActorCombatantId * Combat_MovementOrder_RowSize] = 0xFF; // cancel first movement order only
					seg3092->CombatantFacing[ActorCombatantId] = (unsigned char)Get_Target_Compass_Direction(
						FacingActorPackedX, FacingActorPackedY, FacingTargetPackedX, FacingTargetPackedY); // four original packed WORDs
				}
			}
		}

		// Sol: Reconstructed0AA0..0B7A. Each actor has12 BYTE target slots.
		unsigned short TargetRowOffset = ActorCombatantId * Combat_WeaponTarget_RowSize;
		for (unsigned short ClearedTargetSlot = 0; ClearedTargetSlot < Combat_WeaponTarget_RowSize; ++ClearedTargetSlot) // BP-E; clear all12, not a combatant range
			seg3092->CombatWeaponTarget[TargetRowOffset + ClearedTargetSlot] = 0xFF; // DS:3800 no target

		unsigned short FiringMechRecordId = ActorCombatantId; // BP-2E
		if ((short)ActorCombatantId >= Enemy_All_CombatantId_Range_First)
			FiringMechRecordId -= Enemy_All_CombatantId_Range_First - Enemy_Mech_Record_First; // enemy12..15 -> record4..7
		// Sol:0AC3 reads006E+actor; enemy0AD8 overwrites it with0066+actor.
		// Sol: Effective canonical address is006E+record for either side. CBW
		// Sol: makes this a signed WORD, retaining wrapped negative heat semantics.
		short CurrentMechHeat = seg3092->Mech_HeatLevel[FiringMechRecordId]; // BP-34
		if (CurrentMechHeat < MECH_Heat_Max) // signed heat<30 permits targets
		{
			for (unsigned short WeaponOrdinal = 0; WeaponOrdinal < Mech_WeaponOrdinal_Count; ++WeaponOrdinal) // ten ordinary weapon/ammo ordinals0..9
			{
				// Sol:10A2 returns weapon TABLE INDEX or WORD00FF unavailable,
				// Sol: despite legacy GetAmmo name; unlimited ammoFF is handled inside.
				if (Combat_GetAmmoForSelectedWeapon_10A2(FiringMechRecordId, WeaponOrdinal) != 0xFF)
					seg3092->CombatWeaponTarget[TargetRowOffset + WeaponOrdinal] = SelectedTargetByte;
			}
			// Sol:0B2E assigns reserved kick slot11 unconditionally, not slot10;
			// Sol: range/actuator legality is checked elsewhere, not in this block.
			seg3092->CombatWeaponTarget[TargetRowOffset + Combat_KickTarget_Slot] = SelectedTargetByte;
		}
		else
		{
			seg3092->CombatMovementOrders[ActorCombatantId * Combat_MovementOrder_RowSize] = 0xFF; // cancel first movement mode at heat>=30
			for (unsigned short DisabledTargetSlot = 0; DisabledTargetSlot < Combat_WeaponTarget_RowSize; ++DisabledTargetSlot) // all12 previously-cleared targets
				seg3092->CombatWeaponTarget[TargetRowOffset + DisabledTargetSlot] |= 0x80; // FF remainsFF; preserve redundant original loop
		}
	}

	// Sol:0B7B..0BB4 always calculate movement193B, even with cancelled row.
	// Sol: Preview1774(actor,1) only for friendly-side actors when requested;
	// Sol: restore saved anchor via17BB on every path (not full scratch state).

	Combat_Calculate_Movement(ActorCombatantId);

	if (ActorRecordBankOffset == 0x00 && ShowPlanningPreview != 0x00)
		Combat_MovementTarget_unknown_1774(ActorCombatantId, TRUE);

	//PosX, PosY args
	Move_Map_View_To_Packed_Position_17BB(Character_PosX, Character_PosY);
}

// 1631:0BB5: Register Eq_28151 Combat_Operation_0BB5(short PosX, short PosY)
// Called from:
//      Combat_Computer_Control
//      Combat_Calculate_RangeBracket
//      Combat_Parent_000A
// Sol: Summary: Measure distance between packed world positions.
// Sol: Outline: Separate signed coordinate differences and return half the larger magnitude plus the smaller magnitude.
unsigned short Combat_Operation_0BB5(short PosX, short PosY)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: Unpack region*128 + local coordinate, then take signed WORD
	// Sol: differences. Unsigned locals made the old negative tests impossible.
	short DeltaX = (((seg246C->CrescentHawk_MapPositionX & 0x0F00) >> 1)
		| (seg246C->CrescentHawk_MapPositionX & 0x7F))
		- ((((unsigned short)PosX & 0x0F00) >> 1) | (PosX & 0x7F));
	short DeltaY = (((seg246C->CrescentHawk_MapPositionY & 0xF000) >> 5)
		| (seg246C->CrescentHawk_MapPositionY & 0x7F))
		- ((((unsigned short)PosY & 0xF000) >> 5) | (PosY & 0x7F));
	if (DeltaX < 0) DeltaX = -DeltaX;
	if (DeltaY < 0) DeltaY = -DeltaY;
	// Sol: floor(max(dx,dy)/2) + min(dx,dy), NOT Euclidean distance.
	return DeltaX > DeltaY ? (DeltaX >> 1) + DeltaY : (DeltaY >> 1) + DeltaX;
}

// 1631:0C63: void Combat_Mech_HeatLevels(Stack Eq_28220 MechId_04)
// Called from:
//      Combat_Mechanics
// Sol: Summary: Update heat, targets and casualty display state.
// Sol: Outline: Clear invalid targets, process all mech heat records, and retire dead personnel positions.
void Combat_Mech_HeatLevels(unsigned char far *MovementMetrics)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: Reconstructed0C63..0F23. FAR BYTE[24] points to execution's
	// Sol: SuccessfulMovementSteps stack array, not an integer/mech record.
	for (unsigned short TargetOwnerCombatantId = 0; TargetOwnerCombatantId < All_CombatantId_Range_Last; ++TargetOwnerCombatantId)
	{
		for (unsigned short TargetSlot = 0; TargetSlot < Combat_WeaponTarget_RowSize; ++TargetSlot) // twelve target BYTES
		{
			unsigned char far *TargetEntry =
				&seg3092->CombatWeaponTarget[TargetOwnerCombatantId * Combat_WeaponTarget_RowSize + TargetSlot]; // original local FAR pointer
			if (*TargetEntry != 0xFF)
			{
				*TargetEntry &= 0x7F; // clear fired/high-bit state before next round
				if (seg3092->CombatantActive[*TargetEntry] == FALSE)
					*TargetEntry = 0xFF; // inactive target discarded; no original ID bounds guard
			}
		}
	}

	for (unsigned short FriendlyMechSlot = 0; FriendlyMechSlot < Friendly_Mech_Record_Count; ++FriendlyMechSlot)
	{
		for (unsigned short MechRecordBank = 0; MechRecordBank <= Enemy_Mech_Record_First;
			MechRecordBank += Enemy_Mech_Record_First) // bank0 then4, not five independent records
		{
			unsigned short MechRecordId = FriendlyMechSlot + MechRecordBank;
			unsigned short MechCombatantId = FriendlyMechSlot +
				(MechRecordBank != 0 ? Enemy_All_CombatantId_Range_First : 0);
			unsigned char far *MechBytes = (unsigned char far *)&seg3092->Mechs[MechRecordId];
			if (MechBytes[0] != MECH_Destroyed) // first Name BYTE, not address of Name[16]
			{
				// Sol: CBW(plan mode)+1 gives Walk1/Run2/Jump3; FF(no move) ->0.
				short MovementHeat = (signed char)seg3092->CombatMovementOrders[MechCombatantId * Combat_MovementOrder_RowSize] + 1; // BP-4
				if (MovementHeat == 3)
				{
					short JumpSteps = (signed char)MovementMetrics[MechCombatantId]; // signed BYTE CMP/JLE
					if (JumpSteps > 3) MovementHeat = JumpSteps; // jump heat minimum3
				}
				// Sol: MUL is unsigned BYTE engine-hit count*5; heatsinks are unsigned.
				MovementHeat += seg3092->Mechs[MechRecordId].EngineHits * 5; // +75; five extra heat per engine hit
				MovementHeat -= seg3092->Mechs[MechRecordId].EngineHeatsinks; // +26 engine-mounted sinks
				for (unsigned short CriticalOffset = MECH_ComponentBlock_Start;
					CriticalOffset <= MECH_ComponentBlock_End; ++CriticalOffset)
					if (MechBytes[CriticalOffset] == Heat_Sink) --MovementHeat; // intact22 only; destroyedA2 does not cool
				MovementHeat += (signed char)seg3092->CombatWeaponHeat[MechRecordId]; // CBW weapon-heat BYTE
				seg3092->Mech_HeatLevel[MechRecordId] =
					(signed char)(seg3092->Mech_HeatLevel[MechRecordId] + (unsigned char)MovementHeat); // ADD BYTE wraps before clamps

				if (seg3092->Mech_Heat[MechRecordId] != 0) // timed inferno state BYTE
				{
					seg3092->Mech_HeatLevel[MechRecordId] = (signed char)(seg3092->Mech_HeatLevel[MechRecordId] + 6); // six heat per affected round
					--seg3092->Mech_Heat[MechRecordId];
				}
				// Sol:32AE/3750 views are BYTE arrays indexed by COMBATANT, not record.
				if (seg3092->TerrainOverlapRows[MechCombatantId] != 0
					&& seg3092->MapTileUnderCombatant[MechCombatantId] < Combat_TerrainCooling_TileRange_End) // original terrain tile class0..15
					seg3092->Mech_HeatLevel[MechRecordId] = (signed char)(seg3092->Mech_HeatLevel[MechRecordId] - 4); // terrain cooling4

				if (seg3092->Mech_HeatLevel[MechRecordId] < 0)
					seg3092->Mech_HeatLevel[MechRecordId] = 0;
				// Sol: BUG-013: original upper clamp omits enemy record bank.
				// Sol: DO NOT change this to MechRecordId; enemy heat may exceed30.
				if (seg3092->Mech_HeatLevel[FriendlyMechSlot] > MECH_Heat_Max)
					seg3092->Mech_HeatLevel[FriendlyMechSlot] = MECH_Heat_Max;
			}
			seg3092->CombatWeaponHeat[MechRecordId] = 0; // unconditional, even destroyed/skipped record
		}
	}

	for (unsigned short InfantryRecordId = 0; InfantryRecordId < Infantry_Record_Count; ++InfantryRecordId) // all friendly/enemy character records
	{
		if (seg3092->Infantry[InfantryRecordId].Name == Character_Dead)
		{
			unsigned short InfantryCombatantId = InfantryRecordId + Friendly_Infantry_Combatant_Range_First;
			if (InfantryRecordId >= Enemy_Infantry_Record_First)
				InfantryCombatantId += Enemy_Infantry_RecordToCombatantId_Offset - Friendly_Infantry_Combatant_Range_First;
			if (InfantryRecordId != Jason)
			{
				seg3092->CombatantPackedY[InfantryCombatantId] = CombatantPosition_Unused; // WORD FFFF
				seg3092->CombatantPackedX[InfantryCombatantId] = CombatantPosition_Unused;
			}
			if (InfantryCombatantId >= Enemy_Infantry_CombatantId_Range_First)
				seg3092->CombatantSpriteFamilyOffset[InfantryCombatantId] = CharacterSpriteFamily_EnemyInfantry; // FE
			if (InfantryRecordId == Jason)
				seg3092->CombatantSpriteFamilyOffset[InfantryCombatantId] = CharacterSpriteFamily_Jason; //96; preserve Jason's coordinates
			// Sol: No active-table clear here; casualty processing owns that state.
		}
	}
}

// 1631:0F24: Register word16 Combat_Calculate_RangeBracket(Register Eq_21 ds, Stack Eq_21 MechLanceId, Stack Eq_21 Mech_CurrentActuators)
// Called from:
//      Combat_Weapon_UI_0004
//      Combat_Select_Weapon_Target_UI
//      Combat_Mechanics
// Sol: Summary: Determine a weapon's range bracket.
// Sol: Outline: Adjust for target footprint, calculate packed-world distance, and compare the weapon's range limits.
unsigned short Combat_Calculate_RangeBracket(unsigned short TargetId, unsigned short WeaponId)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: WORD positions preserve region nibbles; WeaponId is a table index,
	// Sol: not a component code. Typed arrays already account for record stride.
	unsigned short Target_MechPosX = seg3092->CombatantPackedX[TargetId]; //DS:4004
	unsigned short Target_MechPosY = seg3092->CombatantPackedY[TargetId]; //DS:4036

	if (((short)TargetId < Friendly_Infantry_Combatant_Range_First
		|| ((short)TargetId >= Enemy_All_CombatantId_Range_First && (short)TargetId <= Enemy_Mech_CombatantId_Range_Last))
		&& (short)Combat_Operation_0BB5(Target_MechPosX, Target_MechPosY) > 3) // Sol: distant mech footprint correction; signed ASM ID/distance tests
	{
		if (seg246C->CrescentHawk_MapPositionX < Target_MechPosX) //A44B - Character Position X 
		{
			Target_MechPosX = Target_MechPosX - 0x01;

			if ((Target_MechPosX & 0x80) != 0x00)
				Target_MechPosX &= 0x0F7F;
		}

		if (seg246C->CrescentHawk_MapPositionX > Target_MechPosX) //A44B - Character Position X 
		{
			Target_MechPosX++;

			if ((Target_MechPosX & 0x80) != 0x00)
				Target_MechPosX += 0x80;
		}

		if (seg246C->CrescentHawk_MapPositionY < Target_MechPosY) //A44D - Character position Y
		{
			Target_MechPosY -= 0x02;

			if ((Target_MechPosY & 0x80) != 0x00)
				Target_MechPosY &= 0xF07F;
		}
	}

	unsigned short DistanceToTarget = Combat_Operation_0BB5(Target_MechPosX, Target_MechPosY);
	unsigned short SelectedRangeBracket = RangeBracket_OutOfRange; //Out of Range Bracket

	

	// Sol: All boundaries are strict (<); equality with maximum is out of range.
	// Sol: Only short/medium thresholds are scaled here; maximum is pre-scaled.
	if (seg3EDB->WeaponStats[WeaponId].MaximumRange > DistanceToTarget)
		SelectedRangeBracket = RangeBracket_Long; // Long range bracket

	unsigned short PackedWeaponRange = seg3EDB->WeaponStats[WeaponId].RangeBracket;
	unsigned short MediumRange = PackedWeaponRange & 0x1F;
	unsigned short ShortRange = PackedWeaponRange >> 0x05;

	//If MECH weaponry (< 80) then rescale range by 3x
	if (seg3EDB->WeaponStats[WeaponId].WeaponType < InfantryWeapons && WeaponId != (Mech_Kick - 1))
	{
		MediumRange = (PackedWeaponRange & 0x1F) * InfantryToMechGridScaling; //0x03 is for 8px character scaling to Mech Scaling
		ShortRange = (PackedWeaponRange >> 0x05) * InfantryToMechGridScaling; //0x03 is for 8px character scaling to Mech Scaling
	}

	if (DistanceToTarget < MediumRange)
		SelectedRangeBracket = RangeBracket_Medium; //Medium Range Bracket

	if (DistanceToTarget < ShortRange)
		SelectedRangeBracket = RangeBracket_Short; //Short Range Bracket

	return SelectedRangeBracket;
}

// 1631:1057: void Combat_Weapon_Display_Text_And_Menu_Options(Stack Eq_21 Ptr)
// Called from:
//      Combat_Weapon_UI_0004
// Sol: Summary: Show a temporary combat weapon message.
// Sol: Outline: Save the panel layout, display text and wait for input, then restore the previous layout.
void Combat_Weapon_Display_Text_And_Menu_Options(unsigned char far *Ptr)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: Save layout BEFORE switching panels (WORD local [BP-2]).
	unsigned short SavedMenuLayout = seg3092->CurrentMenuLayoutIndex;
	Menu_Memory_Variables(0x04);
	Draw_Top_Graphic_Sidebar();
	Display_Text_From_Memory(Ptr);
	Keyboard_Get_ASCII_Hex_Input();
	Draw_Top_Graphic_Sidebar();
	Menu_Memory_Variables(SavedMenuLayout);
}

// 1631:10A2: Register cui16 Combat_GetAmmoForSelectedWeapon_10A2(unsigned char MechLanceId, unsigned char SelectedWeaponId)
// Called from:
//      Combat_Computer_Control
//      Combat_Mechanics
// Sol: Summary: Find the raw component index for a weapon ordinal.
// Sol: Outline: Walk weapon-bearing critical entries and return component-minus-one or 0xFF; the legacy ammo name is misleading.
unsigned short Combat_GetAmmoForSelectedWeapon_10A2(unsigned short MechLanceId, unsigned short SelectedWeaponId)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: Legacy name retained for callers: returns weapon TABLE INDEX or
	// Sol: 00FF, not ammo. SelectedWeaponId is a zero-based weapon ordinal.
	// Sol: TODO rename callers together in the combat execution review.
	unsigned short CurrentWeaponId = 0x00; // Sol: original WORD ordinal counter
	unsigned short WeaponAmmoOffset = 0x00FF;

	for(unsigned short CriticalSlot = MECH_ComponentBlock_Start; CriticalSlot <= MECH_ComponentBlock_End; CriticalSlot++)
	{
		unsigned short MechComponent = ((unsigned char far *)&seg3092->Mechs[MechLanceId])[CriticalSlot]; //DS:C724 + id*7D + offset

		if ((MechComponent & MechWeapons) >= Mech_Small_Laser
		 && (MechComponent & MechWeapons) <= Mech_SRMissile6 )
		{
			if (CurrentWeaponId++ == SelectedWeaponId)
			{
				WeaponAmmoOffset = (MechComponent - 1);

				// Sol: Raw component minus one preserves its destruction high bit.
				// Sol: ASM has no ordinal<10 guard; offsets 31/32 are movement,
				// Sol: not ammo. Preserve this and track it under BUG-012.
				if (((unsigned char far *)&seg3092->Mechs[MechLanceId])[0x27 + SelectedWeaponId] == 0)
					WeaponAmmoOffset = 0x00FF;

				CriticalSlot = 0x57; //LOOP ESCAPE
			}
		}
	} 

	return WeaponAmmoOffset;
}

// 1631:1122: Register unsigned char Combat_StructureHit_1122(unsigned char HitLocationId)
// Called from:
//      Combat_Mechanics
// Sol: Summary: Find where structural damage should transfer.
// Sol: Outline: Map the supplied raw hit-location offset to the original neighbouring section or terminal result.
unsigned short Combat_StructureHit_1122(unsigned short HitLocationOffset)
{	
	// Sol: Whole-body comparison confirms the mapped branches/writes. Native BP-2
	// Sol: remains unassigned on terminal/invalid cases; this research transcription
	// Sol: records that fact, not a valid host-C uninitialized read. The preservation
	// Sol: C caller contract makes the fatal return unobservable after Mech ejection;
	// Sol: invalid offsets still require a native residual-storage representation.
	// Sol: Raw record offsets, not the zero-based switch selector which Reko
	// Sol: exposed. Armour/structure names follow the EXE hit-location text;
	// Sol: A-005 concerns the separate critical groups, not these array locations.
	// Sol: ASM leaves return local unassigned for 1F/20 and invalid inputs;
	// Sol: preserve that finding, not an invented safe/default transfer location.
	// Sol:1631:112C..1141: the first eight armour bytes correspond directly to
	// Sol: the eight internal-structure bytes. +11 is their array storage distance,
	// Sol: NOT eleven damage points or a tabletop modifier. The remaining three
	// Sol: armour bytes use the rear-armour branches. Preservation C now uses
	// Sol: named MechLocation/MechOffset constants; reference offsets remain here.
	enum { FirstPrimaryArmourOffset=0x11, PrimaryArmourLocationCount=8,
		ArmourToStructureOffset=0x0B };
	unsigned short DamageLocation;
	if (HitLocationOffset >= FirstPrimaryArmourOffset &&
		HitLocationOffset < FirstPrimaryArmourOffset + PrimaryArmourLocationCount)
		DamageLocation = HitLocationOffset + ArmourToStructureOffset;
	else if (HitLocationOffset >= 0x19 && HitLocationOffset <= 0x23)
	{
		switch (HitLocationOffset)
		{
		case 0x19: // Sol: rear-left-torso armour -> left-torso structure
			DamageLocation = 0x1D;
			break;

		case 0x1A: // Sol: rear-center-torso armour -> center-torso structure
			DamageLocation = 0x20;
			break;

		case 0x1B: // Sol: rear-right-torso armour -> right-torso structure
			DamageLocation = 0x22;
			break;

		case 0x1C: // Sol: left-arm structure
		case 0x1E: // Sol: left-leg structure -> FRONT left-torso armour, not structure
			DamageLocation = 0x12;
			break;

		case 0x1D: // Sol: left-torso structure
		case 0x22: // Sol: right-torso structure -> FRONT center-torso armour
			DamageLocation = 0x15;
			break;

		case 0x1F: // Sol: head structure
		case 0x20: // Sol: center-torso structure; either destroys the Mech
			seg3092->MechDestroyedFlag = TRUE;
			break;

		case 0x21: // Sol: right-arm structure
		case 0x23: // Sol: right-leg structure -> FRONT right-torso armour
			DamageLocation = 0x17;
			break;
		}
	}

	return DamageLocation;
}

// 1631:11AB: Register Eq_3193 Combat_Critical_Mech_Damage_11AB(Stack int16 MechLanceId, Stack Eq_3193 Mech_CurrentActuators)
// Called from:
//      Combat_Mechanics
// Sol: Summary: Apply section destruction and critical hits to a mech.
// Sol: Outline: Inspect section structure, select critical components, and dispatch weapon, ammo, actuator or system damage.
void Combat_Critical_Mech_Damage_11AB(unsigned short MechId, unsigned short StructureOffset)
{
	// Sol: DS315E is "\rCritical!" with NO trailing CR. The preservation C
	// Sol: already used that exact string; this reference now agrees.
	// Sol:11AB..15F9 WORD mech RECORD ID0..7 and structure BYTE OFFSET1C..23.
	unsigned char far* Record = (unsigned char far*)&seg3092->Mechs[MechId];
	unsigned short SectionDestroyed = Record[StructureOffset] == 0; // SS:BP-4 flag, not pointer.
	unsigned short CriticalHitsRemaining = 1; // BP-0A independent of dice/result/register scratch.
	short CriticalRoll = Roll2D6(); // BP-0C; original always rolls, including destroyed section.
	if (CriticalRoll >= 8)
		CriticalHitsRemaining = ((CriticalRoll - 8) >> 1) + 1; // Sol:11EA roll8/9 ->1,10/11 ->2,12 ->3; below8 remains1.
	if (seg3EDB->CombatMessageVerbosity != CombatMessage_None && CriticalHitsRemaining != 0)
	{
		Menu_Memory_Variables(4);
		Combat_CombatMessageVerbosityFilter("\rCritical!"); // DS:315E; verified EXE text.
		seg3092->CombatNotificationLatch = TRUE; // Sol:1219 WORD4586 notification latch, not hit count.
	}
	if (SectionDestroyed != FALSE)
	{
		CriticalHitsRemaining = 0;
		short Start = (signed char)seg3EDB->CriticalSectionStart[StructureOffset - 0x1C];
		short Count = (signed char)seg3EDB->CriticalSectionCount[StructureOffset - 0x1C]; // Sol:122F/1267 original tables indexed as316E/3176+structure offset.
		for (short Index = 0; Index < Count; ++Index)
			if (Record[Start + Index] != 0) Record[Start + Index] |= 0x80; // Sol: nonempty slot marked destroyed, including already marked ones.
		switch (StructureOffset)
		{
		case 0x1C: Record[MECH_Offset_CurrentActuators_Left] &= MechActuatorLegMask; break; // Sol:128C clears high arm nibble at24.
		case 0x21: Record[MECH_Offset_CurrentActuators_Right] &= MechActuatorLegMask; break; // Sol:12BA high arm nibble at25.
		case 0x1E: Record[MECH_Offset_CurrentActuators_Left] &= MechActuatorArmMask; break; // Sol:12CE clears low leg nibble at24.
		case 0x23: Record[MECH_Offset_CurrentActuators_Right] &= MechActuatorArmMask; break; // Sol:12E2 low leg nibble at25.
		}
		return; // Sol: section-only destruction does not newly set E484 here.
	}
	while (CriticalHitsRemaining != 0)
	{
		unsigned short ComponentStart, ComponentCount, ActuatorOffset;
		unsigned char NibbleMask;
		switch (StructureOffset) // Sol:15E2 eight-entry dispatch; raw offsets intentional under A-005.
		{
		case 0x1F: // Sol:12F6 head-critical systems.
		{
			unsigned short Roll = RollD6();
			if (Roll == 1 || Roll == 6)
			{
				if (seg3092->Mechs[MechId].LifeSupportState == 0) continue; // Sol:131C +78 probable life-support; only ZERO rejected.
				seg3092->Mechs[MechId].LifeSupportState = 0xFF; // Sol: alreadyFF can be hit again; preserve original nonzero gate.
				--CriticalHitsRemaining;
			}
			else if (Roll == 2 || Roll == 5)
			{
				if (seg3092->Mechs[MechId].SensorHits >= 2) continue; // Sol:1347 unsigned BYTE threshold, two sensor hits maximum.
				++seg3092->Mechs[MechId].SensorHits;
				--CriticalHitsRemaining;
			}
			else if (Roll == 3)
			{
				Record[0x1F] = 0; // Sol:136D head structure destroyed.
				CriticalHitsRemaining = 0;
				seg3092->MechDestroyedFlag = TRUE; // DS:E484 WORD.
			}
			else if (Roll == 4)
				CriticalHitsRemaining -= Combat_fn1631_163E(Record + 0x55, 1); // Sol:1393 head critical BYTE; helper0 retries without consumption.
			continue;
		}
		case 0x20: // Sol:13B5 central engine/gyro systems and two-slot block53.
			if ((short)RollD6() <= 3)
			{
				unsigned short Destroyed;
				--CriticalHitsRemaining;
				if ((short)RollD6() <= 3)
				{
					++seg3092->Mechs[MechId].GyroHits; // +76 BYTE increment.
					Destroyed = seg3092->Mechs[MechId].GyroHits >= 2;
				}
				else
				{
					++seg3092->Mechs[MechId].EngineHits; // +75 BYTE increment.
					Destroyed = seg3092->Mechs[MechId].EngineHits >= 3;
				}
				if (Destroyed != FALSE)
				{
					Record[0x20] = 0; // Sol:13E8 centre structure.
					CriticalHitsRemaining = 0;
					seg3092->MechDestroyedFlag = TRUE;
				}
			}
			else
				CriticalHitsRemaining -= Combat_fn1631_163E(Record + 0x53, 2); // Sol:1410 two critical BYTES53/54; not a leg-field alias.
			continue;
		case 0x1D: case 0x22: // Sol:14ED seven-slot torso sections, no actuator nibble.
			ComponentStart = StructureOffset == 0x22 ? 0x48 : 0x3A;
			if (MechId_Random_Count_15FA(Record + ComponentStart, 7) == 0)
				CriticalHitsRemaining = 0; // Sol:1573 no eligible component ends remaining criticals.
			else
				CriticalHitsRemaining -= Combat_fn1631_163E(Record + ComponentStart, 7);
			continue;
		case 0x1E: case 0x23: // Sol:1422 low-nibble leg actuators and two-slot blocks4F/51.
			ActuatorOffset = StructureOffset == 0x23 ? MECH_Offset_CurrentActuators_Right : MECH_Offset_CurrentActuators_Left;
			ComponentStart = StructureOffset == 0x23 ? 0x51 : 0x4F;
			ComponentCount = 2;
			NibbleMask = MechActuatorLegMask;
			break;
		case 0x1C: case 0x21: // Sol:1525 high-nibble arm actuators and seven-slot blocks33/41.
			ActuatorOffset = StructureOffset == 0x21 ? MECH_Offset_CurrentActuators_Right : MECH_Offset_CurrentActuators_Left;
			ComponentStart = StructureOffset == 0x21 ? 0x41 : 0x33;
			ComponentCount = 7;
			NibbleMask = MechActuatorArmMask;
			break;
		default: continue; // Sol:12A7 invalid offset retries forever; legal caller contract1C..23, no silent new validation.
		}
		if ((Record[ActuatorOffset] & NibbleMask) == 0 && MechId_Random_Count_15FA(Record + ComponentStart, ComponentCount) == 0)
		{
			CriticalHitsRemaining = 0;
			continue;
		}
		unsigned short Roll = RollD6(); // Sol:1473/157B roll1..2 component,3..6 actuator if any nibble remains.
		if ((short)Roll >= 3 && (Record[ActuatorOffset] & NibbleMask) != 0)
		{
			unsigned char HitMask = NibbleMask == MechActuatorLegMask
				? seg3EDB->CriticalLowActuatorHitMask[Roll - 3]
				: seg3EDB->CriticalHighActuatorHitMask[Roll - 3];
			if ((Record[ActuatorOffset] & (short)(signed char)HitMask) == 0) continue; // Sol:14A3/15AB CBW mask, missing chosen actuator retries.
			unsigned char ClearMask = NibbleMask == MechActuatorLegMask
				? seg3EDB->CriticalLowActuatorClearMask[Roll - 3]
				: seg3EDB->CriticalHighActuatorClearMask[Roll - 3];
			Record[ActuatorOffset] &= ClearMask; // Sol:14C1 BYTE AND, consumes exactly one hit.
			--CriticalHitsRemaining;
		}
		else
			CriticalHitsRemaining -= Combat_fn1631_163E(Record + ComponentStart, ComponentCount); // Sol:14DA/1520 helper removes one intact critical; zero retries.
	}
}

// 1631:15FA: Register int16 MechId_Random_Count_15FA(Stack Eq_21 MechId_04, Stack int16 LessThanCond)
// Called from:
//      Combat_Critical_Mech_Damage_11AB
//      Combat_fn1631_163E
// Sol: Summary: Count intact critical entries.
// Sol: Outline: Scan the supplied range and count nonzero entries without the destruction high bit.
unsigned short MechId_Random_Count_15FA(unsigned char far *Components, short Count)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: No randomness here: count nonempty, undestroyed critical bytes.
	unsigned short IntactCount = 0;
	for (short Index = 0; Index < Count; ++Index)
	{
		if (Components[Index] != 0 && (Components[Index] & 0x80) == 0)
			++IntactCount;
	}
	return IntactCount;
}

// 1631:163E: Register int16 Combat_fn1631_163E(Stack Eq_21 MechId, Stack int16 EnemyMech_PosY_08)
// Called from:
//      Combat_Critical_Mech_Damage_11AB
// Sol: Summary: Mark one intact critical entry destroyed.
// Sol: Outline: Reject empty ranges, choose a start from zero to three, scan cyclically for an intact entry, mark it and return success.
unsigned short Combat_fn1631_163E(unsigned char far *Components, short Count)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: Mark ONE eligible byte destroyed, return 1; return 0 if none.
	// Sol: Random start is 0..3, not 0..Count-1. The ASM normalizes it at
	// Sol: 1690 BEFORE the first dereference, then scans cyclically.
	if (MechId_Random_Count_15FA(Components, Count) == 0) return 0;
	short Index = Rand_0x00_to_0xFF() & 3;
	for (;;)
	{
		if (Index >= Count) Index = 0;
		if (Components[Index] != 0 && (Components[Index] & 0x80) == 0)
		{
			Components[Index] |= 0x80;
			return 1;
		}
		++Index;
	}
}

// 1631:16AB: WORD Return_bool_fn1631_16AB(WORD actor, WORD dx, WORD dy, WORD crush)
// Called from:
//      Position_0006
//      Combat_Mechanics
// Sol: Summary: Check occupied destinations and possible crushing.
// Sol: Outline: Compare actor footprints at the trial step, apply the native occupancy and crushing rules, and return acceptance.
unsigned short Return_bool_fn1631_16AB(unsigned short ActorId, short StepX, short StepY,
	unsigned short CrushOpposingInfantry)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol:16AB..1B43 four WORD arguments, AX WORD blocked result.
	// Sol: StepX/StepY are passed but never read; candidate is global A44B/A44D.
	unsigned short Blocked = FALSE; // SS:BP-6; independent of distance/Y scratch.
	if (((short)ActorId >= Friendly_Infantry_Combatant_Range_First && (short)ActorId < Enemy_All_CombatantId_Range_First)
	 || (short)ActorId >= Enemy_Infantry_CombatantId_Range_First)
	{
		// Sol:16EE exact-position infantry checks have NO active/sentinel filter.
		for (unsigned short FriendlyId = Friendly_Infantry_Combatant_Range_First; FriendlyId < Enemy_All_CombatantId_Range_First; ++FriendlyId)
		{
			if (FriendlyId != ActorId
			 && seg3092->CombatantPackedX[FriendlyId] == seg246C->CrescentHawk_MapPositionX
			 && seg3092->CombatantPackedY[FriendlyId] == seg246C->CrescentHawk_MapPositionY)
				Blocked = TRUE;
			unsigned short EnemyId = FriendlyId + Enemy_All_CombatantId_Range_First; // Sol:401C/404E aliases -> canonical16..23.
			if (Blocked == FALSE && EnemyId != ActorId
			 && seg3092->CombatantPackedX[EnemyId] == seg246C->CrescentHawk_MapPositionX
			 && seg3092->CombatantPackedY[EnemyId] == seg246C->CrescentHawk_MapPositionY)
				Blocked = TRUE;
			if (Blocked != FALSE) break;
		}
		if (Blocked != FALSE) return Blocked;
		unsigned short SavedX = seg246C->CrescentHawk_MapPositionX; // BP-4 candidate anchor.
		unsigned short SavedY = seg246C->CrescentHawk_MapPositionY; // BP-0A.
		for (unsigned short RelativeMech = 0; RelativeMech < Friendly_Infantry_Combatant_Range_First && Blocked == FALSE; ++RelativeMech)
			for (unsigned short SideBase = 0; SideBase <= Enemy_All_CombatantId_Range_First && Blocked == FALSE; SideBase += Enemy_All_CombatantId_Range_First)
			{
				unsigned short MechId = RelativeMech + SideBase; // Sol:0..3 and12..15; no active guard in this footprint branch.
				seg246C->CrescentHawk_MapPositionX = seg3092->CombatantPackedX[MechId];
				seg246C->CrescentHawk_MapPositionY = seg3092->CombatantPackedY[MechId];
				if (SavedY == seg246C->CrescentHawk_MapPositionY)
				{
					if (SavedX == seg246C->CrescentHawk_MapPositionX)
						Blocked = TRUE;
					else
					{
						Offset_Packed_Position(-1, 0); // Sol:17A4 left footprint cell, including packed region wrap.
						if (SavedX == seg246C->CrescentHawk_MapPositionX)
							Blocked = TRUE;
						else
						{
							Offset_Packed_Position(2, 0); // Sol:17C0 left+2 -> right footprint cell.
							if (SavedX == seg246C->CrescentHawk_MapPositionX) Blocked = TRUE;
						}
					}
				}
			}
		seg246C->CrescentHawk_MapPositionX = SavedX;
		seg246C->CrescentHawk_MapPositionY = SavedY; // Sol:184B always restore candidate anchor.
		return Blocked; // Sol: infantry never enters optional crushing branch.
	}

	// Sol:1864 mech candidate X+1, then packed low-bit80 correction+80h.
	unsigned short CorrectedX = seg246C->CrescentHawk_MapPositionX + 1;
	if ((CorrectedX & 0x80) != 0) CorrectedX += 0x80;
	short MechUnpackedXPlusOne = (short)(((CorrectedX & 0x0F00) >> 1) | (CorrectedX & 0x7F)); // BP-1C; regionX*128 + localX.
	for (unsigned short RelativeMech = 0; RelativeMech < Friendly_Infantry_Combatant_Range_First && Blocked == FALSE; ++RelativeMech)
		for (unsigned short SideBase = 0; SideBase <= Enemy_All_CombatantId_Range_First && Blocked == FALSE; SideBase += Enemy_All_CombatantId_Range_First)
		{
			unsigned short OtherId = RelativeMech + SideBase;
			if (seg3092->CombatantActive[OtherId] != FALSE && OtherId != ActorId
			 && seg3092->CombatantPackedY[OtherId] == seg246C->CrescentHawk_MapPositionY)
			{
				unsigned short OtherX = seg3092->CombatantPackedX[OtherId] + 1;
				if ((OtherX & 0x80) != 0) OtherX += 0x80;
				short OtherUnpackedXPlusOne = (short)(((OtherX & 0x0F00) >> 1) | (OtherX & 0x7F));
				short Distance = (short)(OtherUnpackedXPlusOne - MechUnpackedXPlusOne);
				if (Distance < 0) Distance = (short)-Distance; // Sol:18F5 FAR207F:3C6C signed WORD abs; preserve16-bit overflow, not BYTE helper signature.
				if (Distance < 3) Blocked = TRUE; // Sol: overlapping three-wide mech footprints, same packed Y.
			}
		}
	unsigned short SameSideInfantryBase = (short)ActorId < Enemy_All_CombatantId_Range_First
		? Friendly_Infantry_Combatant_Range_First : Enemy_Infantry_CombatantId_Range_First; // BP-10 side base4/16.
	short MechUnpackedX = (short)(MechUnpackedXPlusOne - 1); // Sol:193C decrement AFTER unpack/correction.
	for (unsigned short InfantryId = SameSideInfantryBase; InfantryId < SameSideInfantryBase + 8; ++InfantryId)
		if (seg3092->CombatantActive[InfantryId] != FALSE
		 && seg3092->CombatantPackedY[InfantryId] == seg246C->CrescentHawk_MapPositionY)
		{
			unsigned short InfantryX = seg3092->CombatantPackedX[InfantryId];
			short InfantryUnpackedX = (short)(((InfantryX & 0x0F00) >> 1) | (InfantryX & 0x7F));
			short Distance = (short)(MechUnpackedX - InfantryUnpackedX);
			if (Distance < 0) Distance = (short)-Distance;
			if (Distance < 2) { Blocked = TRUE; break; } // Sol: friendly personnel under own mech footprint block movement.
		}
	if (Blocked != FALSE || CrushOpposingInfantry == FALSE) return Blocked;
	unsigned short OpposingInfantryBase = SameSideInfantryBase ^ 0x14; // Sol:19C9 XOR low BYTE14 switches4<->16; not record-index XOR.
	for (unsigned short InfantryId = OpposingInfantryBase; InfantryId < OpposingInfantryBase + 8; ++InfantryId)
		if (seg3092->CombatantActive[InfantryId] != FALSE
		 && seg3092->CombatantPackedY[InfantryId] == seg246C->CrescentHawk_MapPositionY)
		{
			unsigned short InfantryX = seg3092->CombatantPackedX[InfantryId];
			short InfantryUnpackedX = (short)(((InfantryX & 0x0F00) >> 1) | (InfantryX & 0x7F));
			short Distance = (short)(MechUnpackedX - InfantryUnpackedX);
			if (Distance < 0) Distance = (short)-Distance;
			if (Distance >= 2) continue;
			unsigned short InfantryRecordId = InfantryId - Friendly_Infantry_Combatant_Range_First; // BP-20; friendly combatants4..11 -> records0..7.
			Menu_Memory_Variables(4);
			Draw_Top_Graphic_Sidebar();
			if (InfantryRecordId < Enemy_All_CombatantId_Range_First)
				Combat_CombatMessageVerbosityFilter(seg3EDB->CharacterNameList[(short)(signed char)seg3092->Infantry[InfantryRecordId].Name]); // Sol:19D6 CBW BYTE name index -> FAR table.
			else
			{
				InfantryRecordId -= 4; // Sol:1B2F enemy combatants16..23 -> records8..15 (id-8).
				Combat_CombatMessageVerbosityFilter("Enemy human"); // DS:319A; verified EXE.
			}
			Combat_CombatMessageVerbosityFilter(" is squashed underfoot."); // DS:31A6
			Play_Sound_If_Enabled(Sound_SquishedByMech); // Sol: sound12h.
			if ((short)seg3EDB->CombatSpeedSetting < 5)
			{
				GameSpeed_RateControl();
				if (InfantryRecordId < 8) GameSpeed_RateControl(); // Sol: friendly death gets a second delay.
			}
			Register_Persistent_Map_Effect_27C9(Sprite_Impact_Small,
				seg3092->CombatantPackedX[InfantryId], seg3092->CombatantPackedY[InfantryId]);
			seg3092->CombatantSpriteFrame[InfantryId] = Sprite_Impact_Small; // Sol:1A35 death tile7E.
			seg3092->CombatantSpriteFamilyOffset[InfantryId] = 0; // Sol:1A57 family base0, not mech-type inference.
			seg3092->CombatantActive[InfantryId] = FALSE;
			seg3092->Infantry[InfantryRecordId].Health = 0;
			seg3092->Infantry[InfantryRecordId].Name = Character_Dead;
			if (InfantryRecordId < 2) seg3EDB->Bool_MainCharactersAlive = FALSE; // Sol:1A9F Jason/Rex record0/1.
			// Sol: no position invalidation,393C casualty/395C loot flag write, or Blocked change on crush; scan continues.
		}
	return Blocked; // Sol:1B3B AX BP-6 stays0 after crushing, so execution caller accepts the mech move.
}

// 1631:1B44: Register unsigned char Combat_Check_Mech_Actuator_Status(unsigned char MechLanceId, unsigned char Mech_CurrentActuators)
// Called from:
//      Combat_Mechanics
// Sol: Summary: Test a mech's requested actuator mask.
// Sol: Outline: Read the actuator damage bytes and test the supplied component mask; individual anatomical bit labels remain uncertain.
unsigned short Combat_Check_Mech_Actuator_Status(unsigned short MechLanceId, unsigned short Mech_CurrentActuators)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: Second argument is raw record offset (normally 24/25). Return
	// Sol: number of missing LOW-three bits, not health or a boolean (0..3).
	unsigned char MechActuator = ((unsigned char far *)&seg3092->Mechs[MechLanceId])[Mech_CurrentActuators]; //DS:C724
	unsigned short ActuatorHealth = 0x00; // Sol: BP-4/AX WORD count

	if ((MechActuator & 0x04) == 0x00)
		ActuatorHealth++;

	if ((MechActuator & 0x02) == 0x00)
		ActuatorHealth++;

	if ((MechActuator & 0x01) == 0x00)
		ActuatorHealth++;

	return ActuatorHealth;
}

// 1631:1B8F: void Combat_Display_Text_From_Memory(Stack int16 eqCond)
// Called from:
//      Combat_Mechanics
// Sol: Summary: Print the name of an armour hit location.
// Sol: Outline: Translate the raw armour location into the corresponding native text entry.
void Combat_DisplayText_ArmourHitLocation(unsigned short ArmourLocation)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: Eleven signed-byte offset keys at DS:3242 select far strings at
	// Sol: DS:324E. First match only; strcpy then append period, not two appends.
	for(unsigned short ArmourLocations = 0x00; ArmourLocations < 0x0B; ArmourLocations++)
	{
		//ds->t3242 range of 10 char values?
		if ((short)(signed char)seg3EDB->t3242[ArmourLocations] == (short)ArmourLocation) // Sol: CBW(key), compare full WORD argument
		{
			Append_Large_Text_To_Memory(&seg3092->DynamicStringVariable, seg3EDB->ArmourLocationText[ArmourLocations]); // Sol: copy to BYTE scratch DS:0012
			Append_Text_To_Memory(&seg3092->DynamicStringVariable, "."); // DS:3240 period suffix
			Combat_CombatMessageVerbosityFilter(&seg3092->DynamicStringVariable);
			ArmourLocations = 0x0B; //LOOP Escape
		}	
	}
}

// 1631:1BFE: WORD Combat_Return_bool_fn1631_1BFE(WORD actor, WORD target, WORD targetX, WORD targetY)
// Called from:
//      Combat_Computer_Control
//      Combat_Mechanics
// Sol: Summary: Check turning and path clearance.
// Sol: Outline: Build the proposed facing and movement footprint and test its intervening terrain and collision conditions.
unsigned short Combat_Return_bool_fn1631_1BFE(unsigned short ActorId, unsigned short TargetId,
	unsigned short TargetX, unsigned short TargetY)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol:1BFE..1DAA four WORD args, AX1 clear /0 tile-blocked. ActorId unused.
	unsigned short PathX = seg246C->CrescentHawk_MapPositionX; // SS:BP-4 local packed path position.
	unsigned short PathY = seg246C->CrescentHawk_MapPositionY; // BP-8.
	PosXY_OffsetGrid(PathX, PathY);
	Update_Cached_Map_Origin_1DF8(); // Sol: cache/view-origin side effects occur even on rental shortcut.
	if (seg3092->ArenaRentalMechMode != FALSE && TargetId == 13) // Sol:1C3D SECOND argument; special arena combatant slot13.
		return TRUE;
	unsigned short CacheIndex = seg246C->CachedMapOriginIndex + 0x96; // BP-10 numeric BYTE-cache index, not pointer.150=6*24+6 central path cell offset.
	short XParity = 1, YParity = PathY & 1; // BP-1C/-2.
	if ((PathX & 1) != 0)
	{
		++CacheIndex;
		XParity = 0; // Sol:1C6B inverted X parity; no invented Character_PosX local.
	}
	unsigned short Heading = Get_Target_Compass_Direction(PathX, PathY, TargetX, TargetY); // BP-12 WORD, including FFFF same-position sentinel.
	unsigned short ClearPath = TRUE; // BP-0E.
	unsigned short Tile = seg246C->CombatMap[CacheIndex]; // Sol:1C91 zero-extended BYTE.
	if ((short)seg3EDB->BlockingTileCodeThreshold <= (short)Tile)
		return FALSE; // Sol:1C9F signed comparison; starting tile must pass, even when origin=target.
	while (PathX != TargetX || PathY != TargetY)
	{
		unsigned short DesiredHeading = Get_Target_Compass_Direction(PathX, PathY, TargetX, TargetY);
		short Difference = (short)(DesiredHeading - Heading);
		if (Difference != 0)
		{
			Difference &= 7; // Sol:1D90 modulo8:1..4 turn+1,5..7 turn-1.
			Heading = (Heading + (Difference < 5 ? 1 : -1)) & 7;
		}
		short StepX = seg3EDB->CombatPathStepX[Heading];
		short StepY = seg3EDB->CombatPathStepY[Heading];
		PathX += StepX;
		if ((PathX & 0x80) != 0) PathX += seg3EDB->CombatPathBoundaryX[Heading];
		PathY += StepY;
		if ((PathY & 0x80) != 0) PathY += seg3EDB->CombatPathBoundaryY[Heading]; // Sol:1CBA..1CEB WORD packed-region crossing.
		if (StepX != 0)
		{
			XParity = (XParity + StepX) & 1;
			if (XParity == 0) CacheIndex += StepX; // Sol:1D08 column changes only on this parity transition.
		}
		if (StepY != 0)
		{
			YParity = (YParity + StepY) & 1;
			if (YParity == 0) CacheIndex += seg3EDB->CombatPathCacheRowDelta[Heading]; // Sol:1D28 row delta0/+24/-24; no division or pointer expression.
		}
		Tile = seg246C->CombatMap[CacheIndex];
		if ((short)seg3EDB->BlockingTileCodeThreshold <= (short)Tile)
		{
			PathX = TargetX;
			PathY = TargetY; // Sol:1D4B original forces local loop termination; does not move global actor/anchor.
			ClearPath = FALSE;
		}
	}
	return ClearPath; // Sol:1DA3 WORD result. No occupancy call, actor writes, budget or iteration/cache bounds guard in ASM.
}

// 1631:1DAB: void Combat_CombatMessageVerbosityFilter(Stack Eq_21 CombatMessage)
// Called from:
//      Combat_Mech_Eject_0A35
//      Combat_Critical_Mech_Damage_11AB
//      Return_bool_fn1631_16AB
//      Combat_Display_Text_From_Memory
//      Combat_Mechanics
//      Combat_AudioVisual_Effects
// Sol: Summary: Display a combat message if its verbosity is enabled.
// Sol: Outline: Check the combat-message setting before sending the supplied string to the renderer.
void Combat_CombatMessageVerbosityFilter(unsigned char far *CombatMessage)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	if (seg3EDB->CombatMessageVerbosity != FALSE)
		Display_Text_From_Memory(CombatMessage);
}

// 1631:1DCC: void GameSpeed_RateControl()
// Called from:
//      Combat_Mech_Eject_0A35
//      Return_bool_fn1631_16AB
//      Combat_Mechanics
// Sol: Summary: Apply the selected game-speed delay.
// Sol: Outline: Translate the speed setting and timing calibration into the original wait behaviour.
void GameSpeed_RateControl()
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: Settings 0..4 wait setting*12 vertical retraces; >=5 waits for a
	// Sol: keypress. Setting zero is no delay, not an implicit minimum.
	if ((short)seg3EDB->CombatSpeedSetting < 0x05) // Sol: signed JGE; legal menu values0..5
		Wait_For_N_Vertical_Retraces(seg3EDB->CombatSpeedSetting * 0x0C);
	else
		Keyboard_Get_ASCII_Hex_Input();
}

// 1631:1DF8: void Combat_CompassPos_1DF8(unsigned short PosX, unsigned short PosY, unsigned short CharacterPosX_Mech, unsigned short CharacterPosY_Mech)
// Called from:
//      Combat_AudioVisual_Effects
// Sol: Summary: Convert packed-world displacement to effect-screen coordinates.
// Sol: Outline: Step each packed axis toward the other position, applying boundary corrections and updating the shared coordinates around screen anchor26,12.
void Combat_CompassPos_1DF8(unsigned short PosX, unsigned short PosY, unsigned short CharacterPosX_Mech, unsigned short CharacterPosY_Mech)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: Packed-world displacement to screen-cell coordinates anchored at
	// Sol: (26,12). This updates E486/E488, does not return a compass heading.
	seg3092->CrescentHawk_CompassPositionX = 0x1A; //tE486 PosX
	seg3092->CrescentHawk_CompassPositionY = 0x0C;

	while (PosY > CharacterPosY_Mech)
	{
		PosY--;
		if ((PosY & Char_MostSignificantBit) != 0x00)
			PosY = PosY & 0xF07F;

		seg3092->CrescentHawk_CompassPositionY--;
	}

	while (PosY < CharacterPosY_Mech)
	{
		PosY++;
		if ((PosY & Char_MostSignificantBit) != 0x00)
			PosY += 0x0F80;
			
		seg3092->CrescentHawk_CompassPositionY++;
	}

	while (PosX > CharacterPosX_Mech)
	{	
		PosX--;
		if ((PosX & Char_MostSignificantBit) != 0x00)
			PosX &= 0x0F7F;

		seg3092->CrescentHawk_CompassPositionX--; //tE486 PosX
	}

	while (PosX < CharacterPosX_Mech)
	{	
		PosX++;

		if ((PosX & Char_MostSignificantBit) != 0x00) 
			PosX += 0x0080;
			
		seg3092->CrescentHawk_CompassPositionX++; //tE486 PosX
	}
}

// 1631:1EA2: Register word16 Combat_AudioVisual_1EA2(unsigned short PosX, unsigned short PosY)
// Called from:
//      Combat_AudioVisual_Effects
// Sol: Summary: Select an effect-direction octant from signed deltas.
// Sol: Outline: Compare signed delta magnitudes using native WORD negation and tie rules, then return octant zero to seven.
unsigned short Combat_AudioVisual_1EA2(short PosX, short PosY)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol: Reconstructed1EA2..1F08. Signed WORD deltas select octant, no audio.
	// Sol: NEG results are narrowed to WORD before signed comparison;8000
	// Sol: remains negative. Tie rules include(0,0)->6; no atan2 substitution.
	unsigned short Octant;
	if (PosX < 0)
	{
		if (PosY > 0)
		{
			Octant = 2;
			if ((short)-PosX <= PosY) return Octant;
		}
		else
		{
			Octant = 4;
			if ((short)-PosY <= (short)-PosX) return Octant;
		}
	}
	else if (PosY <= 0)
	{
		Octant = 6;
		if ((short)-PosY >= PosX) return Octant;
	}
	else
	{
		Octant = 0;
		if (PosY <= PosX) return Octant;
	}
	return Octant + 1;
}

// 1631:1F09: effects buffer FAR pointer -> restore focused world presentation
// Called from:
//      Combat_AudioVisual_Effects
// Sol: Summary: Prepare effect rendering at a mech position.
// Sol: Outline: Read the supplied position data, update the view anchor, and rebuild the working graphics.
void Combat_AudioVisual_MechPositioning_And_GraphicsMemory_1F09(unsigned char far *dwArg04)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol:1F09..1F72: forward real FAR pointer plus WORD1 to207F:1ECE.
	// Sol: Focus Jason's assigned mech, otherwise on-foot combatant4; original
	// Sol: assignment test is signed BYTE JGE and selected value is CBW to WORD.
	Combat_1ECE(dwArg04, TRUE);
	unsigned short FocusCombatantId = Friendly_Infantry_Combatant_Range_First;
	if ((signed char)seg3092->Infantry[Jason].Piloting < Character_OnFoot)
		FocusCombatantId = (unsigned short)(short)(signed char)seg3092->Infantry[Jason].Piloting; // DS:C620
	Move_Map_View_To_Packed_Position_17BB(
		seg3092->CombatantPackedX[FocusCombatantId],
		seg3092->CombatantPackedY[FocusCombatantId]);
	Update_Animated_Map_Tiles_240B();
	Copy_Data_To_GraphicsMemory();
	Draw_Menu_MultiSelect_0E4B();
}

// 1631:1F73: effects sprite draw wrapper; original arguments are three WORDs
// Called from:
//      Combat_AudioVisual_Effects
// Sol: Summary: Draw a combat sprite at the requested position.
// Sol: Outline: Resolve its sprite pointer and dispatch the retained EGA drawing path.
void Draw_Combat_Sprites_1F73(unsigned short SpriteId, unsigned short PosX, unsigned short PosY)
{
	// Sol: Fresh whole-body ASM comparison2026-09-17: locally matched under
	// Sol: native WORD/FAR and shared-call contracts; see systematic segment report.
	// Sol:1F73..1FDE loads ONE FAR pointer: offset39FA+id*4, segment39FC+id*4.
	// Sol: EGA branch4FBA==2 pushes(dest AC00:0000, source16:16, X WORD, Y WORD).
	// Sol: User intentionally removed other adapters; retain EGA-only pipeline.
	// Sol: Original non-EGA branch called207F:28EB with dest246C:244B and
	// Sol: identical source/X/Y. Not restored; detailed evidence in segment MD.
	// Sol: Shared0377 now has signed WORD X/Y and recovered clipping/plane flow;
	// Sol: see207F graphics checkpoint, including original early-cleanup BUG-019.
	DrawCall_EGA_CharacterPos_0377((unsigned long)EGA_Buffer << 16, // encoded DOS FAR AC00:0000, not segment-only AC00
		seg3092->CombatSpritePointers[SpriteId].Offset,
		seg3092->CombatSpritePointers[SpriteId].Segment,
		PosX, PosY);
}

// 1631:1FDF: void Display_Text_CBill_Balance()
// Called from:
//      Main_Game_Loop
//      Draw_Health_and_C_Bills_Sidebar
//      Execute_Bld_Bytecode_01C0
//      Mechlube_Repair_Mech
//      Mechlube_Upgrade_Mech
//      Mechlube_Buy_Ammo
//      Citadel_Building_Dialogs
// Sol: Summary: Display the party's current cash.
// Sol: Outline: Format the multiword C-bill balance and print it in the selected panel.
void Display_Text_CBill_Balance()
{
	// Sol: Correction from expanded EXE:3EDB:55C8 stores2892, relocated3092,
	// Sol: so final WORD37FE restores EGATextColour. Earlier3EDB claim was wrong.
	// Sol: Native32DA starts06/0F, then C-Bills: and endsCR, not spaces.
	unsigned short SavedMenuLayout = seg3092->CurrentMenuLayoutIndex;
	unsigned char far *BalanceText = &seg3092->DynamicStringVariable; //DS:0012 byte scratch storage
	Menu_Memory_Variables(0x03);
	seg3092->HorizontalLine_Offset = 0x00; //w3748 - Horizontal Line Offset for Text
	seg3092->VerticalLine_Offset = 0x09;	//w374E - Vertical Line Offset for Text

	Display_Text_From_Memory("\006\017C-Bills:\r"); // Memory ref: [3EDB:32DA]
	Set_Text_Colour_Bright_Green_28A2();

	//Cbill Balance D370 + D372 
	// Sol: Formatter 207F:3BD2 receives an explicit WORD radix 10 after
	// Sol: the DWORD balance and FAR destination; restored shared helper contract.
	CBill_Text_Formatting(seg3092->CBills, BalanceText, 10);

	unsigned short BalanceTextLength = Loop_Until_TextPtr_Null(BalanceText);
	// Sol: Right-pad decimal balance to ten characters, then terminate.
	while ((short)BalanceTextLength < 0x0A) // Sol: signed JL; minimum display width10, not truncation limit
	{
		BalanceText[BalanceTextLength] = 0x20;
		BalanceTextLength++;
	}

	BalanceText[BalanceTextLength] = 0x00;
	Display_Text_From_Memory(BalanceText);
	seg3092->EGATextColour = EGA_BrightWhite; //w37FE - Text Colour in EGA WeaponId = 0x0F White
	Menu_Memory_Variables(SavedMenuLayout);
}
