// BTECH_0FDC.c
// Generated by decompiling BTECH.EXE
// using Reko decompiler version 0.11.2.0.

#include "BTECH.h"

// 0FDC:0008: void Interact_with_BLD(unsigned short requestedBuildingId)
// Called from:
//      Map_Interactables_Building_Or_Items
//      Interact_with_BLD
//      Draw_STARLEAG_ICN_AND_Game_Logic
//      StarLeague_Cache_PhoenixHawk
//      HPGTransmitter
//      StarLeague_Map_Room
// Sol: Summary: Enter a building's scripted interaction.
// Sol: Outline: Resolve the building script, load it and any entry animation, execute it, then restore the game display.
void Interact_with_BLD(unsigned short RequestedBuildingId)
{
	// TODO Sol: Fresh ASM audit: 002D uses signed JGE for the ID gate; 00A6
	// TODO Sol: uses CBW for the scene ID. Current unsigned promotions differ.
	// Sol: Whole-body comparison: docs/phase4/BTECH_0FDC_SYSTEMATIC_ASM_AUDIT.md.
	seg3092->BldInteractionFlag = TRUE;
	// Sol: Preserve the original building ID for workflows such as Mech-Lube
	// Sol: exit-coordinate restoration. The local may then become a map-specific
	// Sol: alternate BLD ID.
	seg3092->EnteredBuildingId = RequestedBuildingId;
	unsigned short BldFileId = RequestedBuildingId;

	if (BldFileId != BLD_VIEWDISK && BldFileId < BLD_ENDMECH)
	{
		// TODO Sol: Keep future callers bounded to the 16 map-loaded bytes. The
		// TODO Sol: comparison admits 10h/11h and 13h..15h, but every verified shipped caller
		// TODO Sol: supplies map slots 0..0Bh, VIEWDISK, or IDs >= ENDMECH.
		// Sol: CBW sign-extends the raw byte exactly as a signed 16-bit C `char`
		// Sol: promotion would; normal BLD IDs remain in the positive range.
		BldFileId = (unsigned short)(signed char)
			seg3092->AlternativeBldByBuildingId[BldFileId];
	}

	Select_Game_Disk_And_Drive_28CC(1);

	// Sol: The shipped EXE initializes a WORD proceed flag to TRUE, compares the
	// Sol: resolved ID with zero, then unconditionally jumps over 0058..0084.
	// Sol: Those dormant bytes would check the D320 copyright-quiz cooldown,
	// Sol: bypass the quiz for scripted/demo input, call Copyright_Check_Mech_Quiz,
	// Sol: and clear the proceed flag on a nonzero (failed) result. This is the
	// Sol: disabled mech-diagram copyright check, not an unexplained `if (true)`.

	Load_And_Decode_Indexed_BLD_1D30(BldFileId);

	if (seg3EDB->EnterBuildingAnimations[BldFileId] != 0x00)
		Display_Animation_Scene(seg3EDB->EnterBuildingAnimations[BldFileId],
			AnimationPlayback_CallerOwnsRedraw);

	Execute_Bld_Bytecode_01C0(&seg3092->BTStatsORBLDMemoryLocation);
	Citadel_Building_Dialogs(0x0E);

	// Sol: Leaving the Garage with a holoviewer and at least one party member
	// Sol: automatically chains into VIEWDISK the first time only.
	if (seg3092->Bool_HasViewedHolodisk == FALSE
	 && BldFileId == BLD_GARAGE
	 && seg3092->Bool_HasHoloviewer != FALSE
	 && seg3092->Party_NumOfMembers != 0x00)
	{
		Menu_Memory_Variables(0x06);
		Draw_Top_Graphic_Sidebar();
		Display_Text_From_Memory("When you get outside, you decide to use your new "); // DS:1384
		Display_Text_From_Memory_ScreenRetrace_KeyboardInput(
			"holoviewer to watch your father's holodisk."); // DS:13B6
		Keyboard_Get_ASCII_Hex_Input();
		Interact_with_BLD(BLD_VIEWDISK);
		seg2FE8->Viewed_Holodisk = 0x0C;
	}

	// Sol: BARRACK2 also chains directly into the holodisk BLD whenever the
	// Sol: party is nonempty; unlike the Garage branch it does not test inventory
	// Sol: or the persistent already-viewed flag.
	if (BldFileId == BLD_BARRACKS2 && seg3092->Party_NumOfMembers != 0x00)
	{
		Interact_with_BLD(BLD_VIEWDISK);
		seg2FE8->Viewed_Holodisk = 0x0C;
	}

	Menu_Memory_Variables(0x04);
	Draw_Top_Graphic_Sidebar();
	Menu_Memory_Variables(0x03);
	Draw_Health_and_C_Bills_Sidebar(TRUE);

	// Sol: The assembly compares with 14h (ENTRANCE), not 0Eh (MAYOR). D118 is
	// Sol: fog index 060Ch, and a 10h stride clears byte-column 12 in rows 96..103.
	if (BldFileId == BLD_ENTRANCE && seg3092->EntranceBldState != FALSE)
	{
		for (unsigned short FogRow = 0x60; FogRow < 0x68; FogRow++)
			seg3092->Map_FogOfWar_Visibility[(FogRow * 0x10) + 0x0C] = 0x00;

		Draw_STARLEAG_ICN_AND_Game_Logic();
	}
}

// 0FDC:01C0: Execute the decoded BLD bytecode payload.
// Called from:
//      Interact_with_BLD
// Sol: Summary: Run a building dialogue script.
// Sol: Outline: Walk BLD bytes and dispatch text, menus, state tests, branches and native action calls.
void Execute_Bld_Bytecode_01C0(unsigned char far *BldPayload)
{
	// TODO Sol: Fresh whole-body ASM audit found missing operand CBW conversions
	// TODO Sol: (call IDs, state indices/branch values, skill index/minimum/value).
	// TODO Sol: Infantry has named skill bytes, not the Skill[] view used below.
	// TODO Sol: Preserve native WORD/FAR offset wrap and 32-bit C-bill arithmetic.
	// Sol: All 28 opcode paths compared; see BTECH_0FDC_SYSTEMATIC_ASM_AUDIT.md.
	unsigned short Cursor = 0x0000;
	unsigned short ExitInterpreter = FALSE;

	// Sol: The original local cursor and exit flag are WORDs. Reko incorrectly
	// Sol: converted the far byte pointer and cursor into 32-bit array arithmetic.
	while (ExitInterpreter == FALSE)
	{
		unsigned short Opcode = BldPayload[Cursor++];

		// Sol: The assembly subtracts E4h and dispatches only indices 0..1Bh.
		// Sol: Any other byte is ignored as a one-byte no-op at this level.
		if (Opcode < BLD_OPCODE_PLAY_SOUND)
			continue;

		switch (Opcode)
		{
		case BLD_OPCODE_PLAY_SOUND:
			Play_Sound_If_Enabled(BldPayload[Cursor++]); // 0800:19BF
			break;

		case BLD_OPCODE_ADD_C_BILLS:
		{
			signed long Amount = (signed short)Read_Bld_Immediate_Word_19F6(&BldPayload[Cursor]);
			Cursor += 0x0002;
			seg3092->CBills += Amount;
			Display_Text_CBill_Balance(); // 1631:1FDF
			break;
		}

		case BLD_OPCODE_SET_MAP_POSITION:
			seg246C->CrescentHawk_MapPositionX = Read_Bld_Immediate_Word_19F6(&BldPayload[Cursor]);
			seg246C->CrescentHawk_MapPositionY = Read_Bld_Immediate_Word_19F6(&BldPayload[Cursor + 0x0002]);
			Cursor += 0x0004;
			break;

		case BLD_OPCODE_BRANCH_IF_X_EQUALS:
		{
			unsigned short ExpectedX = Read_Bld_Immediate_Word_19F6(&BldPayload[Cursor]);
			Cursor += 0x0002;
			if (seg246C->CrescentHawk_MapPositionX == ExpectedX)
				Cursor = Read_Bld_Target_05F7(&BldPayload[Cursor]);
			else
				Cursor += 0x0002;
			break;
		}

		case BLD_OPCODE_BRANCH_IF_RANDOM_MASK:
		{
			unsigned char Mask = BldPayload[Cursor++];
			if ((Rand_0x00_to_0xFF() & Mask) != FALSE) // 207F:0BC0
				Cursor = Read_Bld_Target_05F7(&BldPayload[Cursor]);
			else
				Cursor += 0x0002;
			break;
		}

		case BLD_OPCODE_RECRUIT_CRESCENT_HAWK:
			Recruit_Crescent_Hawk_Agent(BldPayload[Cursor++]);
			break;

		case BLD_OPCODE_CONDITIONAL_SCENE_ACTION:
		{
			unsigned char SceneId = BldPayload[Cursor++];
			unsigned char Argument = BldPayload[Cursor++];
			if (seg3092->DisableInput == FALSE)
				Display_Animation_Scene(SceneId, Argument); // 0800:48B7
			break;
		}

		case BLD_OPCODE_BRANCH_IF_FIELD_SURGERY_KIT:
			if (seg3092->Purchased_FieldSurgeryKit != FALSE)
				Cursor = Read_Bld_Target_05F7(&BldPayload[Cursor]);
			else
				Cursor += 0x0002;
			break;

		case BLD_OPCODE_BRANCH_IF_MEDKIT:
			if (seg3092->Purchased_Medkit != FALSE)
				Cursor = Read_Bld_Target_05F7(&BldPayload[Cursor]);
			else
				Cursor += 0x0002;
			break;

		case BLD_OPCODE_BRANCH_IF_PARTY_SKILL:
		{
			unsigned char SkillIndex = BldPayload[Cursor++];
			unsigned char Minimum = BldPayload[Cursor++];
			unsigned short PartyMemberId;
			unsigned short PartyHasSkill = FALSE;

			for (PartyMemberId = 0x0000; PartyMemberId < 0x0008; PartyMemberId++)
			{
				if (seg3092->Infantry[PartyMemberId].Name != Character_Dead
				 && seg3092->Infantry[PartyMemberId].Skill[SkillIndex] >= Minimum)
					PartyHasSkill = TRUE;
			}

			if (PartyHasSkill != FALSE)
				Cursor = Read_Bld_Target_05F7(&BldPayload[Cursor]);
			else
				Cursor += 0x0002;
			break;
		}

		case BLD_OPCODE_SUBTRACT_C_BILLS:
		{
			signed long Amount = (signed short)Read_Bld_Immediate_Word_19F6(&BldPayload[Cursor]);
			Cursor += 0x0002;
			if (seg3092->CBills >= (unsigned long)Amount)
				seg3092->CBills -= Amount;
			else
				seg3092->CBills = 0x00000000L;
			Display_Text_CBill_Balance(); // 1631:1FDF
			break;
		}

		case BLD_OPCODE_BRANCH_IF_C_BILLS_AT_LEAST:
		{
			signed long Amount = (signed short)Read_Bld_Immediate_Word_19F6(&BldPayload[Cursor]);
			Cursor += 0x0002;
			if (seg3092->CBills >= (unsigned long)Amount)
				Cursor = Read_Bld_Target_05F7(&BldPayload[Cursor]);
			else
				Cursor += 0x0002;
			break;
		}

		case BLD_OPCODE_SET_TEXT_LAYOUT:
			// Sol: CBW sign-extends each byte before storing the WORD globals.
			seg3092->HorizontalLine_Offset = (signed char)BldPayload[Cursor++];
			seg3092->VerticalLine_Offset = (signed char)BldPayload[Cursor++];
			break;

		case BLD_OPCODE_ADD_STATE_BYTE:
		{
			unsigned char StateIndex = BldPayload[Cursor++];
			seg3092->PersistentBldState[StateIndex] += BldPayload[Cursor++];
			break;
		}

		case BLD_OPCODE_TIMED_WAIT_INPUT_CHECK:
			Wait_For_50Hz_Then_Check_Input(); // 1F3D:086A
			break;

		case BLD_OPCODE_BRANCH_STATE_TABLE:
		{
			unsigned char StateIndex = BldPayload[Cursor++];
			unsigned short TableIndex = seg3092->PersistentBldState[StateIndex];
			Cursor = Read_Bld_Target_05F7(&BldPayload[Cursor + (TableIndex << 0x01)]);
			break;
		}

		case BLD_OPCODE_SET_STATE_BYTE:
		{
			// Sol:02E9 writes BYTE3092:D30C+index. CITADEL payload0F59/0F60/0F67
			// Sol: uses index08 to select D314 skill0/1/2;0F75 uses index15 to set D321 cooldownFF.
			// Sol: TRAINING payload0A89 similarly sets index14 (shared mission/quiz D320) toFF.
			// Sol: HOSPITAL02F2 clears index29=D335 BEFORE injury/fee checks; hospital bypasses recovery gate.
			unsigned char StateIndex = BldPayload[Cursor++];
			seg3092->PersistentBldState[StateIndex] = BldPayload[Cursor++];
			break;
		}

		case BLD_OPCODE_CALL_ACTION_DISPATCHER:
			Citadel_Building_Dialogs(BldPayload[Cursor++]); // 1CD3:0004
			break;

		case BLD_OPCODE_PROMPT_YES_NO_BRANCH:
			if (Prompt_Yes_No(0x0001) != FALSE)
				Cursor = Read_Bld_Target_05F7(&BldPayload[Cursor]);
			else
				Cursor += 0x0002;
			break;

		case BLD_OPCODE_BRANCH_IF_STATE_NONZERO:
		{
			// Sol:CITADEL0F6C tests index09 (D315 immediate purchase result), then
			// Sol:0E6D tests index15 (D321 course cooldown). Result flag and timer are separate bytes.
			unsigned char StateIndex = BldPayload[Cursor++];
			if (seg3092->PersistentBldState[StateIndex] != FALSE)
				Cursor = Read_Bld_Target_05F7(&BldPayload[Cursor]);
			else
				Cursor += 0x0002;
			break;
		}

		case BLD_OPCODE_BRANCH:
			Cursor = Read_Bld_Target_05F7(&BldPayload[Cursor]);
			break;

		case BLD_OPCODE_MENU_BRANCH_TABLE:
		{
			unsigned char MenuId = BldPayload[Cursor++];
			unsigned short Selection = Display_Menu_Choices_And_Check(MenuId);
			Cursor = Read_Bld_Target_05F7(&BldPayload[Cursor + (Selection << 0x01)]);
			break;
		}

		case BLD_OPCODE_DRAW_MENU_BORDER:
			Draw_Menu_Border(BldPayload[Cursor++]); // 1E56:0004
			break;

		case BLD_OPCODE_WAIT_FOR_KEY:
			Keyboard_Get_ASCII_Hex_Input(); // 1F3D:0259
			break;

		case BLD_OPCODE_DISPLAY_TEXT:
		{
			unsigned char far *InlineText = &BldPayload[Cursor];
			Display_Text_From_Memory(InlineText); // 1E56:03F5
			// Sol: 207F:3B9E returns strlen in AX despite Reko declaring void.
			Cursor += Loop_Until_TextPtr_Null(InlineText) + 0x0001;
			break;
		}

		case BLD_OPCODE_REDRAW_SIDEBAR:
			Draw_Top_Graphic_Sidebar(); // 1E56:0388
			break;

		case BLD_OPCODE_APPLY_LAYOUT:
			Menu_Memory_Variables(BldPayload[Cursor++]); // 1E56:0281
			break;

		case BLD_OPCODE_EXIT:
			ExitInterpreter = TRUE;
			break;
		}
	}
}

// 0FDC:05F7: Read a little-endian absolute BLD payload target.
// Called from:
//      Execute_Bld_Bytecode_01C0
// Sol: Summary: Read a BLD branch destination.
// Sol: Outline: Combine two unsigned bytes into the native little-endian WORD target.
unsigned short Read_Bld_Target_05F7(unsigned char far *TargetBytes)
{
	// Sol: Fresh whole-body ASM match under native WORD/FAR16 offset-only wrap.
	unsigned short LowByte = TargetBytes[0x0000];
	unsigned short HighByte = TargetBytes[0x0001];

	// Sol: Both source bytes are explicitly zero-extended. The previous return
	// Sol: added adjacent elements without shifting the high byte and was false.
	return LowByte | (HighByte << 0x0008);
}

// 0FDC:0629: Run a training-centre mission or the jail escape mission.
// Called from:
//      Run_Jailbreak_Mission_And_Award_Stinger_152F
//      Citadel_Building_Dialogs
// Sol: Summary: Run a training or jailbreak mission.
// Sol: Outline: Set up the objective, process movement and world updates, resolve completion, then record the outcome and clean up.
void Mech_Mission_0629(unsigned short MissionNumber)
{
	// TODO Sol: Fresh ASM audit: Name is a 16-byte array (compare Name[0]);
	// TODO Sol: Skill.Gunnery/Piloting are not declared Infantry members. The
	// TODO Sol: native bytes are C61B/C61C. Preserve the native dialogue literals
	// TODO Sol: and renderer controls listed in BTECH_0FDC_SYSTEMATIC_ASM_AUDIT.md.
	// Sol: These are all WORD locals in the original stack frame. Reko's byte and
	// Sol: host-sized `int` guesses lose both wrap behaviour and signed tests.
	unsigned short MissionTimer;
	unsigned short RubbleCoordinateIndex;
	unsigned short SavedObjectiveTile;
	unsigned short RubbleTileIndex;
	unsigned short JailDistinctMechAttempts;
	unsigned short JailMechAttempted[4];
	unsigned short PrematureReturnWarningShown = FALSE;
	unsigned short MissionObjectiveResolved = FALSE;

	if (MissionNumber <= Mission09_JailBreak)
	{
		switch (MissionNumber)
		{
		case Mission00_SouthEastCorner:
			SavedObjectiveTile =
				seg246C->MapTile[CitadelMission00TemporaryTileIndex]; // 246C:200A
			seg246C->MapTile[CitadelMission00TemporaryTileIndex] = 0x00;
			MissionTimer = 0x0000;
			Character_Movement_On_Map(FALSE); // 0800:218F
			MissionObjectiveResolved = FALSE;
			break;

		case Mission01_RubblePickUp:
		{
			RubbleCoordinateIndex = Rand_0x00_to_0xFF() & 0x0007;
			unsigned short RubbleX =
				seg3EDB->TrainingRubbleTargetX[RubbleCoordinateIndex];
			unsigned short RubbleY =
				seg3EDB->TrainingRubbleTargetY[RubbleCoordinateIndex];

			// Sol: The MTP tile payload is arranged as 16x16 blocks of 8x8
			// Sol: tiles. This converts the selected local X/Y to that block-major
			// Sol: byte index; it is not ordinary row-major Y*128+X storage.
			RubbleTileIndex =
				((RubbleY & 0x78) << 0x06)
				+ ((RubbleY & 0x07) << 0x03)
				+ ((RubbleX & 0x78) << 0x03)
				+ (RubbleX & 0x07);

			SavedObjectiveTile = seg246C->MapTile[RubbleTileIndex];
			seg246C->MapTile[RubbleTileIndex] = MapTile_Rubble;

			if (seg3092->Mechs[Character_Jason].Name == KEY_L) //tC724 Checking for ASCII L for Locust
			{
				Draw_Message_Box();
				Display_Text_From_Memory_ScreenRetrace_KeyboardInput("Other cadets snicker as you leave the training center"); //Memory ref: [3EDB:1434]
				Keyboard_Get_ASCII_Hex_Input();
			}
			Character_Movement_On_Map(FALSE); // 0800:218F
			MissionObjectiveResolved = FALSE;
			break;
		}

		case Mission02_DisabledLocust:
			Mission_GenerateEnemies(0x01, 0x00);

			// Sol: BTSTATS confirms index0 (+24) packs LEFT arm/leg actuator nibbles;
			// Sol: index1 (+25) packs RIGHT arm/leg. These writes disable both sides.
			// TODO Sol: Individual joint-bit meanings still require critical-damage mapping.
			seg3092->EnemyMech00.CurrentActuators[1] = FALSE; //bC93D - CurrentActuators[1]
			seg3092->EnemyMech00.CurrentActuators[0] = FALSE; //bC93C - CurrentActuators[0]
		
			//Reduce mech ammo content to Zero
			//Rewritten to use slots directly vs offset
			for(int Ammo_Slots = 0; Ammo_Slots < 10; Ammo_Slots++)
			{
				seg3092->EnemyMech00.CurrentAmmo[Ammo_Slots] = Ammo_Empty; //C918 - Enemy Mech 00		
			}  

			seg3092->EnemyMech00.JumpMove = FALSE; //bC94A - JumpMove
			seg3092->EnemyMech00.WalkMove = FALSE; //bC949 - WalkMove
			Combat_Parent_000A(0x01);
			Restore_Mission_Map_View_After_Combat();
			MissionObjectiveResolved = TRUE;
			break;

		case Mission03_InfantryRobots:
			Mission_GenerateEnemies(0x00, (Rand_0x00_to_0xFF() & 0x03) + 0x03);
			Combat_Parent_000A(0x01);
			Restore_Mission_Map_View_After_Combat();
			MissionObjectiveResolved = TRUE;
			break;

		case Mission04_Locust_NoComputer:
			seg3092->Disable_Computer_Control = TRUE;
			// Sol: Intentional fall-through into the common missions 4..7 setup.

		case Mission05_TwoLocust:
		case Mission06_ThreeLocust:
		case Mission07_KuritaJenners:
			// Sol: Mission 6 has a 50% Kurita interruption; mission 7 forces it.
			if (MissionNumber == Mission06_ThreeLocust && (Rand_0x00_to_0xFF() & 0x01) != FALSE)
				seg3092->Kurita_AttackFlag = TRUE;

			if (MissionNumber == Mission07_KuritaJenners)
				seg3092->Kurita_AttackFlag = TRUE;

			if (seg3092->Kurita_AttackFlag != FALSE)
			{
				// Sol: Replace the final sixteen map bytes during the attack.
				unsigned short TileId;
				for (TileId = 0x0FF0; TileId < 0x1000; TileId++)
					seg246C->MapTile[TileId] = MapTile_KuritaAttack;
			}

			Mission_GenerateEnemies(MissionNumber - 0x03, 0x00);
			Combat_Parent_000A(0x01);
			Restore_Mission_Map_View_After_Combat();
			seg3092->Disable_Computer_Control = FALSE;
			MissionObjectiveResolved = TRUE;
			break;

		case Mission08:
			Mission_GenerateEnemies(0x81, 0x00);
			Combat_Parent_000A(0x02);
			MissionObjectiveResolved = TRUE;
			break;

		case Mission09_JailBreak:
			seg3092->DrawJailMissionParkedMechs = TRUE;
			PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX,
				seg246C->CrescentHawk_MapPositionY);

			Copy_Data_To_GraphicsMemory();
			Draw_Infantry_And_Mechs();
			EGA_DrawBox_Wrapper();

			MissionObjectiveResolved = FALSE;
			MissionTimer = 0x0000;

			// Sol: Four WORD flags at BP-0C..BP-06 remember which parked
			// Sol: jailbreak mechs Jason has already attempted to start.
			for (unsigned short MechId = 0x0000; MechId < 0x0004; MechId++)
				JailMechAttempted[MechId] = FALSE;

			JailDistinctMechAttempts = 0x0000;
			break;
		}
	}
	// Sol: BP-10 is a general loop-exit latch. The global Kurita flag only
	// Sol: supplies its initial value; mission completion and jailbreak paths
	// Sol: also set this local without changing 3092:3772.
	unsigned short ExitMissionLoop = seg3092->Kurita_AttackFlag;

	if (MissionNumber == Mission08)
		ExitMissionLoop = TRUE;

	// Sol: Signed WORD countdown at BP-1E. Starting at zero makes the first idle
	// Sol: iteration decrement to -1 and perform a world redraw immediately.
	signed short MissionUpdateCountdown = 0x0000;
	while (ExitMissionLoop == FALSE)
	{
		// Sol: Packed-position gate for returning to the training-centre hangar.
		if (seg246C->CrescentHawk_MapPositionX <= CitadelMechHangerX
		 && seg246C->CrescentHawk_MapPositionY >= CitadelMechHangerMinY
		 && seg246C->CrescentHawk_MapPositionY <= CitadelMechHangerMaxY)
		{
			if (MissionObjectiveResolved != FALSE)
				ExitMissionLoop = TRUE;
			else
			{
				if (PrematureReturnWarningShown == FALSE)
				{
					Draw_Message_Box();
					Display_Text_From_Memory(
						"Don't Come back here until you complete your mission!"); // DS:146B
					Wait_For_50Hz_Then_Check_Input();
					Keyboard_Get_ASCII_Hex_Input();
				}
				PrematureReturnWarningShown = TRUE;
			}
		}

		if (ExitMissionLoop != FALSE)
			continue;

		unsigned short RunWorldUpdate = FALSE;
		if (Pending_Input() != FALSE)
		{
			unsigned short ASCII = Keyboard_Get_ASCII_Hex_Input();
			unsigned short MovementCommand = Keyboard_Convert_To_MoveCommands(ASCII);
			Drain_Pending_Keyboard_Input_2A2B();
			Update_Friendly_Movement_Animations_231D(MovementCommand);
			Character_Movement_On_Map(MovementCommand);
			RunWorldUpdate = TRUE;
		}
		else
		{
			Wait_For_N_Vertical_Retraces(0x0001);
			MissionUpdateCountdown--;
			if (MissionUpdateCountdown < 0x0000)
				RunWorldUpdate = TRUE;
		}

		if (RunWorldUpdate == FALSE)
			continue;

		MissionUpdateCountdown = 0x000A;
		Update_Animated_Map_Tiles_240B();
		seg3EDB->MissionNpcUpdatePhase++;
		if (seg3EDB->MissionNpcUpdatePhase == 0x0001)
			Update_Roaming_Map_Npcs_24C2();

		seg3EDB->MissionNpcUpdatePhase &= 0x0003;
		Copy_Data_To_GraphicsMemory();
		Draw_Infantry_And_Mechs();
		EGA_DrawBox_Wrapper();

		if (MissionNumber == Mission00_SouthEastCorner)
		{
			MissionTimer++;

			// Sol: MOV AL / CBW / SAR AX,3 makes this a signed-byte value
			// Sol: divided arithmetically by eight, then added to the WORD timer.
			if (seg3092->TerrainOverlapRows[0] != 0x00)
				MissionTimer +=
					((signed short)(signed char)seg3092->TerrainOverlapRows[0]) >> 0x03;

			if (seg246C->CrescentHawk_MapPositionX >= TrainingMission00SoutheastTargetX
			 && seg246C->CrescentHawk_MapPositionY >= TrainingMission00SoutheastTargetY
			 && MissionObjectiveResolved == FALSE)
			{
				MissionObjectiveResolved++;
				Draw_Message_Box();
				// Sol: This wrapper displays the string and performs the 50 Hz wait;
				// Sol: the following call is the separate blocking key read.
				Display_Text_From_Memory_ScreenRetrace_KeyboardInput(
					"You've made it to the southeast corner. Now get back to the training center!"); // DS:14A1
				Keyboard_Get_ASCII_Hex_Input();
			}

			continue;
		}

		if (MissionNumber == Mission01_RubblePickUp)
		{
			signed short PlayerObjectiveGridX =
				(seg246C->CrescentHawk_MapPositionX & 0x007F) >> 0x01;
			signed short PlayerObjectiveGridY =
				(seg246C->CrescentHawk_MapPositionY & 0x007F) >> 0x01;
			signed short RubbleX =
				seg3EDB->TrainingRubbleTargetX[RubbleCoordinateIndex];
			signed short RubbleY =
				seg3EDB->TrainingRubbleTargetY[RubbleCoordinateIndex];

			// Sol: JGE/JLE are signed comparisons. Interaction is permitted from
			// Sol: either X=RubbleX-1 or X=RubbleX, exactly one row south.
			if (PlayerObjectiveGridX < RubbleX - 0x0001
			 || PlayerObjectiveGridX > RubbleX
			 || PlayerObjectiveGridY != RubbleY + 0x0001
			 || MissionObjectiveResolved != FALSE)
				continue;

			MissionObjectiveResolved++;
			Draw_Message_Box();
			if (seg3092->Mechs[Character_Jason].Name == KEY_L)
				Display_Text_From_Memory(
					"You realise your Locust has no hands and can't pick it up"); // DS:14EF
			else
			{
				Display_Text_From_Memory(
					"You use your 'Mech's hands to retrieve the rubble"); // DS:152A
				seg246C->MapTile[RubbleTileIndex] = SavedObjectiveTile;
			}
			Wait_For_50Hz_Then_Check_Input();
			Keyboard_Get_ASCII_Hex_Input();
			continue;
		}
		if (MissionNumber == Mission09_JailBreak)
		{
			// Sol: 0FDC:0AA8-0AE1 compares the timer's old value and increments
			// Sol: the stored WORD before branching. From a reset value of zero,
			// Sol: combat therefore occurs on the 81st processed world update.
			unsigned short EncounterTimerBeforeIncrement = MissionTimer++;
			if ((signed short)EncounterTimerBeforeIncrement >= 0x0050)
			{
				Mission_GenerateEnemies(0x00, 0x88);
				Combat_Parent_000A(0x03);
				MissionTimer = 0x0000;
				if (seg3EDB->Bool_MainCharactersAlive == FALSE) //3EDB:014A
				{
					ExitMissionLoop = TRUE;
					MissionObjectiveResolved = TRUE;
				}
			}

			// Sol: The four rendered 'Mechs stand at X=0D13+4n, Y=702C.
			// Sol: Jason activates one from the adjacent tile X=0D14+4n, Y=702D.
			if (seg3EDB->Bool_MainCharactersAlive != FALSE //3EDB:014A
			 && seg246C->CrescentHawk_MapPositionY == JailParkedMechInteractionY) //246C:A44D
			{
				for (unsigned short JailMechId = 0x0000; JailMechId < 0x0004; ++JailMechId)
				{
					unsigned short InteractionX =
						JailParkedMechInteractionFirstX + JailMechId * JailParkedMechSpacing;
					if (InteractionX == seg246C->CrescentHawk_MapPositionX) //246C:A44B
					{
						if (JailMechAttempted[JailMechId] == FALSE)
						{
							// Sol: This WORD array prevents repeatedly testing one machine
							// Sol: from advancing the distinct-attempt counter.
							JailMechAttempted[JailMechId] = TRUE;
							Menu_Memory_Variables(0x06);
							Draw_Top_Graphic_Sidebar();
							Draw_Menu_Border(0x00);

							Display_Text_From_Memory("You quickly scramble up the boarding ladders of this Mech"); //3EDB:155D
							Display_Text_From_Memory(" hoping that it will function when you get to the cockpit"); //3EDB:159A
							Wait_For_50Hz_Then_Check_Input();
							Keyboard_Get_ASCII_Hex_Input();
							Display_Text_From_Memory("You flip the activation switch..."); //3EDB:15D4

							// Sol: 0FDC:0B96 loads the old counter, increments the stored
							// Sol: WORD, then compares the old value with two. Consequently
							// Sol: attempts one and two fail; the third distinct 'Mech starts.
							unsigned short AttemptsBeforeThis = JailDistinctMechAttempts++;
							if (AttemptsBeforeThis != 0x0002)
							{
								Play_Failed_Mech_Startup_Scene_16B2();
								Menu_Memory_Variables(0x06);
								Display_Text_From_Memory_ScreenRetrace_KeyboardInput("but this 'Mech refuses  to start."); //3EDB:1611
							}
							else
							{
								Display_Animation_Scene(AnimationO00_MechStartUp, AnimationPlayback_RestoreGameView);
								Menu_Memory_Variables(0x06);
								Display_Text_From_Memory_ScreenRetrace_KeyboardInput("and the 'Mech starts up!"); //3EDB:15F8
								MissionObjectiveResolved = TRUE;
								ExitMissionLoop = TRUE;
							}
							// Sol: The text/wait wrapper above does not consume this key.
							Keyboard_Get_ASCII_Hex_Input();
						}
					}
				}
			}
		}
	}

	// Sol: 0FDC:0BF2-0D1C computes the persistent training outcome. Missions
	// Sol: 8 and 9 have no pass test and leave this byte clear.
	seg3092->Bool_TrainingMissionPassed = FALSE; //3092:D30D
	if (MissionNumber != Mission00_SouthEastCorner)
	{
		if (MissionNumber != Mission01_RubblePickUp)
		{
			if (MissionNumber >= Mission02_DisabledLocust && MissionNumber <= Mission07_KuritaJenners)
			{
				// Sol: A standard combat mission passes only if Jason still has a
				// Sol: mech and combat WORD 3992 is clear. The broader meaning of
				// Sol: 3992 remains unresolved, so its existing name is not evidence.
				if (seg3092->Mechs[Character_Jason].Name != MECH_Destroyed //3092:C724
				 && seg3092->Bool_EnemiesWithinRange == FALSE) //3092:3992
					seg3092->Bool_TrainingMissionPassed = TRUE;

				if (MissionNumber > Mission04_Locust_NoComputer)
				{
					// Sol: CBW proves both skill temporaries are signed WORDs even
					// Sol: though each persistent skill is stored as one byte.
					signed short GunnerySkill =
						(signed char)seg3092->Infantry[Character_Jason].Skill.Gunnery; //3092:C61B

					if (GunnerySkill < SkillLevel_Excellent)
						GunnerySkill += Rand_0x00_to_0xFF() & 0x0001;

					seg3092->Infantry[Character_Jason].Skill.Gunnery =
						(unsigned char)GunnerySkill;

					signed short PilotingSkill =
						(signed char)seg3092->Infantry[Character_Jason].Skill.Piloting; //3092:C61C

					if (PilotingSkill < SkillLevel_Excellent)
						PilotingSkill += Rand_0x00_to_0xFF() & 0x0001;

					seg3092->Infantry[Character_Jason].Skill.Piloting =
						(unsigned char)PilotingSkill;
				}

				if (seg3092->Kurita_AttackFlag != FALSE) //3092:3772
				{
					seg3092->Kurita_DestroyedCitadel = TRUE; //3092:D310

					// Sol: The original tests for an extant mech, so D311 records
					// Sol: survival, not destruction as the previous name claimed.
					if (seg3092->Mechs[Character_Jason].Name != MECH_Destroyed) //3092:C724
						seg3092->Bool_TrainingMechSurvivedKuritaAttack = TRUE; //3092:D311
				}

				// Sol: Missions 2..7 always consume the interruption flag.
				seg3092->Kurita_AttackFlag = FALSE; //3092:3772
			}
		}
		else
		{
			// Sol: Restore the rubble tile even if the successful interaction
			// Sol: already restored it; both writes use the saved original byte.
			seg246C->MapTile[RubbleTileIndex] = SavedObjectiveTile;

			// Sol: A Locust cannot retrieve the rubble because it has no hands.
			if (seg3092->Mechs[Character_Jason].Name != KEY_L) //3092:C724
				seg3092->Bool_TrainingMissionPassed = TRUE;

			signed short PilotingSkill =
				(signed char)seg3092->Infantry[Character_Jason].Skill.Piloting; //3092:C61C
			if (PilotingSkill < SkillLeveL_Good)
				PilotingSkill++;

			seg3092->Infantry[Character_Jason].Skill.Piloting =
				(unsigned char)PilotingSkill;
		}
	}
	else
	{
		// Sol: Locust selection subtracts 50 ticks before the signed pass-time
		// Sol: comparison, granting that chassis a larger effective time limit.
		if (seg3092->Mechs[Character_Jason].Name == KEY_L) //3092:C724
			MissionTimer -= 0x0032;

		if (MissionObjectiveResolved != FALSE
		 && (signed short)MissionTimer < 0x00D7)
			seg3092->Bool_TrainingMissionPassed = TRUE;

		seg246C->MapTile[CitadelMission00TemporaryTileIndex] = SavedObjectiveTile;
	}

	// Sol: This is common cleanup, including missions 8 and 9.
	seg3092->DrawJailMissionParkedMechs = FALSE;

	// Sol: BTSTATS and BLD data share a buffer. If BTSTATS displaced the
	// Sol: active BLD during the mission, reload that BLD before returning.
	if (seg3092->BTStatsAssetLoaded != FALSE)
	{
		Load_And_Decode_Indexed_BLD_1D30(seg3092->BLD_FileIndex);
	}
}

// 0FDC:0D49: Prepare the combatant tables and generate requested enemies.
// Called from:
//      Mech_Mission_0629
// Sol: Summary: Create enemies requested by a mission.
// Sol: Outline: Reset encounter state, choose templates and equipment, and populate enemy records and positions.
void Mission_GenerateEnemies(
	unsigned short EnemyMechRequest,
	unsigned short EnemyInfantryRequest)
{
	// TODO Sol: Fresh whole-body ASM audit: these near temporary views discard
	// TODO Sol: segment 3092. Use an explicit FAR/flat-memory binding later.
	// TODO Sol: Native pilot writes precede template copying and RNG calls;
	// TODO Sol: current C places them last. Preserve ordering when correcting.
	// Sol: Both arguments and the prefix temporaries are 16-bit stack WORDs.
	// Sol: Their low-byte high bits act as mode flags; the low seven bits later
	// Sol: hold counts.
	unsigned short EnemyInfantryRequestFlags = EnemyInfantryRequest;
	unsigned short EnemyMechRequestFlags = EnemyMechRequest;

	// Sol: This clears combatant-state byte 3994 for Jason. Its precise combat
	// Sol: meaning is outside this initialization block.
	seg3092->CombatantActionState[Character_Jason] = 0x00;
	unsigned short EnemyMechSpriteFamilyOffset = 0x0000;
	Mech far *MechSpawnTemplate = &seg2FE8->LOCUST; //2FE8:02F0

	unsigned short* CombatantWorldX =
		(unsigned short*)&seg3092->CharacterPosX_Mech; //3092:4004
	unsigned short* CombatantWorldY =
		(unsigned short*)&seg3092->CharacterPosY_Mech; //3092:4036
	unsigned short* CombatantOnMap =
		(unsigned short*)&seg3092->Character_OnMap; //3092:406A
	unsigned short* CombatantWreckState =
		(unsigned short*)&seg3092->CombatantCasualtyFlags; //3092:393C

	// Sol: Preserve world positions for combatants 16..23 in the first two
	// Sol: WORDs of their eight 0x1A-byte roaming-map NPC records. Combat setup
	// Sol: then clears the live 24-combatant position tables below.
	for (unsigned short NpcSlot = 0x0000;
		 NpcSlot < Enemy_Infantry_Record_Count;
		 NpcSlot++)
	{
		RoamingMapNpcRecordView* Npc = (RoamingMapNpcRecordView*)(
			(unsigned char*)&seg3092->EnemyInfantryPosX + NpcSlot * 0x1A);
		unsigned short CombatantId =
			Enemy_Infantry_CombatantId_Range_First + NpcSlot;
		Npc->CurrentPositionX = CombatantWorldX[CombatantId];
		Npc->CurrentPositionY = CombatantWorldY[CombatantId];
	}

	// Sol: Mark the four enemy mech records unused by clearing only Name[0].
	for (unsigned short EnemyMechSlot = 0x0000;
		 EnemyMechSlot < Enemy_Mech_Record_Count;
		 EnemyMechSlot++)
		seg3092->Mechs[Enemy_Mech_Record_First + EnemyMechSlot].Name[0] =
			MECH_Destroyed; //3092:C918 + slot*007D

	// Sol: Infantry record indexes 8..15 are the eight enemy infantry records.
	for (unsigned short EnemyInfantryRecord = Enemy_Infantry_Record_First;
		 EnemyInfantryRecord < Enemy_Infantry_Record_First + Enemy_Infantry_Record_Count;
		 EnemyInfantryRecord++)
		seg3092->Infantry[EnemyInfantryRecord].Name = Character_Dead;

	// Sol: The original loop body is inside the loop. A stray semicolon in the
	// Sol: transcription both removed the iteration and leaked its index.
	for (unsigned short CombatantId = 0x0000;
		 CombatantId < All_CombatantId_Range_Last;
		 CombatantId++)
	{
		CombatantWreckState[CombatantId] = FALSE;
		CombatantOnMap[CombatantId] = FALSE;
		CombatantWorldY[CombatantId] = CombatantPosition_Unused;
		CombatantWorldX[CombatantId] = CombatantPosition_Unused;
	}

	// Sol: Values below 0080 deploy Jason's mech at combatant 0. Values with
	// Sol: the low-byte high bit set deploy Jason on foot at combatant 4.
	if ((signed short)EnemyInfantryRequest < 0x0080)
		CombatantOnMap[Character_Jason] = TRUE;
	else
		CombatantOnMap[Friendly_Infantry_Combatant_Range_First] = TRUE;

	unsigned short Rand_PosY;
	unsigned short Rand_PosX;
	unsigned short EnemyMechCountAndFlags = EnemyMechRequest;
	// Sol: Bit 7 of the mech request selects the Mission08/world spawn and
	// Sol: random chassis tables. Clear means a Locust in the training region.
	if ((EnemyMechRequestFlags & Char_MostSignificantBit) == FALSE)
	{
		Rand_PosX =
			(Rand_0x00_to_0xFF() & 0x0007) + TrainingEnemySpawnMinX;
		Rand_PosY =
			(Rand_0x00_to_0xFF() & 0x0007) + TrainingEnemySpawnMinY;

		// Sol: The on-foot/high-bit request is the jailbreak call. The two
		// Sol: random values above are still consumed before this override.
		if ((EnemyInfantryRequestFlags & Char_MostSignificantBit) != FALSE)
		{
			Rand_PosX = Jail_EntranceX;
			Rand_PosY = Jail_EntranceY;
		}

		// Sol: Persistent BLD state byte zero supplies the current training
		// Sol: mission number. Mission 2 fixes X but retains the randomized Y.
		if (seg3092->PersistentBldState[0] == Mission02_DisabledLocust)
			Rand_PosX = TrainingMission02EnemyX;
	}
	else
	{
		// Sol: Preserve the original RNG order: a left-band X is always rolled,
		// Sol: then a coin flip may consume another roll and replace it.
		Rand_PosX =
			(Rand_0x00_to_0xFF() & 0x0003) + Mission08EnemySpawnLeftMinX;
		if ((Rand_0x00_to_0xFF() & 0x01) != 0x00)
			Rand_PosX =
				(Rand_0x00_to_0xFF() & 0x0003) + Mission08EnemySpawnRightMinX;

		Rand_PosY =
			(Rand_0x00_to_0xFF() & 0x0003) + Mission08EnemySpawnMinY;

		// Sol: Rental-mech Arena mode requests a second enemy record whenever
		// Sol: any of the four saved friendly mech-display slots is unused.
		if (seg3092->ArenaRentalMechMode != FALSE)
		{
			for (unsigned short FriendlyMechSlot = 0x0000;
				 FriendlyMechSlot < Friendly_Mech_Record_Count;
				 FriendlyMechSlot++)
			{
				if (seg3092->StoredPartyMechNameInitial[FriendlyMechSlot] == MECH_Destroyed) //3092:D452
					EnemyMechCountAndFlags = 0x02;
			}
		}

		// Sol: The normal index is triangular 2D6-2 (0..10). Rental mode still
		// Sol: consumes that dice roll, then replaces it with a uniform 3..6.
		unsigned short TemplateTableIndex = Roll2D6() - 0x0002;
		if (seg3092->ArenaRentalMechMode != FALSE)
			TemplateTableIndex = (Rand_0x00_to_0xFF() & 0x0003) + 0x0003;

		MechSpawnTemplate =
			seg3EDB->EnemyMechTemplateBy2D6Minus2[TemplateTableIndex];
		EnemyMechSpriteFamilyOffset =
			(signed char)seg3EDB->EnemyMechSpriteFamilyBy2D6Minus2[TemplateTableIndex];
	}

	unsigned short NextEnemyPilotRecord = Enemy_Infantry_Record_First;
	unsigned short NumberOfEnemyMechsToSpawn =
		EnemyMechCountAndFlags & Byte_MostSignificantBitMask;

	// Sol: A Kurita interruption always replaces the requested count with four.
	if (seg3092->Kurita_AttackFlag != FALSE) //3092:3772
		NumberOfEnemyMechsToSpawn = Enemy_Mech_Record_Count;

	for (unsigned short EnemyMechSlot = 0x0000;
		 EnemyMechSlot < NumberOfEnemyMechsToSpawn;
		 EnemyMechSlot++)
	{
		unsigned short EnemyCombatantId =
			Enemy_All_CombatantId_Range_First + EnemyMechSlot;
		Infantry* EnemyPilot = &seg3092->Infantry[NextEnemyPilotRecord];
		Mech* EnemyMech = &seg3092->Mechs[Enemy_Mech_Record_First + EnemyMechSlot];
		unsigned char* EnemyMechBytes = (unsigned char*)EnemyMech;

		Mech far *SourceTemplate = MechSpawnTemplate;
		if (seg3092->Kurita_AttackFlag != FALSE)
			SourceTemplate = &seg2FE8->JENNER;

		// Sol: Copy one complete 007D-byte template. In Arena rental mode slot
		// Sol: one is overwritten byte-for-byte by the Spectator template.
		for (unsigned short MechByte = 0x0000; MechByte < MECH_RecordSize; MechByte++)
		{
			EnemyMechBytes[MechByte] = ((unsigned char far*)SourceTemplate)[MechByte];
			if (seg3092->ArenaRentalMechMode != FALSE
			 && EnemyMechSlot != 0x0000)
				((unsigned char*)&seg3092->Mechs[Enemy_Mech_Record_First + 1])[MechByte] =
					((unsigned char far*)&seg2FE8->Spectator)[MechByte];
		}

		// Sol: Kurita Jenners arrive undamaged. Other encounters clamp the saved
		// Sol: severity byte before applying its armour and critical effects.
		if (seg3092->Kurita_AttackFlag != FALSE)
			seg3092->EnemyMechDamageLevel = 0x00;
		signed short EnemyMechDamageLevel =
			(signed char)seg3092->EnemyMechDamageLevel;
		if (EnemyMechDamageLevel > 0x06)
		{
			seg3092->EnemyMechDamageLevel = 0x06;
			EnemyMechDamageLevel = 0x06;
		}

		// Sol: The original uses signed byte comparisons and CBW before indexing.
		// Sol: Valid state is 0..6; a corrupt high-bit value reads before the table.
		unsigned char ArmourDamage = *(
			&seg3EDB->EnemyMechArmourDamageByLevel[0]
			+ EnemyMechDamageLevel);
		for (unsigned short ArmourLocation = 0x0000;
			 ArmourLocation < sizeof(EnemyMech->CurrentArmour);
			 ArmourLocation++)
		{
			if (EnemyMech->CurrentArmour[ArmourLocation] > ArmourDamage)
				EnemyMech->CurrentArmour[ArmourLocation] -= ArmourDamage;
			else
				EnemyMech->CurrentArmour[ArmourLocation] = 0x00;
		}

		if (EnemyMechDamageLevel > 0x04)
		{
			// Sol: Five selections cover raw record offsets 34..53. Empty slots
			// Sol: are ignored; nonempty component bytes gain the destroyed bit.
			for (unsigned short CriticalAttempt = 0x0000;
				 CriticalAttempt < 0x0005;
				 CriticalAttempt++)
			{
				unsigned short CriticalOffset =
					(Rand_0x00_to_0xFF() & 0x001F) + 0x0034;
				if (EnemyMechBytes[CriticalOffset] != 0x00)
					EnemyMechBytes[CriticalOffset] |= Component_Destroyed;
			}

			if (EnemyMechDamageLevel > 0x05)
			{
				EnemyMech->EngineHits = Rand_0x00_to_0xFF() & 0x01;
				EnemyMech->SensorHits = Rand_0x00_to_0xFF() & 0x01;
				EnemyMech->GyroHits = Rand_0x00_to_0xFF() & 0x01;
			}
		}

		seg3092->CombatantSpriteFamilyOffset[EnemyCombatantId] =
			(unsigned char)EnemyMechSpriteFamilyOffset;
		seg3092->CombatantSpriteFrame[EnemyCombatantId] = 0x0C;
		seg3EDB->CombatantAnimationCursor[EnemyCombatantId] =
			&seg2FE8->MechWalkAnimationStreams[0x30]; //2FE8:02A0
		seg3092->SpawnedCombatant[
			Friendly_Infantry_Combatant_Range_First + EnemyMechSlot] = 0x06;
		seg3092->CombatantAnimationSelector[EnemyCombatantId] = 0x06;
		CombatantOnMap[EnemyCombatantId] = TRUE;
		CombatantWorldX[EnemyCombatantId] = Rand_PosX
			+ seg3EDB->EnemySpawnOffsetX[EnemyMechSlot];
		CombatantWorldY[EnemyCombatantId] = Rand_PosY
			+ seg3EDB->EnemySpawnOffsetY[EnemyMechSlot];

		if (seg3092->ArenaRentalMechMode != FALSE
		 && EnemyMechSlot != 0x0000)
		{
			// Sol: The second generated enemy becomes a non-targetable Spectator
			// Sol: with its own stream, selector, sprite state, and fixed position.
			unsigned short SpectatorId = Enemy_All_CombatantId_Range_First + 1;
			seg3092->CombatantSpriteFrame[SpectatorId] = 0x10;
			seg3092->CombatantSpriteFamilyOffset[SpectatorId] = 0x00;
			seg3EDB->CombatantAnimationCursor[SpectatorId] =
				seg3EDB->SpectatorAnimationStream;
			seg3092->SpawnedCombatant[
				Friendly_Infantry_Combatant_Range_First + 1] = 0x02;
			seg3092->CombatantAnimationSelector[SpectatorId] = 0x02;
			CombatantWorldX[SpectatorId] = Mission08SpectatorX;
			CombatantWorldY[SpectatorId] = Mission08SpectatorY;
		}

		// Sol: Each generated mech receives one enemy infantry record as pilot.
		// TODO Sol: ASM 11E1..1205 performs this BEFORE the template-copy body,
		// TODO Sol: despite its later textual position in the listing (JMP 0FA9).
		EnemyPilot->Name = 0x00;
		EnemyPilot->Piloting = Enemy_Mech_Record_First + EnemyMechSlot; //+0C MechAssignment
		NextEnemyPilotRecord++;
	}
	if (EnemyInfantryRequest != 0x00)
	{
		// Sol: Enemy mech pilots and on-foot enemies share infantry records
		// Sol: 8..15. Existing pilot records therefore reduce infantry capacity.
		unsigned short EnemyRecordLimit = NextEnemyPilotRecord
			+ (EnemyInfantryRequest & Byte_MostSignificantBitMask);

		if (EnemyRecordLimit > Enemy_Infantry_Record_First + Enemy_Infantry_Record_Count)
			EnemyRecordLimit = Enemy_Infantry_Record_First + Enemy_Infantry_Record_Count;

		for (unsigned short EnemyInfantryRecord = NextEnemyPilotRecord;
			 EnemyInfantryRecord < EnemyRecordLimit;
			 EnemyInfantryRecord++)
		{
			Infantry* EnemyInfantry = &seg3092->Infantry[EnemyInfantryRecord];
			unsigned short EnemyCombatantId =
				EnemyInfantryRecord + Enemy_Infantry_RecordToCombatantId_Offset;

			EnemyInfantry->Name = 0x00;
			EnemyInfantry->Piloting = Character_OnFoot;
			seg3092->CombatantSpriteFamilyOffset[EnemyCombatantId] =
				CharacterSpriteFamily_EnemyInfantry;
			seg3092->CombatantSpriteFrame[EnemyCombatantId] = 0x1C;
			seg3EDB->CombatantAnimationCursor[EnemyCombatantId] =
				&seg2FE8->InfantryWalkAnimationStreams[0x30]; //2FE8:02E0
			seg3092->SpawnedCombatant[EnemyInfantryRecord] = 0x06;
			seg3092->CombatantAnimationSelector[EnemyCombatantId] = 0x06;
			CombatantOnMap[EnemyCombatantId] = TRUE;
			CombatantWorldX[EnemyCombatantId] = Rand_PosX
				+ seg3EDB->EnemySpawnOffsetX[EnemyInfantryRecord];
			CombatantWorldY[EnemyCombatantId] = Rand_PosY
				+ seg3EDB->EnemySpawnOffsetY[EnemyInfantryRecord];

			// Sol: Only six consecutive skills, +04 through +09, are randomized.
			// Sol: Medical at +0A and several other record fields remain untouched.
			unsigned char* EnemySkills = &EnemyInfantry->Skill_BowsAndBlade;
			for (unsigned short EnemySkill = 0x0000; EnemySkill < 0x0006; EnemySkill++)
			{
				EnemySkills[EnemySkill] = Rand_0x00_to_0xFF() & 0x01;
			}

			EnemyInfantry->Body = Roll2D6();
			EnemyInfantry->Health = EnemyInfantry->Body * 0x0A;
			EnemyInfantry->Weapon = Rand_0x00_to_0xFF() % 0x0E;
		}
	}
}

// 0FDC:134B: void Restore_Mission_Map_View_After_Combat()
// Called from:
//      Mech_Mission_0629, after combat in training missions 2..7
// Sol: Summary: Return to the mission map after combat.
// Sol: Outline: Restore the mission's world position and map caches, then rebuild the exploration display.
void Restore_Mission_Map_View_After_Combat()
{
	// Sol: Fresh whole-body ASM match, including Y+2 and conditional +0F80 wrap.
	// Sol: The training missions keep Jason's mech in combatant/mech slot zero.
	// Sol: Any assignment other than the on-foot sentinel follows this branch.
	if (seg3092->Infantry[Character_Jason].Piloting != Character_OnFoot) //3092:C620
	{
		seg246C->CrescentHawk_MapPositionX =
			seg3092->CharacterPosX_Mech[Character_Jason]; //3092:4004 -> 246C:A44B
		seg246C->CrescentHawk_MapPositionY =
			seg3092->CharacterPosY_Mech[Character_Jason] + 0x0002; //3092:4036 -> 246C:A44D

		// Sol: Adding two can cross local Y=7F. Adding 0F80 then converts the
		// Sol: noncanonical xx80/xx81 value into the next packed map row's 00/01.
		if ((seg246C->CrescentHawk_MapPositionY & Char_MostSignificantBit) != FALSE)
			seg246C->CrescentHawk_MapPositionY += 0x0F80;
	}
	else
	{
		seg246C->CrescentHawk_MapPositionX =
			seg3092->CharacterPosX_OnFoot[Character_Jason]; //3092:400C -> 246C:A44B
		seg246C->CrescentHawk_MapPositionY =
			seg3092->CharacterPosY_OnFoot[Character_Jason]; //3092:403E -> 246C:A44D
	}

	// Sol: Rebuild and present the exploration view centred on the restored anchor.
	PosXY_OffsetGrid(
		seg246C->CrescentHawk_MapPositionX,
		seg246C->CrescentHawk_MapPositionY);
	Copy_Data_To_GraphicsMemory();
	Draw_Infantry_And_Mechs();
	EGA_DrawBox_Wrapper();
}

// 0FDC:13DE: void Distribute_Purchased_Armour(Stack WORD HeldArmourType, Stack WORD HeldArmourValue)
// Called from:
//      Citadel_Building_Dialogs
// Sol: Summary: Assign purchased armour to party members.
// Sol: Outline: Select eligible recipients, update their armour records, and repeat or finish according to the menu response.
void Distribute_Purchased_Armour(
	unsigned short HeldArmourType,
	unsigned short HeldArmourValue)
{
	// TODO Sol: Fresh ASM audit: retain FAR3092 recipient views and CBW before
	// TODO Sol: character-name/armour-description indexing; DS:1667 starts with
	// TODO Sol: a space missing from the current " to:" literal. See audit report.
	// Sol: The original stack array contains eight WORD party-record IDs and is
	// Sol: initialized to FFFF before being compacted to only living members.
	unsigned short PartyMemberByMenuIndex[8];
	for (unsigned short MenuIndex = 0x0000; MenuIndex < 0x0008; MenuIndex++)
		PartyMemberByMenuIndex[MenuIndex] = 0xFFFF;

	unsigned short LivingPartyMemberCount = 0x0000;
	for (unsigned short PartyMemberId = 0x0000; PartyMemberId < 0x0008; PartyMemberId++)
	{
		if (seg3092->Infantry[PartyMemberId].Name != Character_Dead)
			PartyMemberByMenuIndex[LivingPartyMemberCount++] = PartyMemberId;
	}

	// Sol: The former pseudo-C reversed this condition. A nonzero armour type is
	// Sol: the item currently being held for assignment; type zero ends the chain.
	while (HeldArmourType != ArmourType_None)
	{
		unsigned short MenuChoice;
		if (LivingPartyMemberCount <= 0x0001)
		{
			// Sol: With zero or one living member the executable silently equips
			// Sol: Jason and discards whatever armour record zero previously held.
			seg3092->Infantry[Character_Jason].ArmourType =
				(unsigned char)HeldArmourType;
			seg3092->Infantry[Character_Jason].ArmourValue =
				(unsigned char)HeldArmourValue;
			MenuChoice = LivingPartyMemberCount;
		}
		else
		{
			Draw_Top_Graphic_Sidebar();
			Display_Text_From_Memory("Give "); //3EDB:1661
			Display_Text_From_Memory(
				seg3EDB->ArmourTextDescription[HeldArmourType]);
			Display_Text_From_Memory(" to:\r"); //3EDB:1667

			for (unsigned short MenuIndex = 0x0000;
				 MenuIndex < LivingPartyMemberCount;
				 MenuIndex++)
			{
				Infantry* PartyMember =
					&seg3092->Infantry[PartyMemberByMenuIndex[MenuIndex]];
				unsigned char CharacterNameId = PartyMember->Name;
				if (CharacterNameId != Character_Dead)
				{
					Display_Text_From_Memory(
						seg3EDB->CharacterNameList[CharacterNameId]);
					seg3092->HorizontalLine_Offset = 0x000A;
					Display_Text_From_Memory(
						seg3EDB->ArmourTextDescription[PartyMember->ArmourType]);
					Display_Text_4FA0_Value(); //3EDB:4FA0 is carriage return
				}
			}

			Display_Text_From_Memory("Drop it\r\r\rArmor points left: "); //3EDB:166D
			Display_Text_Dynamic_Value(HeldArmourValue);
			seg305B->w00D6 = LivingPartyMemberCount + 1;
			MenuChoice = Display_Menu_Choices_And_Check(0x04);
		}

		if (MenuChoice == LivingPartyMemberCount)
		{
			HeldArmourType = ArmourType_None;
		}
		else
		{
			Infantry* Recipient =
				&seg3092->Infantry[PartyMemberByMenuIndex[MenuChoice]];
			signed short DisplacedArmourType = (signed char)Recipient->ArmourType;
			signed short DisplacedArmourValue = (signed char)Recipient->ArmourValue;

			Recipient->ArmourType = (unsigned char)HeldArmourType;
			Recipient->ArmourValue = (unsigned char)HeldArmourValue;

			// Sol: The exchange has already occurred when this warning is shown.
			if (HeldArmourType == DisplacedArmourType)
			{
				Display_Text_At_2867(
					"He already has that type of armor.", 0x00, 0x14); //3EDB:168B
				Wait_For_50Hz_Then_Check_Input();
				Keyboard_Get_ASCII_Hex_Input();
			}

			// Sol: The recipient's previous armour becomes the next held item. If
			// Sol: its type is None (zero), the transfer chain ends automatically.
			HeldArmourType = DisplacedArmourType;
			HeldArmourValue = DisplacedArmourValue;
		}
	}
}

// 0FDC:15E6: void Distribute_Weapon_To_Party(Stack WORD HeldWeaponId)
// Called from:
//      Loot_Enemy_Soldiers_Dialog
//      Citadel_Building_Dialogs
// Sol: Summary: Give a purchased or recovered weapon to a party member.
// Sol: Outline: Select a recipient, handle existing equipment, and update the character's weapon slot.
void Distribute_Weapon_To_Party(unsigned short HeldWeaponId)
{
	// TODO Sol: Fresh ASM audit: retain FAR3092 recipient views and signed CBW/
	// TODO Sol: BYTE IMUL17 for name/weapon indices. DS:16B4 starts with a space
	// TODO Sol: missing from the current " to:" literal. See audit report.
	// Sol: These FFFF stores initialize a local WORD menu map. The former
	// Sol: pseudo-C incorrectly turned them into destructive Infantry[] writes.
	unsigned short PartyMemberByMenuIndex[8];
	for (unsigned short MenuIndex = 0x0000; MenuIndex < 0x0008; MenuIndex++)
		PartyMemberByMenuIndex[MenuIndex] = 0xFFFF;

	unsigned short LivingPartyMemberCount = 0x0000;
	for (unsigned short PartyMemberId = 0x0000; PartyMemberId < 0x0008; PartyMemberId++)
	{
		if (seg3092->Infantry[PartyMemberId].Name != Character_Dead)
			PartyMemberByMenuIndex[LivingPartyMemberCount++] = PartyMemberId;
	}

	// Sol: Weapon ID zero is both the Cudgel and this transfer loop's empty/
	// Sol: finished sentinel. A held or displaced Cudgel ends distribution.
	while (HeldWeaponId != Infantry_Cudgel)
	{
		unsigned short MenuChoice;
		if (LivingPartyMemberCount <= 0x0001)
		{
			// Sol: With zero or one living member, equip Jason directly and
			// Sol: discard the weapon previously held in record zero.
			seg3092->Infantry[Character_Jason].Weapon =
				(unsigned char)HeldWeaponId;
			HeldWeaponId = Infantry_Cudgel;
			MenuChoice = LivingPartyMemberCount;
		}
		else
		{
			Draw_Top_Graphic_Sidebar();
			Display_Text_From_Memory("Give "); //3EDB:16AE
			Display_Text_From_Memory(seg3EDB->WeaponStats[HeldWeaponId].Name);
			Display_Text_From_Memory(" to:\r"); //3EDB:16B4

			for (unsigned short MenuIndex = 0x0000;
				 MenuIndex < LivingPartyMemberCount;
				 MenuIndex++)
			{
				Infantry* PartyMember =
					&seg3092->Infantry[PartyMemberByMenuIndex[MenuIndex]];
				unsigned char CharacterNameId = PartyMember->Name;
				if (CharacterNameId != Character_Dead)
				{
					Display_Text_From_Memory(
						seg3EDB->CharacterNameList[CharacterNameId]);
					seg3092->HorizontalLine_Offset = 0x000A;
					Display_Text_From_Memory(
						seg3EDB->WeaponStats[PartyMember->Weapon].Name);
					Display_Text_4FA0_Value(); //3EDB:4FA0 is carriage return
				}
			}

			Display_Text_From_Memory("Drop it"); //3EDB:16BA
			seg305B->w00D6 = LivingPartyMemberCount + 1;
			MenuChoice = Display_Menu_Choices_And_Check(0x04);
		}

		if (MenuChoice == LivingPartyMemberCount)
		{
			HeldWeaponId = Infantry_Cudgel;
		}
		else
		{
			Infantry* Recipient =
				&seg3092->Infantry[PartyMemberByMenuIndex[MenuChoice]];
			signed short DisplacedWeaponId = (signed char)Recipient->Weapon;

			Recipient->Weapon = (unsigned char)HeldWeaponId;
			// Sol: As with armour distribution, the exchange precedes the warning.
			if (HeldWeaponId == DisplacedWeaponId)
			{
				Display_Text_At_2867(
					"He already has that weapon.", 0x00, 0x14); //3EDB:16C2
				Wait_For_50Hz_Then_Check_Input();
				Keyboard_Get_ASCII_Hex_Input();
			}

			HeldWeaponId = DisplacedWeaponId;
		}
	}
}

// 0FDC:17B9: void Talk_To_Building_Occupants()
// Called from:
//      Citadel_Building_Dialogs
// Sol: Summary: Dispatch conversations with a building's occupants.
// Sol: Outline: Inspect the current building and story state, then display or invoke the appropriate conversation.
void Talk_To_Building_Occupants()
{
	// TODO Sol: Fresh ASM audit: roaming NPC views are FAR3092, not near DS.
	// TODO Sol: DS:172D has two spaces after '?'; current literal has only one.
	// Sol: The peculiar last-waiting-waypoint Rick gate is confirmed, not fixed.
	// Sol: Each BLD's "Talk to others" branch first writes D319. The value is
	// Sol: both a purpose-text index and a BLD ID/category. Find which of the
	// Sol: map's first eight exterior building slots resolves to that ID.
	unsigned short CurrentBuildingSlot = 0x0000;
	while (CurrentBuildingSlot < 0x0008
		&& seg3092->AlternativeBldByBuildingId[CurrentBuildingSlot]
			!= seg3092->NpcActivityBuildingId)
	{
		CurrentBuildingSlot++;
	}

	Draw_Top_Graphic_Sidebar();
	unsigned char NpcWaitingInBuilding[8];
	unsigned short WaitingNpcCount = 0x0000;
	unsigned short LastWaitingNpcWaypoint;

	for (unsigned short NpcSlot = 0x0000; NpcSlot < 0x0008; NpcSlot++)
	{
		NpcWaitingInBuilding[NpcSlot] = FALSE;
		RoamingMapNpcRecordView* Npc = (RoamingMapNpcRecordView*)(
			(unsigned char*)&seg3092->EnemyInfantryPosX + (NpcSlot * 0x1A));

		// Sol: A nonzero delay means the NPC is waiting off-map at the high-nibble
		// Sol: waypoint. Delay zero is the travelling/on-map state.
		if (Npc->MovementDelay != 0x00)
		{
			LastWaitingNpcWaypoint = (Npc->WaypointPair >> 4) & 0x07;
			if (LastWaitingNpcWaypoint == CurrentBuildingSlot)
			{
				NpcWaitingInBuilding[NpcSlot] = TRUE;
				WaitingNpcCount++;
			}
		}
	}

	if (WaitingNpcCount == 0x0000)
	{
		Display_Text_From_Memory(
			"Nobody here seems interested in talking to you."); //3EDB:16DE
		Keyboard_Get_ASCII_Hex_Input();
		return;
	}

	Display_Text_From_Memory("You look around and see:\r"); //3EDB:170E
	for (unsigned short NpcSlot = 0x0000; NpcSlot < 0x0008; NpcSlot++)
	{
		if (NpcWaitingInBuilding[NpcSlot] != FALSE)
		{
			Display_Text_From_Memory(seg246C->MapCharacterNames[NpcSlot]);
			Display_Text_4FA0_Value();
		}
	}

	Display_Text_From_Memory("Done"); //3EDB:1728
	seg305B->w01D6 = WaitingNpcCount + 1;
	unsigned short SelectedOccupant = Display_Menu_Choices_And_Check(0x14);
	if (SelectedOccupant == WaitingNpcCount)
		return;

	// TODO Sol: Preserve this peculiar original condition exactly. It uses the
	// TODO Sol: last waiting NPC's waypoint, rather than the current building or
	// TODO Sol: selected NPC. See Astra candidate A-007.
	if (seg3092->HoldRickAtlasUntilLoungeConversation != FALSE
	 && LastWaitingNpcWaypoint == 0x0007
	 && SelectedOccupant == 0x0000
	 && NpcWaitingInBuilding[0] != FALSE)
	{
		seg3092->RickAtlasConversationTriggered = TRUE;
		RoamingMapNpcRecordView* FirstNpc = (RoamingMapNpcRecordView*)
			&seg3092->EnemyInfantryPosX;
		FirstNpc->MovementDelay = 0x00;
		return;
	}

	seg3092->RickAtlasConversationTriggered = FALSE;
	Draw_Top_Graphic_Sidebar();
	if (seg3092->Kurita_DestroyedCitadel != FALSE)
	{
		// Sol: After the Citadel is destroyed, occupants give one of eight
		// Sol: generic dismissive replies; the selected NPC otherwise has no effect.
		unsigned short ReplyIndex = Rand_0x00_to_0xFF() & 0x07;
		Display_Text_From_Memory(
			seg3EDB->DestroyedCitadelNpcReplyText[ReplyIndex]);
		Keyboard_Get_ASCII_Hex_Input();
		return;
	}

	Display_Text_From_Memory(
		"Hi, Jason, how are you? I just stopped in here to "); //3EDB:172D
	unsigned short ActivityId = (unsigned short)(signed char)
		seg3092->NpcActivityBuildingId;
	Display_Text_From_Memory(seg3EDB->NpcActivityReasonText[ActivityId]);
	Display_Text_From_Memory(
		"  After I'm done here, I'm going over to the "); //3EDB:1761

	// Sol: The menu is compact, but NPC route records retain their original slot.
	// Sol: DEC/JNS in the executable selects the Nth marked slot below.
	signed short RemainingChoice = SelectedOccupant;
	for (unsigned short NpcSlot = 0x0000; NpcSlot < 0x0008; NpcSlot++)
	{
		if (NpcWaitingInBuilding[NpcSlot] != FALSE && --RemainingChoice < 0)
		{
			RoamingMapNpcRecordView* SelectedNpc = (RoamingMapNpcRecordView*)(
				(unsigned char*)&seg3092->EnemyInfantryPosX + (NpcSlot * 0x1A));
			unsigned short DestinationBuildingSlot = SelectedNpc->WaypointPair & 0x07;
			Display_Text_From_Memory(
				seg246C->MapBuildingNames[DestinationBuildingSlot]);
			Display_Text_From_Memory("."); //3EDB:178F
			Keyboard_Get_ASCII_Hex_Input();
			return;
		}
	}
}

// 0FDC:19E1: void Display_No_Stock_Transaction_Text()
// Called from:
//      Citadel_Building_Dialogs
// Sol: Summary: Print the no-transaction response.
// Sol: Outline: Display the fixed stock-dialogue string through the shared text renderer.
void Display_No_Stock_Transaction_Text()
{
	// Sol: Fresh whole-body ASM match, including the exact DS:1791 suffix.
	// Sol: This leading-space suffix completes either "You invest" or
	// Sol: "You sell" at the sole caller. The stored text includes the period.
	Display_Text_From_Memory(" nothing this time."); //3EDB:1791
}

// 0FDC:19F6: Read a little-endian immediate WORD from a far BLD pointer.
// Called from:
//      Execute_Bld_Bytecode_01C0
// Sol: Summary: Read a WORD operand from a building script.
// Sol: Outline: Combine its low and high bytes without sign-extending either byte.
unsigned short Read_Bld_Immediate_Word_19F6(unsigned char far *WordBytes)
{
	// Sol: Fresh whole-body ASM match under native WORD/FAR16 offset-only wrap.
	// Sol: The executable briefly sign-extends each byte into a local WORD, then
	// Sol: explicitly rebuilds the result from their low bytes. The net result is
	// Sol: an unsigned little-endian WORD; this helper does not advance the pointer.
	unsigned short LowByte = WordBytes[0x0000];
	unsigned short HighByte = WordBytes[0x0001];
	return LowByte | (HighByte << 0x0008);
}

// 0FDC:1A26: void Prepare_Party_Mech_For_Arena()
// Called from:
//      Citadel_Building_Dialogs
// Sol: Summary: Stage a party mech for arena combat.
// Sol: Outline: Save crew IDs and slot zero, stage the selected mech, hide companions and select owned-mech cleanup.
void Prepare_Party_Mech_For_Arena()
{
	// TODO Sol: Fresh ASM audit: record-byte temporaries must retain FAR3092.
	// Sol: This helper does not save world positions or start combat itself.
	// Sol: Preserve crew assignments before slot zero is repurposed as the
	// Sol: Arena combatant and the selected party 'Mech is hidden in place.
	for (unsigned short MechSlot = 0x0000; MechSlot < 0x0004; MechSlot++)
	{
		seg3092->SavedArenaMechPilotId[MechSlot] =
			seg3092->Mechs[MechSlot].PilotId;
		seg3092->SavedArenaMechRiderId[MechSlot] =
			seg3092->Mechs[MechSlot].RiderId;
	}

	Draw_Top_Graphic_Sidebar();
	Display_Text_From_Memory("Which 'Mech will you take into combat?\r"); //3EDB:17A5
	Display_Text_Mech_Names();

	unsigned short SelectedMechSlot = seg3092->Mech_Selected;
	unsigned char* ArenaMech = (unsigned char*)&seg3092->Mechs[0];
	unsigned char* SelectedPartyMech =
		(unsigned char*)&seg3092->Mechs[SelectedMechSlot];

	// Sol: Save the original slot-zero record, then stage the selected complete
	// Sol: 0x7D-byte party 'Mech record in slot zero for the Arena mission.
	for (unsigned short RecordOffset = 0x0000;
		 RecordOffset < MECH_RecordSize;
		 RecordOffset++)
	{
		seg3092->ArenaMechRecordBackup[RecordOffset] = ArenaMech[RecordOffset];
		ArenaMech[RecordOffset] = SelectedPartyMech[RecordOffset];
	}

	// Sol: D452-D455 preserve the displayed first name byte in workflows where
	// Sol: live records may have been hidden with FF.
	seg3092->Mechs[0].Name[0] = seg3092->StoredPartyMechNameInitial[SelectedMechSlot];

	// Sol: The paired C620+i*11 and C60F+i*11 stores in the executable overlap:
	// Sol: together they set +0C in party records 0..7, not two separate arrays.
	for (unsigned short PartyMemberSlot = 0x0000;
		 PartyMemberSlot < 0x0008;
		 PartyMemberSlot++)
	{
		seg3092->Infantry[PartyMemberSlot].Piloting = 0x03;
	}

	for (unsigned short PartyMemberSlot = 0x0001;
		 PartyMemberSlot < 0x0008;
		 PartyMemberSlot++)
	{
		seg3092->SavedPartyNameId[PartyMemberSlot] =
			seg3092->Infantry[PartyMemberSlot].Name;
		seg3092->Infantry[PartyMemberSlot].Name = Character_Dead;
	}

	seg3092->Mechs[0].PilotId = Character_Jason;
	seg3092->Mechs[0].RiderId = MECH_NoRider;
	// Sol: FALSE selects the party-owned-'Mech restoration path after combat;
	// Sol: the parallel rental setup at 1C9B sets this WORD to TRUE.
	seg3092->ArenaRentalMechMode = FALSE;
}

// 0FDC:1B41: void Restore_Party_After_Arena_Combat()
// Called from:
//      Citadel_Building_Dialogs
// Sol: Summary: Restore the party after an arena match.
// Sol: Outline: Return owned-mech damage or discard the rental, restore saved records and crew, then dismount the party.
void Restore_Party_After_Arena_Combat()
{
	// TODO Sol: Fresh ASM audit: record-byte temporaries must retain FAR3092.
	// Sol: Both cleanup branches and the selected-slot-zero alias were compared.
	unsigned char* ArenaMech = (unsigned char*)&seg3092->Mechs[0];

	if (seg3092->ArenaRentalMechMode != FALSE)
	{
		// Sol: The rented Locust was temporary. Restore the complete party mech
		// Sol: record which occupied slot zero before the Arena setup.
		for (unsigned short RecordOffset = 0x0000;
			 RecordOffset < MECH_RecordSize;
			 RecordOffset++)
		{
			ArenaMech[RecordOffset] =
				seg3092->ArenaMechRecordBackup[RecordOffset];
		}
	}
	else
	{
		unsigned short SelectedMechSlot = seg3092->Mech_Selected;
		unsigned char* SelectedPartyMech =
			(unsigned char*)&seg3092->Mechs[SelectedMechSlot];

		// Sol: Preserve the selected party-owned mech's post-combat state by
		// Sol: copying the staged slot-zero record back to its roster slot.
		for (unsigned short RecordOffset = 0x0000;
			 RecordOffset < MECH_RecordSize;
			 RecordOffset++)
		{
			SelectedPartyMech[RecordOffset] = ArenaMech[RecordOffset];
		}

		// Sol: D452-D455 retain each roster mech's first name byte while its live
		// Sol: record is hidden. Propagate destruction before hiding this record.
		if (ArenaMech[0] == MECH_Destroyed)
			seg3092->StoredPartyMechNameInitial[SelectedMechSlot] = MECH_Destroyed;
		SelectedPartyMech[0] = MECH_Destroyed;

		// Sol: When another roster slot supplied the Arena mech, put Jason's
		// Sol: original slot-zero record back after saving the combat result.
		if (SelectedMechSlot != 0x0000)
		{
			for (unsigned short RecordOffset = 0x0000;
				 RecordOffset < MECH_RecordSize;
				 RecordOffset++)
			{
				ArenaMech[RecordOffset] =
					seg3092->ArenaMechRecordBackup[RecordOffset];
			}
		}

		// Sol: Own-mech setup temporarily installed Jason/no-rider in the staged
		// Sol: record. Restore the original byte-sized crew IDs in every slot.
		for (unsigned short MechSlot = 0x0000; MechSlot < 0x0004; MechSlot++)
		{
			seg3092->Mechs[MechSlot].PilotId =
				seg3092->SavedArenaMechPilotId[MechSlot];
			seg3092->Mechs[MechSlot].RiderId =
				seg3092->SavedArenaMechRiderId[MechSlot];
		}
	}

	// Sol: The paired C620+i*11/C60F+i*11 stores cover party slots 1..7
	// Sol: and 0..6 respectively, so every party member is dismounted.
	for (unsigned short PartyMemberSlot = 0x0000;
		 PartyMemberSlot < 0x0008;
		 PartyMemberSlot++)
	{
		seg3092->Infantry[PartyMemberSlot].Piloting = Character_OnFoot;
	}

	for (unsigned short PartyMemberSlot = 0x0001;
		 PartyMemberSlot < 0x0008;
		 PartyMemberSlot++)
	{
		seg3092->Infantry[PartyMemberSlot].Name =
			seg3092->SavedPartyNameId[PartyMemberSlot];
	}
}

// 0FDC:1C9B: void Prepare_Rental_Locust_For_Arena()
// Called from:
//      Citadel_Building_Dialogs
// Sol: Summary: Prepare the arena's rental Locust.
// Sol: Outline: Back up slot zero, copy the Locust template, hide companions and select rental cleanup.
void Prepare_Rental_Locust_For_Arena()
{
	// TODO Sol: Fresh ASM audit: ArenaMech must retain FAR3092, not near DS.
	// Sol: Template copying is confirmed; pilot assignment/position are callers' work.
	unsigned char* ArenaMech = (unsigned char*)&seg3092->Mechs[0];
	unsigned char far* ReferenceLocust =
		(unsigned char far*)&seg2FE8->MechRefs[MECH_REF_Locust];

	// Sol: Preserve the complete party mech record in slot zero, then replace it
	// Sol: byte-for-byte with the static Locust template at 2FE8:02F0.
	for (unsigned short RecordOffset = 0x0000;
		 RecordOffset < MECH_RecordSize;
		 RecordOffset++)
	{
		seg3092->ArenaMechRecordBackup[RecordOffset] =
			ArenaMech[RecordOffset];
		ArenaMech[RecordOffset] = ReferenceLocust[RecordOffset];
	}

	// Sol: As in the party-owned setup, the paired C620+i*11/C60F+i*11
	// Sol: stores cover all eight MechAssignment bytes with literal 03.
	for (unsigned short PartyMemberSlot = 0x0000;
		 PartyMemberSlot < 0x0008;
		 PartyMemberSlot++)
	{
		seg3092->Infantry[PartyMemberSlot].Piloting = 0x03;
	}

	// Sol: Hide every party member except Jason. The Arena dispatcher which
	// Sol: follows this helper assigns Jason to staged mech slot zero.
	for (unsigned short PartyMemberSlot = 0x0001;
		 PartyMemberSlot < 0x0008;
		 PartyMemberSlot++)
	{
		seg3092->SavedPartyNameId[PartyMemberSlot] =
			seg3092->Infantry[PartyMemberSlot].Name;
		seg3092->Infantry[PartyMemberSlot].Name = Character_Dead;
	}

	// Sol: Select rental cleanup plus the Arena's special spectator rules.
	seg3092->ArenaRentalMechMode = TRUE;
}

// 0FDC:1D30: void Load_And_Decode_Indexed_BLD_1D30(unsigned short BldFileId)
// Called from:
//      Interact_with_BLD
//      Mech_Mission_0629
// Sol: Summary: Load and decode a selected building script.
// Sol: Outline: Resolve the filename table entry, read the original BLD, and decode it into the shared script buffer.
void Load_And_Decode_Indexed_BLD_1D30(unsigned short BldFileId)
{
	// Sol: Fresh whole-body ASM match under native WORD/FAR address arithmetic.
	// Sol: Signed JL disk gates are equivalent to these unsigned tests for all
	// Sol: WORD IDs; filename-table byte offsets must still wrap before lookup.
	// Sol: Decode all 2328h bytes, clear cache flag, and .dis return tail compared.
	// Sol: Select logical Game Disk 1 first. TRAINING/CITADEL and BLD IDs
	// Sol: 11h-19h are stored on Disk 2; IDs 02h-10h remain on Game Disk 1.
	Select_Game_Disk_And_Drive_28CC(0x0001);
	if (BldFileId < 0x0002 || BldFileId >= 0x0011)
		Select_Game_Disk_And_Drive_28CC(0x0002);

	seg3092->BLD_FileIndex = BldFileId;
	Load_File_To_Memory(
		seg3EDB->BldFileNameById[BldFileId],
		&seg3092->BTStatsORBLDMemoryLocation[0]);

	// Sol: Decode in place. Addition precedes XOR and byte assignment provides
	// Sol: the original 8-bit wrap. The fixed span intentionally exceeds every
	// Sol: shipped length-prefixed BLD payload; see QUIRK-001.
	for (unsigned short BufferOffset = 0x0000;
		 BufferOffset < BLD_FIXED_DECODE_SPAN;
		 BufferOffset++)
	{
		seg3092->BTStatsORBLDMemoryLocation[BufferOffset] = (unsigned char)(
			(seg3092->BTStatsORBLDMemoryLocation[BufferOffset] + 0x29) ^ 0xE9);
	}

	// Sol: BLD data now occupies the shared buffer; BTSTATS must be reloaded
	// Sol: before its next use.
	seg3092->BTStatsAssetLoaded = FALSE;
}

