// BTECH_183B.c
// Generated by decompiling BTECH.EXE
// using Reko decompiler version 0.11.2.0.

#include "BTECH.h"

// Sol: Fresh whole-file ASM audit2026-09-17:12 locally matched,5 mismatched.
// Sol: docs/phase4/BTECH_183B_SYSTEMATIC_ASM_AUDIT.md records contracts and
// Sol: discrepancies. Checking-only pass: executable statements unchanged.

// Sol: Movement/weapon workflow checkpoint:
// Sol: docs/phase4/COMBAT_MOVEMENT_AND_WEAPON_LINKAGE.md. Only explicitly
// Sol: reconstructed blocks are port candidates; parent/menu bodies retain
// Sol: damaged Reko expressions. Header views overlap DOS addresses and do
// Sol: NOT form a compilable sequential memory-layout struct.

// 183B:000A: void Combat_Parent_000A(Stack Eq_21 TargetMechId)
// Called from:
//      Main_Game_Loop
//      Mech_Mission_0629
//      Recruit_Rex_And_Start_KuritaParty_Ambush
// Sol: Summary: Coordinate a complete combat encounter.
// Sol: Outline: Assess enemies, run planning and mechanics rounds, check betrayal and endings, then handle salvage and mode outcomes.
void Combat_Parent_000A(unsigned short CombatRules)
{
	// Sol: TODO ASM audit: restore native CR at3402/341B and period at34B8.
	// Sol: TODO ASM audit: betrayal CharacterNameList indexes need native CBW
	// Sol: signed names, not unsigned BYTE indexes (high-bit inputs differ).
	// Sol: SS:BP-1C..BP-14, nine saved terrain BYTES. Reko's fp is a
	// Sol: frame-pointer placeholder, not a file pointer; fp-30 was off by two.
	unsigned char SavedCombatTerrainFlags[9];
	unsigned short KuritaMessageIndex; // Sol: WORD SS:BP-8; initialized by Kurita encounter setup, not a text pointer.
	unsigned short EscapeAllowed; // Sol: WORD BP-0C escape latch; suppresses arena outcome when set.
	seg3EDB->EnemyTargetId = Enemy_All_CombatantId_Range_First;
	unsigned short Character_PosX = seg246C->CrescentHawk_MapPositionX;
	unsigned short Character_PosY = seg246C->CrescentHawk_MapPositionY;
	for (unsigned short GridId = 0; GridId < 9; ++GridId) // Sol: local 3x3 terrain cache, preserved for post-combat salvage.
		SavedCombatTerrainFlags[GridId] = seg246C->LocalTerrainFlags[GridId];

	unsigned short EncounterAssessmentResult = FALSE; // Sol: WORD BP-0A encounter gate; first-active-enemy path reachability from28DB.
	if (CombatRules == FALSE) // Sol: random encounter mode; nonzero callers supply prearranged combat state.
	{
		for (unsigned short NpcSlot = 0; NpcSlot < Enemy_Infantry_Record_Count; ++NpcSlot)
		{
			RoamingMapNpcRecordView far *Npc = (RoamingMapNpcRecordView far *)((unsigned char far *)&seg3092->EnemyInfantryPosX + NpcSlot * 0x1A); // Sol: D390 base, 26-byte NPC stride, not a contiguous X array.
			Npc->CurrentPositionX = seg3092->CombatantPackedX[NpcSlot + Enemy_Infantry_CombatantId_Range_First]; // Sol: original WORD4024+slot*2.
			Npc->CurrentPositionY = seg3092->CombatantPackedY[NpcSlot + Enemy_Infantry_CombatantId_Range_First]; // Sol: original WORD4056+slot*2.
		}
	}
	// Sol: 00A1..017C's split aliases cover complete matrices. No calls
	// Sol: observe the intermediate clear order; express the same BYTE writes directly.
	for (unsigned short CombatantId = 0; CombatantId < All_CombatantId_Range_Last; ++CombatantId)
	{
		for (unsigned short PlanByte = 0; PlanByte < 24; ++PlanByte) // Sol: twelve signed X/Y step pairs.
			seg3092->CombatMovementPlanBytes[CombatantId * 24 + PlanByte] = 2; // Sol: stop sentinel in either axis.
		for (unsigned short WeaponSlot = 0; WeaponSlot < 12; ++WeaponSlot) // Sol: twelve target slots, kick is slot11.
			seg3092->CombatWeaponTarget[CombatantId * 12 + WeaponSlot] = 0xFF; // Sol: no assigned target.
		for (unsigned short OrderByte = 0; OrderByte < 48; ++OrderByte) // Sol: twelve four-byte orders per combatant.
			seg3092->CombatMovementOrders[CombatantId * 48 + OrderByte] = 0xFF;
		if (CombatRules == FALSE)
		{
			seg3092->CombatantCasualtyFlags[CombatantId] = FALSE; // Sol: WORD death/wreck state.
			seg3092->CombatantActive[CombatantId] = FALSE; // Sol: prearranged mode preserves supplied active/position state.
			seg3092->TerrainOverlapRows[CombatantId] = 0;
			seg3092->CombatantFacing[CombatantId] = 0xFF;
			seg3092->CombatantPackedY[CombatantId] = 0xFFFF; // Sol: CBW of FF produces WORD -1.
			seg3092->CombatantPackedX[CombatantId] = 0xFFFF;
		}
	}
	// Sol: 0181 clears eight BYTES at3994 and3998, overlapping by four:
	// Sol: union is twelve action-state BYTES3994..399F, not sixteen WORDs.
	for (unsigned short FriendlyId = 0; FriendlyId < Enemy_All_CombatantId_Range_First; ++FriendlyId)
		seg3092->CombatantActionState[FriendlyId] = 0;
	for (unsigned short MechRecordId = 0; MechRecordId < 8; ++MechRecordId) // Sol: all eight friendly/enemy mech records.
	{
		seg3092->Mech_Heat[MechRecordId] = 0; // Sol: BYTE timed/inferno heat state.
		seg3092->Mech_HeatLevel[MechRecordId] = 0; // Sol: BYTE current heat.
	}
	short AllowEscapeCombat = FALSE; // Sol: WORD BP-38, reused in later turn/menu logic.
	unsigned short InfantryFormationSlot = 0, MechFormationSlot = 0;
	for (unsigned short PartyMemberId = 0; PartyMemberId < Enemy_Infantry_Record_First; ++PartyMemberId) // Sol: friendly character records0..7.
	{
		if (seg3092->Infantry[PartyMemberId].Name != Character_Dead
			&& (signed char)seg3092->Infantry[PartyMemberId].Piloting >= Character_OnFoot)
		{
			Offset_Packed_Position(seg3EDB->PartyInfantryFormationDeltaX[InfantryFormationSlot], seg3EDB->PartyInfantryFormationDeltaY[InfantryFormationSlot]); // Sol: compact formation index advances only for living on-foot members.
			unsigned short CombatantId = PartyMemberId + Friendly_Infantry_Combatant_Range_First;
			seg3092->CombatantPackedX[CombatantId] = seg246C->CrescentHawk_MapPositionX;
			seg3092->CombatantPackedY[CombatantId] = seg246C->CrescentHawk_MapPositionY;
			++seg3092->CombatantActive[CombatantId]; // Sol: ASM increments WORD4072+record*2; do not replace with boolean assignment.
			Combat_Move_Position(Character_PosX, Character_PosY);
			++InfantryFormationSlot;
		}
	}
	for (unsigned short MechRecordId = 0; MechRecordId < Friendly_Infantry_Combatant_Range_First; ++MechRecordId) // Sol: friendly mech records/combatants0..3.
	{
		if (*((unsigned char far *)&seg3092->Mechs[MechRecordId]) != MECH_Destroyed) // Sol: unsigned first Name BYTE atC724, not doubled typed-array stride.
		{
			Offset_Packed_Position(seg3EDB->FriendlyMechFormationDeltaX[MechFormationSlot], seg3EDB->FriendlyMechFormationDeltaY[MechFormationSlot]);
			++MechFormationSlot;
			seg3092->CombatantPackedX[MechRecordId] = seg246C->CrescentHawk_MapPositionX;
			seg3092->CombatantPackedY[MechRecordId] = seg246C->CrescentHawk_MapPositionY;
			++seg3092->CombatantActive[MechRecordId]; // Sol: original WORD increment, including prearranged combat.
			Combat_Move_Position(Character_PosX, Character_PosY);
		}
	}

	// Sol: 02DB..048A: prompt/result WORD BP-6 is only consumed when encounter gate is nonzero.
	unsigned short Bool_AcceptEngageCombat;
	if (CombatRules != FALSE)
		Bool_AcceptEngageCombat = TRUE; // Sol: prearranged encounters bypass consent prompt.
	else
	{
		Generate_Random_Encounter_Enemies();
		Menu_Memory_Variables(4); // Sol: force-description/sidebar layout.
		Draw_Top_Graphic_Sidebar();
		seg3092->EGATextColour = EGA_BrightWhite;
		EncounterAssessmentResult = FALSE;
		for (unsigned short EnemyId = Enemy_All_CombatantId_Range_First; EnemyId < All_CombatantId_Range_Last; ++EnemyId) // Sol: all enemy combatants12..23.
		{
			if (seg3092->CombatantActive[EnemyId] != FALSE
				&& seg3092->CombatantPackedX[EnemyId] != 0xFFFF
				&& seg3092->CombatantPackedY[EnemyId] != 0xFFFF) // Sol: WORD -1 sentinels, confirmed in clean Reko intermediate.
				EncounterAssessmentResult = TRUE;
		}
		if (EncounterAssessmentResult != FALSE)
			EncounterAssessmentResult = Combat_Assess_FirstEnemy_Reachability_28DB(); // Sol: first-active-enemy30-step probe, not movement-budget query.
		if (EncounterAssessmentResult != FALSE)
		{
			unsigned short NumberOfEnemyMechs = 0;
			Display_Text_From_Memory("Attacking force: "); // Memory ref: [3EDB:3402]
			for (unsigned short MechRecordId = Friendly_Infantry_Combatant_Range_First; MechRecordId < Enemy_Infantry_Record_First; ++MechRecordId) // Sol: enemy mech records4..7.
				if (*((unsigned char far *)&seg3092->Mechs[MechRecordId]) != MECH_Destroyed)
					++NumberOfEnemyMechs; // Sol: first Name BYTE; this count does not separately test active/position.
			if (NumberOfEnemyMechs != 0)
			{
				Display_Text_Dynamic_Value(NumberOfEnemyMechs);
				Display_Text_From_Memory(" 'Mech"); // Memory ref: [3EDB:3414]
				if (NumberOfEnemyMechs > 1) Display_Plural_Suffix_2A69();
				Display_Text_From_Memory(" and "); // Memory ref: [3EDB:341B]
			}
			unsigned short NumberOfEnemyHumans = 0;
			for (unsigned short CharacterRecordId = Enemy_Infantry_Record_First; CharacterRecordId < Enemy_Infantry_CombatantId_Range_First; ++CharacterRecordId) // Sol: enemy character records8..15, not combatant IDs.
			{
				unsigned short EnemyId = CharacterRecordId + Enemy_Infantry_RecordToCombatantId_Offset; // Sol: combatant IDs16..23.
				if (seg3092->Infantry[CharacterRecordId].Name != Character_Dead
					&& seg3092->CombatantActive[EnemyId] != FALSE
					&& seg3092->CombatantPackedX[EnemyId] != 0xFFFF
					&& seg3092->CombatantPackedY[EnemyId] != 0xFFFF)
					++NumberOfEnemyHumans;
			}
			Display_Text_Dynamic_Value(NumberOfEnemyHumans);
			Display_Text_From_Memory(" human"); // Memory ref: [3EDB:3421]
			if (NumberOfEnemyHumans != 1) Display_Plural_Suffix_2A69(); // Sol: zero also pluralizes.
			Display_Sentence_Period_2A7E();
			Menu_Memory_Variables(3); // Sol: consent/escape message layout.
			Draw_Top_Graphic_Sidebar();
			Display_Text_From_Memory("Engage in combat?"); // Memory ref: [3EDB:3428]
			Bool_AcceptEngageCombat = Prompt_Yes_No(TRUE);
		}
	}
	if (CombatRules != FALSE)
		EncounterAssessmentResult = TRUE;
	if (EncounterAssessmentResult != FALSE
		&& (Bool_AcceptEngageCombat != FALSE || (Rand_0x00_to_0xFF() & 3) == 0)) // Sol: declined engagement still forces combat when random low two bits are zero (1/4 under uniform bits).
	{
		if (Bool_AcceptEngageCombat == FALSE)
		{
			Draw_Top_Graphic_Sidebar();
			Display_Text_From_Memory("You did not evade them!"); // Memory ref: [3EDB:343A]
			Prompt_And_Wait_For_Key_2A4F();
			Bool_AcceptEngageCombat = TRUE; // Sol: 04A2..04BE stores1 after forced engagement.
		}
		if (seg3092->Kurita_AttackFlag != FALSE)
		{
			Draw_Message_Box();
			Display_Text_From_Memory_ScreenRetrace_KeyboardInput("These 'Mechs are unlike any you've fought against.  You feel uneasy."); // Sol: verified EXE text3EDB:3452; prior duplicate consent text was wrong.
			Keyboard_Get_ASCII_Hex_Input();
			KuritaMessageIndex = 0; // Sol:04CA initializes persistent five-message cursor before combat rounds.
		}
		if (CombatRules == 2) // Sol: prearranged rules variant2 performs an immediate map refresh.
		{
			PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY);
			Copy_Data_To_GraphicsMemory();
			Draw_Menu_MultiSelect_0E4B();
			EGA_DrawBox_Wrapper();
		}
		seg3092->Combat_Computer_Control = FALSE;
		Drain_Pending_Keyboard_Input_2A2B();
		if (seg3092->Disable_Computer_Control == FALSE)
			seg3092->Combat_Computer_Control = Return_Bool_Allow_Computer_Control_Dialog();
		Drain_Pending_Keyboard_Input_2A2B();
		seg3EDB->CombatMessageVerbosity = SettingsMenu_CombatMessages();
		Drain_Pending_Keyboard_Input_2A2B();
		seg3EDB->CombatDisplayGraphics = SettingsMenu_SeeCombatGraphics_bool();
		EscapeAllowed = FALSE;

		unsigned short RoundExitStatus = FALSE; // Sol: WORD BP-12 is round-exit status, not a duplicate boolean.
		while (RoundExitStatus == FALSE)
		{
			unsigned short Character_PosX = seg246C->CrescentHawk_MapPositionX; // Sol: round anchor WORD BP-20.
			unsigned short Character_PosY = seg246C->CrescentHawk_MapPositionY; // Sol: round anchor WORD BP-24.
			seg3092->Bool_EnemiesWithinRange = FALSE;
			if (seg3092->Combat_Computer_Control != FALSE)
			{
				// Sol: 07D0 handles friendly AI instead of opening the manual menu.
				Combat_Computer_Control_1482(0); // Sol: start at friendly combatant0.
				if (seg3092->Bool_EnemiesWithinRange != FALSE)
				{
					AllowEscapeCombat = TRUE;
					for (unsigned short MechRecordId = 0; MechRecordId < Friendly_Infantry_Combatant_Range_First; ++MechRecordId)
						if (*((unsigned char far *)&seg3092->Mechs[MechRecordId]) != MECH_Destroyed)
							AllowEscapeCombat = FALSE; // Sol: any surviving friendly mech suppresses this AI-only exit check.
					if (AllowEscapeCombat != FALSE)
					{
						AllowEscapeCombat = Rand_0x00_to_0xFF() & 3; // Sol: retain result0..3, not normalized boolean; zero continues.
						RoundExitStatus = AllowEscapeCombat;
					}
				}
				goto PlanAndExecuteEnemyTurn;
			}
			for (unsigned short FriendlyId = 0; FriendlyId < Enemy_All_CombatantId_Range_First; ++FriendlyId)
			{
				if (seg3092->CombatantActive[FriendlyId] != FALSE)
				{
					if (seg3092->CombatantPackedX[FriendlyId] == 0xFFFF || seg3092->CombatantPackedY[FriendlyId] == 0xFFFF)
						seg3092->CombatantActive[FriendlyId] = FALSE;
					for (unsigned short PlanByte = 0; PlanByte < 24; ++PlanByte) // Sol: still clears plan for a unit just deactivated; twelve step pairs.
						seg3092->CombatMovementPlanBytes[FriendlyId * 24 + PlanByte] = 2;
				}
			}
			AllowEscapeCombat = Combat_UI_Menu_Logic(); // Sol: WORD result;0 executes orders, nonzero requests exit.
			if (seg3092->Kurita_AttackFlag != FALSE
				&& (seg3092->CombatantPackedY[0] >= KuritaAttack_MinY
					|| (short)seg3092->CombatantPackedX[0] >= KuritaAttack_MinX
					|| seg3092->CombatantPackedY[0] < KuritaAttack_MaxY
					|| (short)seg3092->CombatantPackedX[0] < KuritaAttack_MaxX)) // Sol: target is mech slot0; unsigned Y, signed X exactly match JNC/JC versus JGE.
				AllowEscapeCombat = 2; // Sol: special Kurita boundary exit, bypasses ordinary escape roll.
			if (AllowEscapeCombat != FALSE)
			{
				if (AllowEscapeCombat != 2)
					AllowEscapeCombat = (Rand_0x00_to_0xFF() & 3) != 0; // Sol: SBB/INC yields0 for low bits00,1 otherwise (3/4 under uniform bits).
				Menu_Memory_Variables(3); // Sol: escape-result text layout.
				Draw_Top_Graphic_Sidebar();
				if ((short)CombatRules >= 2)
					AllowEscapeCombat = FALSE; // Sol: prearranged rules>=2 prohibit escape, including boundary result2.
				if (seg3092->Kurita_AttackFlag != FALSE && AllowEscapeCombat != 2)
				{
					Display_Text_From_Memory("You cannot escape these Jenners!"); // Memory ref: [3EDB:3497]
					AllowEscapeCombat = FALSE;
					Prompt_And_Wait_For_Key_2A4F();
				}
				else if (AllowEscapeCombat == FALSE)
				{
					Display_Text_From_Memory("You do not escape! The enemies engage in combat"); // Memory ref: [3EDB:34B8]
					Prompt_And_Wait_For_Key_2A4F();
				}
				else if ((short)CombatRules > 0)
					seg3092->Bool_EnemiesWithinRange = TRUE; // Sol: successful prearranged exit feeds later end-of-round state.
			}
			RoundExitStatus = AllowEscapeCombat;
			if (AllowEscapeCombat == FALSE)
			{
				for (unsigned short FriendlyId = 0; FriendlyId < Enemy_All_CombatantId_Range_First; ++FriendlyId) // Sol: friendly mech/personnel combatants0..11.
				{
					if (seg3092->CombatantActive[FriendlyId] == FALSE) continue;
					if (seg3092->CombatantActionState[FriendlyId] != 0)
					{
						Combat_Computer_Control(FriendlyId, FALSE); // Sol:1631:03AB handles per-unit AI action state.
						continue;
					}
					if (seg3092->CombatMovementPlanBytes[FriendlyId * 24] != 2
						|| seg3092->CombatMovementOrders[FriendlyId * 48] == 0xFF)
						continue; // Sol: skip existing step plan or absent first order.
					Move_Map_View_To_Packed_Position_17BB(seg3092->CombatantPackedX[FriendlyId], seg3092->CombatantPackedY[FriendlyId]);
					PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY);
					Update_Cached_Map_Origin_1DF8();
					if (FriendlyId < Friendly_Infantry_Combatant_Range_First)
						Combat_Mech_Movement(FriendlyId, (short)(signed char)seg3092->CombatMovementOrders[FriendlyId * 48]); // Sol: CBW sign-extends movement mode BYTE.
					else
						Combat_Infantry_Movement(FriendlyId);
					Combat_Calculate_Movement(FriendlyId);
				}
			}
PlanAndExecuteEnemyTurn: // Sol: native turn handoff at 183B:0826.
			if (AllowEscapeCombat == FALSE)
			{
				// Sol:0826..089D enemy AI planning and twelve-slice mechanics handoff.
				Move_Map_View_To_Packed_Position_17BB(Character_PosX, Character_PosY);
				seg3092->EnemyPersonnelFlightPossible = FALSE; // Sol: WORD374C cleared before enemy AI; later influences personnel flight.
				Combat_Computer_Control_1482(Enemy_All_CombatantId_Range_First); // Sol: enemy combatants start at12.
				Move_Map_View_To_Packed_Position_17BB(Character_PosX, Character_PosY);
				PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY);
				Combat_Mechanics((short)CombatRules > 0); // Sol: signed WORD rules comparison -> WORD boolean; no StatusTextPtr assignment exists.

				if (seg3EDB->Bool_MainCharactersAlive != FALSE && seg3092->Traitor_InParty != FALSE && seg3092->TraitorWarning != FALSE)
				{
					Menu_Memory_Variables(6); // Sol: betrayal narrative layout.
					Draw_Top_Graphic_Sidebar();
					Draw_Menu_Border(0);
					short TraitorMemberId = (signed char)seg3092->Traitor_CharacterId; // Sol: BYTE D331 sign-extends into BP-44.
					short TraitorMechId = (signed char)seg3092->Infantry[TraitorMemberId].Piloting; // Sol: BYTE C620 -> WORD; read value, not address.
					unsigned char TraitorNameId = seg3092->Infantry[TraitorMemberId].Name;
					if (TraitorMechId == Character_OnFoot)
					{
						// Sol:08FF..09AD on-foot traitor is killed under Rex's interrogation.
						Display_Text_From_Memory("You watched "); //3EDB:34E9
						Display_Text_From_Memory(seg3EDB->CharacterNameList[TraitorNameId]);
						Display_Text_From_Memory(" carefully, and saw that "); //3EDB:34F6
						Display_Text_From_Memory(" the Dracos didn't shoot at him at all.  Under Rex's interrogation, "); //3EDB:3510
						Display_Text_From_Memory("which involved fists, it turns out that he was a Kurita "); //3EDB:3555
						Display_Text_From_Memory("double agent!  You put an end to that situation, to say the least."); //3EDB:358E
						unsigned short TraitorCombatantId = TraitorMemberId + Friendly_Infantry_Combatant_Range_First; // Sol: character record -> on-foot combatant.
						Register_Persistent_Map_Effect_27C9(Sprite_Impact_Small, seg3092->CombatantPackedX[TraitorCombatantId], seg3092->CombatantPackedY[TraitorCombatantId]);
						seg3092->CombatantPackedY[TraitorCombatantId] = 0xFFFF;
						seg3092->CombatantPackedX[TraitorCombatantId] = 0xFFFF;
					}
					else if (seg3092->Mechs[TraitorMechId].PilotId != TraitorMemberId)
					{
						// Sol:0BD4..0CA1 traitor is a rider; existing pilot survives.
						seg3092->Mechs[TraitorMechId].RiderId = MECH_NoRider;
						Register_Persistent_Map_Effect_27C9(Sprite_Impact_Small, seg3092->CombatantPackedX[TraitorMechId], seg3092->CombatantPackedY[TraitorMechId]);
						Display_Text_From_Memory(seg3EDB->CharacterNameList[TraitorNameId]);
						Display_Text_From_Memory(" knew you were suspicious of him, and he tried to sabotage the Mech "); //3EDB:37B8
						Display_Text_From_Memory("he was riding in.  He was a Kurita double agent!  "); //3EDB:37FD
						unsigned char PilotRecordId = seg3092->Mechs[TraitorMechId].PilotId;
						Display_Text_From_Memory(seg3EDB->CharacterNameList[seg3092->Infantry[PilotRecordId].Name]);
						Display_Text_From_Memory(" was able to overcome him, and threw the doublecrosser out the cockpit.  "); //3EDB:3830
						Display_Text_From_Memory("Then he \"accidentally\" stepped on him, to rid you of the problem."); //3EDB:387A
					}
					else
					{
						// Sol:09C8 reads unsigned rider BYTE; sentinel is WORD00FF, NOTFFFF.
						unsigned short RiderRecordId = seg3092->Mechs[TraitorMechId].RiderId;
						Display_Text_From_Memory(seg3EDB->CharacterNameList[TraitorNameId]);
						Display_Text_From_Memory(" tried to turn and fire on you!  He's a Kurita double agent!  "); //3EDB:35D1
						if (RiderRecordId != MECH_NoRider && seg3092->Infantry[RiderRecordId].Skill_Piloting != 0)
						{
							// Sol:0B40 skilled rider takes over, traitor dies; mech retained.
							Display_Text_From_Memory(seg3EDB->CharacterNameList[seg3092->Infantry[RiderRecordId].Name]);
							Display_Text_From_Memory(" was able to overcome him and throw him out the cockpit.  "); //3EDB:36F6
							Display_Text_From_Memory("Then he took command of the Mech, but in the process he must have "); //3EDB:3731
							Display_Text_From_Memory("jolted the controls, because the Mech stepped on the doublecrosser."); //3EDB:3774
							seg3092->Mechs[TraitorMechId].PilotId = RiderRecordId;
							seg3092->Mechs[TraitorMechId].RiderId = MECH_NoRider;
							Register_Persistent_Map_Effect_27C9(Sprite_Impact_Small, seg3092->CombatantPackedX[TraitorMechId], seg3092->CombatantPackedY[TraitorMechId]);
						}
						else
						{
							if (RiderRecordId == MECH_NoRider)
							{
								Display_Text_From_Memory("You were able to stop him, but it involved destroying the Mech he "); //3EDB:3610
								Display_Text_From_Memory("was piloting also."); //3EDB:3653
							}
							else
							{
								Display_Text_From_Memory(seg3EDB->CharacterNameList[seg3092->Infantry[RiderRecordId].Name]);
								Display_Text_From_Memory(" was able to stop him, but in the process he destroyed the Mech's "); //3EDB:3666
								Display_Text_From_Memory("cockpit.  He was able to eject in time, but the doublecrossing pilot didn't."); //3EDB:36A9
								seg3092->Infantry[RiderRecordId].Piloting = Character_OnFoot;
								unsigned short RiderCombatantId = RiderRecordId + Friendly_Infantry_Combatant_Range_First;
								seg3092->CombatantActive[RiderCombatantId] = TRUE;
								seg3092->CombatantPackedX[RiderCombatantId] = seg3092->CombatantPackedX[TraitorMechId];
								seg3092->CombatantPackedY[RiderCombatantId] = seg3092->CombatantPackedY[TraitorMechId];
							}
							// Sol:0AD4 destroys first Name BYTE; wreck uses exact anchor, unlike normal -1/-1 placement.
							*((unsigned char far *)&seg3092->Mechs[TraitorMechId]) = MECH_Destroyed;
							unsigned short WreckSprite = seg3092->CombatantSpriteFamilyOffset[TraitorMechId] == MECH_Sprite_LOCUST ? Sprite_Locust_Wreck : Sprite_Commando_Wreck; // Sol: CMP family,1 / SBB / INC / ADD80.
							Register_Persistent_Map_Effect_27C9(WreckSprite, seg3092->CombatantPackedX[TraitorMechId], seg3092->CombatantPackedY[TraitorMechId]);
							seg3092->CombatantPackedY[TraitorMechId] = 0xFFFF;
							seg3092->CombatantPackedX[TraitorMechId] = 0xFFFF;
							seg3092->CombatantActive[TraitorMechId] = FALSE;
						}
					}
					Wait_For_50Hz_Then_Check_Input();
					Keyboard_Get_ASCII_Hex_Input();
					seg3092->Infantry[TraitorMemberId].Name = Character_Dead;
					seg3092->CombatantActive[TraitorMemberId + Friendly_Infantry_Combatant_Range_First] = FALSE;
					seg3092->Traitor_InParty = FALSE;
					seg3092->Traitor_BattleProbability = 0x7F; // Sol: BYTE D330 restored127; probabilistic role remains separately documented.
				}
				// Sol:0CDB..0D0E latches special arena-escape condition; signed X only, no Y check.
				if (seg3092->Bool_AllowEscape != FALSE && seg3092->CombatantActive[0] != FALSE
					&& (short)seg3092->CombatantPackedX[0] > 0x0900 && (short)seg3092->CombatantPackedX[0] < 0x0A07)
					EscapeAllowed = TRUE; // Sol: open X interval0900..0A07 for active mech slot0.

				RoundExitStatus = TRUE;
				for (unsigned short EnemyId = Enemy_All_CombatantId_Range_First; EnemyId < All_CombatantId_Range_Last; ++EnemyId)
				{
					if (seg3092->CombatantPackedX[EnemyId] == 0xFFFF || seg3092->CombatantPackedY[EnemyId] == 0xFFFF)
						seg3092->CombatantActive[EnemyId] = FALSE;
					if (seg3092->CombatantActive[EnemyId] != FALSE) RoundExitStatus = FALSE;
				}
				if (RoundExitStatus == FALSE && seg3092->EnemyPersonnelFlightPossible != FALSE && CombatRules == FALSE)
				{
					unsigned short AnyEnemyMechActive = FALSE;
					for (unsigned short EnemyId = Enemy_All_CombatantId_Range_First; EnemyId < Enemy_Infantry_CombatantId_Range_First; ++EnemyId)
						if (seg3092->CombatantActive[EnemyId] != FALSE) AnyEnemyMechActive = TRUE;
					if (AnyEnemyMechActive != FALSE)
					{
						unsigned short SavedMapX = seg246C->CrescentHawk_MapPositionX, SavedMapY = seg246C->CrescentHawk_MapPositionY;
						seg3092->EnemyPersonnelFlightPossible = FALSE; // Sol: suppresses subsequent global-flight coin flip in this branch.
						unsigned short AnyPersonnelFled = FALSE;
						for (unsigned short EnemyId = Enemy_Infantry_CombatantId_Range_First; EnemyId < All_CombatantId_Range_Last; ++EnemyId)
						{
							if (seg3092->CombatantActive[EnemyId] == FALSE) continue;
							seg246C->CrescentHawk_MapPositionX = seg3092->CombatantPackedX[EnemyId];
							seg246C->CrescentHawk_MapPositionY = seg3092->CombatantPackedY[EnemyId];
							short TargetId = (signed char)seg3092->CombatWeaponTarget[EnemyId * 12]; // Sol:0DF3 CBW, no low7-bit mask or sentinel guard in original.
							if ((short)Combat_Operation_0BB5(seg3092->CombatantPackedX[TargetId], seg3092->CombatantPackedY[TargetId]) > 25) // Sol: signed range metric greater than25; not Euclidean pixels.
							{
								seg3092->CombatantActive[EnemyId] = FALSE;
								seg3092->CombatantPackedY[EnemyId] = 0xFFFF;
								seg3092->CombatantPackedX[EnemyId] = 0xFFFF;
								AnyPersonnelFled = TRUE;
							}
						}
						if (AnyPersonnelFled != FALSE)
						{
							Draw_Message_Box();
							Display_Text_From_Memory_ScreenRetrace_KeyboardInput("Some of the enemy humans have fled!"); //3EDB:38BC
							Keyboard_Get_ASCII_Hex_Input();
						}
						seg246C->CrescentHawk_MapPositionX = SavedMapX;
						seg246C->CrescentHawk_MapPositionY = SavedMapY;
					}
					if (seg3092->EnemyPersonnelFlightPossible != FALSE)
						seg3092->EnemyPersonnelFlightPossible = Rand_0x00_to_0xFF() & 1; // Sol: no enemy mech active -> 50/50 global flight, assuming uniform bit0.
					if (seg3092->EnemyPersonnelFlightPossible != FALSE)
					{
						Draw_Message_Box();
						Display_Text_From_Memory_ScreenRetrace_KeyboardInput("The enemy humans have fled!"); //3EDB:38E0
						Keyboard_Get_ASCII_Hex_Input();
						RoundExitStatus = TRUE;
					}
				}
				if (CombatRules == 1 && seg3092->CombatantActive[0] == FALSE)
					RoundExitStatus = TRUE; // Sol: rules1 ends when combat mech0 is inactive.
				if (EscapeAllowed == FALSE && CombatRules == 2
					&& seg3092->CombatantActive[0] == FALSE && seg3092->Bool_AllowEscape == FALSE)
					RoundExitStatus = TRUE; // Sol: rules2 has additional escape-story flag gating.
				if (EscapeAllowed != FALSE || seg3EDB->Bool_MainCharactersAlive == FALSE) RoundExitStatus = TRUE;
				if (seg3092->Kurita_AttackFlag != FALSE)
				{
					unsigned short MessagesRemaining = RoundExitStatus != FALSE ? 5 - KuritaMessageIndex : 1; // Sol: ongoing rounds show one message; final round drains remaining five-entry sequence.
					while (MessagesRemaining != 0) // Sol:0FF0 tests OLD count before decrement, not post-decrement equality.
					{
						--MessagesRemaining;
						if (KuritaMessageIndex >= 5) continue;
						if (KuritaMessageIndex == 1)
							Display_Animation_Scene(AnimationO02_NeuroHelment, AnimationPlayback_CallerOwnsRedraw); // Sol: helmet cutscene before message1; does NOT skip/increment message.
						Draw_Message_Box();
						unsigned short MessageToShow = KuritaMessageIndex++;
						Display_Text_From_Memory_ScreenRetrace_KeyboardInput(seg3EDB->KuritaMissionTextMessages[MessageToShow]); // Sol: FAR pointer stride4 handled by typed table.
						Keyboard_Get_ASCII_Hex_Input();
						if (KuritaMessageIndex == 3) // Sol: after message2 (Citadel destroyed), load ruined Citadel.
						{
							DOS_Load_Map_Files(4, MAP_Destroyed_Citadel);
							Map_NineGrid_Parent_1DA8();
							seg2FE8->Current_Map = MAP_Destroyed_Citadel;
						}
						Menu_Memory_Variables(4);
						Draw_Top_Graphic_Sidebar();
					}
				}
			}
			if (seg3092->Combat_Computer_Control != FALSE  //w009E = Combat_Computer_Control
			&& seg3092->DisableInput == FALSE //w3938 - Disable Input
			&& Pending_Input() != FALSE)
			{
				seg3092->Combat_Computer_Control = FALSE; //w009E = Combat_Computer_Control
				Drain_Pending_Keyboard_Input_2A2B();
			}
		}
	}

	// Sol:1037..1481 post-combat outcomes. BP-0A is an encounter gate,
	// Sol: not a damage sprite or movement budget; helper28DB supplies its result.
	if (EncounterAssessmentResult == FALSE)
	{
		Combat_Character_Pos_Grid(Character_PosX, Character_PosY); // Sol:140D original outer WORD map anchor.
		goto ExitCombat;
	}

	Menu_Memory_Variables(0x03);
	Draw_Top_Graphic_Sidebar();

	if ((short)CombatRules < 1 || CombatRules == 3) // Sol: random encounter / salvage-enabled special mode.
	{
		// Sol:1060 requires accepted engagement, normal victory (exit status0),
		// Sol: and surviving main characters. Reko lost the BP-6 consent gate.
		if (Bool_AcceptEngageCombat == FALSE || AllowEscapeCombat != 0
		 || seg3EDB->Bool_MainCharactersAlive == FALSE)
		{
			if (seg3EDB->Bool_MainCharactersAlive != FALSE)
			{
				Draw_Top_Graphic_Sidebar();
				Display_Text_From_Memory("You have eluded your enemies!"); // DS:3936
				Prompt_And_Wait_For_Key_2A4F();
			}
		}
		else
		{
			Menu_Memory_Variables(0x01);
			Draw_Menu_Border(0x01);
			Draw_Top_Graphic_Sidebar();

			unsigned short AnyEnemyCasualty = FALSE; // Sol: reused WORD BP-3A, not mech-only.
			for (unsigned short EnemyId = Enemy_All_CombatantId_Range_First; EnemyId < All_CombatantId_Range_Last; ++EnemyId)
				if (seg3092->CombatantCasualtyFlags[EnemyId] != FALSE) // DS:393C WORD casualty/wreck table.
					AnyEnemyCasualty = TRUE;
			if (AnyEnemyCasualty != FALSE)
			{
				Display_Text_From_Memory("After an invigorating scuffle, you defeated the Kuritans."); // DS:38FC
				Prompt_And_Wait_For_Key_2A4F();
			}

			unsigned short HasFriendlyMech = FALSE;
			for (unsigned short MechId = 0; MechId < Friendly_Infantry_Combatant_Range_First; ++MechId)
				if (*((unsigned char far*)&seg3092->Mechs[MechId]) != MECH_Destroyed) // DS:C724 + MechId*0x7D; first name BYTE.
					HasFriendlyMech = TRUE;

			unsigned short HasEnemyMechWreck = FALSE;
			for (unsigned short EnemyId = Enemy_All_CombatantId_Range_First; EnemyId < Enemy_Infantry_CombatantId_Range_First; ++EnemyId)
				if (seg3092->CombatantCasualtyFlags[EnemyId] != FALSE)
					HasEnemyMechWreck = TRUE;
			if (HasFriendlyMech != FALSE && HasEnemyMechWreck != FALSE)
			{
				for (unsigned short PartyId = 0; PartyId < Enemy_Infantry_Record_First; ++PartyId) // Sol: friendly records0..7.
				{
					// Sol:115B CBW;115C CMP AX,00FFh. Preserve BUG-017:
					// Sol: a dead FF name becomes FFFF and DOES NOT fail this test.
					if ((short)(signed char)seg3092->Infantry[PartyId].Name != Character_Dead
					 && seg3092->Infantry[PartyId].Skill_Tech != 0) // DS:C61D
					{
						Salvage_Armour_Dialog(); // Sol:0DAB:0002 once, first qualifying tech.
						break;
					}
				}
			}

			unsigned short HasFriendlyMechSalvageFlag = FALSE;
			for (unsigned short MechId = 0; MechId < Friendly_Infantry_Combatant_Range_First; ++MechId)
				if (seg3092->CombatantCasualtyFlags[MechId] != FALSE
				 || seg3092->Bool_DeadInfantry[MechId] != FALSE)
					HasFriendlyMechSalvageFlag = TRUE; // Sol:3954 WORDs0..3 tested here; legacy "DeadInfantry" label remains uncertain.

			unsigned short HasAvailablePilot = FALSE;
			for (unsigned short PartyId = 0; PartyId < Enemy_Infantry_Record_First; ++PartyId)
				if (seg3092->Infantry[PartyId].Name != Character_Dead
				 && seg3092->Infantry[PartyId].Skill_Piloting != 0 // DS:C61C
				 && (signed char)seg3092->Infantry[PartyId].Piloting >= Character_OnFoot) // DS:C620 signed BYTE;8+ unassigned/on foot.
					HasAvailablePilot = TRUE;

			unsigned short HasFreeMechSlot = FALSE;
			for (unsigned short MechId = 0; MechId < Friendly_Infantry_Combatant_Range_First; ++MechId)
				if (*((unsigned char far*)&seg3092->Mechs[MechId]) == MECH_Destroyed)
					HasFreeMechSlot = TRUE; // Sol: FF slot can accept a salvaged mech.
			unsigned short TerrainAllowsMechSalvage = TRUE;
			for (unsigned short GridId = 0; GridId < 9; ++GridId)
				if ((SavedCombatTerrainFlags[GridId] & 0x80) != 0) // Sol:1232 saved 3x3 terrain BYTE high bit prohibits mech salvage.
					TerrainAllowsMechSalvage = FALSE;
			if (HasFriendlyMechSalvageFlag != FALSE && HasAvailablePilot != FALSE
			 && HasFreeMechSlot != FALSE && TerrainAllowsMechSalvage != FALSE)
				Salvage_Mechs_Dialog(); // Sol:0DAB:04F9; no independent enemy-wreck test on this branch.

			Loot_Enemy_Soldiers_Dialog(); // Sol:1251 called on every victory path, regardless of either salvage dialog.
			seg3092->Party_HealthRecoveryTimer = 0; // DS:D335 BYTE reset.
			Menu_Memory_Variables(0x03);
			Draw_Top_Graphic_Sidebar();

			unsigned short TotalMissingHealth = 0; // Sol: WORD BP-3A accumulator, NOT boolean; wraps at16 bits.
			for (unsigned short PartyId = 0; PartyId < Enemy_Infantry_Record_First; ++PartyId)
				if (seg3092->Infantry[PartyId].Name != Character_Dead)
					TotalMissingHealth = (unsigned short)(TotalMissingHealth
					 + 10 * (signed char)seg3092->Infantry[PartyId].Body
					 - (signed char)seg3092->Infantry[PartyId].Health); // Sol:128F..12A0 signed BYTE inputs; max health =10*Body.
			if (TotalMissingHealth != 0)
				Heal_Characters(MedEquip_None); // Sol:1431:000A WORD0; this does not pass the injury sum.
		}

		if (seg3EDB->Bool_MainCharactersAlive != FALSE)
		{
			Menu_Memory_Variables(0x04);
			Draw_Top_Graphic_Sidebar();
			Draw_Health_and_C_Bills_Sidebar(TRUE);
			Draw_Message_Box();
			Display_Text_From_Memory("You return to where you were before combat took place."); // DS:3954
			Drain_Pending_Keyboard_Input_2A2B();
			Keyboard_Get_ASCII_Hex_Input();

			// Sol:1330..136A restores the OUTER pre-combat map anchor,
			// Sol: not the shadowed round-local combat viewport coordinates.
			Move_Map_View_To_Packed_Position_17BB(Character_PosX, Character_PosY);
			Combat_Load_9Grid_Map_2835();
			PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY);
			Copy_Data_To_GraphicsMemory();
		}
		goto ExitCombat;
	}

	if (seg3EDB->Bool_MainCharactersAlive == FALSE)
		goto ExitCombat;
	if (seg3092->Kurita_AttackFlag != FALSE) // Sol:136D..140C scripted outcome takes precedence over normal mode messages.
	{
		if (AllowEscapeCombat == 2) // Sol: Kurita boundary exit, not ordinary escape1 or AI exit3.
		{
			Menu_Memory_Variables(0x03);
			Draw_Top_Graphic_Sidebar();
			Display_Text_From_Memory("You have eluded your enemies!"); // DS:39F7
			Prompt_And_Wait_For_Key_2A4F();
		}
		goto ExitCombat;
	}
	if (CombatRules == 1) // Sol: training/base-return mode.
	{
		Draw_Message_Box();
		Display_Text_From_Memory_ScreenRetrace_KeyboardInput("You should return to base now."); // DS:398B
	}
	else
	{
		if (EscapeAllowed != FALSE) // Sol: escape latch suppresses arena outcome.
			goto ExitCombat;
		Draw_Message_Box();
		seg3092->Bool_WonInArena = TRUE; // DS:D32D BYTE; outcome tests friendly mech slot0, not character health.
		if (*((unsigned char far*)&seg3092->Mechs[Character_Jason]) == MECH_Destroyed)
		{
			Display_Text_From_Memory_ScreenRetrace_KeyboardInput("The crowd boos resoundingly.  You have lost."); // DS:39CA
			seg3092->Bool_WonInArena = FALSE;
		}
		else
			Display_Text_From_Memory_ScreenRetrace_KeyboardInput("Congratulations!  You have won!"); // DS:39AA; verified expanded EXE text.
	}
	Keyboard_Get_ASCII_Hex_Input();

ExitCombat:
	// Sol:141A..147B common to ALL exits, including no encounter and death.
	for (unsigned short NpcSlot = 0; NpcSlot < Enemy_Infantry_Record_Count; ++NpcSlot)
	{
		RoamingMapNpcRecordView far* Npc = (RoamingMapNpcRecordView far*)
			((unsigned char far*)&seg3092->EnemyInfantryPosX + NpcSlot * 0x1A); // DS:D390/D392, record stride26; not contiguous arrays.
		unsigned short CombatantId = Enemy_Infantry_CombatantId_Range_First + NpcSlot;
		seg3092->CombatantPackedX[CombatantId] = Npc->CurrentPositionX; // DS:4024 + slot*2 WORD.
		seg3092->CombatantPackedY[CombatantId] = Npc->CurrentPositionY; // DS:4056 + slot*2 WORD.
		seg3092->CombatantAnimationSelector[CombatantId] = 0xFF; // DS:397C; no animation.
		seg3092->CombatantAnimationSelector[NpcSlot] = 0xFF; // Sol: DS:396C only slots0..7, NOT all friendly0..11.
		seg3092->CombatantSpriteFrame[CombatantId] = 0x10; // DS:40AA; world NPC standing frame.
	}
}

// 183B:1482: void Combat_Computer_Control_1482(Stack int16 TargetMechId)
// Called from:
//      Combat_Parent_000A
// Sol: Summary: Plan a group of computer-controlled combatants.
// Sol: Outline: Walk the requested actor range and call the single-actor planning routine for eligible entries.
void Combat_Computer_Control_1482(unsigned short StartCombatantId)
{
	// Sol:1482..14C2 applies1631:03AB to twelve active combatants:
	// Sol: start0 -> friendly0..11, start12 -> enemy12..23. Not mech-only.
	for (unsigned short RelativeId = 0; RelativeId < Enemy_All_CombatantId_Range_First; ++RelativeId)
	{
		unsigned short CombatantId = RelativeId + StartCombatantId;
		if (seg3092->CombatantActive[CombatantId] != FALSE) // Sol: WORD active table.
			Combat_Computer_Control(CombatantId, FALSE);
	}
}

// 183B:14C3: Register word16 Combat_UI_Menu_Logic()
// Called from:
//      Combat_Parent_000A
// Sol: Summary: Handle the friendly turn-planning menu.
// Sol: Outline: Read menu choices and dispatch movement, weapons, kicks, scanning or combat settings.
unsigned short Combat_UI_Menu_Logic()
{
	// Sol:14C3..1773. All six SS:BP locals are WORDs, not BYTEs/pointers.
	unsigned short InitializeDefaultChoice = TRUE; // BP-4; only first menu selects Begin Fight.
	unsigned short SelectedCombatantId = 0; // BP-0A; this is an ID, not a count.
	while (SelectedCombatantId < Enemy_All_CombatantId_Range_First
	 && seg3092->CombatantActive[SelectedCombatantId] == FALSE) // DS:406A WORD active flags, friendly0..11.
		++SelectedCombatantId;
	// Sol: no explicit no-active-friendly guard: scan may yield12. Next Unit
	// Sol: assumes at least one active friendly; leave this original precondition visible.

	unsigned short FleeRequested = FALSE; // BP-2; AX return0 Begin Fight /1 Flee.
	unsigned short FinishPlanning = FALSE; // BP-6; independent of text addresses and selected unit.
	unsigned short MenuChoice = 1; // BP-0C; initial1 is overwritten by menu result before use.
	if (seg3092->Disable_Computer_Control != FALSE) // DS:0090 WORD; only initially selected unit is cleared here.
		seg3092->CombatantActionState[SelectedCombatantId] = 0;

	while (FinishPlanning == FALSE)
	{
		Menu_Memory_Variables(0x04);
		Draw_Top_Graphic_Sidebar();
		Display_Friendly_Combatant_Description_18E8(SelectedCombatantId, FALSE, FALSE);
		seg3092->EGATextColour = EGA_BrightWhite; // DS:37FE WORD.
		if (seg3092->CombatantActionState[SelectedCombatantId] != 0) // DS:3994 BYTE nonzero action/AI state.
		{
			Display_Text_From_Memory("\rThe computer is currently moving this unit.\r"); // DS:3A42; EXE text.
			Combat_Computer_Control(SelectedCombatantId, TRUE); // Sol:1631:03AB; preview/planning flag1.
		}
		else
			Combat_MovementTarget_unknown_1774(SelectedCombatantId, TRUE); // Sol:1774 selection marker + friendly movement preview, independently audited.

		Menu_Memory_Variables(0x03);
		Draw_Top_Graphic_Sidebar();
		seg3092->EGATextColour = EGA_BrightWhite;
		if (SelectedCombatantId < Friendly_Infantry_Combatant_Range_First) // Sol: mech combatants0..3.
		{
			Display_Text_From_Memory("Walk\rRun\rJump\rUse Weapons\rKick\rComputer\rScan Unit\rNext Unit\rFlee\rBegin Fight\r"); // DS:3A6F
			seg305B->Menu_HorizontalSections = 10; // Sol: ten mech choices; zero-based indices0..9.
		}
		else // Sol: friendly infantry4..11, assuming entry precondition above.
		{
			Display_Text_From_Memory("Move\rClear Moves\rUse Weapon\rComputer\rScan Unit\rNext Unit\rFlee\rBegin Fight\r"); // DS:3ABC
			seg305B->Menu_HorizontalSections = 8; // Sol: eight personnel choices; indices0..7.
		}
		if (InitializeDefaultChoice != FALSE)
		{
			seg305B->Menu_DefaultOptions = seg305B->Menu_HorizontalSections - 1; // DS:00C8; initially Begin Fight.
			InitializeDefaultChoice = FALSE;
		}
		Drain_Pending_Keyboard_Input_2A2B();
		MenuChoice = Display_Menu_Choices_And_Check(0x03); // Sol:15F2 AX WORD, not truncated BYTE.
		// Sol:1602 signed comparison; last two choices are Flee / Begin Fight.
		if ((short)MenuChoice >= (short)(seg305B->Menu_HorizontalSections - 2))
		{
			++FinishPlanning; // Sol: original increments BP-6, never a text pointer.
			if (MenuChoice == seg305B->Menu_HorizontalSections - 2)
				FleeRequested = TRUE;
		}

		// Sol:161A mech0/1/2 = Walk/Run/Jump; personnel0 = Move.
		if ((SelectedCombatantId < Friendly_Infantry_Combatant_Range_First && (short)MenuChoice < 3)
		 || (SelectedCombatantId >= Friendly_Infantry_Combatant_Range_First && MenuChoice == 0))
			Combat_Select_Movement_Plan_For_Turn(SelectedCombatantId, MenuChoice);

		if (SelectedCombatantId >= Friendly_Infantry_Combatant_Range_First && MenuChoice == 1) // Sol: personnel Clear Moves.
		{
			for (unsigned short OrderByte = 0; OrderByte < 48; ++OrderByte) // BP-8; entire24-pair movement row, not weapon targets.
				seg3092->CombatMovementOrders[SelectedCombatantId * 48 + OrderByte] = 0xFF; // DS:32C6
			seg3092->CombatantActionState[SelectedCombatantId] = 0;
			Combat_MovementTarget_unknown_1774(SelectedCombatantId, FALSE);
		}
		if (SelectedCombatantId < Friendly_Infantry_Combatant_Range_First && MenuChoice == 4) // Sol: mech Kick.
			Combat_Kick_Target(SelectedCombatantId);

		if (((SelectedCombatantId < Friendly_Infantry_Combatant_Range_First && MenuChoice == 5)
		  || (SelectedCombatantId >= Friendly_Infantry_Combatant_Range_First && MenuChoice == 3))
		 && seg3092->Disable_Computer_Control == FALSE) // Sol: Computer choice remains displayed when disabled, but does nothing.
			Combat_Computer_Control(SelectedCombatantId, TRUE);
		if ((SelectedCombatantId < Friendly_Infantry_Combatant_Range_First && MenuChoice == 3)
		 || (SelectedCombatantId >= Friendly_Infantry_Combatant_Range_First && MenuChoice == 2)) // Sol: Use Weapon(s).
			Combat_Weapon_UI_0004(SelectedCombatantId);
		if ((SelectedCombatantId < Friendly_Infantry_Combatant_Range_First && MenuChoice == 6)
		 || (SelectedCombatantId >= Friendly_Infantry_Combatant_Range_First && MenuChoice == 4)) // Sol: Scan Unit.
			Scan_Enemies(SelectedCombatantId);

		if (MenuChoice == seg305B->Menu_HorizontalSections - 3) // Sol:1716 Next Unit, mech7/personnel5.
		{
			do
			{
				++SelectedCombatantId;
				if (SelectedCombatantId >= Enemy_All_CombatantId_Range_First)
					SelectedCombatantId = 0; // Sol: wrap at12; never select an enemy.
			} while (seg3092->CombatantActive[SelectedCombatantId] == FALSE);
			seg305B->Menu_DefaultOptions = SelectedCombatantId < Friendly_Infantry_Combatant_Range_First ? 7 : 5; // DS:00C8; keep Next Unit highlighted in new menu type.
		}
	}
	return FleeRequested; // Sol:176C AX WORD consumed by parent0605; planning does not execute the round here.
}

// 183B:1774: void Combat_MovementTarget_unknown_1774(Stack Eq_21 TargetMechId, Stack Eq_21 SelectedMovementMode)
// Called from:
//      Combat_Browse_Scan_Targets_1467
//      Combat_Weapon_UI_0004
//      Combat_Select_Weapon_Target_UI
//      Combat_Computer_Control
//      Combat_UI_Menu_Logic
//      Combat_Select_Movement_Plan_For_Turn
// Sol:1774..193A selection marker + friendly movement preview; legacy name retained.
// Sol: Summary: Preview a selected actor and its movement.
// Sol: Outline: Optionally recenter, draw the actor marker, and render friendly step glyphs into shared endpoint coordinates.
void Combat_MovementTarget_unknown_1774(unsigned short TargetId, unsigned short Bool)
{
	unsigned short UnitPackedX = seg3092->CombatantPackedX[TargetId]; // DS:4004 WORD, initial BP-6.
	unsigned short UnitPackedY = seg3092->CombatantPackedY[TargetId]; // DS:4036 WORD, initial BP-0A.

	if (Bool != FALSE)
	{
		// Sol: Bool is WORD redraw/recenter flag, not movement mode.
		Move_Map_View_To_Packed_Position_17BB(UnitPackedX, UnitPackedY); // Sol:17A4 distinct WORD X,Y, not Y,Y.
		PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY); //A44B - Character Position X //A44D - Character position Y
		Copy_Data_To_GraphicsMemory();
		Draw_Menu_MultiSelect_0E4B();
	}

	short MarkerSize = 1, MarkerOffsetX = 0, MarkerOffsetY = 0; // Sol: WORD BP-6/-2/-4, reused stack slots.

	if ((short)TargetId < Friendly_Infantry_Combatant_Range_First
	 || ((short)TargetId >= Enemy_All_CombatantId_Range_First && (short)TargetId <= Enemy_Mech_CombatantId_Range_Last))
	{
		MarkerSize = 3; // Sol: friendly0..3/enemy12..15 mechs use3x3 marker cells; infantry uses1x1.
		MarkerOffsetX = -1;
		MarkerOffsetY = -2; // Sol: original FFFE WORD, not BYTE FE.
	}

	EGA_DrawBox_Wrapper(); // Sol:1F3D:06C3 graphics/background preparation; own body audit pending.
	seg246C->wB782 = 1; // DS:B782 WORD; only adapter3 branch of2B87 consults this flag.

	for (short MarkerRow = 0; MarkerRow < MarkerSize; ++MarkerRow) // Sol:1819..1843 BP-8 row counter.
		DrawCall_Combat_Menu(26 + MarkerOffsetX, 12 + MarkerOffsetY + MarkerRow,
			MarkerSize, EGA_BrightWhite); // Sol:207F:2B87(x,y,width,color); each call draws8 scanlines, not coordinate endpoints.

	//Friendly Combatants
	if ((short)TargetId < Enemy_All_CombatantId_Range_First) // Sol:1844 friendly0..11 only; enemies stop after marker.
	{
		if ((short)TargetId < Friendly_Infantry_Combatant_Range_First) // Sol: friendly mech0..3.
			Combat_Mech_Movement(TargetId, (short)(signed char)seg3092->CombatMovementOrders[TargetId * 48]); //Sol: 183B:1853..1869, mode BYTE load then WORD push
		else
			Combat_Infantry_Movement(TargetId); //Friendly Infantry

		Combat_Calculate_Movement(TargetId); // Sol: generates signed dx/dy step pairs, not actual movement.

		// Sol: Reconstructed 183B:187C..1934: SS:BP-0E holds the glyph,
		// Sol: SS:BP-0D is its NUL. Reko's fp-16 is not file-backed data.
		unsigned char MovementPreviewGlyph[2] = { 0, 0 }; // Sol: native189A..1902 passes SS:BP-0E; retain explicit stack-segment binding in a port.
		short StepByte = 0, PreviewScreenX = 26, PreviewScreenY = 12; // Sol: preview character-cell origin, not packed world coordinates.
		unsigned char far *Steps = &seg3092->CombatMovementPlanBytes[TargetId * 24];
		// Sol:1903 sentinel read precedes189A byte-count guard: a full row
		// Sol: probes the next row's first BYTE. Preserve observed order in research C.
		while (Steps[StepByte] != 2)
		{
			if (StepByte >= 24) break; // Sol: at most12 dx/dy pairs;2 stops, FF means signed -1.
			short DeltaX = (signed char)Steps[StepByte++];
			short DeltaY = (signed char)Steps[StepByte++];
			PreviewScreenX += DeltaX;
			PreviewScreenY += DeltaY;
			MovementPreviewGlyph[0] = seg3EDB->CombatMovementPreviewGlyphs[(DeltaX + 1) + (DeltaY + 1) * 4];
			// Sol: four-column direction glyph table3B06; FAR SS:glyph plus WORD X,Y,colors15/0.
			Draw_EGA_Text_To_Screen((unsigned char far *)MovementPreviewGlyph,
				PreviewScreenX, PreviewScreenY, EGA_BrightWhite, EGA_Black);
		}
		seg3092->HorizontalStatsLineOffset = PreviewScreenX; // DS:3778 WORD endpoint, origin if empty; enemy branch leaves unchanged.
		seg3092->VerticalStatsLineOffset = PreviewScreenY; // DS:377A WORD endpoint.
	}
}

// 183B:193B: void Combat_Calculate_Movement(Register Eq_21 ds, Stack Eq_21 TargetMechId)
// Called from:
//      Combat_Computer_Control
//      Combat_Parent_000A
//      Combat_MovementTarget_unknown_1774
//      Combat_Select_Movement_Plan_For_Turn
// Sol: Summary: Build an actor's combat movement steps.
// Sol: Outline: Follow destination orders, append signed steps, subtract terrain costs, and restore the saved facing.
void Combat_Calculate_Movement(unsigned short CombatantId)
{
	// Sol: TODO ASM audit: SUB CX,13 wraps WORD before SAR; narrow
	// Sol: ScreenX-13 before shifting.1A30 uses signed combatant<12, unlike C.
	// Sol: Reconstructed 183B:193B..1C1E; destination orders -> signed step
	// Sol: pairs. Stored actor position is NOT moved by this preview/path builder.
	unsigned char far *Orders = &seg3092->CombatMovementOrders[CombatantId * 48]; //DS:32C6
	unsigned char far *Steps = &seg3092->CombatMovementPlanBytes[CombatantId * 24]; //DS:40B4
	for (short i = 0; i < 24; ++i) Steps[i] = 2;
	seg3092->CrescentHawk_CompassPositionX = seg246C->CrescentHawk_MapPositionX;
	seg3092->CrescentHawk_CompassPositionY = seg246C->CrescentHawk_MapPositionY;
	short SavedFacing = (signed char)seg3092->CombatantFacing[CombatantId];
	short ScreenX = 26, ScreenY = 12, OrderByte = 0, StepByte = 0;
	for (;;)
	{
		short Mode = (signed char)Orders[OrderByte++];
		if (Mode == -1) break; // Sol: FF termination, NOT mode01.
		unsigned short Region = (unsigned short)Orders[OrderByte++] << 8;
		unsigned short TargetX = (short)(signed char)Orders[OrderByte++] | (Region & 0x0F00);
		unsigned short TargetY = (short)(signed char)Orders[OrderByte++] | (Region & 0xF000);
		if ((CombatantId < 12 && seg3092->CombatantActionState[CombatantId] == 0) || SavedFacing == -1)
			seg3092->CombatantFacing[CombatantId] = Get_Target_Compass_Direction(
				seg3092->CrescentHawk_CompassPositionX, seg3092->CrescentHawk_CompassPositionY, TargetX, TargetY);
		seg3092->CombatDestinationBlocked = 0;
		while ((short)seg3092->CharacterMovementPointsRemaining > 0)
		{
			if ((seg3092->CrescentHawk_CompassPositionX == TargetX && seg3092->CrescentHawk_CompassPositionY == TargetY)
				|| seg3092->CombatDestinationBlocked != 0) break;
			Position_0006(CombatantId, TargetX, TargetY, ScreenX, ScreenY, 0);
			ScreenX += seg3092->CombatChosenStepX;
			ScreenY += seg3092->CombatChosenStepY;
			// Sol: Append low BYTE of WORD outputs, FF means -1. ASM has no
			// Sol: StepByte<24 guard; validate upstream budgets before managed port.
			Steps[StepByte++] = (unsigned char)seg3092->CombatChosenStepX;
			Steps[StepByte++] = (unsigned char)seg3092->CombatChosenStepY;
			short Cell = (ScreenY >> 1) * 24 + ((ScreenX - 13) >> 1);
			short Mask = (signed char)seg3EDB->CombatMovementTerrainMasks[(ScreenX & 1) + (ScreenY & 1) * 2];
			if ((ScreenX & 1) && (seg246C->CrescentHawk_MapPositionX & 1)) { ++Cell; Mask ^= 10; }
			if ((ScreenY & 1) && (seg246C->CrescentHawk_MapPositionY & 1)) { Cell += 24; Mask ^= 5; }
			unsigned short Tile = seg246C->CombatMap[seg246C->CachedMapOriginIndex + Cell];
			short Cost = 1;
			if (Mode != 2 && Tile < 0x40 && (Tile & Mask) != 0)
				Cost = (Tile & 0xF0) == 0x20 ? 3 : 2;
			short Remaining = (short)seg3092->CharacterMovementPointsRemaining - Cost;
			seg3092->CharacterMovementPointsRemaining = Remaining < 0 ? 0 : Remaining;
			// Sol: Step is appended BEFORE cost subtraction; final terrain step
			// Sol: can cost more than the budget left. Do not silently invert this.
		}
	}
	seg3092->CombatantFacing[CombatantId] = (unsigned char)SavedFacing;
}

// 183B:1C1F: void Combat_Select_Movement_Plan_For_Turn(Register Eq_21 ds, Stack Eq_21 TargetMechId, Stack Eq_5339 SelectedMovementMode)
// Called from:
//      Combat_UI_Menu_Logic
// Sol: Summary: Let the player build a combat movement plan.
// Sol: Outline: Preview steps and facing, check clearance and budget, and commit or cancel the per-actor plan.
void Combat_Select_Movement_Plan_For_Turn(unsigned short CombatantId, unsigned short SelectedMovementMode)
{
	// Sol: TODO ASM audit: native3B38 is "ing.";3B3D/3B8C/3C5B start CR
	// Sol: and3C0D ends CR. Restore punctuation/control bytes in fixing pass.
	// Sol:1C1F..2230 WORD arguments/locals; friendly manual planning UI.
	unsigned char far* Orders = &seg3092->CombatMovementOrders[CombatantId * 48]; // DS:32C6; twelve4-BYTE destinations.
	if ((short)CombatantId < Enemy_All_CombatantId_Range_First)
	{
		if (seg3092->CombatantActionState[CombatantId] != 0)
		{
			for (short i = 0; i < 48; ++i) Orders[i] = 0xFF;
			Combat_MovementTarget_unknown_1774(CombatantId, TRUE); // Sol: original clears orders, previews while action state still nonzero.
		}
		seg3092->CombatantActionState[CombatantId] = 0; // Sol: hand control back to player.
	}
	unsigned short AcceptMovementMode = TRUE; // SS:BP-0C; dec before prompt /inc on Yes, not text-address values12/13.
	short ExistingMode = (signed char)Orders[0]; // BP-0E; FF -> -1 means no existing orders.
	if ((short)CombatantId < Friendly_Infantry_Combatant_Range_First && ExistingMode != -1
	 && (SelectedMovementMode != MovementMode_Jump || seg3092->Mechs[CombatantId].JumpMove != JumpJets_Removed)
	 && ExistingMode != SelectedMovementMode)
	{
		--AcceptMovementMode;
		Menu_Memory_Variables(4);
		Draw_Top_Graphic_Sidebar();
		Display_Text_From_Memory("This mech is now "); // DS:3B24
		Append_Large_Text_To_Memory(&seg3092->DynamicString, seg3EDB->SelectedMovementModeText[ExistingMode]); // Sol:3CD4 FAR pointer table, stride4.
		if (ExistingMode == MovementMode_Run)
			Append_Text_To_Memory(&seg3092->DynamicString, "n"); // DS:3B36; Run+n+ing.
		Append_Text_To_Memory(&seg3092->DynamicString, "ing"); // DS:3B38
		Display_Text_From_Memory(&seg3092->DynamicString);
		Display_Text_From_Memory("Do you wish to "); // DS:3B3D
		Display_Text_From_Memory(seg3EDB->SelectedMovementModeText[SelectedMovementMode]);
		Display_Text_From_Memory(" instead?"); // DS:3B4E
		if (Prompt_Yes_No(TRUE) != FALSE)
		{
			++AcceptMovementMode;
			Draw_Top_Graphic_Sidebar();
			Display_Text_From_Memory("All your current movement orders have been deleted."); // DS:3B58
			Display_Text_From_Memory("Press a key to enter new moves."); // DS:3B8C
			for (short i = 0; i < 48; ++i) Orders[i] = 0xFF;
			Combat_MovementTarget_unknown_1774(CombatantId, FALSE);
			Keyboard_Get_ASCII_Hex_Input();
		}
	}
	if (AcceptMovementMode == FALSE) goto PlanningDone; // Sol: No preserves existing manual orders; earlier AI takeover remains applied.

	short DestinationSlot = 0; // SS:BP-0A BYTE offset, not count/vertical cursor.
	while (DestinationSlot < 48 && Orders[DestinationSlot] != 0xFF)
		DestinationSlot += 4; // Sol: scan ONLY mode BYTES at four-byte boundaries.
	if ((short)CombatantId < Friendly_Infantry_Combatant_Range_First)
		Combat_Mech_Movement(CombatantId, SelectedMovementMode);
	else
		Combat_Infantry_Movement(CombatantId);
	Combat_Calculate_Movement(CombatantId);
	// Sol:1E43/1E50 also save cursor WORDs to BP-16/-1A, but never read them.
	// Sol: path builder193B does not update3778/377A;1774 is the endpoint renderer.
	Menu_Memory_Variables(4);
	Draw_Top_Graphic_Sidebar();

	if (seg3092->CharacterMovementPointsRemaining == 0) // DS:3770 WORD exhausted budget / inhibited movement.
	{
		if (SelectedMovementMode == MovementMode_Jump && seg3092->Mechs[CombatantId].JumpMove == JumpJets_Removed)
		{
			Display_Text_From_Memory("This 'Mech has no jump jets."); // DS:3BAD
			goto WaitForMovementMessage;
		}
		if ((short)CombatantId < Friendly_Infantry_Combatant_Range_First && seg3092->Mech_HeatLevel[CombatantId] == MECH_Heat_Max)
		{
			Display_Text_From_Memory("This 'Mech has overheated and shut down."); // DS:3BCA; heat30.
			goto WaitForMovementMessage;
		}
		if ((short)CombatantId >= Friendly_Infantry_Combatant_Range_First && (short)CombatantId < Enemy_All_CombatantId_Range_First)
		{
			seg3092->CurrentMech_Overheated = 0; // DS:4592 WORD; infantry must not inherit stale mech penalty.
			seg3092->CurrentMech_LegDamage = 0; // DS:377C WORD.
		}
		if (seg3092->CurrentMech_LegDamage != 0 || seg3092->CurrentMech_Overheated != 0)
		{
			Display_Text_From_Memory("Movement is inhibited by "); // DS:3BF3
			if (seg3092->CurrentMech_LegDamage != 0)
				Display_Text_From_Memory("leg damage."); // DS:3C0D; takes precedence over heat.
			else if (seg3092->CurrentMech_Overheated != 0)
				Display_Text_From_Memory("this 'Mech's heat level."); // DS:3C1A
		}
		else
		{
			Display_Text_From_Memory("You can't "); // DS:3C33
			if ((short)CombatantId < Friendly_Infantry_Combatant_Range_First)
				Display_Text_From_Memory(seg3EDB->SelectedMovementModeText[SelectedMovementMode]);
			else
				Display_Text_From_Memory("move"); // DS:3C3E
			Display_Text_From_Memory(" any further this turn."); // DS:3C43
			if ((short)CombatantId < Friendly_Infantry_Combatant_Range_First && SelectedMovementMode != MovementMode_Run)
				Display_Text_From_Memory("You might move farther if you tried running."); // DS:3C5B
		}
		seg3092->CurrentMech_Overheated = 0;
		seg3092->CurrentMech_LegDamage = 0; // Sol:1F7A normal status paths clear penalties; no-jets/shutdown branches bypass this.
WaitForMovementMessage:
		Prompt_And_Wait_For_Key_2A4F();
		goto PlanningDone;
	}

	Display_Text_From_Memory("You have "); // DS:3C89
	Display_Text_Dynamic_Value(seg3092->CharacterMovementPointsRemaining);
	Display_Text_From_Memory(" movement points left.  Move the cursor to where you want to go."); // DS:3C93; verified EXE.
	DrawCall_Combat_Menu(seg3092->HorizontalStatsLineOffset, seg3092->VerticalStatsLineOffset, 1, 14); // Sol: single-cell yellow destination cursor, not return-value state.
	unsigned short MoveCommand; // SS:BP-12 WORD; retain FFxx commands without BYTE truncation.
	do
	{
		MoveCommand = Keyboard_Convert_To_MoveCommands(Keyboard_Get_ASCII_Hex_Input());
		short DeltaX = 0, DeltaY = 0; // BP-4/-8 WORD signed -1/0/+1.
		// Sol:2005 eleven-slot jump table indexed by command-FFAF, NOT doubled C case values.
		switch (MoveCommand)
		{
		case COMMAND_MOVE_SouthEast: DeltaX = 1; DeltaY = 1; break;
		case COMMAND_MOVE_South: DeltaY = 1; break;
		case COMMAND_MOVE_SouthWest: DeltaX = -1; DeltaY = 1; break;
		case COMMAND_MOVE_East: DeltaX = 1; break;
		case COMMAND_MOVE_West: DeltaX = -1; break;
		case COMMAND_MOVE_NorthEast: DeltaX = 1; DeltaY = -1; break;
		case COMMAND_MOVE_North: DeltaY = -1; break;
		case COMMAND_MOVE_NorthWest: DeltaX = -1; DeltaY = -1; break;
		}
		seg3092->HorizontalStatsLineOffset += DeltaX;
		if ((short)seg3092->HorizontalStatsLineOffset < 13 || (short)seg3092->HorizontalStatsLineOffset > 39) // Sol: inclusive map-panel character columns13..39.
			seg3092->HorizontalStatsLineOffset -= DeltaX;
		seg3092->VerticalStatsLineOffset += DeltaY;
		if ((short)seg3092->VerticalStatsLineOffset < 0 || (short)seg3092->VerticalStatsLineOffset > 24) // Sol: inclusive rows0..24, WORD sign check.
			seg3092->VerticalStatsLineOffset -= DeltaY;
		if ((DeltaX | DeltaY) != 0) // Sol: requested delta, even when a boundary rejects cursor movement.
		{
			unsigned short SavedMapX = seg246C->CrescentHawk_MapPositionX; // BP-10.
			unsigned short SavedMapY = seg246C->CrescentHawk_MapPositionY; // BP-14.
			Offset_Packed_Position(seg3092->HorizontalStatsLineOffset - 26, seg3092->VerticalStatsLineOffset - 12); // Sol: cursor cell offsets from preview anchor.
			unsigned short DestinationX = seg246C->CrescentHawk_MapPositionX & 0x7F; // BP-2 local tileX.
			unsigned short DestinationY = seg246C->CrescentHawk_MapPositionY & 0x7F; // BP-6 local tileY.
			unsigned short RegionByte = ((seg246C->CrescentHawk_MapPositionY & 0xF000)
				| (seg246C->CrescentHawk_MapPositionX & 0x0F00)) >> 8; // BP-18 packed highY/lowX region nibbles.
			unsigned short WriteDestination = TRUE; // BP-8 reused.
			for (short OrderByte = 0; OrderByte < DestinationSlot; OrderByte += 4)
				if ((short)(signed char)Orders[OrderByte + 1] == RegionByte
				 && (short)(signed char)Orders[OrderByte + 2] == DestinationX
				 && (short)(signed char)Orders[OrderByte + 3] == DestinationY)
				{
					WriteDestination = FALSE;
					Orders[DestinationSlot] = 0xFF; // Sol:2159 clears provisional slot, not the matching earlier order.
				}
			if (WriteDestination != FALSE)
			{
				// Sol:217B no DestinationSlot<48 guard; preserve BUG-018 potential row overrun.
				Orders[DestinationSlot] = (unsigned char)SelectedMovementMode;
				Orders[DestinationSlot + 1] = (unsigned char)RegionByte;
				Orders[DestinationSlot + 2] = (unsigned char)DestinationX;
				Orders[DestinationSlot + 3] = (unsigned char)DestinationY;
			}
			// Sol: same DestinationSlot reused on EVERY cursor move: live provisional waypoint, not append-per-key.
			seg246C->CrescentHawk_MapPositionX = SavedMapX;
			seg246C->CrescentHawk_MapPositionY = SavedMapY;
			unsigned short SavedCursorX = seg3092->HorizontalStatsLineOffset; // BP-1C.
			unsigned short SavedCursorY = seg3092->VerticalStatsLineOffset; // BP-36.
			Combat_MovementTarget_unknown_1774(CombatantId, FALSE); // Sol: recalculate/render path and update endpoint.
			seg3092->HorizontalStatsLineOffset = SavedCursorX;
			seg3092->VerticalStatsLineOffset = SavedCursorY; // Sol: restore user's destination cursor, not renderer's reachable endpoint.
			DrawCall_Combat_Menu(SavedCursorX, SavedCursorY, 1, 14);
		}
	} while (MoveCommand != 0x20 && MoveCommand != 0x0D); // Sol: Space/Enter FINISH entry; no cancel/rollback branch here.
PlanningDone:
	Draw_Top_Graphic_Sidebar(); // Sol:2226 common exit; UI is void, orders already stored.
}

// 183B:2231: void Combat_Kick_Target(Register Eq_21 ds, Stack Eq_21 TargetMechId)
// Called from:
//      Combat_UI_Menu_Logic
// Sol: Summary: Choose a target for a friendly mech's kick.
// Sol: Outline: Find eligible nearby targets, display choices, and store the selected melee order.
void Combat_Kick_Target(unsigned short FriendlyAttackingMechId)
{
	// Sol: TODO ASM audit: native3CFA starts "This 'Mech", not "This mech".
	// Sol:2231..22BB WORD friendly mech record/combatant ID0..3.
	Menu_Memory_Variables(0x04);
	Draw_Top_Graphic_Sidebar();

	// Sol:2231 helper reads C748/C749 + id*0x7D, actuator BYTES+24/+25.
	// Sol: bit08 = intact hip on each leg; BOTH required to offer a kick.
	// Sol: other leg/arm actuator bits are not eligibility gates here.
	if ((seg3092->Mechs[FriendlyAttackingMechId].CurrentActuators[0] & 0x08) != 0
	 && (seg3092->Mechs[FriendlyAttackingMechId].CurrentActuators[1] & 0x08) != 0)
	{		
		Display_Text_From_Memory("Choose the enemy to kick: "); // Memory ref: [3EDB:3CE0]  
		Combat_Select_Weapon_Target_UI(FriendlyAttackingMechId, (Mech_Kick - 1), 0x0B); // Sol:1543:07CB WORD args: zero-based kick weapon index20h, reserved target slot11 of12. Selects an order, not immediate damage.
	}
	else
	{		
		Display_Text_From_Memory("This mech can't kick because it has damaged hips. Press a key."); // Memory ref: [3EDB:3CFA] 
		Keyboard_Get_ASCII_Hex_Input();
	}

	seg305B->Menu_DefaultOptions = 0x04; // Sol:22AC DS:00C8 WORD; keep mech menu's Kick index4 highlighted on either outcome.
}

// 183B:22BC: void Combat_Mech_Movement(Stack Eq_21 TargetMechId, Stack Eq_5339 SelectedMovementMode)
// Called from:
//      Combat_Computer_Control
//      Combat_Parent_000A
//      Combat_MovementTarget_unknown_1774
//      Combat_Select_Movement_Plan_For_Turn
// Sol: Summary: Set a mech's movement budget and mode.
// Sol: Outline: Apply chassis speed, actuator losses, heat penalty, run/jump rules and shutdown to the shared movement budget.
void Combat_Mech_Movement(unsigned short MechId, unsigned short SelectedMovementMode)
{
	// Sol: Reconstructed 183B:22BC..2473. Mech RECORD ID, not combatant ID:
	// Sol: enemy callers normalize combatant12..15 to record4..7.
	seg3092->CurrentMech_Overheated = 0; //DS:4592 heat penalty WORD
	seg3092->CurrentMech_LegDamage = 0; //DS:377C WORD
	short Points = seg3092->Mechs[MechId].WalkMove;
	if (SelectedMovementMode == MovementMode_Jump)
		Points = seg3092->Mechs[MechId].JumpMove;
	else
	{
		unsigned char First = seg3092->Mechs[MechId].CurrentActuators[0];
		unsigned char Second = seg3092->Mechs[MechId].CurrentActuators[1];
		if (((First | Second) & 8) == 0)
		{
			Points = 1;
			seg3092->CurrentMech_LegDamage = 1;
		}
		else
		{
			if ((First & 8) == 0 || (Second & 8) == 0)
			{
				Points = (Points >> 1) + (seg3092->Mechs[MechId].WalkMove & 1); //Sol: ceil(walk/2)
				seg3092->CurrentMech_LegDamage = 1;
			}
			// Sol: SHR-style signed positive mask 4,2,1; old Reko increment
			// Sol: created an unbounded loop. High actuator nibble is not read.
			for (short Mask = 4; Mask > 0; Mask >>= 1)
			{
				if ((First & Mask) == 0) { --Points; seg3092->CurrentMech_LegDamage = 1; }
				if ((Second & Mask) == 0) { --Points; seg3092->CurrentMech_LegDamage = 1; }
				if (seg3092->CurrentMech_LegDamage != 0 && Points == 0) Points = 1;
			}
		}
		short HeatPenalty = seg3092->Mech_HeatLevel[MechId] / 5; //Sol: signed IDIV, truncates toward zero
		seg3092->CurrentMech_Overheated = HeatPenalty;
		Points -= HeatPenalty;
		if (SelectedMovementMode == MovementMode_Run)
		{
			Points += Points >> 1; //Sol: SAR, NOT (points+points)/2
			if (seg3092->Mechs[MechId].WalkMove & 1) ++Points;
		}
	}
	// Sol: Original equality test is ==30, not >=30; jump bypasses leg/heat
	// Sol: penalties above but NOT this shutdown or final negative clamp.
	if (seg3092->Mech_HeatLevel[MechId] == MECH_Heat_Max) Points = 0; // Sol: exactly30 shutdown, not >=30.
	seg3092->CharacterMovementPointsRemaining = Points < 0 ? 0 : Points;
}

// 183B:2474: void Combat_Infantry_Movement(Stack Eq_21 TargetMechId)
// Called from:
//      Combat_Computer_Control
//      Combat_Parent_000A
//      Combat_MovementTarget_unknown_1774
//      Combat_Select_Movement_Plan_For_Turn
// Sol: Summary: Set personnel movement capacity.
// Sol: Outline: Use the character's statistics and condition to initialise the infantry movement budget.
void Combat_Infantry_Movement(unsigned short CombatantId)
{
	// Sol:2474..24EF WORD combatant ID, NOT infantry record ID. Legal
	// Sol: personnel callers use friendly4..11 or enemy16..23 (not mechs).
	seg3092->CharacterMovementPointsRemaining = 6; // DS:3770 WORD; fixed enemy budget, no enemy stats/armour lookup.
	if ((short)CombatantId < Enemy_All_CombatantId_Range_First)
	{
		unsigned short PartyRecordId = CombatantId - Friendly_Infantry_Combatant_Range_First; // Sol:248F subtracts4 from stack argument; friendly records0..7.
		short Points = (3 * (signed char)seg3092->Infantry[PartyRecordId].Dexterity) >> 2; // Sol:249F signed BYTE IMUL -> AX, two SARs; floor(3*Dex/4), no BYTE product truncation. DS:C616 + record*0x11.
		seg3092->CharacterMovementPointsRemaining = Points;
		if (Points < 3)
			seg3092->CharacterMovementPointsRemaining = 3; // Sol: minimum BEFORE armour penalty, not a final minimum.
		if ((signed char)seg3092->Infantry[PartyRecordId].ArmourType > ArmourType_FlakVest) // DS:C621 signed BYTE; Flak Suit/environment suits/ablative halve movement; None/Vest do not.
			seg3092->CharacterMovementPointsRemaining = (short)seg3092->CharacterMovementPointsRemaining >> 1; // Sol:24D2 SAR; minimum3 may become1.
	}
	if ((short)seg3092->CharacterMovementPointsRemaining > 8)
		seg3092->CharacterMovementPointsRemaining = 8; // Sol:24DB final maximum AFTER armour, not before. Does not clear mech heat/leg penalty globals.
}

// 183B:24F0: Register Eq_5339 SettingsMenu_CombatMessages()
// Called from:
//      Combat_Parent_000A
// Sol: Summary: Choose combat-message verbosity.
// Sol: Outline: Display the setting choices and return the selected WORD; the parent stores it.
unsigned short SettingsMenu_CombatMessages()
{
	// Sol:24F0..2555 returns AX WORD; parent stores it in2E38. This helper does not store the setting itself.
	Menu_Memory_Variables(0x03);
	Draw_Top_Graphic_Sidebar();	
	Display_Text_From_Memory("Combat messages:\rNone\rBrief\rVerbose\r"); // DS:3D3A; verified EXE separators.
		
	seg305B->Menu_VerticalSections = 0x02; //w00C2 - Menu Vertical Lines 
	seg305B->Menu_HorizontalSections = 0x03; //w00C6 - Menu Horizontal Options
	seg305B->Menu_DefaultOptions = seg3EDB->CombatMessageVerbosity; //w2E38 - Combat Message Verbosity Setting [Menu option]

	unsigned short CombatMessagesOptionSelected = Display_Menu_Choices_And_Check(0x03); // Sol: AX/BP-2 WORD; indices0 None,1 Brief,2 Verbose; no new validation.
	seg305B->Menu_VerticalSections = 0x00; //w00C2 - Menu Vertical Lines
	return CombatMessagesOptionSelected;
}

// 183B:2556: Register uint16 SettingsMenu_SeeCombatGraphics_bool()
// Called from:
//      Combat_Parent_000A
// Sol: Summary: Choose whether combat effects are shown.
// Sol: Outline: Display the graphics prompt and return its WORD result; the parent stores it.
unsigned short SettingsMenu_SeeCombatGraphics_bool()
{	
	// Sol:2556..2590 returns Prompt_Yes_No AX WORD; parent stores2E3A. No BYTE truncation or forced boolean conversion.
	Menu_Memory_Variables(0x03);
	Draw_Top_Graphic_Sidebar();	
	Display_Text_From_Memory("See combat graphics:"); // Memory ref: [3EDB:3D5E]

	return Prompt_Yes_No(seg3EDB->CombatDisplayGraphics); //w2E3A - See Combat Graphics [Menu Option]
}

// 183B:2591: void Scan_Enemies(Stack Eq_21 PtrScanningMech)
// Called from:
//      Combat_UI_Menu_Logic
// Sol: Summary: Open the combat scan menu.
// Sol: Outline: Browse visible eligible opponents and show the selected actor's status information.
void Scan_Enemies(unsigned short ScanningCombatantId)
{
	// Sol:2591..273C WORD selected friendly combatant ID, not a pointer.
	unsigned short AllowDetailedMechScan = TRUE; // SS:BP-4; include-mechs/detail flag, not count. Browser0DAB:1467 skips mech IDs when0.
	Menu_Memory_Variables(3);
	Draw_Top_Graphic_Sidebar();
	Display_Text_From_Memory("\x06\x0FScan...\rFriends\rEnemies\rCancel\r"); // DS:3D73; original color controls and CR-separated choices.
	seg305B->Menu_VerticalSections = 1; // DS:00C2 WORD layout.
	seg305B->Menu_HorizontalSections = 3; // DS:00C6 choices0 Friends,1 Enemies,2 Cancel.
	seg305B->Menu_DefaultOptions = 0;
	short ScanOption = Display_Menu_Choices_And_Check(3); // SS:BP-8 WORD; original signed comparisons.
	unsigned short CanBrowseTargets = TRUE; // BP-2; availability/permission flag, NOT number of humans.
	if (ScanOption == 1) // Sol: restrictions apply only to enemy browsing.
	{
		Menu_Memory_Variables(4);
		Draw_Top_Graphic_Sidebar();
		if ((short)ScanningCombatantId >= Friendly_Infantry_Combatant_Range_First) // Sol: on-foot friendly4..11 cannot scan enemy mechs.
		{
			unsigned short AnyActiveEnemyMech = FALSE; // BP-6.
			for (unsigned short EnemyId = Enemy_All_CombatantId_Range_First; EnemyId < Enemy_Infantry_CombatantId_Range_First; ++EnemyId)
				if (seg3092->CombatantActive[EnemyId] != FALSE) // DS:4082 + relativeId*2 aliases active WORD slots12..15.
					AnyActiveEnemyMech = TRUE;
			if (AnyActiveEnemyMech != FALSE)
			{
				Display_Text_From_Memory("You can only see and describe enemy humans.\rPress a key.\r"); // DS:3D94; message only if an enemy mech is active.
				Keyboard_Get_ASCII_Hex_Input();
			}
			CanBrowseTargets = FALSE;
			AllowDetailedMechScan = FALSE;
		}
		else if (seg3092->Mechs[ScanningCombatantId].SensorHits == 2) // DS:C79B + id*0x7D = record+77; exactly two hits, not >=2.
		{
			Display_Text_From_Memory("Because your sensors are destroyed you can't scan enemy mechs.\rPress a key.\r"); // DS:3DCD
			AllowDetailedMechScan = FALSE; // Sol:266B clears capability BEFORE waiting; BP-2 remains1.
			Keyboard_Get_ASCII_Hex_Input();
			Draw_Top_Graphic_Sidebar();
		}
	}
	for (unsigned short EnemyId = Enemy_Infantry_CombatantId_Range_First; EnemyId < All_CombatantId_Range_Last; ++EnemyId)
		if (seg3092->CombatantActive[EnemyId] != FALSE
		 && seg3092->CombatantPackedX[EnemyId] != CombatantPosition_Unused) // Sol:269D WORD sentinelFFFF, confirmed .dis; ASM pretty-prints sign-extended imm8 asFF.
			CanBrowseTargets = TRUE; // Sol: only X tested, no extra Y/visibility/name filter.
	CanBrowseTargets += AllowDetailedMechScan; // Sol:26B7 BP-2 sum0..2 is tested for zero, not a population count.
	if (CanBrowseTargets == 0 && ScanOption == 1)
	{
		Menu_Memory_Variables(4);
		Draw_Top_Graphic_Sidebar();
		Display_Text_From_Memory("There are no enemy humans in this battle."); // DS:3E19
		Prompt_And_Wait_For_Key_2A4F();
	}
	Draw_Top_Graphic_Sidebar();
	if (ScanOption < 0) ScanOption = 0; // Sol: negative return falls back to Friends; Cancel2 skips browser.
	if (ScanOption < 2 && CanBrowseTargets != 0)
		Combat_Browse_Scan_Targets_1467(ScanningCombatantId,
			Enemy_All_CombatantId_Range_First * ScanOption, AllowDetailedMechScan); // Sol: WORD args(id,start0/12,detail flag); browser handles target filtering.
	seg305B->Menu_VerticalSections = 0;
	seg305B->Menu_DefaultOptions = (short)ScanningCombatantId < Friendly_Infantry_Combatant_Range_First ? 6 : 4; // DS:00C8; restore Scan Unit default mech6/personnel4.
}

// 183B:273D: void Check_If_CriticalSlot_Destroyed(unsigned char MechId, unsigned char ComponentOffset)
// Called from:
//      Salvage_Armour_Dialog
// Sol: Summary: Read the structure supporting a critical slot.
// Sol: Outline: Map raw component thresholds to a structure byte, or return1 for the special C8 package.
unsigned short Check_If_CriticalSlot_Destroyed(unsigned short MechId, unsigned short ComponentOffset)
{
	// Sol: Legacy name misleading: returns supporting STRUCTURE BYTE, not
	// Sol: critical destruction bit or bool. Reconstructed 183B:273D..27C8.
	short StructureOffset = 0x1C;
	if ((short)ComponentOffset >= 0x3A) StructureOffset = 0x1D;
	if ((short)ComponentOffset >= 0x41) StructureOffset = 0x21;
	if ((short)ComponentOffset >= 0x48) StructureOffset = 0x22;
	if ((short)ComponentOffset >= 0x4F) StructureOffset = 0x1E;
	if ((short)ComponentOffset >= 0x51) StructureOffset = 0x23;
	if ((short)ComponentOffset >= 0x53) StructureOffset = 0x20;
	if ((short)ComponentOffset >= 0x55) StructureOffset = 0x1F;
	// Sol: C79F is record+7B (UpgradePackageBase), NOT an engine rating.
	// Sol: Special C8 bypass returns1; purpose still unresolved under A-005.
	if (seg3092->Mechs[MechId].UpgradePackageBase == 0xC8) return 1;
	return ((unsigned char far *)&seg3092->Mechs[MechId])[StructureOffset];
}

// 183B:27C9: void Register_Persistent_Map_Effect_27C9(Stack uint8 Sprite, Stack word16 PosX, Stack word16 PosY)
// Called from:
//      Return_bool_fn1631_16AB
//      Combat_Parent_000A
//      Combat_Mechanics
//      Combat_AudioVisual_Effects
//      Combat_Random_CreateFire
// Sol: Summary: Store a persistent map effect.
// Sol: Outline: Overwrite the next ring slot, pack the sprite and coordinates, and advance the slot counter.
void Register_Persistent_Map_Effect_27C9(unsigned char Sprite, unsigned short PosX, unsigned short PosY)
{
	// Sol: TODO ASM audit: native increments WORD at D557, then tests/resets
	// Sol: only its low BYTE. C BYTE increment loses carry into D558 for FF.
	// Sol: Ordinary slots0..63 agree; do not infer an original-game bug yet.
	// Sol: This is the producer for the saved 64-slot effect ring rendered by
	// Sol: 0800:2A93. Callers register fires, impacts, and wrecks—not only wrecks.
	unsigned char EffectSlot = seg3092->NextMapEffectSlot;
	seg3092->MapEffectSpriteIndex[EffectSlot] = Sprite;
	seg3092->MapEffectPackedPage[EffectSlot] =
		(unsigned char)((PosX | PosY) >> 8);
	seg3092->MapEffectPositionXLow[EffectSlot] =
		(unsigned char)(PosX & Byte_MostSignificantBitMask);
	seg3092->MapEffectPositionYLow[EffectSlot] =
		(unsigned char)(PosY & Byte_MostSignificantBitMask);

	seg3092->NextMapEffectSlot++;
	if (seg3092->NextMapEffectSlot > 0x3F)
		seg3092->NextMapEffectSlot = 0;
}

// 183B:2835: void Combat_Load_9Grid_Map_2835(Register Eq_21 ds)
// Called from:
//      Combat_Parent_000A
// Sol: Summary: Load the map regions needed for combat.
// Sol: Outline: Determine the encounter's surrounding regions and populate the nine-grid map cache.
void Combat_Load_9Grid_Map_2835()
{
	// Sol:2835..28DA region index is combined packed X/Y high BYTE.
	short TopLeftRegion = (unsigned short)(seg246C->CrescentHawk_MapPositionX | seg246C->CrescentHawk_MapPositionY) >> 8;
	TopLeftRegion -= 0x11; // Sol: previous coarse row(-16) and column(-1); corrected Reko SHR/precedence.
	for (short Row = 0; Row < 3; ++Row)
	{
		for (short Column = 0; Column < 3; ++Column)
		{
			short RegionIndex = TopLeftRegion + Column;
			if (RegionIndex >= 0 && RegionIndex < 256 && seg2FE8->MapFile[RegionIndex] != 0) // DS:0030 region-to-map-number BYTE table;0 absent.
			{
				unsigned short Slot = Row * 3 + Column;
				unsigned char far* Descriptor = seg3EDB->CachedMapGridSlotPointer[Slot]; // Sol: LES16:16 FAR pointer, stride4.
				if (Descriptor[0] != 0x90) // Sol: first populated block descriptor90; NOT map-identity comparison.
					DOS_Load_Map_Files(Slot, (short)(signed char)seg2FE8->MapFile[RegionIndex]); // Sol:28A6 map BYTE CBW -> WORD.
			}
		}
		TopLeftRegion += 0x10; // Sol: next coarse row in16-column region table.
	}
	Map_NineGrid_Parent_1DA8(); // Sol: always rebuild combined cached map; skipped slots are not explicitly cleared here.
}

// 183B:28DB: Register word16 Combat_Assess_FirstEnemy_Reachability_28DB()
// Called from: Combat_Parent_000A
// Sol: legacy Combat_MovementPointsRemaining_28DB name misleading; this is a path probe.
// Sol: Summary: Assess reachability of the first enemy.
// Sol: Outline: Probe the relevant actor and terrain relationships and return the encounter assessment flag.
unsigned short Combat_Assess_FirstEnemy_Reachability_28DB()
{
	unsigned short SavedMapX = seg246C->CrescentHawk_MapPositionX; // SS:BP-12 WORD.
	unsigned short SavedMapY = seg246C->CrescentHawk_MapPositionY; // SS:BP-14 WORD.
	unsigned short StartX = seg3092->CombatantPackedX[Friendly_Infantry_Combatant_Range_First]; // DS:400C Jason's on-foot combatant4.
	unsigned short StartY = seg3092->CombatantPackedY[Friendly_Infantry_Combatant_Range_First]; // DS:403E.
	if (seg3092->Infantry[Character_Jason].Piloting != Character_OnFoot) // DS:C620 BYTE; exactly8 means on foot.
	{
		short MechId = (signed char)seg3092->Infantry[Character_Jason].Piloting; // Sol:291F CBW, no high-bit/sentinel validation.
		StartX = seg3092->CombatantPackedX[MechId];
		StartY = seg3092->CombatantPackedY[MechId];
	}
	Move_Map_View_To_Packed_Position_17BB(StartX, StartY);
	PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY);
	Update_Cached_Map_Origin_1DF8();
	seg3092->CrescentHawk_CompassPositionX = seg246C->CrescentHawk_MapPositionX; // DS:E486 working path coordinate.
	seg3092->CrescentHawk_CompassPositionY = seg246C->CrescentHawk_MapPositionY; // DS:E488.
	unsigned short EnemyFound_ThenReached = FALSE; // SS:BP-2 WORD reused; AX return.
	unsigned short TargetX, TargetY; // BP-0C/-0E; only consumed after active enemy found.
	short ScreenX = 26, ScreenY = 12; // BP-8/-0A WORD character-cell probe anchor.
	for (unsigned short Id = Enemy_All_CombatantId_Range_First; Id < All_CombatantId_Range_Last; ++Id)
		if (EnemyFound_ThenReached == FALSE && seg3092->CombatantActive[Id] != FALSE)
		{
			TargetX = seg3092->CombatantPackedX[Id]; // Sol:29BB missing Reko assignment restored.
			TargetY = seg3092->CombatantPackedY[Id];
			EnemyFound_ThenReached = TRUE; // Sol: FIRST active enemy12..23, not nearest/all; no coordinate/visibility filter.
		}
	seg3092->CharacterMovementPointsRemaining = 30; // DS:3770 WORD path iteration limit, not actual unit budget or heat level.
	if (EnemyFound_ThenReached != FALSE)
	{
		EnemyFound_ThenReached = FALSE;
		while ((short)seg3092->CharacterMovementPointsRemaining > 0)
		{
			if (seg3092->CrescentHawk_CompassPositionX == TargetX && seg3092->CrescentHawk_CompassPositionY == TargetY)
				break; // Sol:29FD already-at-target exits FALSE; only post-step arrival sets TRUE.
			Position_0006(0x80, TargetX, TargetY, ScreenX, ScreenY, FALSE); // Sol:2A19 WORD80 special probe actor, NOT targetY. Position0006 has >=80 bypass of ordinary actor collision checks; deeper audit pending.
			ScreenX += seg3092->CombatChosenStepX;
			ScreenY += seg3092->CombatChosenStepY;
			--seg3092->CharacterMovementPointsRemaining;
			if (seg3092->CrescentHawk_CompassPositionX == TargetX && seg3092->CrescentHawk_CompassPositionY == TargetY)
			{
				seg3092->CharacterMovementPointsRemaining = 0;
				EnemyFound_ThenReached = TRUE; // Sol:2A6F post-step arrival including last of30.
			}
		}
	}
	Combat_Character_Pos_Grid(SavedMapX, SavedMapY); // Sol:2A8E unconditional viewport/cache restore; compass/budget scratch not restored.
	return EnemyFound_ThenReached; // Sol: AX WORD1 only on post-step arrival at first active enemy.
}

// 183B:2AA3: void Combat_Character_Pos_Grid(WORD PosX, WORD PosY)
// Called from: Combat_Parent_000A; Combat_Assess_FirstEnemy_Reachability_28DB
// Sol: Summary: Restore the exploration map position after combat.
// Sol: Outline: Set the packed world anchor and rebuild the map regions and display state around it.
void Combat_Character_Pos_Grid(unsigned short PosX, unsigned short PosY)
{
	// Sol:2AA3..2ADB restores viewport/cache ONLY, no actor position writes,
	// Sol: framebuffer copy or movement-budget/compass-coordinate restoration.
	Move_Map_View_To_Packed_Position_17BB(PosX, PosY);
	PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY);
	Update_Cached_Map_Origin_1DF8(); // Sol: ASM export ends before tail; .dis/raw EXE confirm FAR187F:1DF8 (logical207F), POP BP/RETF.
}
