// BTECH_1CD3.c
// Generated by decompiling BTECH.EXE
// using Reko decompiler version 0.11.2.0.
// Sol: Fresh systematic ASM/.dis audit 2026-09-17: all five methods checked;
// Sol: three locally matched, two mismatched. Checking-only comments, not fixes.
// Sol: See docs/phase4/BTECH_1CD3_SYSTEMATIC_ASM_AUDIT.md.

#include "BTECH.h"

// 1CD3:0004: void Citadel_Building_Dialogs(Stack unsigned short Action)
// Called from:
//      Inspect_Characters
//      Interact_with_BLD
//      Execute_Bld_Bytecode_01C0
//      Mechlube_Repair_Mech
//      Mechlube_Modify_Mech
//      Heal_Characters
//      Citadel_Building_Dialogs
// Sol: Summary: Perform native actions requested by building scripts.
// Sol: Outline: Convert the raw action to a zero-based case and dispatch purchases, training, recruitment, services or story changes.
void Citadel_Building_Dialogs(unsigned short Action)
{
	// Sol TODO ASM-1CD3-0004: Mech.Name is BYTE[16] in the current header;
	// Sol: native initial-byte comparisons/saves/stores below require Name[0].
	// Sol: Several text literals omit prose, CR/colour controls and punctuation.
	// Sol: DWORD text-table entries need explicit16:16 FAR decoding, not integer
	// Sol: arguments. These discrepancies prevent a whole-method matched result.
	Alloca(0x34);

	// Sol: AX is decremented and compared with unsigned JBE. Action 0 wraps to
	// Sol: FFFFh and is rejected; valid raw F5 operands are 01h..2Fh.
	unsigned short ActionIndex = Action - 0x0001;
	if (ActionIndex <= 0x002E)
	{
		unsigned char far *DialogueText; // Sol:shared text paths pass original16:16 FAR pointer
		unsigned char far *TextToDisplayPtr; // Sol:fixed dialogue strings feed the same FAR text path
		unsigned char far *InvestOrSellText; // Sol: shared FAR string, not assignable local array
		unsigned short StockDialogueTextOffset; // Sol: original AX-backed near offset, paired with DS at0957

		short CharacterNameId; // Sol:signed WORD after CBW for name lookup; also reused for WORD crew slot handoff

		// Sol: The jump-table index is (CaseOption - 1). Existing case labels in
		// Sol: this transcription are zero-based table indexes, not raw F5 operands.
		switch (ActionIndex)
		{
		case 0x00:
			// Locust string
			seg3092->CombatantSpriteFamilyOffset[Jason] = MECH_Sprite_LOCUST; //D55E

			unsigned char far *MechSelectionPtr = (unsigned char far *)&seg2FE8->LOCUST; // Sol:FAR125-byte template, not just a name string

			if (seg3092->MechSelectionIdForTraining != 0x00)
			{
				seg3092->CombatantSpriteFamilyOffset[Jason] = MECH_Sprite_COMMANDO; //D55E

				MechSelectionPtr = (unsigned char far *)&seg2FE8->WASP; // Sol:FAR2FE8:036D template

				if (seg3092->MechSelectionIdForTraining == 0x02)
				{					
					MechSelectionPtr = (unsigned char far *)&seg2FE8->CHAMELEON; // Sol:FAR2FE8:04E4 template
				}
			}

			seg3092->Infantry[Character_Jason].Piloting = 0; // Sol:0071 BYTE C620; mech slot0
			unsigned char far *TrainingMechBytes = (unsigned char far *)&seg3092->Mechs[0];
			for (unsigned short MechStats_Reference = 0; MechStats_Reference < MECH_RecordSize; ++MechStats_Reference)
				TrainingMechBytes[MechStats_Reference] = MechSelectionPtr[MechStats_Reference]; // Sol:007C copies125 bytes C724..C7A0, WORD counter BP-16; broken3959 limit removed
			seg3092->Mechs[0].PilotId = Character_Jason; // Sol:009A BYTE C79D

			if (seg3092->DisableInput == FALSE) // Sol:00A0 WORD3938
				Display_Animation_Scene(AnimationO00_MechStartUp, AnimationPlayback_RestoreGameView);

			seg246C->CrescentHawk_MapPositionY = 0xC04F; //A44D - Character position Y

			//Storing SegPtr
			seg3EDB->CombatantAnimationCursor[0] = seg2FE8->MechWalkAnimationStreams + 0x10; // Sol:00C3 FAR2FE8:0280, direction-stream2

			seg246C->CrescentHawk_MapPositionX = UnknownMapX; //A44B - Character Position X 
			
			while (seg246C->CrescentHawk_MapPositionX < UnknownMapY) //A44B - Character Position X 
			{
				seg3092->CombatantSpriteFrame[0] = Advance_Combatant_Animation_Stream_1732(0); // Sol:0145 preserves returned AL, not constant0
	
				for (unsigned short TrainingMarchRedrawIndex = 0; TrainingMarchRedrawIndex < 6; ++TrainingMarchRedrawIndex) // Sol:00E5 WORD BP-1C, six redraws per world-X step; original suffix retained
				{
					Update_Animated_Map_Tiles_240B();
					PosXY_OffsetGrid(seg246C->CrescentHawk_MapPositionX, seg246C->CrescentHawk_MapPositionY); //A44B - Character Position X //A44D - Character position Y

					Copy_Data_To_GraphicsMemory();
					Draw_Infantry_And_Mechs();
					EGA_DrawBox_Wrapper();

					if (seg3092->CpuTimingCalibration > 0x08)
						Wait_For_N_Vertical_Retraces(0x03);
				}			
				seg246C->CrescentHawk_MapPositionX++; //A44B - Character Position X 
			}
			seg3092->CombatantSpriteFrame[0] = Advance_Combatant_Animation_Stream_1732(0); // Sol:015F returned AL

			//Check Mission rules
			Mech_Mission_0629((unsigned short)(signed char)seg3092->bD30C); // Sol:0170 CBW mission BYTE
			goto FinishScriptAction;

		case 0x01: //Debrief on Mission00 - Race to SouthEast Corner
			unsigned char far *MechNameText;
			if (seg3092->Mechs[Jason].Name == KEY_L) // Sol:0193 Locust path jumps straight to common display; it does not display the suffix
				TextToDisplayPtr = "Locust"; // Memory ref: [3EDB:48B3]
			else
			{
				
				if (seg3092->Mechs[Jason].Name == 'W') // Sol:0198 literal ASCII W; removed KEY_W define is not needed
					MechNameText = "Wasp"; // Memory ref: [3EDB:48DF]
				else
				{					
					MechNameText = "Chameleon"; // Memory ref: [3EDB:48E4] 
				}
				Display_Text_From_Memory(MechNameText);
				TextToDisplayPtr = " , the results are all the more impressive."; //Memory ref: [3EDB:48EE]
			}
			goto SelectScriptDialogueText;

		case 0x02:
			// Sol TODO ASM-1CD3-01F7: Native skips cleanup when D310!=0 and
			// Sol: clears fire effects when D310==0; current C condition is reversed.

			seg3092->Mechs[Jason].Name = MECH_Destroyed; //aC724 Mech destoyed / removed
			seg3092->Infantry[Jason].Piloting = Character_OnFoot; // Sol:01C2 writes BYTE C620, not address

			seg246C->CrescentHawk_MapPositionX = CitadelBuilding02PosX; //A44B - Character Position X 
			seg246C->CrescentHawk_MapPositionY = CitadelBuilding02PosY; //A44D - Character position Y

			if (seg3092->Kurita_DestroyedCitadel) //bD310 - Kurita Destroy Citadel
			{
				unsigned char CitadelEffectSlot = 0x00;
				do
				{
					if ((seg3092->MapEffectSpriteIndex[CitadelEffectSlot] & 0x7E) == 0x7C)
					{
						seg3092->MapEffectPositionXLow[CitadelEffectSlot] = 0x00;
						seg3092->MapEffectPackedPage[CitadelEffectSlot] = 0x00;
						seg3092->MapEffectSpriteIndex[CitadelEffectSlot] = 0x00;
					}
					CitadelEffectSlot++;
				} while (CitadelEffectSlot < 0x40);
			}
			break;

		case 0x03:
			// Sol TODO ASM-1CD3-0244: Native X is39-strlen(formatted score),
			// Sol: not fixed21. Preserve right alignment in this and stock panels.

			for (int SkillOffset = 0x00; SkillOffset < 0x03; SkillOffset++)
			{
				// Sol:0244 IMUL signed skill BYTE at3092:C618+index by125, then ADD75.
				// Sol:125 is transcript score step, NOT MECH_RecordSize or an address calculation.
				unsigned char far *CharacterMemory = (unsigned char far *)0x30920000UL;
				short SkillLevel = (signed char)CharacterMemory[0xC618 + SkillOffset]; // Bows/blade, pistol, rifle
				short TranscriptScore = (short)(SkillTranscriptBaseScore + SkillTranscriptScorePerLevel * SkillLevel);
				ASM_Text_Formatting_3BB6((unsigned short)TranscriptScore, &seg3092->DynamicString, 0x0A); // Sol: verified0244..026B WORD value
				Loop_Until_TextPtr_Null(&seg3092->DynamicString);

				//(Textptr, Horizonal_StatsLine_Offset, Vertical_StatsLine_Offset, EGAColour_Font, EGAColour_Background)
				Draw_EGA_Text_To_Screen(&seg3092->DynamicString, 21, SkillOffset + 5, EGA_BrightGreen, EGA_Black);
			}
			break;

		case 0x04:	//Citadel school		

			//This display text might be dynamic first and then display below
			Display_Text_From_Memory("By looking at your transcripts there is nothing more we can teach you"); // Memory ref: [3EDB:491A] 

			// Sol:02A5 loads and CBW-sign-extends D314, then reads the skill BYTE at C618+index.
			short SelectedTrainingSkillOffset = (signed char)seg3092->Skill_Selection; // DS3092:D314; bows/blade, pistol, rifle indices0..2
			unsigned char far *SelectedTrainingSkill = (unsigned char far *)0x3092C618UL + SelectedTrainingSkillOffset;
			short Skill_Level = (signed char)*SelectedTrainingSkill; // Sol: skill VALUE, not its address; native second CBW

			//[3EDB:4EA2] - Skill_level_Descriptions[5] - "completely unskilled.an amateur.competent.a whiz.a grand master"
			Display_Text_From_Memory(seg3EDB->Skill_level_Descriptions[Skill_Level]);

			//[3EDB:4EB6] - Skill_Level_Verbose[3]
			//"in the use of bows and blades.."
			//"when it comes to pistols and handguns.."
			//"with a rifle or submachinegun"
			Display_Text_From_Memory(seg3EDB->Skill_Level_Verbose[SelectedTrainingSkillOffset]); // Sol:02A5..0301 FAR entry at4EB6+index*4, one-dimensional table

			if (Skill_Level == SkillLevel_Excellent) // Sol:02FB equality to level4, not a greater-than clamp
			{				
				Display_Text_From_Memory("I'm afraid that we here can't possibly teach you more than you already know."); // Memory ref: [3EDB:4948] 
			}
			else
			{
				// Sol:031B signed BYTE IMUL125 +75 produces a WORD cost, not a mech-record address.
				short TuitionCostWord = (short)(SkillTrainingBaseCost + SkillTrainingCostPerLevel * Skill_Level);
				unsigned long Tuition_CBill_Price = (unsigned long)(long)TuitionCostWord; // Sol:CWD sign-extends cost to native DWORD DX:AX, then unsigned cash comparison

				//If CBill Balance enough for Tutition - Cbill Balance D370 + D372
				if (Tuition_CBill_Price <= seg3092->CBills) // Sol:031B..0344 JA rejects only cost ABOVE cash; exact balance succeeds
				{
					seg3092->Bool_Skill_Learning = TRUE; //D315 - Learning Skill

					//Level up skill by 1 Level
					++*SelectedTrainingSkill; // Sol:0344 INC BYTE C618+selected index; native byte wrap, no invented cap

					seg3092->CBills -= Tuition_CBill_Price; // Sol:0355 CWD then SUB/SBB debits native DWORD D370/D372
			
					goto DisplayServiceBalance; // Sol: successful training uses the existing shared dialog-return path
				}				
				Display_Text_From_Memory("I'm afraid you don't have enough C_Bills for tutition"); // Memory ref: [3EDB:4999] 
				Display_Text_Shop_Cannot_Afford_Text();
			}
			seg3092->Bool_Skill_Learning = FALSE;  //D315 - Bool Learning Skill
			break;

		case 0x05:
			// Sol TODO ASM-1CD3-037A: Native cash/stock X=39-strlen, stock
			// Sol: row is full WORD374E; VerticalOffset currently truncates it.
			// Sol: Native adapter0 uses colour1; maintained EGA2 uses colour2.
			unsigned char AccountTextColour = EGA_Green;
						
			CBill_Text_Formatting(seg3092->CBills, &seg3092->DynamicString, 10); //(tD370 & tD372) 32 bit value - C-Bill Balance

			Loop_Until_TextPtr_Null(&seg3092->DynamicString);

			//(Textptr, Horizonal_StatsLine_Offset, Vertical_StatsLine_Offset, EGAColour_Font, EGAColour_Background)
			Draw_EGA_Text_To_Screen(&seg3092->DynamicString, 21, 0x01, AccountTextColour, EGA_Black);
			seg3092->wE482 = 0x00;

			//Defhas, Nasdiv, Bakphar		
			for(int StockId = 0x00; StockId < 0x03; StockId++)
			{
				if (seg3092->Stock[StockId] != 0) // Sol:03F0 ORs balance low/high WORD, not its address
				{
					seg3092->EGATextColour = EGA_BrightWhite; //w37FE - Text Colour in EGA Palette = 0x0F White
					Display_Text_From_Memory(seg3EDB->StockMarketNames[StockId]);

					//tD374 = Start stock block, 32bit values. Defhas, Nasdiv, Bakphar
					CBill_Text_Formatting(seg3092->Stock[StockId], &seg3092->DynamicString, 10); // Sol: ASM byte offset ID*4 corresponds to typed DWORD index ID.
					unsigned char VerticalOffset = seg3092->VerticalLine_Offset; //w374E - Vertical Line Offset for Text
					Loop_Until_TextPtr_Null(&seg3092->DynamicString);

					//(Textptr, Horizonal_StatsLine_Offset, Vertical_StatsLine_Offset, EGAColour_Font, EGAColour_Background)
					Draw_EGA_Text_To_Screen(&seg3092->DynamicString, 21, VerticalOffset, AccountTextColour, EGA_Black);

					seg3092->wE482++;
				}
			} 

			if (seg3092->wE482 == 0x00)
			{
				TextToDisplayPtr = "None."; // Memory ref: [3EDB:49D3]
				goto SelectScriptDialogueText;
			}
			break;

		case 0x06: //Comstar Investing
			// Sol TODO ASM-1CD3-07C2: Native balance X=39-strlen, not21;
			// Sol: restore exact stock dialogue CR/06/0F bytes and wording.

			if (seg3092->CBills == 0x00) //(tD370 & tD372) 32 bit value - C-Bill Balance
			{
				TextToDisplayPtr = "You need some cash in your c-bill account before you can buy stock."; // Memory ref: [3EDB:4AF5]
				goto SelectScriptDialogueText;
			}

			Draw_Top_Graphic_Sidebar();			
			Display_Text_From_Memory("Invest in which stock?"); // Memory ref: [3EDB:4B3B] 

			//Listing Stocks for Menu
			for(int Stock_Option = 0x00; Stock_Option < 0x03; Stock_Option++)
			{
				Display_Text_From_Memory(seg3EDB->StockMarketNames[Stock_Option]);						
			} 

			unsigned short Selected_Stock = Display_Menu_Choices_And_Check(0x07); // Sol: native WORD stock selector
			Display_Text_From_Memory("Invest how much?"); // Memory ref: [3EDB:4B52] 

			//(Textptr, Horizonal_StatsLine_Offset, Vertical_StatsLine_Offset, EGAColour_Font, EGAColour_Background)
			Draw_EGA_Text_To_Screen("C-bill account:", seg3092->BTBORDER_XStart, 0x17, EGA_BrightWhite, EGA_Black);
			unsigned char InvestmentTextColour = EGA_Green;

			CBill_Text_Formatting(seg3092->CBills, &seg3092->DynamicString, 10); //(tD370 & tD372) 32 bit value - C-Bill Balance
			Loop_Until_TextPtr_Null(&seg3092->DynamicString);

			//(Textptr, Horizonal_StatsLine_Offset, Vertical_StatsLine_Offset, EGAColour_Font, EGAColour_Background)
			Draw_EGA_Text_To_Screen(&seg3092->DynamicString, 21, 0x17, InvestmentTextColour, EGA_Black);

			unsigned long Amount_to_Invest = Prompt_For_Unsigned_Decimal_0CDE();

			// Sol:0822..0854 compares requested DWORD against cash using unsigned high/low WORDs.
			if (Amount_to_Invest > seg3092->CBills)
			{
				Display_Text_From_Memory("You don't have that much, but you invest all that you do have."); //3EDB:4B77
				Amount_to_Invest = seg3092->CBills;
			}

			if (Amount_to_Invest != 0x00)
			{				
				Display_Text_From_Memory("You have invested a total of "); // Memory ref: [3EDB:4BB8] 
				CBill_Text_Formatting(Amount_to_Invest, &seg3092->DynamicString, 10);

				seg3092->EGATextColour = EGA_Green; //w37FE - Text Colour in EGA Palette = 0x02 Green
				
				Display_Text_From_Memory(&seg3092->DynamicString);
				Display_Text_From_Memory(" in"); // Memory ref: [3EDB:4BD8]
				Display_Text_From_Memory(seg3EDB->StockMarketNames[Selected_Stock]); //Stock companies
				
				Display_Text_From_Memory(" bring your balance up to a total of "); // Memory ref: [3EDB:4BDF] 

				// Sol:0910 ADD/ADC credits selected stock DWORD; typed ID already accounts for native ID*4.
				seg3092->Stock[Selected_Stock] += Amount_to_Invest;

			
			
				//(tD370 & tD372) 32 bit value - C-Bill Balance
				seg3092->CBills -= Amount_to_Invest; 
			

				//tD374 = Start stock block, 32bit values. Defhas, Nasdiv, Bakphar
				CBill_Text_Formatting(seg3092->Stock[Selected_Stock], &seg3092->DynamicString, 10); // Sol: ASM pushes balance high/low WORDs, not FAR address.
				seg3092->EGATextColour = InvestmentTextColour; //w37FE - Text Colour in EGA Palette = 0x02 Green

				Display_Text_From_Memory(&seg3092->DynamicString);
				StockDialogueTextOffset = 0x4C07;
				goto DisplayStockTransactionResult;
			}
			else
			{
				InvestOrSellText = "You Invest "; // Memory ref: [3EDB:4C0B]
				goto DisplayNoStockTransaction;
			}

		case 0x07:
			// Sol TODO ASM-1CD3-0560: Same right-alignment/text discrepancies
			// Sol: as investing. DWORD clamp/credit/debit order otherwise agrees.

			if (seg3092->wE482 == 0x00)
			{				
				TextToDisplayPtr = "You have no stock to sell"; // Memory ref: [3EDB:49D9] 
				goto SelectScriptDialogueText;
			}

			Draw_Top_Graphic_Sidebar();			
			Display_Text_From_Memory("Sell which stock?"); // Memory ref: [3EDB:49F6] 

			for(int StockOptionsToDisplay = 0x00; StockOptionsToDisplay < 0x03; StockOptionsToDisplay++)
			{
				Display_Text_From_Memory(seg3EDB->StockMarketNames[StockOptionsToDisplay]);							
			} 

			unsigned short StockId = Display_Menu_Choices_And_Check(0x07); // Sol: native WORD stock selector

			//tD374 = Start stock block, 32bit values. Defhas, Nasdiv, Bakphar
			if (seg3092->Stock[StockId] == 0x00) //tD374
			{
				TextToDisplayPtr = "You can't sell any stock you don't own!"; //Memory ref [3EDB:4ACB]
				goto SelectScriptDialogueText;
			}
			
			Display_Text_From_Memory("Sell how much?"); // Memory ref: [3EDB:4A09] 

			//(Textptr, Horizonal_StatsLine_Offset, Vertical_StatsLine_Offset, EGAColour_Font, EGAColour_Background)
			Draw_EGA_Text_To_Screen("Stock Account: ", seg3092->BTBORDER_XStart, 0x17, EGA_BrightWhite, EGA_Black);

			unsigned char StockSaleTextColour = EGA_Green;

			//tD374 = Start stock block, 32bit values. Defhas, Nasdiv, Bakphar
			CBill_Text_Formatting(seg3092->Stock[StockId], &seg3092->DynamicString, 10); // Sol: ASM pushes DWORD balance value.
			Loop_Until_TextPtr_Null(&seg3092->DynamicString);

			//(Textptr, Horizonal_StatsLine_Offset, Vertical_StatsLine_Offset, EGAColour_Font, EGAColour_Background)
			Draw_EGA_Text_To_Screen(&seg3092->DynamicString, 21, 0x17, StockSaleTextColour, EGA_Black);
			unsigned long StockToBeSold = Prompt_For_Unsigned_Decimal_0CDE(); // Sol:05B0 returns DWORD DX:AX
			unsigned long AvailableStockBalance = seg3092->Stock[StockId]; // Sol:05C0 two WORD values, not address
			// Sol:05DE..0604 unsigned DWORD clamp; no segment literal belongs in the comparison.
			if (StockToBeSold > AvailableStockBalance)
			{
				Display_Text_From_Memory("You don't have that much but you sell all you have"); //3EDB:4A2B
				StockToBeSold = AvailableStockBalance;
			}
			

			if (StockToBeSold != 0x00)
			{				
				Display_Text_From_Memory("You have a total of "); // Memory ref: [3EDB:4A6A] 
				CBill_Text_Formatting(StockToBeSold, &seg3092->DynamicString, 10);
				seg3092->EGATextColour = EGA_Green; //w37FE - Text Colour in EGA Palette = 0x02 Green

				Display_Text_From_Memory(&seg3092->DynamicString);
				Display_Text_From_Memory(" of "); // Memory ref: [3EDB:4A86] 
				Display_Text_From_Memory(seg3EDB->StockMarketNames[StockId]);	//Array of memory locations to stock strings			
				Display_Text_From_Memory(" stock, bring your balance in that stock to "); // Memory ref: [3EDB:4A8D] 

				seg3092->Stock[StockId] -= StockToBeSold; //tD374 = Start stock block, 32bit values. Defhas, Nasdiv, Bakphar
			
								//(tD370 & tD372) 32 bit value - C-Bill Balance
				seg3092->CBills += StockToBeSold; // Sol:06B0 ADD/ADC credits cash; stock debit above uses SUB/SBB
				

				//tD374 = Start stock block, 32bit values. Defhas, Nasdiv, Bakphar
				CBill_Text_Formatting(seg3092->Stock[StockId], &seg3092->DynamicString, 10);
				seg3092->EGATextColour = StockSaleTextColour; //w37FE - Text Colour in EGA Palette = 0x02 Green
				Display_Text_From_Memory(&seg3092->DynamicString);
				StockDialogueTextOffset = 0x4ABC; // Sol:original DS near text offset
DisplayStockTransactionResult: // Sol: native shared path at 1CD3:0957.
				Display_Text_From_Memory(SEQ(ds, StockDialogueTextOffset));
				goto DisplayServiceBalance;
			}
			
			InvestOrSellText = " You sell "; // Memory ref: [3EDB:4AC0] 
DisplayNoStockTransaction:
			Display_Text_From_Memory(InvestOrSellText);
			Display_No_Stock_Transaction_Text();
			break;

		case 0x08: // Sol:raw action09, purchase and distribute infantry armour
			unsigned short SelectedArmourType = seg305B->AlternateArmourShopSelection; // Sol:305B:0178 menu0E selection (suffix retained)

			if (seg3092->BldInteractionFlag != FALSE)
				SelectedArmourType = seg305B->ArmourShopSelection; // Sol:305B:0168 menu0D selection when D316 is nonzero

			seg3092->CBillPayment_Successful = FALSE; //bD317 - Payment successful
			unsigned long ArmourPurchaseCost = seg3EDB->ArmourPurchaseCost[SelectedArmourType - 1]; // Sol:09E9 native DWORD at4F26+type*4 =4F2A+(type-1)*4; type0 exits in script
		

			//(tD370 & tD372) 32 bit value - C-Bill Balance
			if (seg3092->CBills >= ArmourPurchaseCost)
			{
				//(tD370 & tD372) 32 bit value - C-Bill Balance
				seg3092->CBills -= ArmourPurchaseCost;
			
				seg3092->CBillPayment_Successful = TRUE; //bD317 - Payment successful

				Display_Text_CBill_Balance();
				Distribute_Purchased_Armour(
					SelectedArmourType,
					(signed char)seg3EDB->ArmourTypeDurability[SelectedArmourType]); // Sol:0A1E CBW durability BYTE, then WORD type argument
				break; // Sol:native01BC only discards FAR-call arguments then exits; no additional dialogue
			}
			break;

		case 0x09: // Sol:raw action0A, display current cash within shop dialogue
			
			CBill_Text_Formatting(seg3092->CBills, &seg3092->DynamicString, 10); //(tD370 & tD372) 32 bit value - C-Bill Balance
			seg3092->EGATextColour = EGA_Green; //w37FE - Text Colour in EGA Palette = 0x02 Green

			Display_Text_From_Memory(&seg3092->DynamicString);
			Display_Text_From_Memory((unsigned char far *)"\006\017."); // Sol:096F..09C6 bytes06,0F,'.',NUL; repair prose starts separately at4C1C // Sol: exact EXE text 3EDB:4C18; readable text restored
			break;
SelectScriptDialogueText:
			DialogueText = TextToDisplayPtr;
			goto DisplaySelectedDialogueText;

		case 0x0A: // Sol:raw action0B, purchase and distribute an infantry weapon
			unsigned short WeaponPriceIndex = seg305B->MeleeWeaponShopSelection; // Sol:305B:0198 menu10; selection1..6 is weapon ID1..6

			if (seg3092->WeaponShopCategoryOffset == WeaponShopFirearmCategoryOffset)
				WeaponPriceIndex = (unsigned short)(seg305B->FirearmShopSelection + WeaponShopFirearmCategoryOffset); // Sol:menu11 selection1..3 -> weapon IDs7..9

			if (seg3092->WeaponShopCategoryOffset == WeaponShopHeavyCategoryOffset)
				WeaponPriceIndex = (unsigned short)(seg305B->HeavyWeaponShopSelection + WeaponShopHeavyCategoryOffset); // Sol:menu12 shipped purchasable selection1 -> weapon ID10

			seg3092->CBillPayment_Successful = FALSE; //bD317 - Payment successful
			WeaponPriceIndex--; // Sol:0A8A one-based weapon ID -> zero-based DWORD price index
			unsigned long WeaponPurchaseCost = seg3EDB->InfantryWeaponPurchaseCost[WeaponPriceIndex]; // Sol:4F44+index*4, NOT armour or BYTE prices
		

			//(tD370 & tD372) 32 bit value - C-Bill Balance
			if (seg3092->CBills >= WeaponPurchaseCost)
			{

				//(tD370 & tD372) 32 bit value - C-Bill Balance			
				seg3092->CBills -= WeaponPurchaseCost;
				

				seg3092->CBillPayment_Successful = TRUE; //bD317 - Payment successful
				Display_Text_CBill_Balance();
				Distribute_Weapon_To_Party((unsigned short)(WeaponPriceIndex + 1));
				break; // Sol:0181 discards WORD call argument and exits; payment precedes distribution
			}
			break;

		case 0x0B:
			Talk_To_Building_Occupants();
			break;

		case 0x0C:
			// Sol TODO ASM-1CD3-0B8C: Living Name ID is CBW signed before
			// Sol: FAR name-table lookup, not the current unsigned NameId.
			Citadel_Building_Dialogs(0x0E);

			// Sol:0B36 initializes SS:BP-08..BP-01 BYTE row->character-slot map, not fp-0A.
			unsigned char LivingPartySlotMap[8] = { 0 };

			seg305B->VerticalOffset = seg3092->VerticalLine_Offset; //w374E - Vertical Line Offset for Text

			//w0206 NumOfAliveCrescentHawks + 1
			seg305B->NumberOfPartyMembers = (unsigned short)((short)(signed char)seg3092->Party_NumOfMembers + 1); // Sol:0B46 CBW count +Jason; native no recount here
			seg305B->CrescentHawks = 0x00; //w0208 NumOfAliveCrescentHawks SegPtr
			int LivingPartyMembers = 0x00;

			for(int PartyMemberId = 0x00; PartyMemberId < 0x08; PartyMemberId++)
			{
				unsigned char NameId = seg3092->Infantry[PartyMemberId].Name; //C614 Name 

				if (NameId != Character_Dead)
				{					
					Display_Text_From_Memory(seg3EDB->CharacterNameList[NameId]); // Character name lookup	
					Display_Text_4FA0_Value();				
					LivingPartySlotMap[LivingPartyMembers++] = (unsigned char)PartyMemberId; // Sol:0BAA appends actual slot, skips dead records
				}	
			} 

			unsigned short SelectedPartyMenuRow = Display_Menu_Choices_And_Check(0x17);
			seg3092->SelectedPartyMemberSlot = LivingPartySlotMap[SelectedPartyMenuRow]; // Sol:0BC2..0BD9 row->slot lookup, not raw menu index
			// Sol: No row bounds check in original; metadata0206 assumes earlier party count is consistent.
			break;

		case 0x0D: //Count total living characters

			
			seg3092->Party_NumOfMembers = 0x00; //bD31A = Number of Party Members / Select Party Member
	
			for (unsigned char PartyMemberId = 0x01; PartyMemberId < 0x08; ++PartyMemberId)
			{
				if (seg3092->Infantry[PartyMemberId].Name != Character_Dead) //C614 Name 
					seg3092->Party_NumOfMembers++; //bD31A = Number of Party Members / Select Party Member
			}
			break;

		case 0x0E: // Sol:raw action0F, selected character's Tech apprenticeship
			if (seg3092->CBills < SpecialistTrainingCost)
			{
				seg3092->SpecialistTrainingPurchaseResult = FALSE;
				break;
			}
			short TechTraineeSlot = (signed char)seg3092->SelectedPartyMemberSlot; // Sol:0C11 signed BYTE IMUL17; consume slot BEFORE overwriting D31A
			seg3092->CBills -= SpecialistTrainingCost;
			++seg3092->Infantry[TechTraineeSlot].Skill_Tech;
			seg3092->Infantry[TechTraineeSlot].TrainingFlags |= CharacterTraining_Tech;
			seg3092->SpecialistTrainingPurchaseResult = TRUE; // Sol:0C9B shared result then balance display
			Display_Text_CBill_Balance();
			break;

		case 0x0F: // Sol:raw action10, test selected character's Tech training bit
			short TechFlagSlot = (signed char)seg3092->SelectedPartyMemberSlot;
			seg3092->SelectedSpecialistTrainingMask = seg3092->Infantry[TechFlagSlot].TrainingFlags & CharacterTraining_Tech; // Sol:0BE1..0BF5 BYTE value, not SEQ/address
			break;

		case 0x10: // Sol:raw action11, count currently visible friendly mech records

			//Reset before recount
			seg3092->NumberOfActiveLanceMechs = 0x00;	
			for (unsigned short MechLanceId = 0; MechLanceId < Friendly_Mech_Record_Count; ++MechLanceId)
			{
				if (seg3092->Mechs[MechLanceId].Name != MECH_Destroyed) // Sol:0CA4..0CD7 native byte addressC724+slot*125; typed array uses slot only
					seg3092->NumberOfActiveLanceMechs++;
			}
			break;

		case 0x11:
			Mechlube_Repair_Mech();
			break;

		case 0x12:
			Mechlube_Modify_Mech();
			break;

		case 0x13:
			Mechlube_Upgrade_Mech();
			break;

		case 0x14: // Sol:raw action15, selected character's Medical seminar
			if (seg3092->CBills < SpecialistTrainingCost)
			{
				seg3092->SpecialistTrainingPurchaseResult = FALSE;
				break;
			}
			short MedicalTraineeSlot = (signed char)seg3092->SelectedPartyMemberSlot;
			seg3092->CBills -= SpecialistTrainingCost;
			++seg3092->Infantry[MedicalTraineeSlot].Skill_Medical; // Sol:0C71 INC BYTE C61E+slot*17
			seg3092->Infantry[MedicalTraineeSlot].TrainingFlags |= CharacterTraining_Medical;
			seg3092->SpecialistTrainingPurchaseResult = TRUE;
			Display_Text_CBill_Balance();
			break;

		case 0x15: // Sol:raw action16, test selected character's Medical training bit
			short MedicalFlagSlot = (signed char)seg3092->SelectedPartyMemberSlot;
			seg3092->SelectedSpecialistTrainingMask = seg3092->Infantry[MedicalFlagSlot].TrainingFlags & CharacterTraining_Medical; // Sol:0C46 AND2, result is0 or2
			break;

		case 0x16: // Sol:raw action17, identify any living party member not at full health
			seg3092->Party_HasInjuredMember = FALSE;
			for (unsigned short PartyMemberId = 0; PartyMemberId < 8; ++PartyMemberId)
			{
				if (seg3092->Infantry[PartyMemberId].Name != Character_Dead
				 && CharacterHealthPerBodyPoint * (short)(signed char)seg3092->Infantry[PartyMemberId].Body != (short)(signed char)seg3092->Infantry[PartyMemberId].Health)
					seg3092->Party_HasInjuredMember = TRUE; // Sol:0D29 signed Body*10 != signed Health VALUE; no address-of and no less-than substitution
			}
			break;

		case 0x17: // Sol:raw action18, paid medical service or own-party healing
			// Sol:HOSPITAL02F2 clears D335,040A prepays facilities25,061E calls this action.
			// Sol:Recovery does not block that hospital call; doctor failure refunds facilities below.
			short EquipmentLevel = (signed char)seg3092->Party_MedEquipLevel; // Sol:D326 CBW; scripted service tier, not just inventory equipment
			if (EquipmentLevel == MedEquip_None)
			{
				Heal_Characters(MedEquip_None); // Sol:0DB7 passes WORD0, no fee
				break;
			}
			unsigned long MedicalTreatmentCost = (unsigned long)(long)seg3EDB->MedicalServiceFee[EquipmentLevel]; // Sol:0D50 WORD fee +CWD, not DWORD table index*2
			if (seg3092->CBills >= MedicalTreatmentCost)
			{
				seg3092->CBills -= MedicalTreatmentCost;
				Heal_Characters((unsigned short)EquipmentLevel); // Sol:0D76 native WORD argument; fee is debited before helper outcome
			}
			else
			{
				Display_Text_4FA0_Value();
				Display_Text_Shop_Cannot_Afford_Text();
				Wait_For_50Hz_Then_Check_Input();
				Keyboard_Get_ASCII_Hex_Input();
				seg3092->CBills += MedicalServiceInsufficientFundsCredit; // Sol:0D92 refunds HOSPITAL040A's25; direct callers must honor this convention
			}
DisplayServiceBalance: // Sol: native shared path at 1CD3:0961.
			Display_Text_CBill_Balance();
			break;

		case 0x18: //Buy Medikit
			seg3092->Purchased_Medkit = TRUE;
			break;

		case 0x19: //Buy Field Surgery Kit
			seg3092->Purchased_FieldSurgeryKit = TRUE;
			break;

		case 0x1A: // Sol:raw action1B, rebuild four friendly sprite families and assign Jason's crew
			goto RebuildFriendlyMechSprites;

		case 0x1B: // Sol:raw action1C, temporarily hide four friendly mechs and put eight characters on foot

			for (unsigned short MechLanceId = 0; MechLanceId < Friendly_Mech_Record_Count; ++MechLanceId)
			{
				seg3092->StoredPartyMechNameInitial[MechLanceId] = seg3092->Mechs[MechLanceId].Name; // Sol:0DEF saves Name BYTE only; other125-byte fields stay intact
				seg3092->Mechs[MechLanceId].Name = MECH_Destroyed; // Sol:FF hides/marks unavailable here, not permanent record destruction
				seg3092->Infantry[MechLanceId].Piloting = Character_OnFoot; // Sol:C620+slot*17 -> characters0..3 assignment+0C
				seg3092->Infantry[MechLanceId + Friendly_Mech_Record_Count].Piloting = Character_OnFoot; // Sol:C664=C620+4*17 -> characters4..7; NOT an extra character stride
			}
			break;

		case 0x1C: // Sol:raw action1D, count saved uppercase mech-name initials

			//Reset before recount
			seg3092->NumberOfActiveLanceMechs = 0x00;
			for (unsigned short SavedMechSlot = 0; SavedMechSlot < Friendly_Mech_Record_Count; ++SavedMechSlot)
			{
				if (seg3092->StoredPartyMechNameInitial[SavedMechSlot] >= KEY_A && seg3092->StoredPartyMechNameInitial[SavedMechSlot] <= KEY_Z) // Sol:0E9B..0ED1 signed ASCII A..Z test; SavedMechSlot is the party Mech index.
					seg3092->NumberOfActiveLanceMechs++;
			}
			break;

		case 0x1D: // Raw BLD action 1Eh: recruit Rex and start the Kurita ambush
			Recruit_Rex_And_Start_KuritaParty_Ambush();
			break;

		case 0x1E: // Sol:raw action1F, selected character's armour-type query
			short ArmourQuerySlot = (signed char)seg3092->SelectedPartyMemberSlot;
			seg3092->SelectedPartyArmourType = seg3092->Infantry[ArmourQuerySlot].ArmourType; // Sol:0EDA copies BYTE value C621+slot*17
			break;

		case 0x1F: // Sol:raw action20, per-point infantry armour repair
			short SelectPartyMemberId = (signed char)seg3092->SelectedPartyMemberSlot; // Sol:0EF3 CBW slot, then IMUL17
			short ArmourTypeId = (signed char)seg3092->Infantry[SelectPartyMemberId].ArmourType;
			short ArmourDurability = (signed char)seg3092->Infantry[SelectPartyMemberId].ArmourValue;
			short FullArmourDurability = (signed char)seg3EDB->ArmourTypeDurability[ArmourTypeId]; // Sol:4DDC+(type-1) equals4DDB+type
			unsigned char far *ArmourRepairStatusText;
			if (FullArmourDurability == ArmourDurability)
			{
				Display_Text_From_Memory((unsigned char far *)"Why, this armor looks brand new to me!  It doesn't need any repair."); // Sol: exact EXE text 3EDB:4C1C; readable text restored
				Keyboard_Get_ASCII_Hex_Input();
				break;
			}
			Display_Text_From_Memory((unsigned char far *)"This armor has lost "); // Sol: exact EXE text 3EDB:4C60; readable text restored
			short LostArmourPoints = (short)(FullArmourDurability - ArmourDurability);
			short ArmourPointsToRepair = LostArmourPoints;
			if (ArmourDurability == 0)
				Display_Text_From_Memory((unsigned char far *)"all"); // Sol: exact EXE text 3EDB:4C75; readable text restored
			else
			{
				Display_Text_Dynamic_Value((unsigned short)LostArmourPoints);
				Display_Text_From_Memory((unsigned char far *)" points"); // Sol: exact EXE text 3EDB:4C79; readable text restored
			}
			Display_Text_From_Memory((unsigned char far *)" of its protective capacity.  It would cost "); // Sol: exact EXE text 3EDB:4C81; readable text restored
			short RepairRate = (signed char)seg3EDB->ArmourRepairCostPerPoint[ArmourTypeId - 1]; // Sol:0F70 signed BYTE at4F3E+(type-1), equivalently4F3D+type; five real rates
			Display_Text_Dynamic_Value((unsigned short)(RepairRate * LostArmourPoints)); // Sol:IMUL low WORD quote, no DWORD widening
			Display_Text_From_Memory((unsigned char far *)" C-bills to repair it, and you have "); // Sol: exact EXE text 3EDB:4CAE; readable text restored
			Citadel_Building_Dialogs(0x0A); // Sol:shared cash display, raw action0A
			Display_Text_From_Memory((unsigned char far *)"  Do you want it repaired?"); // Sol: exact EXE text 3EDB:4CD3; readable text restored
			if (Prompt_Yes_No(1) == FALSE)
				break; // Sol:0FD0 no purchase on refusal
			unsigned short AnyArmourPointRepaired = FALSE; // Sol:SS:BP-2C tracks partial work, not sufficient funds for entire job
			while (ArmourPointsToRepair != 0)
			{
				unsigned long RepairCost = (unsigned long)(long)RepairRate; // Sol:0FDA CBW+CWD; unsigned DWORD affordability
				if (RepairCost > seg3092->CBills)
					break;
				AnyArmourPointRepaired = TRUE;
				ArmourPointsToRepair = (short)(ArmourPointsToRepair - 1);
				seg3092->CBills -= RepairCost;
				++seg3092->Infantry[SelectPartyMemberId].ArmourValue;
				Display_Text_CBill_Balance(); // Sol:one debit and BYTE increment per affordable point; exact balance succeeds
			}
			if (ArmourPointsToRepair != 0)
			{
				Display_Text_From_Memory((unsigned char far *)"\r\rYou did not have enough C-bills to "); // Sol: exact EXE text 3EDB:4CEE; readable text restored
				ArmourRepairStatusText = AnyArmourPointRepaired ? (unsigned char far *)"finish the job, but we repaired all that you could afford." : (unsigned char far *)"get your armor patched."; // Sol: exact EXE text 3EDB:4D14, 3EDB:4D4F; readable text restored
			}
			else
				ArmourRepairStatusText = (unsigned char far *)"\r\rThere you are, sir, good as new!"; // Sol: exact EXE text 3EDB:4D67; readable text restored
			Display_Text_From_Memory(ArmourRepairStatusText);
			Keyboard_Get_ASCII_Hex_Input(); // Sol:0F2A shared terminal dialogue/wait, now local to this case
			break;

		case 0x20:
			Prepare_Rental_Locust_For_Arena();
			break;

		case 0x21:
			Prepare_Party_Mech_For_Arena();
			break;

		case 0x22: // Sol:raw ARENA.BLD action23, mission8 entry and normal/escape return
			seg3092->CombatantSpriteFamilyOffset[Character_Jason] = MECH_Sprite_LOCUST;
			if (seg3092->Mechs[0].UpgradePackageBase != 0) // Sol:1062 exact BYTE C79F=C724+7B, not a hands/engine field
				seg3092->CombatantSpriteFamilyOffset[Character_Jason] = MECH_Sprite_COMMANDO;
			seg3092->Infantry[Character_Jason].Piloting = 0; // Sol:1082 character assignmentC620 -> mech slot0
			seg3092->Mechs[0].PilotId = Character_Jason; // Sol:C79D is mech+79, NOT an Infantry.Pilot member
			Display_Animation_Scene(AnimationO00_MechStartUp, AnimationPlayback_RestoreGameView);
			seg246C->CrescentHawk_MapPositionX = 0x0A2B; // Sol:arena mission entry packed X
			seg246C->CrescentHawk_MapPositionY = 0x8057; // Sol:arena mission entry packed Y
			seg3EDB->CombatantAnimationCursor[Character_Jason] = seg2FE8->MechWalkAnimationStream; // Sol:10A0 writes native FAR2FE8:02A0; named BYTE-array view decays to stream pointer
			seg3092->CombatantSpriteFrame[Character_Jason] = Advance_Combatant_Animation_Stream_1732(Character_Jason); // Sol:stores returned AL, not literal0
			Arena_Select_And_Apply_Combat_Map_Patch_137F();
			Mech_Mission_0629(8); // Sol:arena mission number, not ordinary training stage
			for (unsigned short ArenaEffectSlot = 0; ArenaEffectSlot < PersistentMapEffect_SlotCount; ++ArenaEffectSlot)
			{
				if ((seg3092->MapEffectSpriteIndex[ArenaEffectSlot] & 0x7E) == Sprite_Fire_Large
				 && seg3092->MapEffectPackedPage[ArenaEffectSlot] == 0x8A) // Sol:10EF fire family7C/7D incl high-bit variants, packed page X=A/Y=8
				{
					seg3092->MapEffectPositionXLow[ArenaEffectSlot] = 0;
					seg3092->MapEffectPackedPage[ArenaEffectSlot] = 0;
					seg3092->MapEffectSpriteIndex[ArenaEffectSlot] = 0; // Sol:Y-lowD517 untouched; zero sprite disables effect
				}
			}
			if (seg3EDB->Bool_MainCharactersAlive == FALSE)
				seg3092->RequiredMainCharacterDead = TRUE; // Sol:1129 sets on death only, no else-reset

			if (seg3092->Bool_AllowEscape == FALSE)
			{
				Arena_Remove_And_Randomize_Combat_Map_Patch_1441();
				Restore_Party_After_Arena_Combat();
				seg246C->CrescentHawk_MapPositionX = 0x0A39; // Sol:normal arena return packed X
				seg246C->CrescentHawk_MapPositionY = 0x805D; // Sol:normal arena return packed Y
			}
			else
			{
				// Sol:116E escape deliberately skips the normal crowd-patch removal and party helper.
				// Sol TODO ASM-1CD3-116E: Read WORD4036/403E/406A values via
				// Sol: CombatantPackedY[0]/[4] and CombatantActive[0]; legacy array
				// Sol: names here decay to addresses instead of those WORD values.
				seg246C->CrescentHawk_MapPositionX = 0x0970; // Sol:escape anchor packed X
				seg246C->CrescentHawk_MapPositionY = seg3092->CharacterPosY_Mech;
				if (seg3092->Character_OnMap == FALSE)
					seg246C->CrescentHawk_MapPositionY = seg3092->CharacterPosY_OnFoot; // Sol:406A zero selects403E instead of4036
				for (unsigned short PartyMemberId = 1; PartyMemberId < 8; ++PartyMemberId)
					seg3092->Infantry[PartyMemberId].Name = seg3092->SavedPartyNameId[PartyMemberId]; // Sol:11AA restores companions only, not Jason

				unsigned short KeepArenaSlotZero = TRUE; // Sol:BP-28; initially true iff no saved friendly mech exists
				for (unsigned short SavedMechScanIndex = 0; SavedMechScanIndex < Friendly_Mech_Record_Count; ++SavedMechScanIndex)
				{
					if (seg3092->StoredPartyMechNameInitial[SavedMechScanIndex] != MECH_Destroyed)
						KeepArenaSlotZero = FALSE; // Sol:11DB scans exactly four BYTEs, NOT pointer range ending2BB2
				}
				for (unsigned short MechLanceId = 1; MechLanceId < Friendly_Mech_Record_Count; ++MechLanceId)
				{
					if (KeepArenaSlotZero == FALSE && seg3092->StoredPartyMechNameInitial[MechLanceId] == MECH_Destroyed)
					{
						KeepArenaSlotZero = TRUE; // Sol:1212 first free companion slot handles relocation, later slots skipped
						for (unsigned short RestoreSlot = 1; RestoreSlot < Friendly_Mech_Record_Count; ++RestoreSlot)
							seg3092->Mechs[RestoreSlot].Name = seg3092->StoredPartyMechNameInitial[RestoreSlot];
						unsigned char far *RelocatedMechBytes = (unsigned char far *)&seg3092->Mechs[MechLanceId];
						for (unsigned short MechStats = 0; MechStats < MECH_RecordSize; ++MechStats)
							RelocatedMechBytes[MechStats] = seg3092->ArenaMechRecordBackup[MechStats]; // Sol:1240 copies original slot-zero125 BYTE backup to vacancy
						seg3092->Mechs[MechLanceId].Name = seg3092->StoredPartyMechNameInitial[0]; // Sol:126B restores original name after relocation, arena slot0 remains
					}
				}
				if (KeepArenaSlotZero == FALSE)
				{
					unsigned char far *SlotZeroMechBytes = (unsigned char far *)&seg3092->Mechs[0];
					for (unsigned short MechStats = 0; MechStats < MECH_RecordSize; ++MechStats)
						SlotZeroMechBytes[MechStats] = seg3092->ArenaMechRecordBackup[MechStats]; // Sol:1295 no vacancy -> original slot0 restored, arena record discarded
					for (unsigned short RestoreSlot = 0; RestoreSlot < Friendly_Mech_Record_Count; ++RestoreSlot)
						seg3092->Mechs[RestoreSlot].Name = seg3092->StoredPartyMechNameInitial[RestoreSlot];
				}
				// Sol:If all saved names wereFF, neither restoration branch runs: keep arena slot0 unchanged.
				Map_data_structure(0x89); // Sol:12D7 centre packed region X=9/Y=8 ->3x3 descriptor cache
				unsigned short MapRegionRowBase = 0x78; // Sol:top-left region row7,column8; native map-file table is16 columns wide
				for (unsigned short MapGridRow = 0; MapGridRow < 3; ++MapGridRow)
				{
					for (unsigned short MapGridColumn = 0; MapGridColumn < 3; ++MapGridColumn)
					{
						unsigned char FileEnum = seg2FE8->MapFile[MapRegionRowBase + MapGridColumn]; // Sol:12F2 BYTE2FE8:0030+region index, not (index)[48]
						if (FileEnum != 0)
							DOS_Load_Map_Files(MapGridRow * 3 + MapGridColumn, (unsigned short)(signed char)FileEnum); // Sol:1308 CBW file BYTE, WORD grid slot
					}
					MapRegionRowBase += 0x10; // Sol:next row in16x16 map-file table
				}
				Map_NineGrid_Parent_1DA8();
				Starport_MapPatch_SaveApply_Or_Restore_0C72(FALSE); // Sol:1332 escape saves/applies temporary starport patch, distinct from normal arena removal
				for (unsigned short MechLanceId = 0; MechLanceId < Friendly_Mech_Record_Count; ++MechLanceId)
				{
					seg3092->StoredPartyMechNameInitial[MechLanceId] = MECH_Destroyed;
					seg3092->Mechs[MechLanceId].RiderId = MECH_NoRider;
					seg3092->Mechs[MechLanceId].PilotId = MECH_NoPilot; // Sol:1347 clears four crew pairs; live Name/otherfields remain
				}
				for (unsigned short PartyMemberId = 0; PartyMemberId < 8; ++PartyMemberId)
					seg3092->Infantry[PartyMemberId].Piloting = Character_OnFoot; // Sol:1375 clears all eight assignments
			}
			seg3092->ArenaRentalMechMode = FALSE; // Sol:138C common WORD reset for normal and escape paths
			break;

		case 0x23: // Sol:raw action24, display traitor's character NAME, not recruit or crew assignment
			short TraitorPartySlot = (signed char)seg3092->Traitor_CharacterId; // Sol:13B2 signed BYTE IMUL17
			CharacterNameId = (signed char)seg3092->Infantry[TraitorPartySlot].Name;
			goto DisplayCharacterName;

		case 0x24: // Sol:raw action25, script marks Jason dead/unavailable
			seg3EDB->Bool_MainCharactersAlive = FALSE; // Sol:139A clears WORD014A
			seg3092->Infantry[Character_Jason].Name = Character_Dead; // Sol:C614 BYTEFF; does not zero Health or immediately write D334
			break;

		case 0x25: // Sol:raw action26, display next recruit's name ID atD456
			CharacterNameId = (signed char)seg3092->NextRecruitNameId;
DisplayCharacterName: // Sol:original l1CD3_13CE; CBW Name ID then FAR pointer table1CA+id*4
			DialogueText = seg3EDB->CharacterNameList[CharacterNameId];
DisplaySelectedDialogueText: // Sol:original l1CD3_01B7; common FAR text call also used by fixed-dialogue paths
			Display_Text_From_Memory(DialogueText);
FinishDialogueAction:
			break;

		case 0x26: // Sol:raw action27, crew assignment for character SLOT1; not a name-table ID operation
			CharacterNameId = Character_Rex; // Sol:13E6 MOV AX,1 then shared1467:0002 crew call
			goto AssignSelectedCharacterCrew;

		case 0x27: // Raw JAIL.BLD action28h: run Jason's jailbreak mission
			Run_Jailbreak_Mission_And_Award_Stinger_152F();
			if (seg3EDB->Bool_MainCharactersAlive == FALSE) // Sol:13EC..140C latches D334 only on zero014A
				seg3092->RequiredMainCharacterDead = TRUE;
			break;

		case 0x28: // Sol:raw WEAPON2.BLD action29, laser-weapon grants followed by scripted health CAP
			if (seg3092->Party_NumOfMembers != 0)
			{
				for (short PartyEquipmentGrantIndex = 0; PartyEquipmentGrantIndex <= (short)(signed char)seg3092->Party_NumOfMembers; ++PartyEquipmentGrantIndex) // Sol:1423 reloads signed companion count, inclusive0..count
				{
					unsigned short WeaponGrantId = Infantry_LaserRifle;
					if (PartyEquipmentGrantIndex != 0)
						WeaponGrantId -= Rand_0x00_to_0xFF() & 1; // Sol:143C subsequent grants are rifle13 or laser gun12; recipient chosen by distributor
					Distribute_Weapon_To_Party(WeaponGrantId);
				}
			}
			else
			{
				Draw_Top_Graphic_Sidebar();
				Display_Text_From_Memory((unsigned char far *)"Do you want to drop your "); // Sol: exact EXE text 3EDB:4D8A; readable text restored
				short JasonWeaponId = (signed char)seg3092->Infantry[Character_Jason].Weapon;
				Display_Text_From_Memory(seg3EDB->WeaponStats[JasonWeaponId].Name); // Sol:1454 FAR3EDB:2ED8+signed weapon*17, record starts with name bytes
				Display_Text_From_Memory((unsigned char far *)" and take the Laser Rifle?"); // Sol: exact EXE text 3EDB:4DA4; readable text restored
				if (Prompt_Yes_No(1) != FALSE)
					seg3092->Infantry[Character_Jason].Weapon = Infantry_LaserRifle;
			}
			for (unsigned short PartyMemberId = 0; PartyMemberId < 8; ++PartyMemberId)
			{
				if (seg3092->Infantry[PartyMemberId].Name != Character_Dead)
				{
					short ScenarioHealthCapPerBody = ScenarioHealthCapMinimumPerBody + (Rand_0x00_to_0xFF() & 1);
					short ScenarioHealthCap = (short)(ScenarioHealthCapPerBody * (signed char)seg3092->Infantry[PartyMemberId].Body); // Sol:14D2 signed Body*6 or*7, NOT a healing amount
					if ((short)(signed char)seg3092->Infantry[PartyMemberId].Health > ScenarioHealthCap)
						seg3092->Infantry[PartyMemberId].Health = (unsigned char)ScenarioHealthCap; // Sol:1501 lowers only health ABOVE cap; leaves lower health unchanged
				}
			}
			break;

		case 0x29: // Sol:raw action2A; 1513..157D stages all eight roaming NPCs at the party's current world position
			for (unsigned short NpcSlot = 0; NpcSlot < 8; ++NpcSlot)
			{
				RoamingMapNpcRecordView far *Npc = (RoamingMapNpcRecordView far *)(
					(unsigned char far *)&seg3092->EnemyInfantryPosX + NpcSlot * 0x1A); // Sol:3092:D390, BYTE stride26; NOT WORD-array index26
				unsigned short CombatantId = Enemy_Infantry_CombatantId_Range_First + NpcSlot;
				seg3092->CombatantPackedX[CombatantId] = seg246C->CrescentHawk_MapPositionX; // Sol:4024+slot*2, WORD world coordinate
				Npc->CurrentPositionX = seg246C->CrescentHawk_MapPositionX;
				seg3092->CombatantPackedY[CombatantId] = seg246C->CrescentHawk_MapPositionY; // Sol:4056+slot*2
				Npc->CurrentPositionY = seg246C->CrescentHawk_MapPositionY;
				Npc->MovementDelay = (unsigned char)NpcSlot; // Sol:D399+slot*26, staggered movement delay, NOT active flag
				Npc->WaypointPair = 0x77; // Sol:D398: start waypoint7 and destination waypoint7; destination X/Y remain untouched
			}
			++seg246C->CrescentHawk_MapPositionY; // Sol:1572 increments the party WORLD Y WORD after staging, including FFFF->0000 wrap
			break;

		case 0x2A: // Sol:raw action2B; 157E..15DC stages NPC0, NOT Jason's combatant position
			RoamingMapNpcRecordView far *FirstNpc = (RoamingMapNpcRecordView far *)&seg3092->EnemyInfantryPosX;
			seg3092->CombatantPackedX[Enemy_Infantry_CombatantId_Range_First] = seg3092->MapInteractable_PosX[7]; // Sol:3092:4572=4564+7*2
			FirstNpc->CurrentPositionX = seg3092->MapInteractable_PosX[7];
			seg3092->CombatantPackedY[Enemy_Infantry_CombatantId_Range_First] = seg3092->MapInteractable_PosY[7]; // Sol:45A4=4596+7*2
			FirstNpc->CurrentPositionY = seg3092->MapInteractable_PosY[7];
			FirstNpc->MovementDelay = 0xFF; // Sol:D399; initial delay255, not fog-of-war visibility
			FirstNpc->WaypointPair = 0x70; // Sol:D398: start waypoint7, destination waypoint0
			FirstNpc->DestinationX = seg3092->MapInteractable_PosX[0]; // Sol:D394 <-4564 WORD
			FirstNpc->DestinationY = seg3092->MapInteractable_PosY[0]; // Sol:D396 <-4596 WORD
			break;

		case 0x2B:
			Mechlube_Buy_Ammo();
			break;

		case 0x2C: // Sol:raw action2D, ending screen then restoration of the Star League tile asset; 15DD..174D
			// Sol:Native 207F:00D1(2FE8:01F0) is adapter0-only colour conversion, omitted from maintained EGA path.
			seg3EDB->GraphicsCompatibilityFlag = FALSE; // Sol:1605 clears WORD before full-screen load
			Select_Game_Disk_And_Drive_28CC(2); // Sol:1612 original ending assets require disk2
			Load_File_To_Memory("ENDMECH.CMP", &seg3092->Ptr_File_To_Memory_Block); // Memory ref: [3EDB:4DBF]
			Decompress_File_Into_Memory(&seg3092->Ptr_File_To_Memory_Block, &seg246C->Ptr_DecompressedFile_Memory_Block);						
			if (seg3EDB->GraphicsAdapter == EGA_VGA) // Sol:1649 only adapter2 stages packed pixels at A800:0000
				DrawCall_Image_To_VGA_Memory(&seg246C->Ptr_DecompressedFile_Memory_Block, VGA_MEMORYADDRESS);
			// Sol:0525 retains FAR3058:0000, distinct from the default2FE8:0000 palette.
			Set_Palette_registers(seg3058->EndingEgaPalette); // Sol:maintained EGA path; original adapter3 selects3058:0010
			Draw_GraphicsFile_In_Memory(&seg246C->Ptr_DecompressedFile_Memory_Block, 0x00, 0x00, 0x28, 200); // Sol: ASM pushes FAR246C:244B plus four WORDs; EGA ignores buffer.
			
			seg3EDB->GraphicsCompatibilityFlag = TRUE; // Sol:169F sets WORD before restoring compressed tiles
			// Sol:Native adapter0 colour-map switch2FE8:01B0 is omitted; no restored CGA/Tandy body.
			Load_File_To_Memory("STARLEAG.ICN", &seg246C->Ptr_DecompressedFile_Memory_Block); // Memory ref: [3EDB:4DCB]
			Decompress_File_Into_Memory(&seg246C->Ptr_DecompressedFile_Memory_Block, &seg3092->Ptr_File_To_Memory_Block);

			Wait_For_50Hz_Then_Check_Input();
			Keyboard_Get_ASCII_Hex_Input();
			Graphics_Set_Screen_To_Black();
						
			Set_Palette_registers(seg2FE8->DefaultEgaPalette); // Sol:1731 FAR2FE8:0000; restore default EGA palette
			Draw_Health_and_C_Bills_Sidebar(TRUE);
			Draw_Top_Graphic_Sidebar();
			break;

		case 0x2D: // Sol:raw action2E, restore hidden friendly Name BYTEs, then rebuild sprites/crew
			
			for (unsigned short MechLanceId = 0; MechLanceId < Friendly_Mech_Record_Count; ++MechLanceId)
			{
				seg3092->Mechs[MechLanceId].Name = seg3092->StoredPartyMechNameInitial[MechLanceId]; // Sol:0E2C..0E53 restores one BYTE, not full mech record
			} 
RebuildFriendlyMechSprites: // Sol:original label l1CD3_0E54; raw1B enters here without restoring Name bytes
		
			for (unsigned short MechLanceId = 0; MechLanceId < Friendly_Mech_Record_Count; ++MechLanceId)
			{
				seg3092->CombatantSpriteFamilyOffset[MechLanceId] = MECH_Sprite_LOCUST; //D55E

				if (seg3092->Mechs[MechLanceId].Name != KEY_L) // Sol:0E59 exact Name=='L' -> Locust; every other byte, includingFF, selects Commando
					seg3092->CombatantSpriteFamilyOffset[MechLanceId] = MECH_Sprite_COMMANDO; //D55E
			} 
			CharacterNameId = 0x00;
AssignSelectedCharacterCrew: // Sol:original l1CD3_0E92; WORD character-slot call, separate from name display
			Assign_Pilot_and_rider_to_Mechs(CharacterNameId);
FinishScriptAction: // Sol: native shared exit at 1CD3:0181.
			break;

		case 0x2E: // Sol:raw action2F;174E signed BYTE C623 value, NOT its address
			// Sol:174E reads Health at3092:C623 (+0F), not TrainingFlags atC624.
			// Sol: Native signed BYTE JLE leaves0..5 and80..FF unchanged.
			if ((signed char)seg3092->Infantry[Character_Jason].Health > ScriptHealthDeductionThreshold)
				seg3092->Infantry[Character_Jason].Health -= ScriptHealthDeduction; // Sol:175A BYTE SUB4; training bits remain unchanged.
			break;
		}
	}
}

// 1CD3:17C6: void Draw_Message_Box()
// Called from:
//      Main_Game_Loop
//      Map_Interactables_Building_Or_Items
//      Save_Game
//      Menu_Assign_Pilots
//      Mech_Mission_0629
//      StarLeague_Secret_Passageway_Discovered
//      Display_StarLeague_Cache_Dialog_Window
//      StarLeague_HyperPulse_Power_Dialog_Window
//      StarLeague_Security_Terminal
//      HPGTransmitter
//      StarLeague_Map_Room
//      Draw_STARLEAG_ICN_Scene
//      Cache_StarMap_CorrectPassword
//      StarLeague_Key_Codes
//      Heal_Characters
//      Assign_Pilot_and_rider_to_Mechs
//      Combat_Parent_000A
//      Combat_AudioVisual_Effects
// Sol: Summary: Open the shared dialogue message box.
// Sol: Outline: Select the standard panel layout and draw its border and background.
void Draw_Message_Box()
{
	// Sol:17C6 verified: choose layout7, draw top sidebar, draw border0; no input wait.
	Menu_Memory_Variables(0x07);
	Draw_Top_Graphic_Sidebar();
	Draw_Menu_Border(0x00);
}

// 1CD3:17EA: void Display_Text_From_Memory_ScreenRetrace_KeyboardInput(Stack Eq_21 TextPtr)
// Called from:
//      Main_Game_Loop
//      Map_Interactables_Building_Or_Items
//      Save_Game
//      Menu_Assign_Pilots
//      Interact_with_BLD
//      Mech_Mission_0629
//      Mechlube_Buy_Ammo
//      StarLeague_Secret_Passageway_Discovered
//      Display_StarLeague_Cache_Dialog_Window
//      StarLeague_HyperPulse_Power_Dialog_Window
//      StarLeague_Security_Terminal
//      HPGTransmitter
//      StarLeague_Map_Room
//      Draw_STARLEAG_ICN_Scene
//      Cache_StarMap_CorrectPassword
//      Heal_Characters
//      Assign_Pilot_and_rider_to_Mechs
//      Copyright_Check_Mech_Quiz
//      Combat_Parent_000A
//      Combat_AudioVisual_Effects
// Sol: Summary: Display text and perform the standard presentation wait.
// Sol: Outline: Print the supplied string and call the timed input-check wrapper; callers perform any separate blocking key read.
void Display_Text_From_Memory_ScreenRetrace_KeyboardInput(unsigned char far *TextPtr)
{
	// Sol:17EA forwards BP+6/+8 as a16:16 FAR string, then calls086A.
	// Sol:No ASCII-key read here; the inherited name describes the input bridge, not a separate blocking key call.
	Display_Text_From_Memory(TextPtr);
	Wait_For_50Hz_Then_Check_Input();
}

// 1CD3:1809: void Display_Text_Shop_Cannot_Afford_Text()
// Called from:
//      Mechlube_Repair_Mech
//      Mechlube_Upgrade_Mech
//      Citadel_Building_Dialogs
// Sol: Summary: Print the shop's insufficient-funds response.
// Sol: Outline: Display the fixed affordability message through the common text path.
void Display_Text_Shop_Cannot_Afford_Text()
{	
	// Sol TODO ASM-1CD3-1809: Native3EDB:4F7E ends with a period;
	// Sol: current literal omits it. No additional wait or key read is native.
	Display_Text_From_Memory("Come back when you can afford it"); // Memory ref: [3EDB:4F7E] 
}

// 1CD3:181E: void Display_Text_4FA0_Value()
// Called from:
//      Distribute_Purchased_Armour
//      Distribute_Weapon_To_Party
//      Talk_To_Building_Occupants
//      Mechlube_Repair_Mech
//      Mechlube_Upgrade_Mech
//      Heal_Characters
//      Assign_Pilot_and_rider_to_Mechs
//      Display_Text_Mech_Names
//      Citadel_Building_Dialogs
// Sol: Summary: Print the shared line-break string.
// Sol: Outline: Pass the fixed text at the native string location to the renderer.
void Display_Text_4FA0_Value()
{
	Display_Text_From_Memory((unsigned char far *)"\r"); // Sol:181E passes FAR3EDB:4FA0 directly; inline0D,00 line break, not pointer dereference // Sol: exact EXE text 3EDB:4FA0; readable text restored
}
